### ISSUE TITLE
One line curl examples for API features in API doc

### ISSUE THREAD

**Issue by TimothyStiles** [OAButton/discussion#1002]
## One line curl examples for API features in API doc

Hello everyone!

I have a set of DOIs that I want to check for availability on OAButton's database and I'm struggling to make a successful curl statement to test the availability api. Here's what I got so far:

```
curl  -H "Content-Type: application/json" -H "x-apikey: yourRegisteredApikey" -d "url: https://doi.org/10.1371/journal.pone.0199644" 'https://api.openaccessbutton.org/availability' 
```

which returns:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: invalid json<br> &nbsp; &nbsp;at parse (/home/cloo/live/noddy/node_modules/body-parser/lib/types/json.js:83:15)<br> &nbsp; &nbsp;at /home/cloo/live/noddy/node_modules/body-parser/lib/read.js:108:18<br> &nbsp; &nbsp;at invokeCallback (/home/cloo/live/noddy/node_modules/raw-body/index.js:262:16)<br> &nbsp; &nbsp;at done (/home/cloo/live/noddy/node_modules/raw-body/index.js:251:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/cloo/live/noddy/node_modules/raw-body/index.js:307:7)<br> &nbsp; &nbsp;at emitNone (events.js:106:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:208:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1055:12)<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:138:11)<br> &nbsp; &nbsp;at process._tickDomainCallback (internal/process/next_tick.js:218:9)</pre>
</body>
</html>

```

 I can get the following to work but this works with and without a proper api key.

``` curl -H "Content-Type: application/json" -H "x-apikey: yourRegisteredApikey" 'https://api.openaccessbutton.org'  ```

If anyone could help me figure this out I'd be happy to make a pull request to add more curl examples to the API docs. Thanks!

**Comment by markmacgillivray** [comment]
Hi there. To use the availability API at the moment it is a GET request with a url parameter provided, not a POST of data. Anyway a POST of data would require you to POST valid JSON whereas just now you are trying to send the string "url:YOURURL" which isn't JSON, hence the error you're getting. JSON would be {"url":"YOURURL"}.

But you can avoid that complexity by just putting the URL of the article you want to check as a URL param on the API URL you are calling, like this:

https://api.openaccessbutton.org/availability?url=YOURURL

And you should url-encode your URL first, to make sure it sends correctly. If you're not doing this programmatically, just google "url encoder" and you'll find a page that will do it for you.

So if you do

curl -X GET "https://api.openaccessbutton.org/availability?url=YOURURL"

You should get back the response you expect.

Also yes, please do add your API KEY as a header as you have been doing, although as you also note, we don't actually need it, it is just for our records. We have not actually restricted access to this endpoint yet.

**Comment by TimothyStiles** [comment]
Great and thanks! That worked perfectly. [I've made a pull request to the website to update the api page](https://github.com/OAButton/website/pull/87).
