### ISSUE TITLE
on IE deliveroa doesn't show install instructions box on selection of system

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1003]
As seen here: https://www.dropbox.com/s/sm06y33gnnn4uua/Screenshot%202018-07-18%2022.28.48.png?dl=0

Likely effects other pages using this mechanism. Either we should fix the mechanism, or provide some warning that the page doesn't work and to use IE. I have a strong preference for the former. 

Reported by a user and confirmed on Browserstack (IE 11 on Windows)

**Comment by markmacgillivray** [comment]
There appear to be 3 separate functions bound to the .chooseill buttons on that page. What is it you are actually trying to achieve there?

**Comment by markmacgillivray** [comment]
There is also mobilecheck code on that page although it does not appear to relate to anything on the page.

**Comment by JosephMcArthur** [comment]
In this case the issue is that the box which should appear on the right doesn't. On click the intro part of the page should move left to show instructions, the highlighting of the next action is removed, and then an a set up upsell actions appears too.

**Comment by markmacgillivray** [comment]
I have changed this on dev and looked for other pages with similar code, so I think it should do as you expected. It seems to make sense to me when I look at it, but as I am not exactly sure what the prior intent was, would be good if you can have a look to see if it is what you expect now.

**Comment by JosephMcArthur** [comment]
Still seeing the same error on IE through browserstack. 

Also, I've realised that the screenshot of the bug is broken... so here is another one: https://www.dropbox.com/s/2sphzr5f53plv2i/Screenshot%202018-08-16%2013.00.03.png?dl=0

Note, "clio" has been clicked, the page moved but the instructions don't show up as you'd see on FF or chrome.

**Comment by markmacgillivray** [comment]
Altered to js show/hides to avoid IE css inconsistencies
