### ISSUE TITLE
When searching for articles on the frontpage, and they're found, back button in ff & chrome works inconsistently 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1006]
I haven't figured out how to replicate this consistently, but I've been it on both my mac / FF & another mac with chrome.

Essentially, search for something, and then when it's found try and hit back. It sometimes doesn't respond and take you back to the homepage.

**Comment by markmacgillivray** [comment]
I haven't looked at this yet

**Comment by markmacgillivray** [comment]
Made back button action explicit
