### ISSUE TITLE
Feedback on stats at OAB document

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1009]
Been thinking a lot about how we can level up measuring our work etc. It's a bit complex, so I ended up writing it up. 

Would value feedback on it from you both: https://docs.google.com/document/d/1-2x_qQKN0lqisSaTuHi7w-gq_riznQD-W0CIw9gjJRs/edit# 

As ever, bit messy as I had to throw it together before going away but it's the best I've got.

**Comment by natalianorori** [comment]
hey, 
left you some feedback, I feel that you are on the right track. I share many of the frustrations that you want to address. There are also various issues that relate to the topic, you can find my point of view on stats here https://github.com/OAButton/discussion/issues/985

**Comment by JosephMcArthur** [comment]
@markmacgillivray, have you managed to look at this?

**Comment by markmacgillivray** [comment]
This was discussed already, I believe Joe to list how stat requirements fit with current /stats and /export pages, aiming to ensure the necessary data can be exported into spreadsheet, and key figures are on /stats in a way that Joe prefers, e.g. what figures to be graphed, and in what time ranges.

**Comment by JosephMcArthur** [comment]
I know we've gone back and forth on this, and have struggled to prioritize it. I can't see that changing, so having recently reviewed the doc I've suggested some small incremental changes to what we have that'll make it much more useful and bring it close enough to what's laid out in the doc. 

If they seem do-able, this can be closed.

**Comment by JosephMcArthur** [comment]
I'm happy with this now, closing.
