### ISSUE TITLE
opening requests in a new tab from the main request page 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#1011]
when clicking in an individual request on openaccessbutton.org/request , have the system open a new tab. At the moment I right click on each individual request in order to have the main request page always open.

**Comment by JosephMcArthur** [comment]
Do you still want this?

**Comment by JosephMcArthur** [comment]
@natalianorori nudge, if yes, we can ship in the next batch.

**Comment by JosephMcArthur** [comment]
@markmacgillivray if it his quick, would be great to get it in before we ship today.

**Comment by markmacgillivray** [comment]
Done, make sure you refresh your browser, then will get new pages when clicking titles.
