### ISSUE TITLE
show DOI link Zenodo gives on successful request page not Zenodo link

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1012]

**Comment by markmacgillivray** [comment]
I have altered our API requests to zenodo to prereserve a DOI, so when we get that back from zenodo we can now store it along with the zenodo URL. Once the item is published in zenodo and then status for the request on our system is set to 'received", then the request page will show success and will display the zenodo DOI link if available, and only display the zenodo URL direct if we don't have a zenodo DOI.
