### ISSUE TITLE
Is there a way to display suggested author names in the spreadsheet with request data we export ?

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#1024]
I am currently evaluating moderating requests in bulk, and one advantage of the live system vs bulk is that suggested author names appear in the admin box. Is there a way to have suggested author names displayed in the spreadsheet that we download from openaccessbutton.org/export ?

**Comment by JosephMcArthur** [comment]
Yes : ) We can dump into export, and not include in import easily.
