### ISSUE TITLE
Remove old receive pages and update all open requests to relate instead to a new deposit page

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#1037]

**Comment by JosephMcArthur** [comment]
@markmacgillivray this seems to have not been put into a milestone when you did your planning here. Can you put it somewhere? Even just backlog would be fine so it isn't lost.

**Comment by markmacgillivray** [comment]
It would need to be done at the end of the new deposit system build, so I have put this into the Depo 9 milestone, guessing that you have renamed those milestones for that purpose.

**Comment by JosephMcArthur** [comment]
You guessed right, thanks!

**Comment by JosephMcArthur** [comment]
Note. In emails we now send links to our new system, and I've just updated request pages to point to the new system. 

For now, I'm fine with that being 'done' enough. Old receiver pages can continue as they are now, and we will simply not maintain under the assumption that people are not going to be digging through their inboxes for links to these pages.
