### ISSUE TITLE
Ensure that deposits to new system close other requests that seem to be about the same article

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#1038]
In which case email the users who wanted it, but not the author we were trying to get it from - or email them to say no longer needed from them as we have it already, but note that it still COULD be them who did it, so be generic.

**Comment by JosephMcArthur** [comment]
@markmacgillivray this seems to have not been put into a milestone when you did your planning here. Can you put it somewhere? Even just backlog would be fine so it isn't lost.

**Comment by markmacgillivray** [comment]
Relates to #1034

**Comment by JosephMcArthur** [comment]
Note, closing this as for now having Natalia do it is a totally fine solution.
