### ISSUE TITLE
When an author’s name is in the author box, form a Google Scholar link from this to their profile to check for email

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1041]
Here is an example search that should bring out profiles:

https://scholar.google.com/citations?view_op=search_authors&hl=en&mauthors=David+J+Paterson&btnG=

Looks like the name just gets tagged on the end :) 

cc @natalianorori , is this the best approach for you?

**Comment by natalianorori** [comment]
yesssss :)

**Comment by JosephMcArthur** [comment]
Would having the paper DOI linked in a scholar search also be helpful, or the title?

**Comment by JosephMcArthur** [comment]
@natalianorori  Would having the paper DOI linked in a scholar search also be helpful, or the title?

**Comment by markmacgillivray** [comment]
Admin button added
