### ISSUE TITLE
Gather institution of authors we’re emailing automatically from existing data & scrap

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1048]
@markmacgillivray , we’ve already discussed this. Keen to get this implemented from existing data and easy to get stuff from scrap asap. For now we should target data for the corresponding author (who I presume we’re emailing in most cases, @natalianorori ).

**Comment by natalianorori** [comment]
The corresponding author's institution is the primary data we should try to extract, extracting from others might create confusion at the moment

**Comment by markmacgillivray** [comment]
This now happens whenever we don't already have an email address, and if there is affiliation data from a crossref lookup on the DOI of the request. It does not do it by scrape as there are few cases where the institution is available, and no good way to be able to scrape out the relevant string even where it is available in the page.
