### ISSUE TITLE
Odd title being pulled back for some requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1051]
e.g https://openaccessbutton.org/request/6WYL9HYFjyNmWjjNw & https://openaccessbutton.org/request?source={%22query%22:{%22filtered%22:{%22query%22:{%22bool%22:{%22must%22:[{%22query_string%22:{%22default_operator%22:%22AND%22,%22query%22:%22www%20%20%20%20%20%20%20%20%20com%20%20www%20%20%20%20%20%20%20%20com%20%20and%20www%20%20%20%20%20%20%20%20%20com%20%20Defendants%20%22}}]}},%22filter%22:{%22bool%22:{%22must%22:[{%22exists%22:{%22field%22:%22story%22}},{%22query%22:{%22query_string%22:{%22query%22:%22story:*%22}}}]}}}},%22from%22:0,%22size%22:500,%22fields%22:[%22status%22,%22type%22,%22user.profession%22,%22user.affiliation%22,%22_id%22,%22url%22,%22created_date%22,%22createdAt%22,%22title%22,%22email%22,%22user.username%22,%22user.firstname%22,%22user.email%22,%22location.geo.lat%22,%22location.geo.lon%22,%22story%22,%22rating%22,%22count%22],%22sort%22:[{%22createdAt%22:%22desc%22}],%22facets%22:{%22status%22:{%22terms%22:{%22field%22:%22status.exact%22}},%22user%22:{%22terms%22:{%22field%22:%22user.profession.exact%22,%22size%22:100}},%22keyword%22:{%22terms%22:{%22field%22:%22keywords.exact%22,%22size%22:1000}},%22journal%22:{%22terms%22:{%22field%22:%22journal.exact%22,%22size%22:1000}}}}

**Comment by markmacgillivray** [comment]
This was created by a combination of issues where the sciencedirect page returned content that led us to a wrong DOI which got us a wrong article from BASE. The problem with scraping the sciencedirect is that it appears we are once again unable to access sciencedirect from our server. So I have added the URL check back to the front page of the site saying we can't do sciencedirect URLs if someone types one in. So these weird URLs will not come up any more.
