### ISSUE TITLE
story_too_bad not sending the right email. 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1056]
It's currently sending that the request is in progress, which it isn't. @natalianorori can you find the email that should be sent for this?

**Comment by natalianorori** [comment]
https://docs.google.com/document/d/1SKTlhhz1j-wSvxWzwqfXyj_xyzI9eH2Q121wNdCJt2E/edit this is the template that should be sent

**Comment by JosephMcArthur** [comment]
@natalianorori can you find the original issue where we discussed this and see what we said

**Comment by natalianorori** [comment]
new template for "story too bad" button: https://docs.google.com/document/d/1AhQweQqC3fjB5OFZLb4dV0nszWO73A6ZJ0kuR6xlIoo/edit

**Comment by JosephMcArthur** [comment]
Pushed text to dev under `emails/initiator_poorstory.html`

@markmacgillivray can you connect to the quick action and close please?
