### ISSUE TITLE
Sometimes when the DOI is put in as link, title isn't populated

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1058]
e.g 

- https://dev.openaccessbutton.org/request/urQBuwrtCs6CNrtqt, 
- https://openaccessbutton.org/request/gfpyiRkKCk9GBWpwo, 
- https://openaccessbutton.org/request/AmRcogktwWuNwqMB9, 
- https://openaccessbutton.org/request/db7hQdZyw9basrmPP, 
- https://openaccessbutton.org/request/aTLsh3Jqun5QhFFuy, 
- https://openaccessbutton.org/request/Bc3A9wC68aGu9hknY, 

Fixing this by hand sucks up moderator time, so best to have system do

**Comment by markmacgillivray** [comment]
Added an extra catch to check crossref if title not known at any point a request is saved/edited
