### ISSUE TITLE
New loading page text for requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1059]
Now:
We're warming up a request for you. This might take a few seconds. -->

Revised:

"Hold on, we're getting ready to ask the author to make this available." 
then in smaller text
"We'll need you to tell us why you need the research. Get thinking!"

Please send screenshot for review

**Comment by natalianorori** [comment]
> "We'll need you to tell us why you need the research. Get thinking!"

SUPER important to add this
