### ISSUE TITLE
proving feedback to stories based on content ques

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1067]
We often see the same mistakes made time and time again. We can maybe this with nudges. I'd like to provide story feedback based on key-words and regexes. 

They should be as follows:

- if "test" --> Are you just trying out the service? A better way to learn is by reading this blog(blog where we talk about the system). 
- if {{url}} --> Looks like you might be including the paper URL. If so, don't worry, we'll let the author know what you need. Just tell us why the paper is important to you. 
- if {{email}} --> Don't worry about including your email, we'll send you the paper once the author shares it. 
- if {{doi}} --> Looks like you might be including the paper DOI. If so, don't worry, we'll let the author know what you need. Just tell us why the paper is important to you. 
- if {{login code}} --> Are you looking to sign in? If so go here.
- if {{article title}} --> Looks like you might be inc
- if "dear / hi" --> No need to great the author, we'll do that! Just focus on why you need the article. 
- if "regards / thank you" --> 
- if "thesis" or "research" --> Top tip: Be specific with your request. e.g if you need it for your {{keyword}, what exactly is your {{keyword}} about? 
- if "please" --> No need to ask the author to share, just focus your message on why you need the article. We'll send the author a polite request and just need you to tell us why.

For the tips UI, I quite like option 4 here: https://codemyui.com/password-strength-indicator-signup-forms/

**Comment by JosephMcArthur** [comment]
Oh. Some edge cases. If two of these are present at once, show both (one on top of the other). When the prompt is removed, remove the nudge.

**Comment by markmacgillivray** [comment]
Make it easy for an admin to edit the code to add word triggers and a comment they should cause. Does not have to be a UI, just a list somewhere on the page that is straightforward to edit. Just do this on the page UI. Later Joe may want this on the API so other people can get our confirmatory list.
