### ISSUE TITLE
extract journal color data from sherpa romeo API 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#1072]
@markmacgillivray , is this something we can do? 

", could you use the Romeo API to get a list of all ‘Blue’ journals and provide a link to the list? Or export the whole lot of it, put into excel and then filter on Romeo colour to each colour, and have ready made lists for each colour which could be linked to in the appropriate section? There is a ready-made API query on the Romeo API page for getting all yellow journals, but the output seems to give you the entire record for each journal, rather than just a journal name. I’m afraid I’m not techy enough to finesse the query to return only journal titles. The query is below: · RoMEO Colour - All 'Yellow' publishers (omitting 'Mandated OA' data):  http://www.sherpa.ac.uk/romeo/api29.php?colour=yellow&showfunder=none [expect a slow response] "

this would be useful for us to have as lists we can expand, and lists we can point to in resources we are building, such as openaccessbutton.org/versions-explained . Also a good way to extracting general conditions and deposit statements  ( #991 ).

**Comment by markmacgillivray** [comment]
In progress

**Comment by markmacgillivray** [comment]
This has been done and tested on dev, and allows to create a link that lists the journal names for all blue journals (or some other filter). This can be pushed to live on Monday once I finish the bing cap testing, and then I will add here an example of a link URL to the live API that will demonstrate how you can get this sort of data out of it.
