### ISSUE TITLE
{{useremail}} showing "undefined" in oasheet email

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1078]
Doesn't seem possible for this to be undefined. This is in production=. 

> ---------- Forwarded message ---------
> From: Open Access Button <donotreply@mg.openaccessbutton.org>
> Date: Thu, 15 Nov 2018 at 09:15
> Subject: Your OAsheet job has started
> To: <joseph.mcarthur.10@gmail.com>
> 
> 
> Hi, undefined!
> 
> Your OAsheet job "Penn CV example - Sheet1.csv" has started. We'll email you a link to the results once they're 100% complete.
> 
> You can also check the progress of your job, and download the results that have completed already, here
> 
> Best,
> 
> Joe

**Comment by markmacgillivray** [comment]
Fixed, on dev.
