### ISSUE TITLE
Typo on user-group notification page

### ISSUE THREAD

**Issue by rossmounce** [OAButton/discussion#1085]
![image](https://user-images.githubusercontent.com/824120/48898746-7b161900-ee45-11e8-9513-7b508c136e0d.png)

here: https://docs.google.com/forms/d/e/1FAIpQLSeGyTupl6M2-mIZV4FkSIdiRPjH_t350JfzHwC1sPJEOMks3Q/viewform

use -> us

**Comment by rossmounce** [comment]
Likewise for the version explainer sign-form

![image](https://user-images.githubusercontent.com/824120/48898886-ebbd3580-ee45-11e8-9f83-46434262487f.png)

here: https://docs.google.com/forms/d/e/1FAIpQLSdGNV1kMFZecQD8Qtqcfu_jru4jLvejU7wPu5kzjOgpFn3ZTQ/viewform 

use -> us

**Comment by JosephMcArthur** [comment]
fixed, thanks Ross!
