### ISSUE TITLE
pull in publisher metadata from crossref

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1086]
We'll need this to:
- [x] look up even more permissions info
- [ ] pass it through to Zenodo
- [ ] export to sheets

**Comment by markmacgillivray** [comment]
By publisher metadata do you mean the publisher name? If so, I've done that.

Not sure what permissions you want me to look up with that name though - can you elaborate? Or is that for later?

When it comes to zenodo, I have checked and as far as I can tell, we can't pass publisher to zenodo. Here is the metadata description from their docs, it does not have publisher in it:
http://developers.zenodo.org/#representation

For export, publisher has been added to the list of things the export includes, and is an accepted filed at import too.

Will assign to you now, either close or reassign back to me if there are further things to do re. the above.

**Comment by JosephMcArthur** [comment]
Huh... right you are. Let's shut!
