### ISSUE TITLE
Changes to /stats table & lists

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1094]
In the table, can you add:
- [x] A better name for "Widget" I still don't know what it is.
- [x] add in ILLiad
- [x] add in Clio
- [x] add in EmbedOA (aggregate of all)
- [x] add in Integrations

In the list can you add:
- [ ] clearer info on what the stats refer to. For example, I'm not really sure what the final random strings refer to.

**Comment by markmacgillivray** [comment]
@JosephMcArthur this is in place on dev if you want to take a look
