### ISSUE TITLE
Exceptions management on /requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1095]
As we move to automate all the final mile on requests, mainly deposit management and publisher policies, we know there are going to be exceptions to all those rules. 

I'd like to propose we code in a concept of "exceptions" to the system. While this will look to help us make one-off-fixes to our rules, it'll also help us deal with waivers which are a commonly used tool in archiving. 

I'd suggest that we have the system lookup DOIs in a Google Sheet. In that sheet, we'll list key info like what can be deposited, if it needs embargos, statements, etc essentially everything we'd need to form a fully legal deposit. If it finds one, it uses this as the source of truth for what can be deposit and nothing else (or, if left blank let the system lookup the field as usual).

@markmacgillivray I'd be interested in your thoughts on this conceptually. I think of it a bit like the redirects sheet.

**Comment by markmacgillivray** [comment]
It sounds fine, however is it likely we would ever have a DOI exception in that sheet before it was queried on our site? Like, how would we know the exception of a particular DOI if nobody has ever queried us about it? So if we don't have it in the sheet, and we get that first query, then when we look up that DOI we won't find it so wouldn't we end up just treating it in the generic way? At what point will this sheet enable us to catch things as they come in to the system?

**Comment by JosephMcArthur** [comment]
I happened to semi-dream about this last night, haha! I think there are some cases, yes, where we'd have it before but you're right, in many cases we wouldn't. 

We'd need to have some form of signalling that that sheet / dataset had been updated, what it affected, and making the updates. If this was done with an "import" system, that could be triggered whenever an import was made, if it was a gsheet every few minutes it could check a timestamp of "last changed" in the sheet. This would be the same for #1096 and all publisher permissions sheets.

**Comment by JosephMcArthur** [comment]
There is now a sheet for this as part of the larger permissions sheet here: https://docs.google.com/spreadsheets/d/1Oy12v5dRgwBFr3VfogOOepPXXswdCYjv6wn_6lMK57I/edit#gid=0. It'll have the same structure as other data types, but just be about a DOI.

**Comment by JosephMcArthur** [comment]
Closed by #1219 and #1096
