### ISSUE TITLE
Fix Import (as seen in " issues with /import")

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1099]

**Comment by markmacgillivray** [comment]
I am working on this, have pushed an update that is also on live, but don't use it yet, I want to test further on live first. @natalianorori - a note to you, just to make sure you see this, don't use import yet, I will let you know once tested. Thanks :)

**Comment by markmacgillivray** [comment]
Natalia has confirmed this works on dev, I am still to do an additional test on live before closing, then will let Natalia know she can continue to use it.

**Comment by markmacgillivray** [comment]
This has been tested and appears fine to me. The live system could now be used for importing again, however there are further changes that have just been made in issue #1073 and those should be put onto live first. So @natalianorori I will let you know as soon as we update the live system with the changes from that issue, then you will be able to proceed.

**Comment by natalianorori** [comment]
Thanks Mark, please keep me updated to upload all our offline moderation to
the live site.

**Comment by markmacgillivray** [comment]
OK, this is the right issue for this comment :)

@JosephMcArthur @natalianorori the live API has now been updated, so it should be possible for you to import records and click the checkbox on the import page to indicate that you want emails to be sent out as well.

@natalianorori I have tested this, but if possible could you please try an import of just a couple of requests with the checkbox checked, and then let me know which requests they were (email me a copy of the sheet you imported), and I can also check to see that the expected changes happened and that the emails got sent.

There is no reason why this should not work, but as we recently had issues with getting the emails to send on live when people created requests, I want to make sure that there are no gaps in the logic that could cause this to make you think that emails were sent for many requests when they weren't, so this extra check seems valuable.

It will only take me a few minutes to check that emails were sent once I hear from you, then you will be able to do more imports any time after that.

**Comment by natalianorori** [comment]
An update here, I already tested it out and sent the sheet of requests
imported to Mark for him to check if emails were sent out correctly.
