### ISSUE TITLE
Spending limit for bing

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1119]
We need to make sure that we don't accidently spend too much on bing. 

> I can add code to query for how many requests we have checked against bing in the current calendar month any time a bing check is requested. If we are over the limit we set, then it will not run.

**Comment by markmacgillivray** [comment]
Changed to feature, rather than bug - more like an MS bug, not ours. So adding a feature to job runner that can implement caps. In progress.

**Comment by markmacgillivray** [comment]
@JosephMcArthur if we hit the cap on bing, what do you want to do about the process that hits the cap, and subsequent ones within the cap window?

e.g. if we are running a find and we hit our bing cap, should the find run anyway but without bing, or should it not run at all, or should it wait until the cap is cleared again?

Waiting until the cap is cleared could be a long wait. That would certainly be no use for things triggered by the UI/plugin etc. But for batch jobs, admin jobs, etc, would you want them to wait and run once the cap is cleared? Or just run them without bing so they get processed sooner?

For example if the bing cap is "10k per month", if we ran 10k within a few days, anything else waiting for the cap to lift could be stuck for nearly 4 weeks.

So I imagine we just run anyway but without bing... thought I'd better check though. This could make certain analyses appear skewed, like if you run one big job to see what sort of returns we get and then a few days later you run another, if we are just going ahead without bing if we reached the cap, you could get different results.

I can do either way, I am building it as configurable option, just need to know what best suits your intended use.

**Comment by JosephMcArthur** [comment]
> e.g. if we are running a find and we hit our bing cap, should the find run anyway but without bing, or should it not run at all, or should it wait until the cap is cleared again?

Keep running that find, but stop the next one. Keep running find just without bing for the rest.

**Comment by markmacgillivray** [comment]
Sorry didn't update these issues during the week. A capping system has been added to the code and tested in general, but still need to run a specific test with it on oabutton bing connections. This should be done on Monday, then will push it to live.
