### ISSUE TITLE
Tidy up (and export) ISSN collection & SR calling with it. 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1127]
Seems like (in manual checks) we're missing some SR stuff that could be found with ISSN.

From Mark:

> We search sherpa with journal title. At some points we do collect ISSN from crossref, but I don't know if we do at all points or if we always have it before we search sherpa. If we do have an issn for a request, yes we could export it. 

Can we:

- [ ] tidy up to get ISSNs as much as possible from Crossref 
- [ ] call SR with both ISSNs and titles whenever possible (issn preferred by them I presume, and of course no need to do the second if the ISSN returns). 
- [ ] export ISSN in sheets

**Comment by JosephMcArthur** [comment]
For InstantILL, we'll want to get ISSNs during the find process too (they can be got from crossref, so not a massive deal) which it's probably helpful to note here.

**Comment by markmacgillivray** [comment]
If we get ISSN for instantILL do you also mean we should be using that ISSN to do the SR calling also mentioned in this issue? Is instantILL going to need to know sherpa colour or something else from sherpa?

@JosephMcArthur if the above is not needed, then this issue is done and can be closed.

**Comment by JosephMcArthur** [comment]
We do need the ISSN in instantILL, but not sherpa info. 

The original issue was as you had said the process for getting these in requests was a little all over and could do with a look in, but since our attention is elsewhere lets close for now as I've addressed the resulting issue in the bulk sheet for now.

**Comment by markmacgillivray** [comment]
OK yeah I have already reviewed where we get ISSNs and use them anyway, that is done. And it is already added to the exports. (on dev)
