### ISSUE TITLE
Collect Metadata for ILL's in a new mini-service

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1134]

**Comment by markmacgillivray** [comment]
To finish this I need to check what metadata is required - so far I am doing a check to see if we have already got: 

DOI, title, PMID, PMC ID, journal title, journal issn

If we don't have them, it does further searches to try to get them, if possible (e.g. if we have no DOI or title it is impossible to get any further anyway).

As mentioned in issue #1127 are you expecting this metadata to contain sherpa information too?

Is there anything else it must contain?

**Comment by markmacgillivray** [comment]
@JosephMcArthur once my previous comment is answered this can be finished pretty quick.

**Comment by JosephMcArthur** [comment]
We'd want:
* Author list, 
* publication date (split by year, month, day when possible)
* vol
* issue
* journal published in
* pages

**Comment by markmacgillivray** [comment]
journal published in meaning the title and issn? Or other metadata about the journal?

We currently don't collect vol, issue, or pages anywhere at all so that will take a little longer, but not much.

**Comment by JosephMcArthur** [comment]
Totally missed you already had journal title in the original, sorry! Void that.

**Comment by markmacgillivray** [comment]
OK

**Comment by markmacgillivray** [comment]
Done, on dev, details passed to @JosephMcArthur - still some testing to do, then can go live next week.

**Comment by JosephMcArthur** [comment]
Thanks Mark! I've given it a test and it fails to get meta-data through to email at the moment it seems. 

If you could get that working, and do some manual tests as discussed that would be great. 

During that, it would be great to get a feeling for wait times, I'm seeing about 5-15 seconds at the moment (5 for DOI, 15 for title) which seems reasonable but of course, more data is better (and perhaps I'm not measuring the time with meta-data retrieval). I don't want us to spend hours building something to test this... so let's just do gorilla testing for now and we can ask IUPUI do the same. Many hands make light work after all. In a later iteration, we'll want to consider how to unbundle all this probably. 

Seems like in all likely hood, by the time you've done that we'll be on the phone with each other... but regardless, I'll write my proposed next steps here. 

I think the second thing to do is some en-mass testing. As you know, I've set up a sheet which should make that easy for us to collaborate on: https://docs.google.com/spreadsheets/d/1PmghgbCLS94l0iHm_8o2XMKSuOhU53aif_GgN1--CCw/edit#gid=1529676005. 

There is one sheet that generates random DOIs and citation info, and also combines that into forms that users tried to do a lot in user testing (as it would be good to see how it performs then). There is also some titles that IUPUI have had requested by ILL before. Then, there is a sheet that queries the endpoint to pull back whatever we get. We can then dump whatever we need into the sheet and have it give us lots of answers rather than using the UI :) I'd suggest you spend some time on Monday investigating that so that we find problems and can make fixes before IUPUI does! If all is well, it won't take long, but if it isn't let's try and make fixes now while it's fresh (or, at least be aware of downfalls as we progress).

In the above, we want to check for accuracy and recall. How often do we get all the info needed, and how often is it correct. For recall, I've put some placeholders for checks there and that'll be easy to compute. For recall, I'd suggest we we once again try to make light work with many hands or I can use mTurk but I'd certainly suggest we do a couple of dozen each just to make sure something isn't really really weird. 

Either way, come the end of Monday, we should pass something over to IUPUI that works. 

On the call, we should discuss how to think about the openurl stuff.
