### ISSUE TITLE
Build out InstantILL UI for submission through ILL system

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1136]
TODO Joe to Expand

**Comment by JosephMcArthur** [comment]
This mock-up can be used: https://www.figma.com/file/Z99Le15hdGxU24uKkGVtX4iy/InstantILL?node-id=415%3A0

**Comment by markmacgillivray** [comment]
I think this is done, apart from the "other" stuff. I did not quite understand what you mean here, and it was not in the mockups, other than it just showing the links to start with. So we will need to discuss this to complete.

**Comment by JosephMcArthur** [comment]
Generally, links should be bolded and in the headers for responses need to be larger as in the mock-ups. 

Also, the mock-ups were spaced carefully to make it easy to read and separate options. Can we mimic this without CSS control with empty <p></p> tags or <br>?

**Comment by JosephMcArthur** [comment]
Also, when displaying paper info, we should only show volume / issue when we don't have other more useful info like journal name.

**Comment by markmacgillivray** [comment]
Links have been bolded and headers are now h2 size. Spacing has been increased by adding breaks. Volume / issue are no longer shown if the journal title is known.
