### ISSUE TITLE
measure how often we found meta-data in stats

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1142]

**Comment by JosephMcArthur** [comment]
@markmacgillivray can we display this in stats alongside the other figures. Can you use the 'automation' figure for display on the UI as calculated in the sheet we put together?

**Comment by markmacgillivray** [comment]
Just a note to say this is not done yet.

**Comment by markmacgillivray** [comment]
For each embed (uid), calculate the % for all metadata checks done, how many did we find all of article title, journal name, year published, and ISSN.

**Comment by markmacgillivray** [comment]
Also whenever someone hits "this is not the article I searched" that should be recorded as a wrong hit.

**Comment by markmacgillivray** [comment]
Add the two above values to the instantill usage table we already have on stats page.

**Comment by JosephMcArthur** [comment]
> how often we found the specified metadata for ILLs that DID actually get created

This. 

this number will never fluctuate.

> It will, users won't be able to / ever put in the ISSN #, so this figure will be a good reflection. 

The number is about how often submitted ILLs come with all the info required to save staff time, so this is a decent approach. This is true even if the user provided some of that metadata I think. 

Let's just keep the oa number as is, I think it'll provide a reasonable estimate as is. 

Is that all you need here?
