### ISSUE TITLE
Build out InstantILL UI for submission through email

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1144]
See mock-ups here: https://www.figma.com/file/Z99Le15hdGxU24uKkGVtX4iy/InstantILL?node-id=428%3A2

For this, during set up, we'll need to give a box for terms and conditions. 

This is subtly different in that we'll need to provide acceptance of terms, and a box for email.

**Comment by markmacgillivray** [comment]
I think this is done, could do with a test. Is already on live so can be seen on the IUPUI page.

**Comment by JosephMcArthur** [comment]
it seems you can submit the form without putting in an email, should address that

**Comment by JosephMcArthur** [comment]
I also haven't been able to make the T&Cs box appear when I've put that in

**Comment by markmacgillivray** [comment]
Added an email test. Also checked the t&c box, it shows when you don't have a base url.
