### ISSUE TITLE
Serial Subscriptions

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1147]
As discussed in 'Emails'. Joe to expand later.

**Comment by JosephMcArthur** [comment]
We can't do this right now, seems serial often use passwords. So, discussing how best to manage. 

@markmacgillivray , a quick question for you, could a campus whitelist our servers IP as 'on campus' if they were up for that? Do we have a static, personal IP? That would allow us to get past the password without any technical changes to our approach here. 

Once answered, we can move this to 'soon'.

**Comment by JosephMcArthur** [comment]
This issue includes work to add the:
- [ ] UI
- [ ] Stats
- [ ] Set up

and other supporting work

**Comment by markmacgillivray** [comment]
I believe this should work now, however it was more complex than hoped. I had to get the page then build a URL in some convoluted ways then try to follow that URL to get another URL. I still have testing to do, but am updating #1148 and #1149 as well, with full details in the SFX one about what is left to test, as it was the most complex. So will not close this yet, as further tests still to run.

**Comment by markmacgillivray** [comment]
Works
