### ISSUE TITLE
SFX Subscriptions

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1148]
This will be the same as serial solutions, but with a different page URL & tag to look for. Testing in person with a group, and will be sent code soon.

**Comment by JosephMcArthur** [comment]
Info sent over email.

**Comment by markmacgillivray** [comment]
This is related to #1147 and #1149 

I have had more problems than we had hoped in getting these to work. Apart from the need for server IPs being registered and pulling URLs from pages that then need to be followed to decode yet another URL, it has been tricky in particular to get SFX to work. It does not appear that their page actually displays the full results as we had expected to see them - to our server they come with a page that has an obfuscation link that must be clicked as if interacted on by a real user. The link target does not exist in the page structure and is built by their js on click. Following the code to further find how this is done would take even longer, and we are already falling behind on this.

For the other two, I think I have got them to the point of the user being given the link through to the article.

But for SFX, unless we spend even more time on it, the best I have so far is I can tell if the search page does contain an obfuscated link that should go to the article, and if it does, then that link is served to the user. This means it is possible the user will actually get a link to the page where they will then have to click the obfuscated link, which will then open the journal content (or login page, or whatever has to come next for them). But at least in the case where the search did not find a page that seems to link to a subscribed copy, we just won't serve the user a subscription link at all.

I am not sure whether users using this from their own locations are going to see something different than if they had followed the link themselves - they might. In which case they may not have to follow the obfuscation link, but will still get a search result page first. We will just have to get this tested for us and see how it comes out.

@JosephMcArthur if you are happy with the above, and don't want me to spend more time on trying to find a direct link for SFX, then tomorrow I should be able to finish the testing and ensuring these hook up to the plugin. I don't have much time left this week for more OAB stuff, but apart from the delay on this I should be able to get the other things we wanted done this week anyway, probably tomorrow.

If you want further exploring done on this, it will be at least another day of possibly fruitless work, and delay to anything else we won't be able to do instead.

**Comment by JosephMcArthur** [comment]
Let's ship what we have working on all fronts. On sfx, if we can only link
to the page and not give a direct link, that's okay, especially for now.
We'll learn more by testing what we have than plowing ahead with what we
know it seems.

**Comment by markmacgillivray** [comment]
Works
