### ISSUE TITLE
Create release tracks

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1152]
TODO: Mark to expand

**Comment by markmacgillivray** [comment]
This will be done by variables passed to the instantill.js widget, which will be used to control which new features a particular user sees. To control which users get which variable, we will tell them to go to different instantill_X pages on the website. The first one is instantill_alpha, which uses no variable and displays all features. We can create an instantill_beta as soon as we need it, change what that page displays, and have it pass the version:beta variable into the code that the user copies from that page. Then new features written into the js will be checking for that variable to see if the feature is allowed for that user. Placeholder has been added to the code, so this is ready to be used and the issue can be closed.
