### ISSUE TITLE
Add email verification to email submission box

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1153]
We should at least set something to flag an error if what's in the box isn't a full email, however, it may also be nice to loop in the email verification from mailfun if that's easy. 

Certainly important that those emails are right given we won't confirm any other way.

**Comment by markmacgillivray** [comment]
Note that mailgun verification counts against our quota now too though, so if we see a lot of usage of this then we will be doubling our increase in usage if we add a mailgun verification for every ILL.

**Comment by JosephMcArthur** [comment]
That's fine with me

**Comment by markmacgillivray** [comment]
Done. Also, updating live again just now so the latest version after todays work is on there too.
