### ISSUE TITLE
Allow ILL processing time & cost to be an editable value from set up

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1154]
These won't always be the same, so the campus may want to set it. 

TODO me to expand.

**Comment by JosephMcArthur** [comment]
Let's change the basic copy to be: 'It is free. We'll email a link within 24 hours.'

# cost

Provide a box with the following: 

* if nothing, make it free (this will be the default
* if there is a value, display it. We'll ask people to input something like '$4'. So, not _just_ a number.
* Have the box be called 'What do your article ILLs cost, please include your currency symbol? e.g '$4'.

# time

* Going to ask IUPUI about this. Essentially, it'll be similar to the above, I just want to ask for some advice.

**Comment by markmacgillivray** [comment]
Have added this, will assign back to @JosephMcArthur to update after further discussion with IUPUI, then can assign back to me with more instruction.

**Comment by JosephMcArthur** [comment]
This is going to need a bit of consideration, bumping out the sprint. However, create to have 1/2 done!

**Comment by JosephMcArthur** [comment]
I'm going to close this now, it seems unclear to me how to make it better than we have now given the complexity. Will revisit another time.
