### ISSUE TITLE
show only 'default X' in openurl set up boxes.

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1155]
Basically, don't repeat what's being set. Just makes that a bit clearer.

**Comment by markmacgillivray** [comment]
I think this is done, not sure what you mean though. I have removed the ones that said "no default". All other ones are openurl ones, I think. Or do you mean that you want default X removed from all of them?

**Comment by JosephMcArthur** [comment]
Currently the open url set up ones say what the thing being set is, then
the default. Since we put what is being set out the box, it makes sense to
remove it from the box (so it would only say 'default *'.

**Comment by JosephMcArthur** [comment]
e.g 
![image](https://user-images.githubusercontent.com/4953703/55610613-3303ed00-577b-11e9-8050-7ba3bd0f77c2.png)

can just be default: issue

**Comment by markmacgillivray** [comment]
Done
