### ISSUE TITLE
Better confirmation page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1158]
This is mostly on me to make better copy. 

@markmacgillivray can we easily pass user email to confirmation page. I'd like to say something like 'you'll be emailed at <<youremail>> with the paper'.

**Comment by markmacgillivray** [comment]
Yes, and for now I have added that. Assigning just to you for new copy then assign back to me once more can be done.

**Comment by JosephMcArthur** [comment]
Let's do the below: 

> **Thanks! Your request has been received.**
> 
> Your confirmation code is: `<<Code>>`, this will not be emailed to you. The paper will be sent to `<<Email>>` as soon as possible.

**Comment by markmacgillivray** [comment]
Done
