### ISSUE TITLE
Don't pass internal data to ILL staff emails

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1159]
They don't need:
* from: JkXSRq7RffwjgHQEn
* plugin: instantill
* embedded: https://dev.openaccessbutton.org/instantill_alpha#
* started: 1554288286092
* ended: 1554288300503
* took: 14411

since this isn't about the paper, more the process. Obviously lets keep this in our system.

**Comment by markmacgillivray** [comment]
OK, only paper metadata gets passed in the ILL staff email now.
