### ISSUE TITLE
Loading page improvements

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1161]
Let's discuss what makes sense, what we haven't now isn't going to work as is, so need to understand the simplest way to improve.

**Comment by JosephMcArthur** [comment]
- [ ] let's remove the massive text saying what you're searching for now, that would make it less bad an is easy

**Comment by JosephMcArthur** [comment]
Thoughts:
* Need to address that not all loading gaps are 'searching'
* Seems we now have a bar for errors now, can we have that for loading, with it showing above whatever 'page' we were on and any buttons / entry deactivated?

**Comment by markmacgillivray** [comment]
By massive text, do you mean not showing whatever value they typed in? Also, we do already have a bar for searching as well, it is a different colour for the errors. I moved the errors one down to the button you click on, based on your previous feedback. The loading one is in a different place though. Do you want that one down where the errors one is? What gaps are you seeing "searching" for that are not searching? What do you want it to say instead? And you mean you don't want it to remove whatever boxes you typed into, just show the searching bar but leave the boxes, but make them all deactivated... I'm not sure I see how that is better than just removing them, but OK.

**Comment by markmacgillivray** [comment]
Have removed what I think is the massive text, but have not left unusable boxes visible, they still hide. Will await further instructions for what to do here.

**Comment by markmacgillivray** [comment]
When finally submitting, the "searching" alert does not make sense so I changed the text in the alert to say "submitting" in that context. I did not notice it showing up at other times where the content did not make sense, but if there are any, or any other things you still want changed here, let me know.

**Comment by JosephMcArthur** [comment]
Ace, thank you! Seems good for now, no stronger ideas, let's await feedback.
