### ISSUE TITLE
User export gives files with no entries

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1173]
Not urgent, rarely used.

**Comment by JosephMcArthur** [comment]
note: joe if you need the total number you can see it on admin

**Comment by JosephMcArthur** [comment]
To replicate:

* Go to https://openaccessbutton.org/export
* Select users to export
* Hit export
* open covert file downloaded
* note it is empty

Expected: you get a csv of the users.

**Comment by JosephMcArthur** [comment]
Note though. Still not that important. The total number is fine most of the time. Occasionally... we need the emails though (including for https://github.com/OAButton/internal-planning/issues/81)

**Comment by markmacgillivray** [comment]
Fixed on dev
