### ISSUE TITLE
Some DOIs not giving titles to InstantILL

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1186]
e.g 
* 10.1080/19376812.2017.1284007
* 10.1145/2908080.2908114 (this is our test DOI, which seems to suddenly not give answers)

**Comment by JosephMcArthur** [comment]
One other related matter, when I tried to submit these, the meta-data finding meant that it gave a super duper slow rejection. That seemed odd, although I realize that it's exactly what we'd expect. Just noting.

**Comment by markmacgillivray** [comment]
Fixed, was related to bad caching of earlier test results
