### ISSUE TITLE
Add a note when the user enters their own meta-data

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1196]

**Comment by markmacgillivray** [comment]
By "note" do you mean a note to our record? Or a note on a UI somewhere? If note to our record, I have done this and the issue can be closed.

**Comment by JosephMcArthur** [comment]
I mean a note in the openurls we create for ILL staff. Much like we do when we find OA / Subscribed stuff (or, don't).

**Comment by markmacgillivray** [comment]
OK, can do that. How detailed? Just saying "user gave us stuff" or specifying what the user provided and what we provided?

**Comment by JosephMcArthur** [comment]
Just 'user gave stuff'. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
A note has been added to generated openurls to say "The user provided some metadata" when that is the case.
