### ISSUE TITLE
In notes field, presence of '&' in URLs can confuse openurl. Need to escape characters. 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1197]
Seen in 

Ribulose bisphosphate carboxylase: a two-layered, square-shaped molecule of symmetry 422

https://uva.hosts.atlas-sys.com/RemoteAuth/illiad.dll?Action=10&Form=22&Value=ArticleRequest&genre=article&rft.atitle=Ribulose%20bisphosphate%20carboxylase:%20a%20two-layered,%20square-shaped%20molecule%20of%20symmetry%20422&pmid=17756097&pmcid=PMC4167664&rft.au=Baker,%20T%20S,%20Eisenberg,%20D,%20Eiserling,%20F&rft.title=Science%20(New%20York,%20N.Y.)&issn=0036-8075&volume=196&rft.issue=4287&pages=293-295&date=1977-04-01&rft.year=1977&cache=true&&notes=Subscription%20check%20done,%20found%20nothing.%20OA%20availability%20check%20done,%20found%20http://europepmc.org/backend/ptpmcrender.fcgi?accid=PMC4167664&blobtype=pdf.

where the url appears in illiad as

http://europepmc.org/backend/ptpmcrender.fcgi?accid=PMC4167664

**Comment by markmacgillivray** [comment]
This is true, but beyond our control. I can encode the URLs within the notes field, but then the information we pass IN that field would be an encoded string, so probably would be even more gibberish to the end user than the wrong unencoded string. I can encode it if you want though, with this caveat.

**Comment by JosephMcArthur** [comment]
Got it, let's close.
