### ISSUE TITLE
Improve API Docs

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1199]

**Comment by JosephMcArthur** [comment]
@markmacgillivray: next week, can we do a 2 hour meeting where we do our regular chat & we review edits to the API pages. I'd like to give them an upgrade. 

Some edits are [here](https://docs.google.com/document/d/1E19gjd9aQm4fquQzlO3rk2M6akpQWVdOGpztn5eqkEo/edit#) but tbh we should just spend an hour walking through together.

**Comment by markmacgillivray** [comment]
Me to go through the ILL endpoints and make them have the form of the earlier ones we have gone through

**Comment by JosephMcArthur** [comment]
As part of this let's:

- [ ] move /ill/* endpoints to /*.
- [ ] finish docs

**Comment by markmacgillivray** [comment]
Will finish these up once I complete the refactor review, in case that has any impact

**Comment by JosephMcArthur** [comment]
Planning to talk this week to complete technical bits, then next week we'll get code on the site.

**Comment by markmacgillivray** [comment]
@JosephMcArthur the API page on dev still looks like the old page - is the new content we worked on somewhere else on the website? I can't add js very easily without the finalised content, and can't format sample post code nicely if it is still just in a google doc. If you're wanting me to move the new content from the google doc to the site, format it there, then add the js mentioned above, I can do that - just checking.

**Comment by JosephMcArthur** [comment]
I've made a new page at api/new.html where content can go. I've put in /find and /subscribe, which has the example where we need cURL code to pop out and instantill keys need adding.

I'd say, put any post examples needed on that page, with a simple heading / link to pop them out, and I'll wrap them with all the final final copy when I've done it.

Sound okay? 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
ah yes sorry my IDE did not autorefresh

**Comment by markmacgillivray** [comment]
OK. What does finish doc code mean?

**Comment by markmacgillivray** [comment]
By "move ILL endpoints" do you mean move them in the code, or just in the documentation? If in the code, do you mean on dev or on live?

**Comment by JosephMcArthur** [comment]
Move them in the code. Dev, then live on next push. So that
/Ill/subscription sits at /subscription and whatever was using those routes
is updated.

'finish code doc' is for me. Just copy.

**Comment by markmacgillivray** [comment]
OK I have moved the /ill endpoints that I think are relevant to the public docs. There are still some at /ill/* which are for internal use, and don't make much sense to move, such as /ill/validate, /ill/config, /ill/openurl

I think this is my tasks on this issue done so will unassign myself and move on. However, if there is anything you still want done, re assign me and I will move back to this one.

**Comment by JosephMcArthur** [comment]
Re: moving /ill routes, that sounds good to me.

Can see the example stuff too, looks good.

Not seeing the example for POSTs though, am I missing those? 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
I've only put in one working example to the api/new page, I can put in more once you add the content. I assumed POSTs will work the same - click an example button, show a code box, right? Or do you want something else put in for them?

**Comment by JosephMcArthur** [comment]
Yeah that would be the same.

It's your call, if you want to put them in now (just an example link, as
it'll be obvious what api it's for) then we can close this. Otherwise, I'll
circle back when I've done final final copy.

**Comment by markmacgillivray** [comment]
I'm not sure what more I could do right now for a POST than I've already done for the GET example. Would be easier to go through once the content is there I think.

**Comment by markmacgillivray** [comment]
Those API changes are only on dev by the way, not on live yet.

**Comment by JosephMcArthur** [comment]
Sure thing, then I'll put up final copy and you can finish then. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
Okay, a few TODOs in code, but otherwise the copy is up and essentially final.

**Comment by markmacgillivray** [comment]
OK these TODOs have been done, please have a look and close this issue if you are happy with it

**Comment by JosephMcArthur** [comment]
Just looked, all the todo's look great. Made a bunch more changes, including notably moving the page back to /api.

One thing you didn't do is what was left from yesterday, examples for the posts. Just look for posts without examples just.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
OK, I have added those. Please check and close if you are happy with that.

**Comment by JosephMcArthur** [comment]
Cracking, thank you! 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur
