### ISSUE TITLE
Use of '+' in URLs causes titles not to be recognised

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1201]
This is a priority to fix. It affects ILL tools like DeliverOA on Illiad and likely other systems. 

The URL generated by the system is:

https://openaccessbutton.org/?from=illiad&url=Ribulose+Bisphosphate+Carboxylase%3A+A+Two%2DLayered%2C+Square%2DShaped+Molecule+of+Symmetry+422

which used to be understood by our site, but now isn't. Instead, it tries a search but flags a 'this citation is too short' warning.

**Comment by markmacgillivray** [comment]
Fixed, allowed strings without spaces as long as they have + instead, by converting any + into space, and then doing the usual check for minimum number of spaces
