### ISSUE TITLE
error on embed

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1212]
` } catch (e) { console.log(e); } 
`

coming up after embedding, example https://www.ambs.edu/library/instantill-test

**Comment by markmacgillivray** [comment]
Sorry, didn't update issues last week, but did look at this - it is not created by our code. It is coming from the CMS system that is being used to generate the pages, so must be something to do with how that system wraps the form in which they are trying to enter our js widget code. There is nothing we can do about this. Will assign to you to get back to them about it, or can close if no followup needed.

**Comment by JosephMcArthur** [comment]
Make sure they're putting in a HTML box, not java.

**Comment by JosephMcArthur** [comment]
passed this on, closing as we can't fix.
