### ISSUE TITLE
adding 'try again' when we don't find anything

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1213]
This would be clearer than having people have to refresh. Add under 'continue' (when we show the input form) as a bold link.

**Comment by JosephMcArthur** [comment]
Add a similar button on the submission confirmation page when submitting over email.

**Comment by markmacgillivray** [comment]
This is done, shows at the expected points, I think. Have a look on dev and close if happy

**Comment by JosephMcArthur** [comment]
perfect!
