### ISSUE TITLE
Wrong article workflow problems

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1216]
Two issues, likely related:

* when I complete the wrong article form (when we don't initially match), it often then says it can't match the article. That's not the intended idea, if someone fills in that form they should always be able to submit. 
* I've been told that sometimes when people fill that in, the data doesn't make it to the ILL form / email. This is what I was going to test when I found the above. They were testing EXAMINING CRM AND ECRM ADOPTION BY GREEK FIRMS when they found the bug.

**Comment by markmacgillivray** [comment]
In progress

**Comment by markmacgillivray** [comment]
After user gives us metadata, e.g. after we have failed to find it on simple search first time, we should still do another full search but if we don't find anything we should not be passing them through the full loop again asking them for metadata etc again - just pass them straight to an ill submission if we did not find anything else.

**Comment by markmacgillivray** [comment]
Done, added another variable to track when we have already been given metadata by the user and allow that to proceed regardless of how many times we have tried a lookup ourselves.
