### ISSUE TITLE
Use 'names' where available instead of 'name' in Zenodo deposit 'creators'

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1217]
It sounds like Natalia often has to fill in all author names in Zenodo as we only pass 'name' (the author addressed in the request) rather thans 'names'. Where we have it (which isn't always) we should pass 'names' as a neat list. Where it isn't available, we'll pass 'name' still. 

If we have nothing, do whatever we do now.

**Comment by markmacgillivray** [comment]
If names is present in the request, and is a list of strings, each string being a name, these will be used as the names passed to zenodo. If not present, previous behaviour still applies, which is to use any name provided during the receive execution, or any name available in the request in the name field, or the name of the first author, if known.
