### ISSUE TITLE
Add fields to request data, and have zenodo deposits use them

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1219]
Following from #1015, we can now set:

* access_right
* embargo_date
* access_conditions
* license
* description

correctly through our new permissions system. During moderation, and then bulk upload to the site, we can set these fields for most requests that pass through the system. Setting these at that point would save Natalia a lot of work right now, as currently she has to set one by one by hand. 

Doing this now provides a good production test before we take a 'hands off' approach. 

Mark, can you estimate how long it would take to add those to request fields, display them on the request system UI for admins (as simple info boxes), and use them to set deposits in Zenodo. Presume that I will handle actually coding up the rules to set all these values for the bulk upload. I'd like to do this asap if we can.

Where we didn't provide these, we should just do what we do now.

This is a big step towards #738, #991, #483, #1096, #1098, #1111. In fact, it would essentially close them as far as requests were concerned. The depository would then need us to port a lot of logic I've build elsewhere into the API / site etc.

**Comment by JosephMcArthur** [comment]
We would need some logic on the site to review the date of the embargo vs the date of deposit. It would just need to review the date given, and if it's before today use that, and otherwise make it open.

**Comment by JosephMcArthur** [comment]
Update from my end, and a few questions. 

I now have our bulk moderation system able to generate (hopefully) these values, except access_conditions which aren't required. 

Of note:
* I've used headings that match with `access_right` &  `embargo_date`
* Only `open` and `Embargoed` are used for `access_right`
* Dates are provided in YYYY-MM-DD, which should match with zenodo
* Licenses are provided as `cc-by`NOT `CC-BY` which matched what you'd previously said about that field. 
* the description field is intended as plain text. e.g

> The publisher's final version this work can be found at https://dx.doi.org/10.1177/0032885516650873 Deposited by openaccessbutton.org. We've taken reasonable steps to ensure this content doesn't violate copyright, however, if you think it does you can request a takedown by emailing help@openaccessbutton.org.

You can see some of this here: https://docs.google.com/spreadsheets/d/1gdfyX__u6inRxPYdRL6rKgopA04h8EJ7negxPrUofh0/edit#gid=1665451686. 

Let me know if you have any questions!

**Comment by markmacgillivray** [comment]
This has been done on dev, should probably be tested to see if it meets what you expected, so not closing straight away

**Comment by JosephMcArthur** [comment]
@markmacgillivray can we have the 'cc-by' license be set by the new license field? If it's not specified, still use cc-by as now.

**Comment by JosephMcArthur** [comment]
@markmacgillivray on the import page, on dev, /import throws the following errors

> Sorry please fix and try again. Your csv contains columns with unacceptable field names: ["access_right","embargo_date","access_conditions","license"]

Can you fix this asap plz?

**Comment by markmacgillivray** [comment]
done, on dev

**Comment by JosephMcArthur** [comment]
and the license part?

**Comment by markmacgillivray** [comment]
license - means on the request response page show whatever the license field says rather than the default cc-by link that gets shown to the user in the page content.

**Comment by markmacgillivray** [comment]
Done
