### ISSUE TITLE
add quick action for accepted paper

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1220]
Mark, can we add a quick action in the request UI to:

* Send /email/requestors_request_success_article.html to the user, and any supporters
* Send /email/author_thanks_article.html to the author
* Adjust the status to successful, and show the zenodo link

Call it 'successful upload'.

For now, this will *not* affect anything in Zenodo. Publish / not-publish functionality will still live there. @natalianorori, does this seem okay?

**Comment by markmacgillivray** [comment]
Also done. Do you need to test or have natalia look at it?

**Comment by JosephMcArthur** [comment]
@natalianorori can you tell us if this looks okay?
