### ISSUE TITLE
quick action for rejected paper

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1221]
Mark, can we add a quick action in the request UI to:

- [ ] Send /email/emails/author_thanks_article_rejection.html to the author 
- [ ] Reset that status / deposit page to allow another upload

Then, I need to:

- [ ] I need to write that email!! 

Call that, 'Reject Upload'

For now, this will *not* affect anything in Zenodo. Publish / not-publish functionality will still live there. @natalianorori, does this seem okay?

**Comment by JosephMcArthur** [comment]
@natalianorori can you confirm this looks okay before I write the email?

**Comment by JosephMcArthur** [comment]
@markmacgillivray, when I write the email & sync production are we good to close or do you need to do other stuff?

**Comment by markmacgillivray** [comment]
I'll need to update live as well.
