### ISSUE TITLE
when importing through bulk, requests that don't change their status get emails that suggest they do

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1225]
From Natalia:

> I created 4 requests:1 on help status, 1 on moderate, 2 on progress and 1 in closed. Did the changes on the sheet and then imported them back again, tickling the box that says that users from requests should be notified through email. Ideally, I should have only gotten 2 email notifications, but I got notified for all requests, even for those who were not "sent to the author".

**Comment by markmacgillivray** [comment]
I started looking at this but have not finished yet. I suspect that this is because it is how we we built it, and the assumption is indeed that any bulk import with a status change expects them all to have the same status change and to expect them all to get the same email. If this is how we did it, and not what is wanted, what do you want instead?

**Comment by JosephMcArthur** [comment]
How much have you already done? I wanted to chat about this a bit before
moving ahead.

Perhaps pause until we chat.

**Comment by markmacgillivray** [comment]
Yeah no problem, chat is where I am up to. All I did do so far was look at it and work out if there is something wrong or if it is intentional but just not what we want - seems to be intentional. So can discuss tomorrow then will change it.

**Comment by markmacgillivray** [comment]
Only send the progress action if the status was help or moderate and has moved to progress in the bulk upload.

**Comment by JosephMcArthur** [comment]
Think this would take a few hours to do for Mark. I think that's too much, so I'll fix some other way.

**Comment by JosephMcArthur** [comment]
Okay, I have reverted the system on our sheet to just export processed requests. 

However, that does mean we're still losing data from moderated requests that aren't sent. So, asking @markmacgillivray 

> Mark, on the import page, I can import JUST the fields changed right (against the ID) and leave everything out the import, right? 
> 
> If I did that, with say, a request that needed moderation, and I imported '1' in 'rating', what would happen with the status on the site. Would the status update accordingly? 

Doing this as figuring out new status in the sheet is complex, and likely to go wrong depending on the order natalia does stuff etc. Considering this logic must be in the site, just importing new data to power status changes seems to make sense.
