### ISSUE TITLE
Simpler request export for bulk moderation

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1226]
It would be good to be able to export requests on help & moderate (without closed stuff), from a certain date, in one go from /export. This would be for bulk moderation.

**Comment by JosephMcArthur** [comment]
Est: Maybe an hour

**Comment by markmacgillivray** [comment]
Done

**Comment by JosephMcArthur** [comment]
Can you confirm how this works from a UI perspective? It seems hard to select more than one value.

**Comment by JosephMcArthur** [comment]
- [ ] Can you make it possible to export requests filtered on stories? 
- [ ] Can you also make the default start point not right back in 2013? Can you make it like a week ago or something like that?

**Comment by markmacgillivray** [comment]
Meaning if a story is present or not

**Comment by markmacgillivray** [comment]
Done
