### ISSUE TITLE
Show new fields to request moderation box 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1231]
The fields that should be added are the same as in #1219.

**Comment by markmacgillivray** [comment]
What does this issue mean? Added to where? In that previous issue we already did add them, they show up in the admin area for the admin to moderate the request, when they are known.

**Comment by JosephMcArthur** [comment]
Ah yes, so they do. Can they be editable boxes? Natalia may want to edit them from the site from time to time.

**Comment by markmacgillivray** [comment]
ok

**Comment by markmacgillivray** [comment]
OK, done
