### ISSUE TITLE
Incorrectly suggesting access when not giving FT link via subs

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1234]
Follow on from https://github.com/OAButton/discussion/issues/1210.

In that, when we only get journal meta-data, my understanding is that we're using some indication in the XML of that.

I started testing with others, and they flagged false positives on this. 

For example, with 10.1098/rsta.2018.0267. At RIT, on the UI, it gives [this response](http://yv4zn7rr3m.search.serialssolutions.com/?sid=sersol%3ARefinerQuery&url_ver=Z39.88-2004&l=YV4ZN7RR3M&SS_ReferentFormat=JournalFormat&rft.genre=article&rft_id=info%3Adoi%2F10.1098%2Frsta.2018.0267&SS_doi=10.1098%2Frsta.2018.0267&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&citationsubmit=Look+Up&paramdict=en-US&rfr_id=info%3Asid%2Fsersol%3ARefinerQuery&SS_LibHash=YV4ZN7RR3M). The XML for that is [here](http://yv4zn7rr3m.openurl.xml.serialssolutions.com/openurlxml?version=1.0&sid=sersol%3ARefinerQuery&url_ver=Z39.88-2004&l=YV4ZN7RR3M&SS_ReferentFormat=JournalFormat&rft.genre=article&rft_id=info%3Adoi%2F10.1098%2Frsta.2018.0267&SS_doi=10.1098%2Frsta.2018.0267&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&citationsubmit=Look+Up&paramdict=en-US&rfr_id=info%3Asid%2Fsersol%3ARefinerQuery&SS_LibHash=YV4ZN7RR3M). 

A successful one, for 10.1111/evo.13748, looks as follows in [the UI ](http://yv4zn7rr3m.search.serialssolutions.com/?sid=sersol%3ARefinerQuery&url_ver=Z39.88-2004&l=YV4ZN7RR3M&SS_ReferentFormat=JournalFormat&rft.genre=article&rft_id=info%3Adoi%2F10.1111%2Fevo.13748&SS_doi=10.1111%2Fevo.13748&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&citationsubmit=Look+Up&paramdict=en-US&rfr_id=info%3Asid%2Fsersol%3ARefinerQuery&SS_LibHash=YV4ZN7RR3M) and [XML](http://yv4zn7rr3m.openurl.xml.serialssolutions.com/openurlxml?version=1.0&sid=sersol%3ARefinerQuery&url_ver=Z39.88-2004&l=YV4ZN7RR3M&SS_ReferentFormat=JournalFormat&rft.genre=article&rft_id=info%3Adoi%2F10.1111%2Fevo.13748&SS_doi=10.1111%2Fevo.13748&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&citationsubmit=Look+Up&paramdict=en-US&rfr_id=info%3Asid%2Fsersol%3ARefinerQuery&SS_LibHash=YV4ZN7RR3M).

In the false positive, I'm not seeing an element that would suggest a journal link / access is available, so I'm not sure why it's coming up. Both have `<ssopenurl:result format="journal">` but I thought we were looking for something else.

Looking back at the [test of our integration](https://docs.google.com/spreadsheets/d/1LYla2xW0YkThmQiBEiXlzyfx6EZG69a0COTjR4fbtzM/edit#gid=939719120) I'm seeing that some of the 'true' ones in column K do not actually look available when searching their DOIs in the UI. So, perhaps we were looking at the wrong signal for that, or our signal is just too broad. Either way, we need to re-sync on how this works and adjust accordingly.

**Comment by JosephMcArthur** [comment]
Note: Mark confirms that if we find: <ssopenurl:result format="journal"> we do infact think there is journal access.

**Comment by markmacgillivray** [comment]
For now Joe says turn off the journal match, and only say we have a match when we have the fulltext link. Keep this though to come back to later, to find out which ones should actually indicate a journal subscription.

**Comment by markmacgillivray** [comment]
Disabling has been done

**Comment by JosephMcArthur** [comment]
Having done a review of more content here, it looks like this will do for now. It's not perfect, but not as big of an issue as other stuff.
