### ISSUE TITLE
Building fake demo ILL page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1246]
Clarify with Mark how best to do this.

**Comment by JosephMcArthur** [comment]
Page to make is here: https://www.figma.com/file/1UfMhSFnoydCDhosfqUSmT/InstantILL-Setup-%26-Marketing?node-id=817%3A119.

**Comment by markmacgillivray** [comment]
I have done this functionally on the alpha_rebrand page, as I was doing the other additions there, and it was quicker than adding the code to both. But it can be added to the demo_ page too, if you actually need both for some reason.

Note, I was able to get it to load within the page, with no need to open new pages, etc, so it works pretty well. There are still some UX questions around what to do to actually prod the user to do that though, as it is not obvious that they should be expected to click the "complete request" button. Also, what should they do after, once they are looking at the fake ILL?

But anyway, you can see that working there now and see what you think.

This took a bit longer than hoped, but it was probably worth it to get it working within the page, and now we can more easily embed the demo in different places. I still have some more time to spend on this sprint but need to put some effort into the other issues.

**Comment by JosephMcArthur** [comment]
This looks great all round! Will likely have small requests for changes eventually, but can close now.
