### ISSUE TITLE
'#embeddedexample' not working on workflow

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1249]
Seems to not show up. Tested on my end and with IUPUI.

**Comment by markmacgillivray** [comment]
As far as I can tell this is working. When I am logged in I see the embedded example paragraph, and when I check a similar query from your account I can see values there that should get pulled back in the same way. We will probably have to look at this again while on a call and see what is going on.

**Comment by markmacgillivray** [comment]
We checked, this did not work for Joe, the query returned back empty. I checked, but there was definitely results there for his user ID. So, investigate further

**Comment by markmacgillivray** [comment]
Tested again, and tested using Joes user ID, found an error in the search query where it does not find the exact term match on the "from" field with complex IDs. So, switched it to a from.exact term match and now it works.

@JosephMcArthur please check this on dev when logged in as yourself, and if it works you can close this issue.

**Comment by JosephMcArthur** [comment]
working!
