### ISSUE TITLE
Config option to turn off ILL submission when OA or Subs are available

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1252]
wysiwyg. These should be separate options for subs / oa.

**Comment by markmacgillivray** [comment]
This is done and tested but @JosephMcArthur should take a look to make sure it is as expected

**Comment by JosephMcArthur** [comment]
Tested the OA one. Works as expected. May later suggest that we make the links into buttons too, but I need to check with Sam first. For now, closing.
