### ISSUE TITLE
allow toggle-able 'paper' vs 'article' language in InstantILL copy

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1256]
Seems there are some significant regional differences (or at least strongly held opinions) about what term to use that could confuse people. This helps address a fair few copy concerns I've seen, and seems easy, would propose we include.

**Comment by markmacgillivray** [comment]
Done and tested but @JosephMcArthur should check it is as expected

**Comment by JosephMcArthur** [comment]
Tested! Looks great.
