### ISSUE TITLE
PMIDs in LR's are resolving to the wrong article

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1257]
> Sent over from Ex-libris.
> 
> The problem is that openaccessbutton.org is returning the same wrong article for multiple unique PMID requests: 
> 
> https://openaccessbutton.org/?url=16499135 
> 
> https://openaccessbutton.org/?url=7355947 
> 
> These are different articles and they both point to a third, wrong article at https://core.ac.uk/download/pdf/38142439.pdf 
> 
> This makes the integration with 360 Link fail as seen in the button linking to the wrong article from these No Results Pages: 
> 
> http://vb3lk7eb4t.search.serialssolutions.com/?genre=article&id=pmid:16499135 
> 
> http://vb3lk7eb4t.search.serialssolutions.com/?genre=article&id=pmid:7355947 

First sent over two weeks ago, but appears to have got lost in transit. Could it be related to #1186 ?

Putting here to investigate, but short term could up https://core.ac.uk/download/pdf/38142439.pdf  on our 'do not send to' list. 

- [ ] On closing, contact reporter. 'RE: Linking issue (EL *661100)'

**Comment by markmacgillivray** [comment]
Investigating the first one, 16499135, there appear to be combination of issues causing this:

* A current uncached check actually returns something else - a taylor and francis link https://www.tandfonline.com/doi/pdf/10.1080/17521740701702115?needAccess=true that requires login, which is being provided to us by OADOI, for the DOI 10.1080/17521740701702115

* that DOI is not for the correct article - it is for an article titled "MEDLINE, PubMed, PubMed Central, and the NLM:

* whereas PMID 16499135 is actually titled "For neuropathic pain, optimize opioids." according to EUPMC, where we look it up.

* But EUPMC does not provide us a DOI for that PMID/title

* We don't do a crossref resolve before EUPMC, because we only have a URL at that point, but after EUPMC we SHOULD get the title and do a reverse lookup for that

TBC - saving due to browser issues

**Comment by markmacgillivray** [comment]
On further checking with Joe we noticed the article server by T&F actually IS available. It didn't appear to be available earlier in the day, but we believe it is possible it may have changed. Anyway, this means there is no need to further explore OADOI as an issue here, and the DOI we were looking up by that point was incorrect anyway. Just noting this so we remember.

**Comment by markmacgillivray** [comment]
The issue we do actually have to solve is that we are incorrectly reading EPMC results, or EPMC is sending incorrect results (probably our issue, as EPMC has been fine in the past, but may have changed in a way we don't handle).

Also, we noted that CORE returns what appears to be a pdf link EVEN THOUGH it is actually a 404 page. We don't know why it bothers to serve us a link that only goes to a 404 in the first place, but it seems they do. So we are investigating why it does that, when else in the past we can track that it did that, and, if we can't reliably trust links from CORE again, we may remove CORE from our lookups again. We could also check whether links they give us just go to 404s, but we have had issues getting wrong or very slow results from CORE in the past, so will decide which is the best solution for us.

**Comment by markmacgillivray** [comment]
Note also it is a 404 page and also returns a 404 status. So, if we are getting this URL from the CORE system, they are serving URLs that point to nothing. It is possible they don't know this, if something is supposed to be present at that address, in which case these would be valid URLs to open content. So we should probably check with CORE if the error here is that the item is not really open, or if it should be open but their system is serving it wrong. (Waiting for an answer from them on this does not need to hold us up though, we can choose to test their links or drop them from use for the time being anyway, and revisit later if we hear back from them.)

@JosephMcArthur I will check this a bit further, then write up some more info, and you can choose if you'd like to get in touch with them about that part.

Either way, the CORE issue is not the "core" issue for us :) we still have to fix the EPMC part where we probably went wrong in the first place, and that work is continuing.

**Comment by markmacgillivray** [comment]
Our error in reading EPMC results has been found, it lay in us expecting a fulltext url list which appears to not always be present, whereas at some point we expected it even if empty.

Also, it appears that although we get back the aforementioned URL from OADOI, we are sometimes serving up a captcha challenge URL in front of that, and an error on the T&F website is failing to redirect successful challenge responses to the article - instead it just redirects to the T&F website front page. So I need to find out where we are picking up the challenge from, if oadoi is not presenting it (probably comes from when we try to load URLs ourselves to check their validity).

Continuing to investigate.

**Comment by markmacgillivray** [comment]
Fixed the code where we switch the direct URL with the captcha challenge.

**Comment by markmacgillivray** [comment]
Resolve code has been strengthened to not rerun reverse lookup if something that at least looks like a new title has been discovered from EPMC or other source.

**Comment by markmacgillivray** [comment]
Whilst the error is fixed we still have decisions to make about CORE, and will at least have to run some scripts on our data to clean up. There are about 100k availabilities in our live system that link to CORE. Quickly checking a few manually, I was able to find other CORE PDF links other than those listed above that also don't work, some recent and some up to a year ago. There are also some that do work though.

* We could figure out why CORE returns these wrong links - but could take a while, probably a day to start and then can continue or not.

* We could continue using CORE and do a GET check on every URL we receive from CORE to see if it really is there (will take about an hour). This is probably a good idea whether or not we do the investigation above.

* Or we could stop using CORE as a source again, until we have time to work out why it sometimes does this (will take about ten minutes to disable it).

* Regardless of what we choose above, we do need to clear the CORE cache on our system (won't take long, maybe an hour)

* We also need to clear the availabilities history - either of all CORE availabilities (won't take long, maybe a couple of hours) or check them all and only remove those that return 404s (slower, maybe a day or 1.5 days)

We can discuss this today

**Comment by JosephMcArthur** [comment]
2, 4 & 5 make the most sense to me at face value, but lets discuss.

**Comment by markmacgillivray** [comment]
Remove CORE from how we process finds for now. Wipe our cache. Remove all CORE availabilities, don't bother checking them, just remove all.

**Comment by JosephMcArthur** [comment]
- [ ] move stuff to fix core long term to a new issue

**Comment by markmacgillivray** [comment]
Core has been removed on dev, and have added code to not re-use any previous availabilities we found in core, but I did not wipe our cache and old availabilities as we have since been asked further questions, and if we want to do later analysis we will need the cached data.

**Comment by markmacgillivray** [comment]
Also to decide if we are putting more time into this issue to be able to respond with more useful info for Core.
