### ISSUE TITLE
show full publication date in moderation boxes for dates

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1258]

**Comment by JosephMcArthur** [comment]
@natalianorori is this *always* not there, or *sometimes* not there

**Comment by natalianorori** [comment]
always not there. We always get the year only.

**Comment by JosephMcArthur** [comment]
okay, this is likely to just be an issue with our data not ending up in the right place then. Over to you @markmacgillivray

**Comment by markmacgillivray** [comment]
I added a display of either "publication year" or "publication date" to the request admin info area, however it will only show when we do succeed in getting a publication date. I have done some extra testing on this to see why we might not always have them, and here is an example:

https://dev.api.cottagelabs.com/use/crossref/works/doi/10.4103/1110-1067.170217

The data we get for that article (a recent dev request created by Joe) does not provide a publication date that we can use. So we only get a publication year. You can see it on the request page:

https://dev.openaccessbutton.org/request/PHjwu4KGrPrD2r8Ru

To see a "publication date" one, look at:

https://dev.openaccessbutton.org/request/vgrmR2MoQBg8EcWCq

There are no moderation boxes that show dates in an editable way, so I assumed this is where you meant to display the date/year.

I'll close this, but re-open if something needs changed.
