### ISSUE TITLE
Is blacklist still functioning? 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1261]
Recently seen quite a few requests on RG & DOAJ:

* izNAw9RPCEvgkGbm7
* GpScLmda5XsN2whLW

I think they should've been stopped before making. Not seen this in a while. cc @natalianorori

**Comment by JosephMcArthur** [comment]
added doaj to list of things we won't run on. We should run on research gate, so made an issue: #1265

**Comment by natalianorori** [comment]
The problem of running on researchgate is that we need to be careful with
article publications dates there.
When the system runs researchgate requests, I've noticed they're links from
old articles. You can see many examples in this batch we moderated last
month:
https://docs.google.com/spreadsheets/d/1r-kOw2AEvjbxarxhn4jG_wtYxx64lLb6-tXrIY_6uik/edit#gid=1299996950
 .

Appart from that, I have nothing against running researchgate requests, as
long as they have dois.

**Comment by natalianorori** [comment]
During the past week, We've got a couple of requests that should not have gone through, they're only a few, but still important to report: 

Scihub - id EycRBQwPJPe53svPq
Researchgate - id quhQ7w7JDmpg2DKGL
coursehero.com - id j7j26Z5ASe2SgKKJX
