### ISSUE TITLE
Generated openurls contain unhelpful info

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1267]
The URLs we generate for ILL submission, like:

> https://aeu.relais-host.com/user/login.html?sid=InstantILL&atitle=Marine%20Insurance%20and%20the%20Trade%20of%20Rotterdam,%201755-63&title=Maritime%20History&rft.year=1972&createdAt=1568043126721&created_date=2019-09-09%201632.06&_id=KtYctk6ZLLyp3jh5N&&notes=Subscription%20check%20done,%20found%20nothing.%20OA%20availability%20check%20done,%20found%20nothing.

The following:

createdAt=
created_date=
_id

should all be internal, and I don't think see in the openurl.

Also, I often see a double `&&` in them, right before notes, and that shouldn't be happening I don't think.

**Comment by markmacgillivray** [comment]
&& does not make any difference in a URL but I have added a catch to remove them anyway, along with those additional fields we don't want
