### ISSUE TITLE
faking response from subscriptions for instantill demo

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1271]
Can discuss on call

**Comment by markmacgillivray** [comment]
Set up a demo account that returns an example subscription for a pretend doi that we make up. Change the demo to use the same demo account rather than the account of whoever the logged in user is.

**Comment by markmacgillivray** [comment]
This should point to some URL of our choice, but we don't know yet which URL we want in.

**Comment by markmacgillivray** [comment]
I have added a dev and live demo account and if either is checked for a subscription to DOI 10.1234/567890 it will return the URL https://instantill.org

Let me know what else you need done to close this.

**Comment by JosephMcArthur** [comment]
Just tested it at https://dev.openaccessbutton.org/instantill/ , it's saying the service is down. Maybe I tested too soon? :D

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
I don't see anything saying the service is down. What do you see saying that?

**Comment by markmacgillivray** [comment]
InstantILL won't show a subscription if we don't also have the necessary metadata, so just passing a fake DOI is not enough to cause the demo to show a subscription link. Will need to alter the approach to fake the entire availability response to get the demo to show a fake subscription link. Work continuing here after fixing #1285

**Comment by markmacgillivray** [comment]
I think this works as expected now, have a look clicking through the demo options and when you get to that one that shows you the pretend subscription result link for the fake DOI, you should see it shows a link to https://instantill.org

I can change the address it points to once you decide where you want it to go.

**Comment by JosephMcArthur** [comment]
Fake DOI seems to work well. Missing a title though, which makes it look odd. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
I added "An example subscription title". Do you want it to say anything else?

**Comment by JosephMcArthur** [comment]
Good progress, but it's coming below 'This is not the article I searched.' which isn't right.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Moved it above

**Comment by JosephMcArthur** [comment]
Perfecto!
