### ISSUE TITLE
new rules on what's allowed through URL box on receiver pages

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1275]
Author's seem to put their published PDF links in there... which we want to stop.

So, we want to:

* flag if it’s the same DOI, or a URL the DOI resolves to
* or *contains* either of the above URLs
* then show a response on the UI / API.

**Comment by JosephMcArthur** [comment]
A note from Natali:

> I wanted to update you and share we've received three researchgate urls from requests we sent out this week. I have already rejected them, but it would be good if we didn't accept them in the first place :)

Seems like this system may not actually be working. Worth checking as it's updated.

**Comment by markmacgillivray** [comment]
I have done some investigating on this one. Our current receiver page checks to see if a submitted URL contains researchgate, academia.edu, or readcube. If it does, it shows a warning saying that these are often not suitable for sharing, and tells them to check sherpa/romeo etc, but does then let them submit if they try the same URL a second time.

So at the moment it is not broken - it is intentionally warning and then allowing them if they submit again after seeing the warning.

Of course I can change this to just reject and not allow at all, but just letting you know, we have intentionally done it this other way in the past.

As for the main part of this issue - I have not yet been able to think of a way to achieve this without consequences:

* If we disallow any URL with the DOI in it, we could easily block things that are valid resources, for example an institutional/subject (like zenodo) repo may use the official DOI to use as part of the naming URL for their own local copy. Is that acceptable?

* If we are given a DOI or a URL with a DOI in it, and if we disallow any URL that resolves to the same URL the DOI resolves to (e.g. by looking it up on crossref then comparing where the two resolve to) then we may again block legitimate shares where for example the author gives us a URL to an article that IS open but which we were unable to find, or had misidentified as not open. Or, if an author shares something that was embargoed but now is not, we would block that too.

* If we are given a URL that does not have a DOI in it we cannot know whether it resolves to the same content or not (except in the case above where they just resolve to exactly the same URL) - any way we currently have of checking the content, such as looking for the DOI, the author names etc, would match against an "official" publication as well as the content of an "unofficial" one. So we could not distinguish the two.

If any or all of these consequences are acceptable, let me know which, and I can implement as desired.

**Comment by JosephMcArthur** [comment]
Hmm, okay sounds like this is a decent amount harder than we expected and so for now I'd suggest we move back to backlog. I think the answer will be that these things can happen, but the cost-benefit will be significantly in our favour. We'd just want to again give the users a chance to re-confirm if they're sure.

**Comment by JosephMcArthur** [comment]
> If we disallow any URL with the DOI in it, we could easily block things that are valid resources, for example an institutional/subject (like zenodo) repo may use the official DOI to use as part of the naming URL for their own local copy. Is that acceptable?

This would probably be solved by:
* Taking the full DOI address, e.g `https://doi.org/10.something`. I think it's unlikely we'd see a system, e.g zenodo, use that as part of a url. Say, though, they did extend it. e.g `https://doi.org/10.something.V2`. If we didn't catch that, I think it would be okay. 
* Allowing for overrides, as with the RG.

If we are given a DOI or a URL with a DOI in it, and if we disallow any URL that resolves to the same URL the DOI resolves to (e.g. by looking it up on crossref then comparing where the two resolve to) then we may again block legitimate shares where for example the author gives us a URL to an article that IS open but which we were unable to find, or had misidentified as not open. Or, if an author shares something that was embargoed but now is not, we would block that too.

* I think a custom message is all we could do for this.

> If we are given a URL that does not have a DOI in it we cannot know whether it resolves to the same content or not (except in the case above where they just resolve to exactly the same URL) - any way we currently have of checking the content, such as looking for the DOI, the author names etc, would match against an "official" publication as well as the content of an "unofficial" one. So we could not distinguish the two.

This seems to me to be a problem we have now, and not something to address in this issue.

**Comment by JosephMcArthur** [comment]
these pages are retired!
