### ISSUE TITLE
InstantILL Loading %

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1278]
Thinking of adding a loading bar (%) to InstantILLs initial search. We can't reflect real progress without complex changes, so we're going to fake it, as is common. 

@markmacgillivray I've found some Javascript which approximates the math we need: https://codepen.io/Stormix/pen/xWrMKQ. There you'll find javascript that creates a % (which, we'll need to do with decimal places) that looks semi-real, while never hitting 100 until a process returns. Can we use this code? 

If so, I'll let you know the settings I want, and we can drop it in.

**Comment by markmacgillivray** [comment]
Yes, the maths is not hard. All that is required is the decision of which way to do it (we've decided faking) and scheduling the time to put it in place - and design, if necessary.

**Comment by JosephMcArthur** [comment]
The design would just be adding the % number after the '...'

**Comment by JosephMcArthur** [comment]
fast enough to not be important now
