### ISSUE TITLE
Pings causing CORS error (needed for instantill)

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#1284]
Our ping endpoint that picks up actions from instantill has started causing a CORS error, so I need to fix this before I can complete the instantill issues in #1266 - adding this issue to keep track of that extra work

**Comment by JosephMcArthur** [comment]
Thanks for tracking!

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur
