### ISSUE TITLE
On our email boxes, for InstantILL & requests / login, utilize browser email auto-complete

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1292]
I think this is described here: 
* https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill
* https://cloudfour.com/thinks/autofill-what-web-devs-should-know-but-dont/

This seems easy, and something worth doing.

**Comment by markmacgillivray** [comment]
What effect is it that you are wanting to see that you don't already see?

As far as I can tell there is no change mentioned in these articles for autocomplete/autofill that we don't already achieve.

**Comment by markmacgillivray** [comment]
Also, when I look at our account login page, I do get the usual chrome autofill options trying to provide my email address for me, so what we have now is already working for that effect.

Is there something else here you are meaning?

**Comment by JosephMcArthur** [comment]
I had autofill turned off in my browser so I didn't realize we already did this 🙃Good for us!
