### ISSUE TITLE
Allow "val" to be set by user in /instantill/setup#subscription

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1301]
I'd like the preview button on that page to be able to test with an article the uni for sure has access to, which means it'll need to be set. Ideally, I think, this would be saved so they'd be able to do it over and over again over different sessions.

**Comment by markmacgillivray** [comment]
This has been added and tested, the #subscription section has a new box for providing the val, and you can edit the words around the box if you wish. Otherwise, @JosephMcArthur you can just close this issue. My changes have been pushed to dev.
