### ISSUE TITLE
Domain management on instantill.org

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1302]
As discussed on call. Just tracking here.

**Comment by markmacgillivray** [comment]
I have made these changes, should be how we described. Note if you want instantill.org to show that index page then develop needs to merge into master. @JosephMcArthur  is there anything you have in there that you don't want pushed onto master?

**Comment by JosephMcArthur** [comment]
I've merged it

**Comment by JosephMcArthur** [comment]
can dev.instantill.org/setup go to dev set up too?

**Comment by markmacgillivray** [comment]
I think it already does

**Comment by JosephMcArthur** [comment]
your right, I may have had a bit of a cache or something odd going on!
