### ISSUE TITLE
correct lingering centreing issues on set up page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1305]
#1

When going from a page like:

https://dev.openaccessbutton.org/instantill/setup#ill

and clicking 

> Go to Menu

It would appear that the centering doesn't update.

See below the resulting screen:

![image](https://user-images.githubusercontent.com/4953703/66999304-a47b0b80-f0cd-11e9-88ff-08cc316a8c99.png)

#2

Centering when not InstantILL

**Comment by markmacgillivray** [comment]
I've tried a change which tries to get it close to centre on first opening the page, then places it a fixed height from top. Have a look on dev and see if this is good enough.

**Comment by JosephMcArthur** [comment]
This is good to go on!

**Comment by JosephMcArthur** [comment]
One last question! did these changes affect the demo?

**Comment by markmacgillivray** [comment]
Perhaps a little bit, but demo page looks fine to me too. Similarly, it is centred on start, and then after is a fixed height from the top of the area it is contained in. I had a look and I think it is OK, but you can check on dev too.
