### ISSUE TITLE
Add config options for account & page management

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1307]
Often where InstantILL is recommended to be embedded people not only want to allow people to make requests, but manage them and find out about the service. This tends to get messy, so lets help people control it.

Eventually, it'll look something like the below:

![image](https://user-images.githubusercontent.com/4953703/67094752-54bf4180-f1ac-11e9-89d2-8bb80d27354c.png)

The idea here is to provide all the functions on this issue in a new line.

They are three separate functions that can be activated independently. This is similar to the line for book / other requests.

The three links are:
* 'ill-info': When a link is given for this, the link is shown. The link should read 'learn about Interlibrary Loan'
* 'view-account': When a link is given for this, the link is shown. The link should read 'view account'
* 'advanced-form': When a link is given for this, the link is shown. The link should read 'use advanced form'

and to ensure however they're clicked this makes sense, we should have:

* The line alway start 'Or'
* If there are >1 given, always an 'and' before the final one
* if there are >2 given, put a comma after the 1nd one
* always show in the following order: advanced-form --> view-account --> ILL-info. Eg. if only ILL-info & advanced-form are used, show advanced-form then ILL-info

I've made questions for these in set-up, under the following IDs:

* ILL-info
* view-account
* advanced-form

So, you don't need to write set up copy or anything like that.

**Comment by markmacgillivray** [comment]
Done and tested, please check on dev that it works as you expect

**Comment by JosephMcArthur** [comment]
Looks perfect, thanks Mark!
