### ISSUE TITLE
Rollout stats

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1309]
This has been discussed with Mark, and I've considered it since.

Into set up, I've introduced two options:

* pilot (id = 'pilot')
* live (id= 'live')

- [ ] We need the backend to recognize these.

In #1308 I've discussed the UI changes that happen when pilot is clicked. There are no UI changes when 'live' is true. 

This issue deals with backend details.

When either of these are clicked, 

- [ ] we need to track the fact this is done (e.g =true) 
and
- [ ] the date it was clicked.

We can assume each click happens only once per embed. e.g you can't run two pilots or two rollouts per embed.

Conceptually, 'live' is telling us that you're really using InstantILL with patrons. You're not just testing / playing around etc. Pilot is somewhat a subset of live, and tells us that you're live and that this is a pilot. If you click pilot=true without live, that's fine, and tells us that you're just trying the UI, or preparing to go live.

Together, these bits of data should allow us to:

*1 Answer how many embeds (i.e uni's) are using InstantILL for real now
*2 Answer how many embeds are being piloted now 
*3 Show a graph of both of these (cumulative counts) over time
*4 Tell a uni their total usage (including pings, and api hits as we do now), their pilot usage, and rollout usage. This could be done by segmenting usage stats against the date. 

eventually... once we take the time to process the data to do that, yes? For 1, 2, and 4 though, I should be able to answer those will relatively straightforward queries though, yes? e.g 1 is 'find me number of accounts with instantill IDs and pilot=true' and 4 is 'find me the usage on x embed since 'pilot date''

This comes with the downside of, if someone unclicks without knowing their stats, we'll lose the data I presume. But, it also seems more straightforward, and that's okay for now I think. I can deal with this risk by telling people not to unclick before they have their figures.

Let's discuss again, over issues / a call before moving ahead. My goal was the make this not a week long job.

**Comment by markmacgillivray** [comment]
This has been done, and is possible to issue queries to get the desired results. 

This does not include UI changes to allow admins to view on stats or to allow users to view their stats - it is just the API work necessary to record and track these.

Making this work on live will require an update to the main API code, so note that just pushing to master will not do it - you'll need to let me know when you want this released and I will do the necessary manual parts to the main API code.

Do you want more done to show these stats on the UI as part of this issue? If so let me know, otherwise you can close this.

**Comment by JosephMcArthur** [comment]
Can you let me know the queries here, and then we can test and shut. 

I'd say push to master asap though. We want this and other stuff live, so if you're confident it's all working let's get it pushed so we con't have to co-ordinate future releases.

**Comment by markmacgillivray** [comment]
You'll need your apikey and the relevant dev or live API URL. Then:

1: /users?q=service.openaccessbutton.ill.config.live:*
2: /users?q=service.openaccessbutton.ill.config.pilot:*

4 involves multiple queries. The new ones would be:
Get all their pilot availability checks /availabilities?q=from:USERID AND pilot:*
Get all their live availability checks /availabilities?q=from:USERID AND live:*
Get all their pilot ILLs /ills?q=from:USERID AND pilot:*
Get all their live ILLs /ills?q=from:USERID AND live:*

**Comment by JosephMcArthur** [comment]
Gotcha. Total availability checks would be on stat, yes? Can I do the same style thing with pings?

**Comment by markmacgillivray** [comment]
I'm not sure what you mean about stats and pings. Stats remains as it was, as do pings. What else do you want to do with them?

**Comment by markmacgillivray** [comment]
I have updated the main API code now, but have not pushed to live on OAB. However, now that the main API code is done, OAB code can be pushed any time as normal.

**Comment by JosephMcArthur** [comment]
Can I query pings per embed done in pilot, for instance? 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
Fab! Let's push it now. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
No. I can add that if you want though

**Comment by markmacgillivray** [comment]
No point pushing it if we are going to add stuff to pings

**Comment by JosephMcArthur** [comment]
Can we add this to pings too then. Pings are being used to do some important stats, so let's make sure they're included here. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Pings do not currently record which user they came from though. So it is not possible to know which pings from which user were pilot or live, because currently we do not know which pings came from which user, as far as I can tell.

**Comment by JosephMcArthur** [comment]
Ah, you know what, I'm probably missing something. For some reason I was thinking 'Wrong hits' was measured by pings, but that's probably not the case. 

Let's take a step back. The general question I'd like to answer is, for each embed, when in pilot mode how many people clicked 'the old form'. My thought was pings was the best way to do that. Can you advise on way to measure that, and let me know what additionally it might take to build? 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
We already do that using a pinger, we have added a pinger to the "old form" button, and from that we can answer the question "how many people clicked 'the old form'". But if the question has to be "for each embed" then I just have to add a "from" param to the pinger and then also the "pilot" and "live" params if there are values set for those in the user config.

That will take another half hour to an hour to finish and test.

**Comment by JosephMcArthur** [comment]
fab, let's do that then. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
ok

**Comment by markmacgillivray** [comment]
That's done, do you want live updated?

**Comment by JosephMcArthur** [comment]
Yes please

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
OK done
