### ISSUE TITLE
boxes for subs don't always show up during set up

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1311]
The bug looks like the below:
![image](https://user-images.githubusercontent.com/4953703/67496930-1971b680-f675-11e9-8b54-1fd3a3317adf.png)

I've seen this in many accounts, but for sure in: mark+instantilldemo@cottagelabs.com. Mike at IUPUI has also seen it.

I can't replicate this reliably yet. Often I can get rid of it by refreshing. I see no issues on console when I see it. Opening an issue to track.

**Comment by JosephMcArthur** [comment]
Had a few more people replicate this. It appears just refreshing fixes the problem.

**Comment by markmacgillivray** [comment]
They disappear when moving back through the different page types, after an edit to them, if there was only one set left. I have altered that to always leave at least one empty set so that they are available at all times to add content to.
