### ISSUE TITLE
have dev. appended to shareyourpaper.org & instantILL.org addresses on dev.

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1313]
Our normal systems don't work on this now due to new domains. Not urgent, but worth a few minutes as at some point we'll have some weird bug due to the issue.

**Comment by JosephMcArthur** [comment]
would be great to also make sure the dev api is served from dev.api.openaccessbutton.org.

**Comment by markmacgillivray** [comment]
There don't appear to be any cases where shareyourpaper.org has been used as a functional url in the content or static pages of the site. There are many cases of shareyourpaper.org being used in the actual visual content, and also cases of it being used as a string to control what is visually displayed. Do you mean you want all those visual uses of it to change? Or only some?

I can create variables that can be written into content or static files anywhere, but we would also have to go through the content pages and replace any use of the string with the variable instead, then when the content is built the appropriate string would be inserted depending on dev or live config. Replacing all occurrences of the string with a variable would be fairly easy but still a bit time consuming. Replacing only certain ones, e.g. where used in certain paragraph contexts but not in others, and not replacing when being used as a control trigger for js visuals on the page, would take quite a while.

Please clarify what you want done here.

For instantill.org there are 4 uses of it in the content, all of which appear to be uses of it as an actual URL, so they should be easy to replace with a variable which can then be set from dev/live config. There are no uses of instantill.org in the static files. Please confirm this is what you mean here.

For serving the dev API from dev.api.openaccessbutton.org - this is something we have never done. The dev API is served on dev.api.cottagelabs.com/service/oab. There should already be variables in use for display the relevant API address, as we were already using them on the API docs. So, there should not be any change required on the site UI content for this, unless you have been manually writing the site API address in some places where you now want it to be dynamic. Please confirm if this is the case or not.

For actually changing the URL we serve the dev API at - this is possible, but is quite a different issue and probably needs separate scheduling. I will need to point that subdomain, configure nginx, create a secure cert for it, then test all the UI js code to make sure none of it relies on the old URL for any functionality.

**Comment by JosephMcArthur** [comment]
okay let's just not do this. Currently, after a bit of cleaning there are no places where the new domains would confuse things and for the api it's not worth the hassle.
