### ISSUE TITLE
reset preview during set up

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1314]
During a natural set up process, we'll want the preview to go from being on the results page, to start page, and back. We need a way to reset and pull the preview from results to the entry page.

If you give me the class name, I'll put it where it needs to be.

**Comment by markmacgillivray** [comment]
I have checked and tested this, there is a class called "restart" in instantill, if you put that class on some trigger then it would cause the visible instantill form to go back to the starting configuration.

If you are doing a save you can already cause this to happen by doing the preview, and you can already do the preview directly - of course both of these cause it to go back to the starting configuration and then run again.

So if you want to get it back to the starting configuration without doing anything, try adding the "restart" class to the trigger where you want to cause this effect. If it works you can close this issue, if this is not what you mean then respond here and let me know what else to change.

**Comment by markmacgillivray** [comment]
@JosephMcArthur pinging your name in here re. the above comment just to be sure you notice it.

**Comment by JosephMcArthur** [comment]
Can you commit the code for this? Can't see the class / test. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
There wasn't any to commit. I started writing some code for it on the UI pages, but then reviewed what we already had in the main embed itself, and confirmed that it has a restart class which it already exposes in a way that should make it available to whatever page it is embedded on. So, as the setup page already includes the embed, that restart class should already work. So I removed the code I had started to add to the setup UI.

**Comment by JosephMcArthur** [comment]
Got you! Testing now and thank you. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
This is working great!
