### ISSUE TITLE
more redirecting fun

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1315]
Lets set:
- [ ] openaccessbutton.org/instantill --> instantill.org
- [ ] openaccessbutton.org/shareyourpaper.org --> shareyourpaper.org
- [ ] openaccessbutton.org/instantill_alpha --> instantill.org/setup

**Comment by markmacgillivray** [comment]
These have been done - @JosephMcArthur you can check and close if happy, I have checked and they seem to work, but just make sure they are as you intended.
