### ISSUE TITLE
Shareyourpaper.org embed doesn't work without jquery?

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1325]
E.g on here: https://josephmcarthur.github.io/playground/syp

With InstantILL, I think we call jquery in the script so it's not needed, we should do the same here.

**Comment by markmacgillivray** [comment]
I have changed the code on shareyourpaper setup and on instantill setup to remove the jquery wrapper, which cannot work until after the jquery has been retrieved if not already available. Try altering the code on your playground page to what you can now see in setup and see if it works now.

**Comment by JosephMcArthur** [comment]
Still nothing

**Comment by markmacgillivray** [comment]
ok fixed now

**Comment by JosephMcArthur** [comment]
How will this change affect existing embeds or set up?
