### ISSUE TITLE
ILL IDs are undefined in some InstantILL requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1328]
Mark, I think you get the confirmations, search for: “Open access button ILL ID: undefined” and you’ll see errors turning up.

**Comment by markmacgillivray** [comment]
Certain user-provided values did not match requirements when saving the ILL records, causing errors. This has been changed to not store author strings if we receive them from users, as they are not as detailed as author objects we find from other APIs, and clash with the storage type. Also, we never use author strings to find anything anyway, so they are only causing us problems in the backend for no additional value, so just removed them before saving.
