### ISSUE TITLE
 Demo article incorrect

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1330]
In [part 2](https://instantill.org/#part2), the open article in a new tab link should be: https://scholarworks.iupui.edu/bitstream/handle/1805/20422/07-PAXTON.pdf?sequence=1&isAllowed=y not instantill.org

This was originally in, and that URL is where it should be, but something else has changed.

**Comment by markmacgillivray** [comment]
Yeah I missed this in the change to refactored code, we had the correct URL in one place in the old code but had instantill.org in another place, and i used the wrong one in the new code. Fixed now on dev, needs a push to live to repair there.
