### ISSUE TITLE
AAM deposit currently not working

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1336]
If I try and upload a PDF it leaves me to the AAM page after a quick refresh. The URL is then:

http://www.lib.montana.edu/services/publication/scholarworks/?file=Open+For+Whom.pdf&service=openaccessbutton

**Comment by markmacgillivray** [comment]
Refresh and try this again, I think it works now.

**Comment by JosephMcArthur** [comment]
When I did this, I appear to have got an email for dark deposit, not file deposit

**Comment by markmacgillivray** [comment]
There is a problem on the montana site because our embed is being embedded inside a form element on their page. This must be a "feature" of their CMS. It is stopping our embedded file upload form from functioning. I am looking for a way round this problem.

**Comment by markmacgillivray** [comment]
OK, this works now. Try again and you should get a file.

**Comment by JosephMcArthur** [comment]
Thank you! They had to do this to get it to show up. May actually be a
useful trick for others who have issues. Is it advisable for us to suggest
this as a solution / something to try?
