### ISSUE TITLE
fix stats

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1337]
Apparently it'll be broken by refactor, should fix.

**Comment by JosephMcArthur** [comment]
Estimate:

> It depends how fixed you want it. There will be some work to change the stats page itself to query the new catalogue/find endpoints instead of the old ones, which will no longer get updated. That will probably take a couple of hours, as there may be some other small changes that affect how the queries for the tables/graphs operate so they will need to be checked.
> 
> Then, if you want to continue to be able to see old and new data all on that page, we will need to write and run some scripts to convert all the old availability checks into new finds. That will probably be two or three hours to write, test, run on dev, then run on live and check results.

**Comment by JosephMcArthur** [comment]
Oh, would be great to have all the data on one page. So, the second version of this would be great please.

**Comment by markmacgillivray** [comment]
Done, took longer than hoped. Script to bring across old data is written, but script still needs to be run. Also Joe asked for adding pilot and live instantill stats, I have still to do that part too, won't take much longer to add that though, so just keeping this issue open until all done.

**Comment by JosephMcArthur** [comment]
Follow on issue is here: https://github.com/OAButton/discussion/issues/1372

- [ ] Good to close once we comment out stats.

**Comment by markmacgillivray** [comment]
Requests have been commented out for stats page, live stats page should start working after next push to live.
