### ISSUE TITLE
Check through embeds for failing jquery binds

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#1338]
We found an issue over the weekend with jquery binds that previously worked now not working on certain embeds. It may be a problem to do with how binds are used in conjunction with other binds on the pages. So change all uses of .bind to .on instead.

Making an issue for this because it is a reasonable amount of work on its own and has to be done before we push to live.

**Comment by JosephMcArthur** [comment]
Sure thing, thanks for putting up an issue!

**Comment by JosephMcArthur** [comment]
While you're doing this, can you try and keep dev working for as much of the time as possible. Will be showing shareyourpaper.org to people (and can only do on dev).
