### ISSUE TITLE
Dark deposit route needs unique ending

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1340]
The final screen should be:

![Published _ 1 2 (1)](https://user-images.githubusercontent.com/4953703/70863134-db8a6380-1f3c-11ea-94c7-a7efdfd26df5.png)

This is different to the one for submission via the resubmit route.

**Comment by markmacgillivray** [comment]
This is testable on dev, please have a look and close if it is what you want, or add further info if not.

**Comment by JosephMcArthur** [comment]
Now the route that generates the `redeposit deposit` email where folks click 'I still want it in ScholarWorks.' has the wrong copy on the confirmation screen 🙃 

It should be:

![Published _ Live (2)](https://user-images.githubusercontent.com/4953703/72426931-97c88b00-3782-11ea-9c71-2ecec19b1ad3.png)

It is the 1st screenshot in the issue.

**Comment by JosephMcArthur** [comment]
Can't verify the fix for this.

**Comment by markmacgillivray** [comment]
OK, sorted. Sorry, I tested that and then made another change and caused it to fail again. But just tested again and it works, and adding it to the demo examples

**Comment by JosephMcArthur** [comment]
It looks like this may have caused this: https://github.com/OAButton/discussion/issues/1375#issuecomment-577116553. Not sure. 

If so, let's jump on a call and talk about why these keep going back and forth. Something doesn't seem robust enough in our process here.

**Comment by markmacgillivray** [comment]
I think it must have been coincidental, I just fixed that other one by putting the right demo DOI in, which I had got wrong. So you can close this one unless there is anything else still wrong here.

**Comment by JosephMcArthur** [comment]
Okay but now the dark deposit page goes to "Hmmm, something looks wrong" 🙃

**Comment by markmacgillivray** [comment]
OK fixed that too. It was due to the demo not resetting properly rather than directly to do with the shareyourpaper code.
