### ISSUE TITLE
Add 'I don't have a doi' button

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1341]
If folks don't have a DOI we still want them to be able to use shareyourpaper. Sadly, supporting stuff without it is likely to be hard for a while, so, on the landing let's have a secondary button that just says "I don't have a DOI". Then, let's point that to a mail to to the embed owners email address.

**Comment by markmacgillivray** [comment]
This is on dev, please test and close or update here. If there is a configured email address to contact the lib that configured the embed then that gets used, if not then it defaults to "help@openaccessbutton.org" (can make that whatever you want)

**Comment by JosephMcArthur** [comment]
Should default to embed owner

**Comment by markmacgillivray** [comment]
It can't if there isn't one. If there is one, it would. But so far we have not configured shareyourpaper setup to actually set any config values for shareyourpaper installs - they are entirely built for the one user so far, as instructed.

**Comment by JosephMcArthur** [comment]
It looks to me that the button doesn't have the normal styling of 2ndary buttons here. 

For example, the button looks off here:
https://dev.openaccessbutton.org/shareyourpaper/setup#menu
http://www.lib.montana.edu/services/publication/scholarworks/
and
https://josephmcarthur.github.io/playground/syp

It should be similar to styling in 'Open article in a new tab'

**Comment by markmacgillivray** [comment]
You've said above it should be similar in styling to 'Open article in a new tab'. But I can't find any button on shareyourpaper called that. Which button/style do you mean?

**Comment by JosephMcArthur** [comment]
Oh that's a button from InstantILL. So far, I don' think there is a similar button type on shareyourpaper.org ( http://shareyourpaper.org/ )

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Ah OK. I have found URL links on instantill that have that text in them, but they don't have any styling applied to them. They are just inline text URLs, same as the "I don't have a DOI" button is now on instantill. That is also the same as other inline text URLs in use on shareyourpaper such as "terms and conditions".

The only difference I can find was that I had added a reduction in font size to the "I don't have a DOI" text, but I have changed that back so it is the same font size as everything else. Is that the difference you meant? Or is there something else I am missing?

**Comment by JosephMcArthur** [comment]
let's also bold it, then we're done!

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
OK, done. Have a look and close if good

**Comment by JosephMcArthur** [comment]
\o/
