### ISSUE TITLE
Check file deposited is the article it says it is

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1342]
Part one of the file checking system is making sure the file is what it says it is. This should be thought of as independent from what verison it is. 

For now, the checks we did to check stuff from Bing should be fine. The things I have in my head are:

* Can we find the article title (or a close match)
* Can we find other metadata like author names (or a close match)
* Is it the length of a paper (2+ pages)
* Is it a .docx, .pdf, .tex

If we fail to find one of those, we should probably flag for human review. Another Q would be:

* Can we find the DOI

Finding this should increase the chance we think it's the correct paper. 

If we can't find this, we should put the file into the human moderated process we have now. Ideally, we'd also be able to include a statement of why it failed, and eventually, show this to the author in the UI.

**Comment by markmacgillivray** [comment]
Nearly done, should be finished by our next meeting

**Comment by markmacgillivray** [comment]
Done but testing still in progress

**Comment by JosephMcArthur** [comment]
Note: https://dev.api.cottagelabs.com/service/oab/permissions?url=https://static.cottagelabs.com/obstm.pdf is an example URL for use. 

@markmacgillivray to pass a doi param, would it be:

https://dev.api.cottagelabs.com/service/oab/permissions?url=https://static.cottagelabs.com/obstm.pdf&doi=<DOI HERE>

**Comment by JosephMcArthur** [comment]
If it is, then it looks like we actually get less info when a DOI is passed in terms of metadata.

**Comment by JosephMcArthur** [comment]
@markmacgillivray where would you suggest we put files so that they're analyzable by this endpoint, but safe from the internet at large. I have access to a lot of files, but they're on my harddrive.

**Comment by JosephMcArthur** [comment]
Dropbox is the best I've found so far.

The links look like this: https://www.dropbox.com/s/0ec8utlso8swo25/Hou_et_al-manuscript.pdf?dl=0

By default they come with ?dl=0 on the end, which I thought I could just take off but when I do that the endpoint doesn't pick up the file correctly.

With it, it thinks the file type is pdf?dl=0 which isn't suprising, but not ideal for testing.

**Comment by markmacgillivray** [comment]
Yes you can pass in metadata as url params as you describe above. However, DOI is the only one considered necessary, so if you give it a DOI it may not look for any more. It will only look for more if we can't find an answer from Ricks in which case it tries to get more so we can find it in sherpa by issn or journal. Then later if we can't find the doi in the file it will try again to get at least a title to look for that in the file. But as looking up sherpa is not mandatory, and looking for a title is not really necessary if we find the doi, it doesn't bother getting all the metadata in all cases. 

I can change that to make metadata lookup mandatory if you want, or any of the other bits mandatory.

For passing files in I have updated dev so you can hopefully give it a dropbox url, it will try stripping off extra params now to get proper file types etc. Alternatively put a file in the static folder on dev branch then push, a while later you will be able to use the url https://dev.openaccessbutton.org/static/YOURFILE.NAME

**Comment by JosephMcArthur** [comment]
It seems like whatever you did stop it being able to recognize the files at the URL, so I'll just the static endpoint for now. No problem right now tbh.

**Comment by JosephMcArthur** [comment]
Righto, using static now and passing both DOI & title which is fine for testing.

Looking at this first test response:
https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Hou_et_al-manuscript.pdf&doi=10.1073/pnas.1905762116&title=SerpinB1%20controls%20encephalitogenic%20T%20helper%20cells%20in%20neuroinflammation

we're not matching the title. Can you see why?

**Comment by markmacgillivray** [comment]
PDFs can have bad use of spaces in text content, and we also throw away small strings when using titles for matching. This led to the pdf content having a space near the end of one of the words in the title and leaving a single character hanging, which we then would strip on the title matching as being too short to contribute to the match. As it is possible PDFs will contain this type of error for layout purposes, I have altered the algorithm so that it removes all spaces first, and then tries to match the title. It works now.
