### ISSUE TITLE
Search for text strings in articles that suggest certain versions

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1343]
So, the first wave of checking can be done by looking for text strings. I have booted up a google sheet for this as you suggest: https://docs.google.com/spreadsheets/d/1XA29lqVPCJ2FQ6siLywahxBTLFaDCZKaN5qUeoTuApg/edit#gid=0

The sheet specifies a few things:
* what to search. 
* how to search.
* where to search: i.e the filename or file itself
* what version it indicates. We may also want to include something that tells us how strongly we think it indicates that version. 

Some examples are in the file.

However, I'd also love it if you add / integrated the system you have at CL, and checked what Unpaywall do: https://github.com/Impactstory/oadoi/blob/master/page.py#L179 and see if we can glean anything (I've already added some regexes).

**Comment by markmacgillivray** [comment]
Also almost done, should be finished by our next meeting

**Comment by markmacgillivray** [comment]
Done but still testing

**Comment by JosephMcArthur** [comment]
Oh, just re-opening to ask a question. 

What of impactstory stuff did we use here?

**Comment by markmacgillivray** [comment]
I didn't add anything from the impactstory stuff.
