### ISSUE TITLE
Explore using Zenodo OAI PMH for deposit ingest

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1347]
I imagine that some repositories allow content ingest via OAI-PMH. I.e They can bring things *into* the repository via OAI-PMH, probably for migration purposes. 

We could explore using Zenodo communities, which allow generation of OAI-PMH feeds, to provide this as a way to get deposits into uni's repos.

The process would be something like this:
* They set up community
* Give us ID
* We put stuff there and give OAI-PMH link

**Comment by JosephMcArthur** [comment]
I feel good this can move ahead, especially as it's easy!

**Comment by markmacgillivray** [comment]
When you say we would "give oai-pmh link" - where?

**Comment by JosephMcArthur** [comment]
I'll clarify all this (hopefully) tomorrow. We likely won't actually need to give the OAI PMH link, we can just put them to zenodo in set up.

**Comment by markmacgillivray** [comment]
OK, I have put the ability to pass the community IDs in place, so all we need is a config option box where they enter their community ID. Then if you want that link displayed somewhere, just let me know where. But as you say, perhaps in the config page just referring them to zenodo is the better option. I will be testing the community ID gets passed as expected as part of my currently ongoing zenodo testing.

**Comment by JosephMcArthur** [comment]
There is an option now under `Community_ID`with copy on set up.

**Comment by markmacgillivray** [comment]
You appear to have put two entities with the ID community_ID on that page. entity IDs are supposed to be unique. If they are not, then there is no guarantee over how they will be treated, and there is a risk of one overwriting the other, or both being used as a combined value instead of singular. Can you narrow down to just using one of any given ID within a page?

**Comment by JosephMcArthur** [comment]
For the community ID, can you 

- [ ] strip it from the URL we've asked users to give
- [ ] make some code that helps manage the case where we have two ids. I can't think of a way to do this well for the user. I'm presuming this won't be hard, if it is, we'll alter the UI.

**Comment by markmacgillivray** [comment]
I think this is now the case

**Comment by JosephMcArthur** [comment]
Any chance you already have a test community on the sandbox we can use to test this?

**Comment by JosephMcArthur** [comment]
I've made a community with the URL: https://sandbox.zenodo.org/communities/test-community-oab

**Comment by JosephMcArthur** [comment]
This doesn't look like it's working, neither wrt to the having one community field be applied to both or actually having it go to a community.

**Comment by markmacgillivray** [comment]
On the sneakpeak page on dev, when I tested, the user account that the page uses to retrieve a shareyourpaper config returns a config that does not have a community ID set for it. Had you already tried setting that in a config for that user account? If there is no community value set for the account that the embed config comes from, then it cannot be deposited into that community on zenodo.

I'm not sure what you mean by "one community field applied to both" either. What fields do you mean? Are they on the sneakpeak page or somewhere else?

We can talk through this as well when we discuss later this week.

**Comment by JosephMcArthur** [comment]
I had tried, but since there there was dozens of other configs saved due to the overwrite issue. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Test again after adding a community ID to the config that runs that page.

About the "field applied to both" thing is about when we had multiple community ID fields in the config, need to make sure those values are being written in correctly.

**Comment by JosephMcArthur** [comment]
test id here: https://sandbox.zenodo.org/communities/test-community-oab/edit/

**Comment by JosephMcArthur** [comment]
Add the ID here: https://dev.openaccessbutton.org/shareyourpaper/setup#programatically

**Comment by JosephMcArthur** [comment]
While looking at this again I noticed that the 'programmatically' section was trying to do too much, so I've set up a section for api ingest and oai-pmh ingest. 

The place for you to test is now: https://dev.openaccessbutton.org/shareyourpaper/setup#oai-pmh

**Comment by markmacgillivray** [comment]
More changes made to allow for multiple community IDs, more testing done to see that they save properly to the config, they do.

I have found it pretty hard to test whether or not I can actually get a file into zenodo though. Please login to whatever account it is you want to work in this way, and go to whatever page you expect should be able to get a file into zenodo under that account, and you should then be able to confirm if the file ended up in the community.

**Comment by JosephMcArthur** [comment]
It's working!

I've updated /test to make it easier to test deposits (has ready made files to use etc). Let me know if that can be improved to make it easier. 

I tend to use my own embed: https://josephmcarthur.github.io/playground/syp-dev for testing as it lets me pay around with config settings and what not.
