### ISSUE TITLE
Support putting deposits into certain Zenodo communities for a minimal repo solution

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1348]
For folks who don't have an IR, they could get up to speed with shareyourpaper.org really fast by using Zenodo communities, which would provide them a very minimal repository solution. 

Example here: https://zenodo.org/communities/biosyslit/?page=1&size=20

Config as in #1347

**Comment by JosephMcArthur** [comment]
I feel good this can move ahead!

**Comment by markmacgillivray** [comment]
This has been done on the API side of things, now just needs to go into the shareyourpaper config page whenever you start doing that

**Comment by JosephMcArthur** [comment]
Done as part of #1347
