### ISSUE TITLE
Pass email in URL for shareyourpaper.org

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1350]
Have it so that if 'email' is specified as a parameter, email boxes are pre-filled with whatever value is given. 

This aims to help cut down data-entry by authors, and help with tracking of deposits.

**Comment by JosephMcArthur** [comment]
Ah, if this is passed, when authors upload a file we should also pass this. Can that be done?

**Comment by markmacgillivray** [comment]
Pass it where? Where is it not yet passed to that you want it to be passed to? I think it already shows in the boxes on the page, and is already passed to the backend, so not sure what you mean.

**Comment by JosephMcArthur** [comment]
Through to the deposit record, and in deposit emails

**Comment by markmacgillivray** [comment]
We already do this too, when a deposit is received with an email it is stored in the record and put into the email we send out to the institution/ourselves
