### ISSUE TITLE
Add pilot & rollout modes to Shareyourpaper.org

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1351]
This can be basically exactly the same as InstantILL in terms of functionality, configs, stats etc. 

We'll need to adjust the copy slightly to suit, and I can do that after it's built.

**Comment by markmacgillivray** [comment]
OK pilot and rollout modes are in the shareyourpaper embed, they just need to be set in the config whenever you start working on that page - the config for them would be set in the same way as the instantill config.

For the shareyourpaper ui, i need to know what you want it to display, and where, for either of the modes. So I will assign to you, you can update the issue with that info, then assign back to me

**Comment by JosephMcArthur** [comment]
Let's have the pilot mode statement show up the same way, in the same place as on instantill. I.e at the bottom, and staying there the whole time. 

> Notice a change? We're testing a simpler and faster way to deposit your articles. You can give feedback or use the old form.

The config page for this is copied from InstantILL, and up now.

**Comment by markmacgillivray** [comment]
What will "use the old form" be in this context? On instantill it was a redirect to their advancedform if they had set one in config, or else their ill redirect base URL, or else just a mailto. What would be the appropriate form URL link for shareyourpaper?

**Comment by JosephMcArthur** [comment]
It's defined by 'old_way' in the config doc I sent. 

https://docs.google.com/document/d/1FK_jIUxNG3ONQalV4JSjVYZV1QRgjn-mn8fa2BhS2r0/edit#heading=h.ob9mcwfs4vbq

But generally, similar to last time if they do nothing we use the embed email. If they give another email we use that. If they give a link we use that. 

J

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur
