### ISSUE TITLE
Importing request data not working

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1352]
From @natalianorori 
> I am having trouble changing the status of sent requests on the site. I am using openaccessbutton.org/import and the site tells me that the records have been updated, but when I click on individual requests they are still on help.

This started a couple of weeks back, but I thought it was fixed / fine, sadly it wasn't!

**Comment by markmacgillivray** [comment]
Hi @natalianorori or @JosephMcArthur could one of you try doing an import on the dev site, I have made some changes there. If it still does not change the actual requests when you look at them individually, please email me the sheet you uploaded and I will do further testing.

**Comment by natalianorori** [comment]
Hey Mark,

I've tried this on dev and its working! Thanks your help. Let me know when
this is up on live.

**Comment by JosephMcArthur** [comment]
@natalianorori give this a try in about 24 hours or so! This should all be live then.
