### ISSUE TITLE
Deposit when publisher PDF is allowed

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1353]
The deposit page should look like this:

![Published _ Can Share Post (4)](https://user-images.githubusercontent.com/4953703/71656016-85396500-2d31-11ea-931f-da3d8cf1e9a5.png)

Basically the same opening & upload statements, but with no conditions. 

After deposit, we should follow the same deposit process as for an AAM.

This should be allowed when 'publisher pdf' is found as an allowable version.

**Comment by JosephMcArthur** [comment]
Can this be shut btw?

**Comment by markmacgillivray** [comment]
I'll shut it tomorrow after I make some progress on building the demo, I'm going to use that to check the various end results.

**Comment by JosephMcArthur** [comment]
Seems like a clever move :)

**Comment by JosephMcArthur** [comment]
In the response we still see:

> It's normal to share accepted versions as the research is the same. It's fine to make small edits to formatting, remove comments, etc.

which shouldn't be there. 

A good test doi to evoke is: 10.1063/1.4937158. It would be good to add this to the demo too (I would, but the code isn't on dev)/

**Comment by markmacgillivray** [comment]
OK sorry, I missed that sentence and had it in both options. Removed now, and added the DOI to the demo.
