### ISSUE TITLE
Embargo management in shareyourpaper.org

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1354]
With the new permissions system we will be able to get embargo periods, they'll already be computed for us too.

To respond to them on the UI we should have:

![Published _ Uploaded with DOI _ 2 2 (3)](https://user-images.githubusercontent.com/4953703/71656957-7f458300-2d35-11ea-91c4-b779a1e02134.png)

![Published _ Can Share Post (5)](https://user-images.githubusercontent.com/4953703/71656879-1cec8280-2d35-11ea-9cc1-fb7c0015b6e9.png)

Note, this is intended to the same as the standard ones small copy changes to statements. For the second one, on email submit, folks go to the normal page after this.

On the backend, the process should be the same essentially. Expect of course we'll want to make sure Zenodo gets all the required dates and settings for embargos. Emails to embed owners can be as they are now.

**Comment by JosephMcArthur** [comment]
Btw, giving 10.1073/pnas.1905762116 as a doi to the permissions system will give a response that shows off what embargoed stuff looks like.

**Comment by markmacgillivray** [comment]
@JosephMcArthur we talked yesterday about the requirement for an embargo deposit into zenodo to have a license field present. You mentioned that ricks would give us that, but I can't find a suitable field.

For example the DOI you gave above gives us a field called licenses_allowed but the value is null, and a field called deposit_statement_required_calculated with a value of © 2019 National Academy of Sciences - this gives us two problems, in that neither are a suitable license definition for zenodo, and also if that deposit statement is required, there is no corresponding value in zenodo where we could provide such a required statement.

Looking at the ricks results for the OBSTM test article, I see that deposit_statement_required_calculated is cc-by which would be a suitable license value for zenodo, but this does NOT sound like a deposit statement, it sounds like a licence. This clashes somewhat with the above example where the value provided by ricks does sound more like a statement, not a licence. Also the OBSTM article shows cc-by in the licenses_allowed field as well, but of course the OBSTM article is open anyway so in these cases the license info from ricks is less important as we are more likely to find that from lantern, or default it to cc-by anyway.

So, the problem remains - where in the values from ricks can we reliably find a licence definition for embargoed articles that will suit what the zenodo deposit requires? From the examples above, it does not seem possible. We could just default it to whatever we get from lantern and then fallback to cc-by, but if you can clarify if it should be possible to get from ricks, then let me know and I could have it check that first.

**Comment by markmacgillivray** [comment]
For now I have made it so that we check ricks and lantern and sherpa, if ricks provides any kind of cc- licence on one of those fields we use it, if it does not then we use the lantern licence if found in the file or on the splash page, then we look for cc- statements in the sherpa response if nothing else has been found yet. If we find a cc- statement in any of those then we have something we can use.

There is still a question of whether to still allow deposit with a default cc-by if we cannot find any of those licence statements, but do otherwise think the file can be deposited. Is this safe to assume, or should we just not automatically deposit if we cannot find a cc- statement anywhere, and just make those ones that need review?

**Comment by JosephMcArthur** [comment]
> @JosephMcArthur we talked yesterday about the requirement for an embargo deposit into zenodo to have a license field present. You mentioned that ricks would give us that, but I can't find a suitable field.
> 
> For example the DOI you gave above gives us a field called licenses_allowed but the value is null, and a field called deposit_statement_required_calculated with a value of © 2019 National Academy of Sciences - this gives us two problems, in that neither are a suitable license definition for zenodo, and also if that deposit statement is required, there is no corresponding value in zenodo where we could provide such a required statement.

So, the name `licenses_allowed` is misleading I think. Should be more like `license_required`. If that is null, we can choose what we want, and our judgment call right now is the CC-BY is allowed in these cases. Some might say all rights reserved would be better, but that's not the advice we've been given.

For `deposit_statement_required_calculated`, this should form the basis of the `description` field in zenodo. I realize I may not have communicated with you how to handle this, as it falls in between what Natalia was doing and what you were doing. I'll make an issue.

> Looking at the ricks results for the OBSTM test article, I see that deposit_statement_required_calculated is cc-by which would be a suitable license value for zenodo, but this does NOT sound like a deposit statement, it sounds like a licence. This clashes somewhat with the above example where the value provided by ricks does sound more like a statement, not a licence. Also the OBSTM article shows cc-by in the licenses_allowed field as well, but of course the OBSTM article is open anyway so in these cases the license info from ricks is less important as we are more likely to find that from lantern, or default it to cc-by anyway.

Yeah, so I think heather just put cc-by in the statement in place of leaving it null. I'll ask her to fix that, as it should be null for OA stuff.

> So, the problem remains - where in the values from ricks can we reliably find a licence definition for embargoed articles that will suit what the zenodo deposit requires? From the examples above, it does not seem possible. We could just default it to whatever we get from lantern and then fallback to cc-by, but if you can clarify if it should be possible to get from ricks, then let me know and I could have it check that first.

`licenses_allowed` is going to be the best answer. If we find something in the file with lantern, that can overrule it. 

> For now I have made it so that we check ricks and lantern and sherpa, if ricks provides any kind of cc- licence on one of those fields we use it, if it does not then we use the lantern licence if found in the file or on the splash page, then we look for cc- statements in the sherpa response if nothing else has been found yet. If we find a cc- statement in any of those then we have something we can use.

This seems generally fine.

> There is still a question of whether to still allow deposit with a default cc-by if we cannot find any of those licence statements, but do otherwise think the file can be deposited. Is this safe to assume, or should we just not automatically deposit if we cannot find a cc- statement anywhere, and just make those ones that need review?

Safe to assume cc-by is the fallback. Advice her may change, but that's what we've historically gone with and what we'll continue to go with.

**Comment by markmacgillivray** [comment]
OK, in that case we have completed this. The permissions/file part will not provide a cc-by licence unless it is found in one of the ways described above, but if the file is otherwise suitable for deposit, we will assume cc-by for the licence when sending it to zenodo.
