### ISSUE TITLE
API & log monitoring and alerting

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1361]
Mark suggests three days for log & API monitoring and proactive alerting as a remedy to errors we've had recently.

This will help us to:

* Flag errors in the logs without Mark having to look at them
* Ensure things are happening at the rate we expect (e.g email error rates, successful finds, e.g)

**Comment by JosephMcArthur** [comment]
Quick update for the record: Mark has done a load of work here, it's very cool.

**Comment by markmacgillivray** [comment]
More demo to show here, not quite finished, but almost. Should not delay plans for this week.

**Comment by JosephMcArthur** [comment]
On the call you noted that you were looking at the whole api load and comparing that to previous days on the fly. 

Just curious, are you doing that at the level of endpoints too? e.g requests / availabilities? I think that would be helpful, as drops on one could be made up in other places and / or not be significant in terms of whole api load - but still be important to know about. 

Also, are we not comparing against the same day the week before as it would be significantly more difficult. I seems very likely that'll be needed / useful, and if it's going to require a lot more work it may make sense to do now while we're in the thick of it.

**Comment by JosephMcArthur** [comment]
Still to do:

- [ ] walk joe through the system
- [ ] configure logging

**Comment by markmacgillivray** [comment]
This has been configured and setup to send alerts now, balancing may be tweaked again later but seems good for now.

There is some more to discuss in relation to logging embed events and errors, we could potentially add more "system" notifications from embeds even under normal operation and also on total failure, and send these to the logging system as well to trigger alerts on out-of-average usage. This would be a bit extra work on top of what we have done so far, but fairly easy to add now with the neater embed library and the better log monitoring and alerting system we have.

**Comment by markmacgillivray** [comment]
Forward system load alerts to Joe

**Comment by JosephMcArthur** [comment]
Ready to close once forwarder is set up.

**Comment by JosephMcArthur** [comment]
- [ ] have the system send only one request per issue
