### ISSUE TITLE
Improve UX of bug emails

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1364]
Can we:

- [x] Add some spam rejection to the forms (invisible field sort of stuff)
- [x] format them nicely
- [x] stop them threading (again, a throw away id or random number)
- [x] When: `"form": "uninstall"` make the subject: `[OAB forms] Uninstall notice`
- [x] When: `"form": "wrong"` make the subject: `[OAB forms] Wrong article`
- [x] When: `"form": "bug"` make the subject: `[OAB forms] Bug`
- [x] When `"form": "general"` make the subject `[OAB forms] General`
- [x] for other submissions, make the subject `[OAB forms] Other`

and finally, is there any way I can get a spreadsheet of these easily?

**Comment by markmacgillivray** [comment]
These bug reports don't get stored in the system, they only get emailed, so a spreadsheet cannot be generated. The system could be updated to save them somewhere then give you a query/csv endpoint on them, but that would require some extra work.

**Comment by markmacgillivray** [comment]
This issue is all done unless you want the system upgraded to store these and give an output of them. Probably best to close this issue and schedule another one for that work, if you want it.
