### ISSUE TITLE
Set up shareyourpaper.org config

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1366]
Me to expand. Est 2 days.

**Comment by JosephMcArthur** [comment]
- [ ] joe, ideally, once this is shut it also works for us!

**Comment by JosephMcArthur** [comment]
Note, making lots of progress on this, but it's not ready yet so skip if you get to it until I put up what I've got!

**Comment by JosephMcArthur** [comment]
Right, this took me aaaaages, but better me than you.

At the set up page here: https://dev.openaccessbutton.org/shareyourpaper/setup you'll find it has real sections, real copy, all that. 

I have questions for all the key parts of the config, and I gave them IDs. 

If you go [here](https://docs.google.com/document/d/1FK_jIUxNG3ONQalV4JSjVYZV1QRgjn-mn8fa2BhS2r0/edit#heading=h.ob9mcwfs4vbq) and look down for the IDs, you'll see what each can be expected to be and what it should do. There may be some holes in the info I gave, but that's okay.

- [ ] Mark, to close this issue can you have the config do as described on the options that don't involve other issues (always linked). 

I still have to:

- [ ] check all this
- [ ] make changes from feedback
- [ ] add previews

but none of this should get in your way

**Comment by markmacgillivray** [comment]
This is still to be done

**Comment by JosephMcArthur** [comment]
Okay, for right now, I'd like to ship just what's 100% needed by Montana and us to get testing with real users. 

That is:

- [ ] not_a_library
- [ ] deposit_terms
- [ ] email_domains_off
- [ ] email_domains

Once that is done, we can come back and finish the rest off later (I won't close this, but I will move it out the sprint).

**Comment by markmacgillivray** [comment]
What is the purpose of email_domains_off? If we are not given any domains in email_domains, then should we not just accept any email anyway? Or if email_domains is empty, should we never accept any emails? What would be the point of that? email_domains_off seems redundant, we could just allow any domains if no domains are specified in email_domains_off.

Also, for not_a_library, what is the purpose of it?

**Comment by markmacgillivray** [comment]
Never mind about not_a_library, found that.

**Comment by markmacgillivray** [comment]
email_domains_off agreed not necessary, removed it.

**Comment by markmacgillivray** [comment]
@JosephMcArthur the above ones done, as required. Unassigning myself now and moving on to next issue.

**Comment by JosephMcArthur** [comment]
Currently, I can't see the config actually affecting them embed. I *think* it's being saved to the ILL embed, as when I got to the set up page there I see some of the things I've changed turning up there. 

I copied the code from the ILL set up page, I'm guessing that it's saving to the wrong place.

**Comment by markmacgillivray** [comment]
OK I have gone through that and changed anything that looked like it was referring to instantill. Try again now, see if it works - I'm just making as many changes as I can fit whilst going through the airport, so have not tested yet.

**Comment by JosephMcArthur** [comment]
Appreciate the attempt, I'm still not seeing the config get saved properly sadly.

**Comment by markmacgillivray** [comment]
OK config changes are working now, they show up on the setup page, and changing a value there does get saved to the backend and served back to the UI. Will assign to you in case there is anything else you want to check, otherwise can close.

**Comment by JosephMcArthur** [comment]
shouldn't have closed, more config to do later

**Comment by markmacgillivray** [comment]
What else is needed to do on this?

**Comment by JosephMcArthur** [comment]
There are lots of other config this we'd like to see changed, which this is an issue for. But, it's less important than other stuff right now.

**Comment by JosephMcArthur** [comment]
Okay, for this, we need to switch up the 'I don't have a doi button'.

It should be as follows:

if_no_doi_go_here: String, email / link. If present, show the “My paper doesn’t have a DOI’ button and link to it if a link and give a mailto if it’s an email. If the user doesn't enter any value, don't show the link.

**Comment by JosephMcArthur** [comment]
This is basically done, going to close and see what libraries request from us rather than building more
