### ISSUE TITLE
Have file checking API say clearly what version it thinks the file is

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1367]
Right now the file checking part of the API reports if something is acceptable relative to the permissions API. I.e it'll say 'true' this can be deposited vs the list of acceptable versions. 

It would be better if we also plainly reported what version the file checking API thinks it is as 'preprint, postprint, publisher pdf'. We should also spit out standard versions of those (like ricks does) for folks who use those.

**Comment by markmacgillivray** [comment]
Output now states version, and shows unknown if nothing else is found. This is done separately to the permissions.
