### ISSUE TITLE
When file URL doesn't work, have file checking pass back a nice error

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1371]
Right now the file error:

https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/nope.pdf

and

https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/nope.pdf&doi=10.1126/science.196.4287.293

is pretty ugly. I feel like we should have it still return something (especially if other metadata is passed) along the lines of just saying we couldn't fine the file

**Comment by markmacgillivray** [comment]
Done
