### ISSUE TITLE
Check regex's are working in file strings sheet

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1373]
File is [here](https://docs.google.com/spreadsheets/d/1XA29lqVPCJ2FQ6siLywahxBTLFaDCZKaN5qUeoTuApg/edit#gid=0)

**Comment by markmacgillivray** [comment]
I have checked that regexes in general do work. Whether or not specific regexes work as intended would depend on what they were intended to find. Perhaps for regexes we should have an examples column where strings that the regex was intended to match could be put, and that way it would be easier for us to discern what they were supposed to do. I've already shared an online regex tester which is pretty useful, so we can work through those regexes in later testing and when we add new ones. For now I think the aim of this issue, to check that regexes work in general when provided, has been achieved, so will close.

**Comment by JosephMcArthur** [comment]
I like that idea. If I make a new column, will it break anything for you?

**Comment by markmacgillivray** [comment]
No it would be fine.

**Comment by JosephMcArthur** [comment]
perfect, done! thank you
