### ISSUE TITLE
Generate CSV export link for users deposits

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1374]

**Comment by markmacgillivray** [comment]
Did you want this just as the zenodo page links or did you want the file links scraped from them? If you want the zenodo pages directly, you can get them here:

https://api.openaccessbutton.org/requests.csv?q=received.zenodo:*%20AND%20NOT%20undefined&fields=received.zenodo&size=200

**Comment by JosephMcArthur** [comment]
File links scraped please :)

**Comment by markmacgillivray** [comment]
https://dev.api.cottagelabs.com/service/oab/scripts/zenodofiles.csv

**Comment by JosephMcArthur** [comment]
Ah,this issue was actually for generating export sheets for shareyourpaper.org embeds

**Comment by markmacgillivray** [comment]
Oh OK. I'll alter the deposit endpoint to get those file links at the time of deposit then, either from the zenodo API responses if it includes them or by scraping the page at that time.

**Comment by JosephMcArthur** [comment]
So, my comment about the files was related to the script (I didn't realize we were on the wrong issue at the time). BUT. We will actually need to do what you describe (have a link to the record, and link to the file). 

FWIW, I think the file link is just:

https://zenodo.org/record/{ID}/files/{filename}

**Comment by markmacgillivray** [comment]
I'm not sure if the filename will always be identical, it may depend on certain special characters that could appear in it. However I think the zenodo api will return us that file name anyway, I am investigating that while I do the other zenodo API update stuff that I am still working on for the main deposit issue.

**Comment by JosephMcArthur** [comment]
Some notes here. 

In this system (soon to be seen in config), we'll want to:

* provide an export of all data
* provide an export of all records where we have a file (e.g ignoring oa deposit, dark deposit)

be able to get this 'from' a certain date (via date picker). I.e so people can get stuff just from the last week.

**Comment by JosephMcArthur** [comment]
There is now a place to put whatever you're making here in set up at: https://dev.openaccessbutton.org/shareyourpaper/setup#bulk-upload

**Comment by JosephMcArthur** [comment]
I'm relatively sure this is unfortunately not working, at least on dev. 

e.g this is my download link: https://dev.api.cottagelabs.com/service/oab/deposits?uid=JkXSRq7RffwjgHQEn for my test account (posting my github page).

It returns no deposits.

**Comment by markmacgillivray** [comment]
OK I have altered this now we have clarified what was meant here, and it does now output a sheet. Let me know if the format is suitable, can close if so.

**Comment by JosephMcArthur** [comment]
Can we output a line per deposit, not a line per article?

**Comment by JosephMcArthur** [comment]
I'm not seeing it output again. I'd expect the test links below to have deposits.

Test link(s) below:

All: https://dev.api.cottagelabs.com/service/oab/deposits.csv?uid=JkXSRq7RffwjgHQEn
Files: https://dev.api.cottagelabs.com/service/oab/deposits.csv?uid=JkXSRq7RffwjgHQEn,deposit.zenodo.url&q=deposit.zenodo.url:*

**Comment by JosephMcArthur** [comment]
Note: https://dev.api.cottagelabs.com/service/oab/deposits?uid=JkXSRq7RffwjgHQEn&q=deposit.zenodo.url:*

This is the best api link we can currently give for users to get their file deposits. 

Need to discuss more how to manage this.

**Comment by markmacgillivray** [comment]
I have updated /deposits to provide a JSON list of every deposit, even if there are duplicates. It will only contain deposits that were actually made by the specified user, if a user is specified. It lists the deposits in order of when they occurred - it is possible that there could be deposits for a particular article appearing multiple times, and they may not appear next to each other in the list, if deposits from other articles intervened.

I have also added a /deposited route which lists only the deposits for which there is a zenodo file URL available. This one removes duplicates if the DOI and file URL are the same, but in many cases we have same DOIs but different files (because we upload another copy). This could be changed to remove duplicates if just the DOI matches, so that for ingest only one file URL would be given for any particular article.

In both cases, adding .csv to the route gives you the data as a CSV.

**Comment by JosephMcArthur** [comment]
Let's chat about this when we next chat, that seems to be a pretty good way to make headway on this. The changes above sound good at first glance.

**Comment by JosephMcArthur** [comment]
So, I think the object here should contain:

* Any metadata we get
* .permissions.permissions
* .permissions.ricks
* .permissions.file
* .deposit
* .find.url
* the full text link to an oa version

**Comment by markmacgillivray** [comment]
This seems a bit odd. When we first talked about it, it sounded like you didn't want the json results to be article-oriented, and that you wanted them to be deposit-oriented and contain info about the deposits. But now it seems you want the deposits to contain virtually all of the article metadata. That means we are going to create a long list of very duplicated data, where we basically replicate the article metadata over and over again into a record for every deposit. Why would that be useful to anyone using this as an API? Surely, if they want all the metadata pertinent to the article the deposit is about, wouldn't it be better to have what this endpoint originally gave, which was article-oriented data, with deposits contained within them?

I'm finding it increasingly difficult to understand why we are making a lot of the decisions we are making. What actual expressed user need is this trying to fulfil? Who asked for it, and what are they trying to do with it? If we are trying to guess what they are going to do with it, who is it that we are trying to guess about? what kind of user are they, what is their technical skill, and why would they want the data in the way you have described? If we don't know these things, why are we doing it at all?

**Comment by markmacgillivray** [comment]
Actually, never mind. I'll just do what was asked for. There is no point in me second guessing your decisions.

**Comment by JosephMcArthur** [comment]
There's a lot of point, I want to be second guessed! I also want to make sure you understand what decisions are being made and why, so something is obviously going wrong. Let's talk about it.

**Comment by markmacgillivray** [comment]
json for deposits endpoint has been changed to how you describe above, please check and close if confirmed.

**Comment by JosephMcArthur** [comment]
Looks great! 

But to close this issue we need to get it into a CSV. Seems like that's still happening in the old way. When you take a look at that, can you also make sure any data that's complex to get into a single row is handled in the same was a for requests?

**Comment by markmacgillivray** [comment]
I have flattened these out into csv as you have described, take a look, close if happy:

https://dev.api.cottagelabs.com/service/oab/deposits?uid=JkXSRq7RffwjgHQEn

**Comment by JosephMcArthur** [comment]
I can see a couple of things that ideally we'd change here, but that's a refinement I think we can handle later.
