### ISSUE TITLE
Set up shareyourpaper demo

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1375]
TODO for Joe to expand

**Comment by JosephMcArthur** [comment]
So, to make the demo work (independent of copy) we'll need:

- [ ] a fake DOI that can elicit a fake response on the AAM page
- [ ] the demo to ignore a file upload on that page, and show a success page with a fake doi
- [ ] to be able to show a fake 'wrong version' screen after a button click (perhaps responsive to a certain url #?)
- [ ] have a fake doi that shows a dark deposit screen

Generally, we'll want to do this on the shareyourpaper.org domain like we normally do with instantilll.org. We'll want it to be blue and what not, but this is all stuff I can do if you can get the above working for me.

**Comment by JosephMcArthur** [comment]
Another note here, stuff with the file checking API, or any feature related work, is much more important than this even if it's in the next sprint.

**Comment by markmacgillivray** [comment]
Yeah I've actually done more on milestone 77 issues than 76 issues this week probably :) But making progress with these earlier ones too.

**Comment by markmacgillivray** [comment]
This is about three quarters done, but probably not going to get finished today/tonight as I have a meeting coming up and is already quite late. I may get it done over the weekend, otherwise will be the first thing finished on Monday. As we're technically ahead on milestone 77, this should hopefully be OK. We can discuss at Monday meeting.

**Comment by JosephMcArthur** [comment]
Ace thank you! 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
NOTE #1340 and #1353 should also be tested and closed by this

#1340 is dark deposit needs unique ending
#1353 is deposit when publisher pdf is allowed

**Comment by markmacgillivray** [comment]
Have a look at 

https://dev.openaccessbutton.org/shareyourpaper/demo

I think that covers what you wanted for the demo. Let me know if anything is missing, otherwise close this issue. Also the two related issues commented above, I think are fixed as well and have closed them - but take a look and let me know if there is something wrong there as well.

**Comment by JosephMcArthur** [comment]
Just did some testing, great to have this get so far so fast. 

Some issues:

* the demo doesn't show a successful upload on taking a file
* I can see people wanting to test the file checking system IRL. Does sending people to dev seem like a good way of letting them test file upload stuff, or can we activate a catch where it won't upload in a demo div or setup page?

**Comment by markmacgillivray** [comment]
For the successful upload problem, I am looking into that, but to sooner let you know about your second question:

I think if people will want to test the file checking system alone - which I imagine they will, and I would think that some people may not only want to test it but use it to get info about versions - it would be better to have them use that directly, not making them go to dev or adding a catch.

Dev should not be used by real users as they could get all sorts of odd results, or no results. Activating a catch just makes the point of the shareyourpaper embed more confusing. If what people want to do is check a file, then they should check a file. It would be much easier to just do that on a page (or a subset of any page) that allows them to upload a file and provides them the results back. They'd also be able to do that using the API if we document the permissions endpoint separately from the deposit endpoint.

**Comment by JosephMcArthur** [comment]
It looks like https://dev.openaccessbutton.org/shareyourpaper/demo#dark currently goes to the result we'd expect if you could deposit an AAM.

**Comment by markmacgillivray** [comment]
Looks like I did not put the right demo DOI in the page, fixed now.

**Comment by JosephMcArthur** [comment]
Closed before realizing there is stuff about upload we have ticked off.

**Comment by JosephMcArthur** [comment]
```
I think if people will want to test the file checking system alone - which I imagine they will, and I would think that some people may not only want to test it but use it to get info about versions - it would be better to have them use that directly, not making them go to dev or adding a catch.

Dev should not be used by real users as they could get all sorts of odd results, or no results. Activating a catch just makes the point of the shareyourpaper embed more confusing. If what people want to do is check a file, then they should check a file. It would be much easier to just do that on a page (or a subset of any page) that allows them to upload a file and provides them the results back. They'd also be able to do that using the API if we document the permissions endpoint separately from the deposit endpoint.
```

Agreed, pointing them to dev was a bad idea.

When having them upload a file directly, I'm not sure how that's different from a catch though. Either way, somewhere, they'll need to be able to upload a file on live where it'll get punted into the sandbox. I'd suggest we do that when the system is acting in a demo div or on set up pages. As you know, I'd prefer to not expose file checking functionality alone.

**Comment by markmacgillivray** [comment]
Hmm, so you want people to be able to demo on live but actually submit a file into the zenodo sandbox? Does that really provide them with much? If we know they are using it in a demo setting, why don't we just serve them the pretend DEMO response anyway? How would making that a real link to zenodo make anything visibly different to the shareyourpaper demo? If all you want is for them to be able to click it and see it open in zenodo, we could do that by just serving a demo url that actually does go to something we have deposited in zenodo.

The reason I think it is different from a catch is that you said "people may want to test the file checking system in real life". If we think what they are wanting to do is test the file checking system, why wouldn't we just let them upload a file for the purpose of getting back the file checking results so they can test it?

**Comment by JosephMcArthur** [comment]
Hmmm, let's discuss this on our call. 

To close this, we just have to make the fake file upload for AAM leads to a successful page.

**Comment by markmacgillivray** [comment]
For demo page it is fine that we just return a zenodo demo url.

For setup page pass a param saying this is the setup page, so the deposit etc should happen as if it is real including sending the emails etc to the institution, but still should not actually send a file to zenodo and should not save the result into our catalogue.

**Comment by markmacgillivray** [comment]
I think this is now the case

**Comment by JosephMcArthur** [comment]
> Hmmm, let's discuss this on our call.
> 
> * [ ]  To close this, we just have to make the fake file upload for AAM leads to a successful page.

This is still not working it seems. Again, hard for me to track down exactly what the root issue is.

**Comment by markmacgillivray** [comment]
I'm confused here. You seem to have removed or entirely disabled the demos I had already connected up, which sent demo DOIs that triggered the expected results. I don't know what it is you are trying to test, but it doesn't sound like it can be the same thing as what I was trying to build.

**Comment by JosephMcArthur** [comment]
The ones you set up should still be working, I've just added real-ish copy for when this becomes the actual demo. If you need to add more test DOIs you can do it on the first page of the demo no problem, I preserved that. 

Let's chat about it.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
As far as I know, the only thing left to do on the demo is to force a successful upload when the user tries to upload from this point https://dev.shareyourpaper.org/demo#general (and only this point). 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
OK, typing in the 10.1234/oab-syp-aam demo DOI does cause the system to allow the deposit, however a change from earlier today was passing the wrong DOI to the deposit part. Then when the DOIs were not still used by the demo page buttons I was confused about what was putting the other DOI in. So now, typing the demo DOI directly into the box does cause the demo response to occur, and it will do this regardless of where it is used - I did not set up anything to allow based on a certain page hash, so I am not sure what you are referring to there.

**Comment by JosephMcArthur** [comment]
Just got it working! What is going on here is fine, the fake doi approach is all fine, I just forgot about that.

Can we have the link given be a fake demo DOI. And, if this page is representative of the zenodo response generally, can we pull the DOI instead of the zenodo link? 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
Okay, the above is, lets move this to another issue. This is good, there are demo tweaks to make but this issue has done it's part.
