### ISSUE TITLE
Handle deposit statements, and a few other fields in shareyourpaper.org

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1376]
This is all based on what we've done with requests for a while now. 

## `description`

If Rick's gives us a statement, we should use that. If we don't, use:

The publisher's final version of this work can be found at https://dx.doi.org/<<DOI>>.

After that, to all deposits in this field we should have: 

> Deposited by shareyourpaper.org and openaccessbutton.org. We've taken reasonable steps to ensure this content doesn't violate copyright, however, if you think it does you can request a takedown by emailing help@openaccessbutton.org. 

## `related_identifiers`

This should be the DOI being submitted, and the relationship is `isPreviousVersionOf` if we think the file is an AAM or pre-print, and `isIdenticalTo` if we think it's a final publisher pdf.

`Example: [{'relation': 'isPreviousVersionOf', 'identifier':'10.1234/foo'}`

## `version`

We should use NISO standard language to fill this from what the file checking system thinks. 

Mapping for that is as follows:

versions_archivable: [
"preprint",
"postprint",
"publisher pdf"
],
versions_archivable_standard: [
"submittedVersion",
"acceptedVersion",
"publishedVersion"
]

# `keywords`

If we get them from crossref, let's fill them here

We may already do this and I just have forgotten.

# `creators`

If we get them from crossref, let's fill them here

We may already do this and I just have forgotten.

# various journal info...

If we can fill the below, lets:

`journal_titlestring`
`journal_volumestring`
`journal_issuestring`
`journal_pagesstring`

**Comment by markmacgillivray** [comment]
These were either already done or have been added. The only one to confirm is, for description when you say "if Ricks gives us a statement" you mean the "deposit_statement_required_calculated", right? If so, yes I have set it to use that, apart from the cases where that one just seems to have a licence shortname like cc-by.

**Comment by JosephMcArthur** [comment]
Yes, `deposit_statement_required_calculated` is correct. I think soon you'll not see short names like that, but doens't really matter!
