### ISSUE TITLE
Particularly bad wrong article being returned several times over with different queries

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1378]
"Searched for \"Clinical and practical perspectives on the use of intravenous vs. subcutaneous epoetin alfa in hemodialysis patients\" and OAB matched to this page: http://email.mg.openaccessbutton.org/c/eJxtjsEKgzAQRL9Gbw27GhtzyKFQPJf-QRo3KtVEshF_v4H2WJjDGwaGN5pXR8pDvZgGGgBEhZ3s4SpQSFD9AKhh6FV716qSsE0i7hSsc8T8OnKOQcQ01bOBFrBvO9-BJwmjthpwVN5riwokqno1c847V-2taoaS8zzFZtObMtsw_ki4uJXtkcr9k1ayTFx6IZdT5CNNi7PrZQmc07FRyHz5usS0EAvLe53MTOteXP-JfgCrZ07h \

"Electrosurgery Market worth $8.8 billion by 2025\"\ninstead of this article: http://email.mg.openaccessbutton.org/c/eJxtjk2OhSAQhE-DS9LNj8CCxSTGe6i0TxJHiOB7M7efPsCkK52qWlS-FFdLbochRwUKANGhNR5GidKA8zNggNk7PQUnDHy_ZKl0LdtGra1P7-WS5X4NR_RJjc4bswMoXMfgtFfow2L2ZXXB-uGMR-9V6C-hZtaWOzWi-0fm1mVtj6T0cP_O9EllY5fK5zrLkoRmm4WeEBiKL1hpDQahxpt4cOKPHPpvJU417cMdDzor8_4H-wcNmElI", 

From Mike!

**Comment by JosephMcArthur** [comment]
"feedback": "I searched the article title \"Allomogurnda, a new genus of gudgeon (Eleotridae) from fresh waters of New Guinea, with descriptions of seven new species\" and the OAB result points to an article titled \"Electrosurgery market worth 5.17 billion usd by 2021.\"",

**Comment by JosephMcArthur** [comment]
It appears have been made into a request: https://openaccessbutton.org/request/d3jWRCP6WnxaxZ6ci

**Comment by markmacgillivray** [comment]
There were two parts to this problem, one was that recent upgrades to our find system was causing it to return a different metadata structure that did not work with the old requests system properly when the new find system could not find anything. It was not actually matching it to that article or creating a new request, it was just directing the user to the first request it found in a random search. That request itself is just one that someone must have ran in the past on an irrelevant website, so it could be deleted as normal.

I have fixed that issue, so now if the new find system cannot find anything then a new request will be created for the user.

The second part to the problem though is that the new find system indeed does not find anything in this case. I have checked a few of the endpoints we check manually, and they do not yet appear to return a result. So this may not be an error, it may just be that we cannot find this article. I am continuing to check this part though, to see if we should be able to find it.

**Comment by markmacgillivray** [comment]
There were two parts to this problem, one was that recent upgrades to our find system was causing it to return a different metadata structure that did not work with the old requests system properly when the new find system could not find anything. It was not actually matching it to that article or creating a new request, it was just directing the user to the first request it found in a random search. That request itself is just one that someone must have ran in the past on an irrelevant website, so it could be deleted as normal.

I have fixed that issue, so now if the new find system cannot find anything then a new request will be created for the user.

The second part to the problem though is that the new find system indeed does not find anything in this case. I have checked a few of the endpoints we check manually, and they do not yet appear to return a result. So this may not be an error, it may just be that we cannot find this article. I am continuing to check this part though, to see if we should be able to find it.

**Comment by markmacgillivray** [comment]
Having checked some more, we are unable to match this title to a DOI, and we are unable to find the article with just the title. Europepmc does not return a result for the title, and crossref reverse lookup does not accurately match, so we get no DOI. Looking up against DOAJ as a last resort also returns nothing, so the process stops there.

We do have bing checks for titles as a fallback option, but so far we only have that enabled for requests that come in from a widget, oasheet, illiad or clio. So when I check directly bing is not used. We could enable bing for more checks, which may find more suitable results that lead to a URL. A direct check against the bing API from our system does return a URL: https://pdfs.semanticscholar.org/94f7/7c14120796b6f5f430977306f4dfea71a13c.pdf
