### ISSUE TITLE
undefined results in InstantILL confirmation email

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1379]
> title:
> The National Epidemiologic Survey on Alcohol and Related Conditions (NESARC) waves 1 and 2: review and sum- mary of findings
> 
> from:
> AJrfNWswDr4MY8KgD
> 
> plugin:
> instantill
> 
> embedded:
> https://ill.ulib.iupui.edu/ILLiad/IUP/illiad.dll?Action=10&Form=20&Value=GenericRequestSimpleArticle
> 
> pilot:
> 1575663687505
> 
> live:
> 1575663687505
> 
> forwarded:
> true
> 
> Open access button ILL ID:
> hdJEnAESr5d7QnTwY
> 
> Search URL:
> undefined

Seems like the search URL shouldn't be `undefined`.

**Comment by JosephMcArthur** [comment]
In the below, the search URL didn't really make sense and was linked as http://sociology%20of%20race%20and%20ethnicity/

> title:
> Conundrums of Integration: Desegregation in the Context of Racialized Hierarchy
> 
> from:
> AJrfNWswDr4MY8KgD
> 
> plugin:
> instantill
> 
> embedded:
> https://ill.ulib.iupui.edu/ILLiad/IUP/illiad.dll?Action=10&Form=20&Value=GenericRequestSimpleArticle
> 
> journal:
> Sociology of race and ethnicity
> 
> year:
> 2015
> 
> notes:
> The user provided some metadata.
> 
> pilot:
> 1575663687505
> 
> live:
> 1575663687505
> 
> forwarded:
> true
> 
> Open access button ILL ID:
> EAQjM8ZZ9wCYqMSms
> 
> Search URL:
> Sociology of race and ethnicity
> 
> { "name": "Mike", "title": "Conundrums of Integration: Desegregation in the Context of Racialized Hierarchy", "from": "AJrfNWswDr4MY8KgD", "plugin": "instantill", "embedded": "https://ill.ulib.iupui.edu/ILLiad/IUP/illiad.dll?Action=10&Form=20&Value=GenericRequestSimpleArticle", "journal": "Sociology of race and ethnicity ", "year": "2015", "notes": "The user provided some metadata. ", "pilot": 1575663687505, "live": 1575663687505, "forwarded": true, "illid": "EAQjM8ZZ9wCYqMSms" }

**Comment by JosephMcArthur** [comment]
This is the search url being undefined. 

That's now {{worldcatSearchUrl}}

**Comment by markmacgillivray** [comment]
This should be fixed on dev now
