### ISSUE TITLE
Add help menus and article context to shareyourpaper.org UI

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1381]
# Help

These menus show us as [?] and when clicked, javascript should show more information (opening up a hidden text div). 

There is also a version of this as a secondary button, which will open up a hidden text div with more links to hidden text divs. 

# Context

On the AAM pages, and others, we'll want to start providing links to articles and journal policies (quite likely). This, we think, will help people feel like the response is 'about them', which we had originally done with journal names. We could also consider showing journal names, but shortened. 

I'm exploring programmatic journal abbreviations [here](https://docs.google.com/spreadsheets/d/1EWuliDjpTwX_bgPXrIktBtJcffopxL8n3JVVqwt09Jc/edit#gid=0).

Will give copy after I finish UX texting

**Comment by JosephMcArthur** [comment]
The stand. for abbr. is here: https://www.issn.org/services/online-services/access-to-the-ltwa/

**Comment by JosephMcArthur** [comment]
We'll want 'your paper' to link to the DOI of the paper in question.

**Comment by JosephMcArthur** [comment]
# Adding context around journals

During user testing, we clearly saw that if we said 'the journal' people doubted we'd really checked, but if we put the journals name we didn't. As mark has correctly raised before, putting in names is tricky as they can be of unknown length, and most are so long that it'll be a pain given how hard we've worked to keep copy short and sweet. 

That said, the journal name is clearly important. So, what I'd propose is that we take the Crossref journal field and apply abbreviations to it.

I found a list of standard abbreviations here: https://www.issn.org/services/online-services/access-to-the-ltwa/ which could serve as the backbone. Annoyingly, there don't seem to be abbreviations for some pretty common words, like 'science', so we'll add those manually (people don't notice, I tested).

I'm hoping that if we spin up a google sheet with the long form of the word to match, and the abbreviation, a find and replace should be quite do-able. Here's the sheet: https://docs.google.com/spreadsheets/d/1lMaOg1zqpAX0GZpJ_d-U9KoNRiTeTy2tLK5lSfJw7E0/edit#gid=1753325698. The twist is that in the standard file, there are like 60k lines, so I'm a bit worried about speed... but my vlookups are still instant so I'm hoping it won't be too bad. 

- [ ] done

**Comment by JosephMcArthur** [comment]
> The twist is that in the standard file, there are like 60k lines

The twist of the twist is that 18k of them are N/A, or no abbreviation... which is unhelpful. We can just remove those from the file though!

**Comment by JosephMcArthur** [comment]
For the Help menus, I've put a [?] in the text after 

`The library has checked and the journal encourages you to freely share your paper so colleagues and the public can freely read and cite it`

Can you make it so that when it's clicked, it opens up some text after the full stop. You can see what I mean here: https://www.figma.com/proto/jIMGdoIgDdQVLTj2wSGL6g/Shareyourpaper.org?node-id=1501%3A28&scaling=min-zoom

Some placeholder copy you can use is:

`We know you can share your paper as we’ve checked your article against an automated service.`

- [ ] done

Finally, for me:

Specify how to link out to journal full-text policies.

- [ ] done

**Comment by JosephMcArthur** [comment]
Okay, for that placeholder copy above, instead let's do:

> You can read the full text of the publisher's policy here.

The link for that should be the link available at authoritative_permission.can_post_now.provenance.policy_full_text

**Comment by markmacgillivray** [comment]
This still has to be done

**Comment by JosephMcArthur** [comment]
`short-container-title` from crossref also gives short journal names.

**Comment by JosephMcArthur** [comment]
I have removed [?] for the initial shipping.

**Comment by JosephMcArthur** [comment]
This has become a mess, and there are like three things going on here. I'm going to split out and restart.
