### ISSUE TITLE
on shareyourpaper.org and open access button allow for url to share same structure as doi

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1382]
i.e so that:

doi.org/10/10123/something

can be subbed out for

shareyourpaper.org/10/10123/something

without use of ?doi=

This is only required on our sites, and it doesn't need to be a part of embed code.

**Comment by JosephMcArthur** [comment]
Note, that if someone comes to 

shareyourpaper.org/

and puts in 

10/10123/something

would update the url too

shareyourpaper.org/10/10123/something

as well.

**Comment by JosephMcArthur** [comment]
Note, I have a page where we can start to play around with our version here: 

https://dev.shareyourpaper.org/sneakpeak

**Comment by markmacgillivray** [comment]
Where on open access button should this happen? Most pages on the site do not have any functionality to do anything if they were given such a URL with a DOI in it, so what is it that you are wanting to be triggered on the OAB site? I understand for shareyourpaper.org it is triggering the shareyourpaper embed. But on OAB, do you mean you want the front page to behave this way, and do the usual availability search? Or you want the shareyourpaper part of the OAB site to behave this way? Or something else?

**Comment by JosephMcArthur** [comment]
It's a total mystery to me why I have said I want this done on OAB too. If you're done on syp, feel free to close.

**Comment by JosephMcArthur** [comment]
Currently this happens on sites other than shareyourpaper, e.g on https://josephmcarthur.github.io/playground/syp-dev. E.g put 10.1073/pnas.1905762116 into it an it'll appear in the URL. 

This shouldn't happen, this behavior is desirable only for shareyourpaper.org. However, if we updated it to have the URL update to add ?doi=10.1073/pnas.1905762116 that would then be desirable on external sites.

**Comment by JosephMcArthur** [comment]
Also, when a user hits a 'do another' button we should remove the doi from the URL.

Currently we don't, which is replicable on:

https://dev.shareyourpaper.org/sneakpeak/10.1186/1758-2946-3-47

after you submit and press do another.

**Comment by markmacgillivray** [comment]
This should be done now, please test and close

**Comment by JosephMcArthur** [comment]
When ?doi= is present do another doesn't remove the ? at the end. Otherwise, looks good! 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
I don't know what that sentence means.

**Comment by markmacgillivray** [comment]
Understood from call, have a look at why the ? is not being removed.

**Comment by markmacgillivray** [comment]
OK, I have changed this again, I think it works as you intended now. Can you have a look to confirm?

**Comment by JosephMcArthur** [comment]
Can we make this responsive to the back button? 

At the moment when you put in a value like 10.1073/pnas.1905762116 and go to https://dev.shareyourpaper.org/sneakpeak/10.1073/pnas.1905762116 or https://josephmcarthur.github.io/playground/syp-dev?doi=10.1073/pnas.1905762116 and hit 'back' in the browser the URL changes but you don't actually go back on the UI. This is unintuitive and makes it hard to go back.

**Comment by markmacgillivray** [comment]
Where do you want it to go back to

**Comment by JosephMcArthur** [comment]
Ideally whatever the step they were previously on was. Generally, this will be the landing screen (i.e where you enter the DOI).

**Comment by JosephMcArthur** [comment]
Just to be crystal clear. If you come a site like randompage.org by clicking a link directly to https://josephmcarthur.github.io/playground/syp-dev?doi=10.1073/pnas.1905762116, and then clicked back, I think you should still go back to randompage.org, not the doi entry page.

**Comment by markmacgillivray** [comment]
To have it always step back to the start page of our embed is easy. To have it step back to whatever you may have been on before is also not too hard but is quite distinct from any of the functionality we have built in so far. To do it that way we really should think about that sort of thing up front and design around those requirements. I can certainly add that in now, but will take a while. A couple of days. And we would just be making more of a mess of stuff that is already a mess.

**Comment by markmacgillivray** [comment]
If user interacts with page, back should go to start of embed, like restart. If they have not interacted, allow to go back to wherever they came from (which prob passed  param)

**Comment by markmacgillivray** [comment]
OK there is a simple catch in now to restart the embed if the user presses back. If they are already back to the start of the embed it takes a couple of clicks to get back to whatever external page they were on before, but it would take too long to investigate why that is not just one click. Please test and close if this is good enough.

**Comment by JosephMcArthur** [comment]
working great as far as I can tell. I can't see the issue you describe, but it seems acceptable right now
