### ISSUE TITLE
Add response for when deposit isn't allowed, and dark deposit isn't done

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1384]
There are some places (like us) who can't do dark deposit. For them, when deposit isn't allowed we should give them the option to request permissions.

This can be a config option, and will just result in:
* a mailto link with some metadata, config and data from permission merged in
* copy changes

**Comment by JosephMcArthur** [comment]
Right, so I'm still asking for feedback on the finer details here, but I think we have a broad approach outlined in [here](https://docs.google.com/document/d/1PxVaJ-1hhxf_AWccq9SiS5oTTJjlB3ZFd-dFgiT74-E/edit?usp=sharing).

**Comment by markmacgillivray** [comment]
This is still to be done

**Comment by markmacgillivray** [comment]
Is this ready to be done?

**Comment by JosephMcArthur** [comment]
I thought it was until this morning, when I realized there was a giant hole in the workflow :)

**Comment by JosephMcArthur** [comment]
More soon...

**Comment by JosephMcArthur** [comment]
Okay, what to do is now properly specified here: https://docs.google.com/document/d/1PxVaJ-1hhxf_AWccq9SiS5oTTJjlB3ZFd-dFgiT74-E/edit?usp=sharing

**Comment by markmacgillivray** [comment]
OK I believe this has been added to the right place, please configure your embed to how you'd want for these settings to be triggered, and test it to see if it behaves as you expect.

**Comment by JosephMcArthur** [comment]
Seems to be coming up in the right place. 

Did you see the parts of the doc that specified the button functions?

**Comment by markmacgillivray** [comment]
OK I have tried a different way to add the mailto info into the two buttons. Please try again and let me know if they work as you expect now. Or let me know what value you are using to get them to show up.

**Comment by JosephMcArthur** [comment]
Still no luck. Seems like right now it skips directly to the 'do another' screen.

You can test it here: https://josephmcarthur.github.io/playground/syp-dev?doi=10.15650/hebruniocollannu.89.2018.0221 or https://josephmcarthur.github.io/playground/syp-dev?doi=10.15650/hebruniocollannu.89.2018.0159

**Comment by markmacgillivray** [comment]
OK thanks I have fixed that now, it opens a page with the email templates in them. However it does not appear that passing html links display correctly - it just shows the html code. Let me know what you want to do about that, right now it does not work too well trying to pass in link URLs with the paper titles in them.

**Comment by JosephMcArthur** [comment]
It's fine not to include the links. 

However, it seems like the permission_required_contact isn't being used in the above test. 

From the doc:

To: Use: <<authoritative_permission.application.can_archive_conditions.permission_required_contact OR embed owner if permission_required_contact is blank >>
CC: if permission_required_contact is not blank: <<embed owner >>

**Comment by markmacgillivray** [comment]
OK I have removed the links and just added a line to show the DOI within the body text, and I have added that to and cc address when there is a permission required contact (I had just missed that part)

**Comment by JosephMcArthur** [comment]
I think you can remove the line with the DOI in it, it's in the subject. The links was purely a convenience.

The To: in the above is now undefined.

**Comment by markmacgillivray** [comment]
OK sorted

**Comment by JosephMcArthur** [comment]
The address seems to just be totally gone now. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
This is becoming farcical. We will just have to review this one on a call as well. Probably Monday. Or could do Sunday if you are free and want to get it done sooner. I have some other stuff related to getting shareyourpaper running that I want to talk to you about too.

**Comment by JosephMcArthur** [comment]
Let's do Monday as usual. Do we need more time to talk, I can get up earlier. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur
