### ISSUE TITLE
Some authors are undefined in InstantILL

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1385]
title:
Genome-wide search for genes affecting the risk for alcohol dependence

Authors:
Reich undefined, Edenberg undefined, Goate undefined, Williams undefined, Rice undefined, Van Eerdewegh undefined, Foroud undefined, Hesselbrock undefined, Schuckit undefined, Bucholz undefined, Porjesz undefined, Li undefined, Conneally undefined, Nurnberger undefined, Tischfield undefined, Crowe undefined, Cloninger undefined, Wu undefined, Shears undefined, Carr undefined, Crose undefined, Willig undefined, Begleiter undefined

volume:
81

issue:
3

from:
AJrfNWswDr4MY8KgD

plugin:
instantill

embedded:
https://ill.ulib.iupui.edu/ILLiad/IUP/illiad.dll?Action=10&Form=20&Value=GenericRequestSimpleArticle

doi:
10.1002/(sici)1096-8628(19980508)81:3<207::aid-ajmg1>3.3.co;2-x

pmid:
9603606

journal:
American journal of medical genetics

page:
207-215

issn:
0148-7299

year:
1998

published:
1998-05-01

pilot:
1575663687505

live:
1575663687505

forwarded:
true

Open access button ILL ID:
iipHkLMMvZECDY5WH

Search URL:
0148-7299

{ "name": "Mike", "title": "Genome-wide search for genes affecting the risk for alcohol dependence", "author": [ { "fullName": "Reich T", "lastName": "Reich", "initials": "T", "family": "Reich" }, { "fullName": "Edenberg HJ", "lastName": "Edenberg", "initials": "HJ", "family": "Edenberg" }, { "fullName": "Goate A", "lastName": "Goate", "initials": "A", "family": "Goate" }, { "fullName": "Williams JT", "lastName": "Williams", "initials": "JT", "family": "Williams" }, { "fullName": "Rice JP", "lastName": "Rice", "initials": "JP", "family": "Rice" }, { "fullName": "Van Eerdewegh P", "lastName": "Van Eerdewegh", "initials": "P", "family": "Van Eerdewegh" }, { "fullName": "Foroud T", "lastName": "Foroud", "initials": "T", "family": "Foroud" }, { "fullName": "Hesselbrock V", "lastName": "Hesselbrock", "initials": "V", "family": "Hesselbrock" }, { "fullName": "Schuckit MA", "lastName": "Schuckit", "initials": "MA", "family": "Schuckit" }, { "fullName": "Bucholz K", "lastName": "Bucholz", "initials": "K", "family": "Bucholz" }, { "fullName": "Porjesz B", "lastName": "Porjesz", "initials": "B", "family": "Porjesz" }, { "fullName": "Li TK", "lastName": "Li", "initials": "TK", "family": "Li" }, { "fullName": "Conneally PM", "lastName": "Conneally", "initials": "PM", "family": "Conneally" }, { "fullName": "Nurnberger JI Jr", "lastName": "Nurnberger", "initials": "JI", "family": "Nurnberger" }, { "fullName": "Tischfield JA", "lastName": "Tischfield", "initials": "JA", "authorId": { "type": "ORCID", "value": "0000-0003-3217-8287" }, "family": "Tischfield" }, { "fullName": "Crowe RR", "lastName": "Crowe", "initials": "RR", "family": "Crowe" }, { "fullName": "Cloninger CR", "lastName": "Cloninger", "initials": "CR", "family": "Cloninger" }, { "fullName": "Wu W", "lastName": "Wu", "initials": "W", "family": "Wu" }, { "fullName": "Shears S", "lastName": "Shears", "initials": "S", "family": "Shears" }, { "fullName": "Carr K", "lastName": "Carr", "initials": "K", "family": "Carr" }, { "fullName": "Crose C", "lastName": "Crose", "initials": "C", "family": "Crose" }, { "fullName": "Willig C", "lastName": "Willig", "initials": "C", "family": "Willig" }, { "fullName": "Begleiter H", "lastName": "Begleiter", "initials": "H", "family": "Begleiter" } ], "volume": "81", "issue": "3", "from": "AJrfNWswDr4MY8KgD", "plugin": "instantill", "embedded": "https://ill.ulib.iupui.edu/ILLiad/IUP/illiad.dll?Action=10&Form=20&Value=GenericRequestSimpleArticle", "doi": "10.1002/(sici)1096-8628(19980508)81:3<207::aid-ajmg1>3.3.co;2-x", "pmid": "9603606", "journal": "American journal of medical genetics", "page": "207-215", "issn": "0148-7299", "year": 1998, "published": "1998-05-01", "pilot": 1575663687505, "live": 1575663687505, "forwarded": true, "illid": "iipHkLMMvZECDY5WH" }

**Comment by markmacgillivray** [comment]
This should be fixed now on dev
