### ISSUE TITLE
Fake DOIs still give responses

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1386]
It seems that we're a bit too trusting on DOIs for syp. For example if you put:

10.1126/scitranslmed.3008973cats

in it'll give a response.

We should throw an error if the doi isn't valid at crossref.

**Comment by markmacgillivray** [comment]
Note this is because in instantill you said we should assume user data is more correct than any data we are able to recover ourselves, and we added an override to the find system specifically for title, journal, year, and doi. So, anything we get from a user in any find is assumed correct, even if we cannot confirm it. I could change this again so that DOI from a user does not override if we can't find it in crossref, but just want to make sure it is clear this affects previous decisions.

**Comment by markmacgillivray** [comment]
Also for shareyourpaper we don't actually have a response for when nothing is found - we do just assume that anything we can't find is a redirect of the user email to the institution. So would also need to know what the UI should show in the case where we decide the DOI is invalid and so we don't return anything actionable - what will say to the user in such a case? At the moment even if we stopped accepting that bad DOI provided by a user, the UI would still just say "you can share, give us your email, we will pass it to your lib".

**Comment by JosephMcArthur** [comment]
> Note this is because in instantill you said we should assume user data is more correct than any data we are able to recover ourselves, and we added an override to the find system specifically for title, journal, year, and doi. So, anything we get from a user in any find is assumed correct, even if we cannot confirm it. I could change this again so that DOI from a user does not override if we can't find it in crossref, but just want to make sure it is clear this affects previous decisions.

This top is helpful context. Trusting user input on a specific page where they are asked to correct us seems really rather different from trusting it at all times, so I wouldn't have anticipated this. 

In this case, the behavior that we should see is if the DOI isn't real (i.e validated by crossref) we should throw an error on that page like when people give too short titles on InstantILL.

**Comment by JosephMcArthur** [comment]
- [ ] Joe to add what the embed should do if the doi is nonsense

**Comment by JosephMcArthur** [comment]
Let's say;

> Double check your DOI, that doesn't look right to us.

**Comment by JosephMcArthur** [comment]
Speaking of DOI validation, we should do another check here to ensure that the DOI is actually a journal article. We did something similar with requests. I can't totally remember our criteria, what we did there is likely fine.

However, we shouldn't allow DOIs for books, datasets, etc.

If this check fails, we should display:

> That doesn't look like an academic journal article. If you want to deposit it, <a href ="old_way">click here</a>.

**Comment by markmacgillivray** [comment]
I think this is now the case
