### ISSUE TITLE
http://sharemyarticle.org/ redirect error

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1393]
http://sharemyarticle.org/ goes https://bigdeal.test.cottagelabs.com/. should go to http://sharemypaper.org/

**Comment by markmacgillivray** [comment]
Assuming you mean shareyourpaper.org here, not sharemypaper.org? You can close it, unless you do actually mean sharemypaper.org, in which case you'll first need to point that domain at my server.

**Comment by JosephMcArthur** [comment]
Not sure your comment above makes sense. I do mean http://sharemyarticle.org/  though.

**Comment by markmacgillivray** [comment]
Yeah but you said you want it pointed to sharemypaper.org which we don't have. We have shareyourpaper.org so that's what i pointed it to. Close if that's correct

**Comment by JosephMcArthur** [comment]
Sorry, I didn't even see that. The my / your thing is so hard to spot. 

I can see the redirect working now (it was cached in browser).
