### ISSUE TITLE
Add info where people can learn more

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1394]
This is for our site, where we'll make `activate_try_it_and_learn_more` = true

The copy and more info is [here](https://docs.google.com/document/d/1FK_jIUxNG3ONQalV4JSjVYZV1QRgjn-mn8fa2BhS2r0/edit#heading=h.j5ed827p7yal).

As part of this, we can ignore the 'try it example', which might make this just 'learn more' on the homepage, thats fine!

**Comment by markmacgillivray** [comment]
I had a look through this but I don't understand what it is meant to do. We will need to discuss later this week to clarify.

**Comment by JosephMcArthur** [comment]
Okay. I'm off today , around on Weds → Friday. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Use the content in the linked doc to make a button on the sneakpeak page that replaces the "i dont have a doi" button with the "try the example or learn more" buttons, and that then shows the content in the doc. So the content just needs to be in the sneakpeak page, not in the embed, and the embed config does not need an option to control it

**Comment by markmacgillivray** [comment]
This has been done and the about / how it works info can be edited on the sneakpeak page (once I push that into develop which I will in a minute)

**Comment by JosephMcArthur** [comment]
Looks great! I've made minor edits. 

Can we have it add #about to the URL so that when people hit back they go back to the homepage.
