### ISSUE TITLE
Testing on live without putting files in zenodo

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1398]
As discussed with Mark today. 

We want people to be able to test on live, with their own DOIs and settings, how our systems perform. Of course, most people will want to do this without putting junk into Zenodo (or at least, this is a polite thing for us to enable). 

It's proposed that in demos and set up, if people try a deposit, we do everything for real except deposit into zenodo. We do everything else e.g sending emails, normally. The only thing we do differently is give a fake doi like doi.org/10.1234.ThisIsNotReal.

**Comment by markmacgillivray** [comment]
This should now be the case, submissions from demo or setup pages should not go into zenodo, but needs a test

**Comment by JosephMcArthur** [comment]
I just tried this and got:

> Sorry, we were not able to deposit this paper for you. Please try contacting your library directly

**Comment by markmacgillivray** [comment]
Probably to do with changes we made in the interim with what does/does not go into zenodo - investigate and change this to work with whatever we have changed there.

**Comment by markmacgillivray** [comment]
@JosephMcArthur do you happen to know what file/doi you tried when you got the "sorry, we were not able to deposit" msg?

**Comment by JosephMcArthur** [comment]
Sorry, I don't.

**Comment by markmacgillivray** [comment]
ok no problem, I will test a couple random ones. Once this is done should be ready to push to live, will let you know.
