### ISSUE TITLE
Add 'fakeilltable' equivalent for shareyourpaper demo

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1402]
TODO Joe to expand. Consider that this thing might be massive.

**Comment by JosephMcArthur** [comment]
Okay, so we should do a table with:

| Data given           | Value |
|----------------------|-------|
| Citation             |       |
| Archivable version   |       |
| Embargo date         |       |
| Licence required     |       |
| Deposit statement    |       |
| Version uploaded     |       |
| Upload matches paper |       |

as while it isn't everything, it should be impressive. 

For citation, we'll have to bunch our metadata into a citation format. I don't mind which format.

**Comment by JosephMcArthur** [comment]
https://dev.openaccessbutton.org/shareyourpaper/demo#ingest

**Comment by JosephMcArthur** [comment]
similar to https://dev.instantill.org/#fakeill

**Comment by markmacgillivray** [comment]
When clicking on the demo the button that moves the user to the #ingest page should just replace the whole shareyourpaper content with a table of all the metadata we can collect.

**Comment by markmacgillivray** [comment]
I think I have this in the place you want it, please test and close, or reassign to me if not.

**Comment by JosephMcArthur** [comment]
It's hard to tell, as the demo may be doing odd things as the URL is being updated with DOIs again and again, but I don't think the table is showing all the values. 

Should I give you fake values you can hard code in there like with InstantILL?

**Comment by markmacgillivray** [comment]
This has been done now, but it only shows the values that are available from the response. If you always want it to show the SAME values, and have a value for all those listed above, then yes, I will need you to list what values you want. But also, in that case, wouldn't it just have been easier to directly write the page content that you wanted it to display, instead of having it do something like the fake ill table? If it is never going to be different, and is essentially a completely fixed response every time, the backend responses are irrelevant. In fact this is true for most if not all of the demo. Something to consider when we next review how we are planning what work to do.

**Comment by JosephMcArthur** [comment]
Having trouble testing as all the fake dois aren't working. You'll see them fail as you try to click though the demo. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Did you make any changes to the demo page? I tested this working just minutes ago...

**Comment by JosephMcArthur** [comment]
I'm not a clever guy, yes I did, changed the IDs. Will change back and test. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
ha ok

**Comment by JosephMcArthur** [comment]
| Data given           | Value |
|----------------------|-------|
| Citation             |   as now    |
| Archivable version   |    Postprint   |
| Embargo date         |    07/13/21   |
| Licence required     |    cc-by-nc-nd   |
| Deposit statement    |   This is an Accepted Manuscript of an article published by Research Publisher in Journal of Science on 07/13/20, available online: http://www.tandfonline.com/10.1234/oab-syp-dark.    |
| Version uploaded     |    as now   |
| Upload matches paper |    as now   |
