### ISSUE TITLE
when an article isn't oa, and open access button plugin is clicked, requests don't open

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1406]
You can see this on:

doi.org/10.1073/pnas.1905762116
doi.org/10.1016/b978-1-78242-121-4.00003-4
https://academic.oup.com/neurosurgery/article-abstract/85/6/779/5160937
https://www.ncbi.nlm.nih.gov/pubmed/28212138

including when we have an associated request

doi.org/10.1063/1.4905616

These all work okay from the frontpage.

**Comment by markmacgillivray** [comment]
This is fixed

**Comment by JosephMcArthur** [comment]
When I click those, I get two tabs opening with requests now.
