### ISSUE TITLE
Resync with Ricks

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1408]
Rick’s got some updates last week, and we should make sure we’re aligned.

Lets:

- [ ] pull in the whole authorative response, including meta etc. We’ll likely need more parts of it soon.
- [ ] Ensure our use of previous fields aligns with their current names
- [x] use https://api.greenoait.org/permissions/doi/ as the base url.

**Comment by markmacgillivray** [comment]
Ricks is currently broken, returning an internal server error on both the old URL and the new URL given above, so I can't do this work yet. But once I can:

* what do you mean by pulling in the whole authoritative response? We do "pull it in" in the sense that we query it and get the response back. Unless you know what you want done with it, I can't do anything else with it, though.

* what are the field names that changed, and what are their new names?

* should that base url be the same for both dev and live, are they pointing to the same underlying service, or can we expect one to be older/newer than the other, more/less reliable than the other?

**Comment by markmacgillivray** [comment]
Ricks is back up now. Looks like the only changed field is can_post is can_archive. I don't see any changed field names that we rely on - were you expecting there would be some?

**Comment by markmacgillivray** [comment]
Looks like both URLs return the same format of data, so I will point to the new URL for now

**Comment by markmacgillivray** [comment]
I guess this could be closed but will wait until our meeting to discuss

**Comment by JosephMcArthur** [comment]
Bits of rick's are broken atm, which is fine. 

So far, I've only seen permissions return info from authoritative_permission/application. For some future issues, we'll need bits from everything in authoritative_permission, e.g meta and provenance.

**Comment by JosephMcArthur** [comment]
Hmm, for now, if we're getting what we need this can be shut. Let's do that and stay focused.
