### ISSUE TITLE
When UI updates, errors don't disappear

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1411]
To replicate:

* Go to: https://dev.shareyourpaper.org/sneakpeak
* put in 10.1073/pnas.1905762116 (anything will do it, but just so you have something to hand)
* once landing, try and submit without giving a file or anything. 
* you'll see an email address error come up
* give any email and any file
* hit submit

On the next page, you'll note that the email address error is still there

**Comment by JosephMcArthur** [comment]
Note, this may also affect InstantILL, in which case we should fix there too.

**Comment by markmacgillivray** [comment]
Done on instantill and shareyourpaper
