### ISSUE TITLE
How to test deposit when things are already in zenodo

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1413]
It's a little tricky to do testing on zenodo deposits when we can only deposit them once per article. So, i'm starting an issue to discuss any possible solutions. 

This is strictly about what to do on dev, or when testing (e.g on set up pages), rejecting duplicate deposits in real usage is a desirable thing. 

My first question is, even on dev, are we querying the live Zenodo API or the sandbox one to find out if the file is already in there? If we're querying the live api, we may be getting false positives as I don't think the sandbox replicates the live database exactly, and so may let us deposit something that already deposited on live. That would be good as it would mean we could test easily with previous requests, which wouldn't strictly solve this problem, but it would make it much less impactful. 

Then, my understanding is, there are ways we could avoid zenodo's doi check if we wished. On live, we don't want to do this, but on dev, it would likely make sense if it allowed us to test better. I don't much mind how we avoid it, if it's just not passing the DOI, or putting it in some other field.

Mark, you know much more about this than me though, so I'm all ears for what makes sense to you.

**Comment by JosephMcArthur** [comment]
This is related to #1398 where we discuss how to give the user a place on live to do this when they want a realistic test.

**Comment by markmacgillivray** [comment]
When on dev, push to zenodo as a related identifier, even though on live we will not do this, we will put it into review. But this will be useful for dev, and does not matter for zenodo sandbox.
