### ISSUE TITLE
Adding context to which article is being searched

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1420]
So that people can verify which paper we're talking about we should link 'your paper' in the copy to the DOI of the paper in question.

**Comment by markmacgillivray** [comment]
The words "your paper" appear 24 times in the shareyourpaper UI embed code. Do you want them all changed??? If not which ones?

**Comment by JosephMcArthur** [comment]
These places:

> The library has checked and the journal encourages you to freely share *your paper* so colleagues and the public can freely read and cite it

> The library has checked and the journal encourages you to freely share the publisher pdf of *your paper* so colleagues and the public can freely read and cite it.

> We checked and unfortunately the journal won't let you share *this paper* freely with everyone

**Comment by markmacgillivray** [comment]
OK, should be done, I checked and looks fine to me. Please test and close if happy.
