### ISSUE TITLE
Giving links to full text of journal policies

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1421]
At the end of the initial statements:

> The library has checked and the journal encourages you to freely share your paper so colleagues and the public can freely read and cite it.

and

> The library has checked and the journal encourages you to freely share the publisher pdf of your paper so colleagues and the public can freely read and cite it.

and

> We checked and unfortunately the journal won't let you share this paper freely with everyone.

we'll want to provide our source. We can do that by putting a [1] at the end of the sentence. The link for that should be the link available at ricks.authoritative_permission.can_archive.provenance.policy_full_text. Occasionally, there will be more than one link separated by a comma. If that happens, we should provide a [2] with that link.

If we're getting the info from sherpa, we shouldn't provide a source.

**Comment by markmacgillivray** [comment]
This is done, if you know of something that should cause it please test and close if OK.

**Comment by JosephMcArthur** [comment]
Should see it here, but don't; https://josephmcarthur.github.io/playground/syp-dev?doi=10.1016/j.phrs.2019.104618.

**Comment by JosephMcArthur** [comment]
Note, when in our API the route would be:

ricks.provenance.policy_full_text

**Comment by markmacgillivray** [comment]
ok try again

**Comment by JosephMcArthur** [comment]
They're showing up now, yay. But, instead of 1 it's [01], instead of 2, [11]. 

Another note to self, an example with one below:
https://josephmcarthur.github.io/playground/syp-dev?doi=10.1073/pnas.1905762116
