### ISSUE TITLE
On successful deposit pages we should show the zenodo doi, not url

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1425]

**Comment by markmacgillivray** [comment]
@JosephMcArthur testing this, the zenodo doi is often issued but not yet functional, this would mean we would show a link that does not work if anyone clicked it. Probably better to stick to the zenodo url

**Comment by JosephMcArthur** [comment]
Agreed. I would still like us to show a doi long term, but we may need to
issue our own to have this work it seems, or change the UI in some way.
