### ISSUE TITLE
Successful deposit didn't respond to embargo

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1426]
I did a deposit of 10.1073/pnas.1905762116 (file you can use to replicate will be in your inbox from deposit). While Ricks for sure picked up the embargo, we didn't use it to set zenodo up correctly i.e it was an open deposit.

**Comment by markmacgillivray** [comment]
Error related to changes in ricks formatting caused it to be missed. Gets picked up now.
