### ISSUE TITLE
Zenodo tags (and maybe more) in emails not working

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1427]
I saw this in 

> Successful Deposit: 10.1073/pnas.1905762116

which you should have.

The following didn't seem right:
* Depositor Email
* Splash page URL
* Full text URL
* Zenodo DOI

**Comment by markmacgillivray** [comment]
The zenodo ones were missing the zenodo. prefix so I changed those. Others seem to be OK, I have updated the templates now so let me know if you are still missing any.
