### ISSUE TITLE
swapping embeds between dev and live

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1428]
Mark, can you check on openaccessbutton.org/deposit, shareyourpaper.org/demo, shareyourpaper.org/sneakpeak, and shareyourpaper.org/test and make sure that on each it's possible to swap out the embeds used on dev and live. I don't yet have embeds set up on dev and live for each pages needs, but I will soon, and it would sure be great to just be able to drop in the IDs.

A good placeholder for a live would would be what I use here: http://josephmcarthur.github.io/playground/syp-live

**Comment by markmacgillivray** [comment]
Sorry, I have been working on this but not actually clear what you mean. What does swapping out the embeds on dev and live mean? Swapping them for what? Swapping them on dev? Or on live? Swapping the user account IDs? Do you want to use dev embeds on the live site? Why would you want to do that, if so? I do not know what you mean about the placeholder page either, sorry. Please clarify and I will try again.

**Comment by JosephMcArthur** [comment]
Sorry. What I mean is that on live I want to be able to use account IDs from live, and on dev I want to be able to use account IDs from dev. The placeholder page has a account id you can use for live ones on all those pages.
