### ISSUE TITLE
Missing placeholder on email box

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1429]
I wasn't able to nail down when this occurs, but it seems like it's possible for the placeholder in the email box (at least on the long file upload page) to be empty. 

That shoudn't be allowed to happen, and as I'm guessing it happens when we have no domain to fill, I'd suggest we use:

your.name@institution.edu

when nothing else is available.

**Comment by markmacgillivray** [comment]
As far as I can tell this is fixed, I have set that default placeholder and I see it in email boxes. Let me know if you can find one where it does not appear, I can't find any in the code. Otherwise you can close this.

**Comment by JosephMcArthur** [comment]
And thanks! Haven't specifically tested but I'll keep an eye out and reopen if needed
