### ISSUE TITLE
change to demo after fake upload

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1430]
After the user has done a fake upload on https://dev.openaccessbutton.org/shareyourpaper/demo#general, we should change the right hand menu to show #success as the demo shows the fake successful upload.

**Comment by JosephMcArthur** [comment]
I couldn't make this happen when testing today, I'll take a bet it's because DOIs are being added to the end of the URL and overrighting the #'s. On the demo page, dois are added time and again to the page.

**Comment by markmacgillivray** [comment]
I think this is working fine now, I already added code to take care of hashes as well as query params. Can you check again, and if not doing what you expect, we will need to discuss to get a clearer understanding.
