### ISSUE TITLE
Authors still occasionally 'undefined' in emails

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1432]
Seems to only be a subset now. See 

> Review Deposit 10.1176/ajp.150.2.272

for an example

**Comment by JosephMcArthur** [comment]
I think this happens when first names aren't available

**Comment by markmacgillivray** [comment]
This should be fixed on dev, welcome to test @JosephMcArthur

**Comment by JosephMcArthur** [comment]
The authors one seems fixed
