### ISSUE TITLE
Achievable reason is given as unsure when we're sure

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1433]
It seems we're giving:

> We cannot confirm if it is an archivable version or not

as the archivable reason when we're given a publisher pdf when postprints are allowed. This suggests we don't know when we do. Instead, we should say:

> The file given is a Publisher PDF, and only postprints are allowed. 

There are a few occurrences of this happening, but here's a typical example:

> Review Deposit 10.1038/s41586-020-1985-6

**Comment by JosephMcArthur** [comment]
An example: https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Burrow_and_Rainone__2016_.pdf&verbose=true&doi=10.1016/j.jesp.2016.09.005&title=How%20many%20likes%20did%20I%20get%3F%3A%20Purpose%20moderates%20links%20between%20positive%20social%20media%20feedback%20and%20self-esteem.

**Comment by markmacgillivray** [comment]
This has been fixed, was just down to the logic and how we had changed it over time. It is on dev and ready for live (I will push to dev repo soon) and no further testing needed so closing.
