### ISSUE TITLE
Depositor email sometimes undefined

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1434]
See:

> Successful Deposit: 10.1176/ajp.150.2.272

I can't see why it would be.

**Comment by JosephMcArthur** [comment]
This happens when the deposit is done through "My upload was an accepted manuscript". That might not be an issue now, haven't check yet.

**Comment by JosephMcArthur** [comment]
See the message I just forwarded titled:

> Deposit Requires Checking: 10.1176/ajp.150.2.272

Seems like we're missing lots of permissions info in this now under the same conditions.

**Comment by markmacgillivray** [comment]
Which template are you using for that? Seems weird that one of the file info parts is showing but not other parts. Let me know and I will check the template.

**Comment by JosephMcArthur** [comment]
It's:

> forward_deposit.html

**Comment by JosephMcArthur** [comment]
Okay, some tags were just wrong, fixed those and will keep testing

**Comment by JosephMcArthur** [comment]
Still seems to be an issue and I can't tell why

**Comment by markmacgillivray** [comment]
This has been fixed and tested, at least to the extent of depositor email being undefined - that was getting lost when the user was clicking the "my file was an accepted manuscript" button. Now the email does get passed through with the second submission.

If there are other things still wrong with this, let me know, otherwise can close.

**Comment by JosephMcArthur** [comment]
Checking the email:

> Deposit Requires Checking: 10.1176/ajp.150.2.272

from just now, the email is working, yay. 

However, there are some fields I'd expect to be present that aren't. 

> File Archivable:
> Same as published paper:
> Archiving allowed:

I don't think it's a tag issue any more. Can you take a look?

**Comment by JosephMcArthur** [comment]
Hmmm, actually, I see the same fields not present in:

> Successful Deposit: 10.1063/1.4937158

This was certainly working on feb 25th, but not today.

**Comment by markmacgillivray** [comment]
Ah these values are true/false so I have defaulted them to showing text Yes or No. This should work now, but please have a look to make sure that makes sense in the contexts you are using them, then can close this issue.
