### ISSUE TITLE
.permission.permission disagrees with itself

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1435]
For this DOI ricks says we can share, and our permissions summary says we can share a post-print but then says 'archiving_allowed' is false. I think it's likely as Sherpa says archiving isn't allowed. 

https://dev.api.cottagelabs.com/service/oab/permissions?doi=10.1080/00325481.2015.1074030

We should now trust 'can_archive' statements from Ricks, and always trust what ricks says above sherpa.

**Comment by JosephMcArthur** [comment]
Another example of this can be seen in:

OA Redeposit: 10.3389/fsufs.2019.00088

**Comment by markmacgillivray** [comment]
Fixed on dev, was also down to how we had changed the logic over time, as originally we already did trust ricks over sherpa anyway, but it got a bit convoluted. Ready to go on live now, no further testing required, I will push into dev branch soon ready for merging.
