### ISSUE TITLE
after clicking 'My upload was an accepted manuscript' depositing button doesn't show loading correctly

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1437]
The button doesn't do our normal ellipsis animation while depositing, which makes it look frozen

To test you can use:

> https://openaccessbutton.org/deposit?doi=10.1177/1750481317745753
and the attached. 
[yoder_johnstone_2018.pdf](https://github.com/OAButton/discussion/files/4249948/yoder_johnstone_2018.pdf)

**Comment by markmacgillivray** [comment]
This is done, pretty sure it is as expected, just adding the dots to those buttons, so closing.
