### ISSUE TITLE
Same file check should ignore final full stop

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1439]
In this file [revised manuscript December 2019.docx](https://github.com/OAButton/discussion/files/4251502/revised.manuscript.December.2019.docx) (as seen in #1438) we say it isn't the same paper when it is. 

I'm not sure how specific we're trying to be on our title matches atm, but we should certainly ignore the presense of a full stop at the end. That's what is throwing us off here, and funnily on we were specifically warned about publishers liking to put full stops on the end of article titles.

**Comment by markmacgillivray** [comment]
This works now
