### ISSUE TITLE
Turn on caching on live

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1442]
Currently we're not caching results on live, which we can now. This includes Rick's now.

**Comment by markmacgillivray** [comment]
Done in the code but not pushed what i have to dev yet because some other things need sorted first. Once we do the next push and merge then this can be closed

**Comment by JosephMcArthur** [comment]
When we push to live next, can we turn this on please?

**Comment by markmacgillivray** [comment]
Yes, whenever we next merge dev to live, this will start.

**Comment by JosephMcArthur** [comment]
ace@
