### ISSUE TITLE
Update to how to do T&Cs on SYP

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1445]
After review of SYP there are some small changes we need to make to how we do terms.

- [x] Instead of 'terms and conditions' we can just just say 'terms' everywhere
- [x] when 'deposit_terms' is not set (i.e blank), 'terms' should link to https://openaccessbutton.org/terms
- [ ] when 'deposit_terms' is set, 'terms' should no longer be linked and instead we should show '[1][2]' right after, where 1 is linked to https://openaccessbutton.org/terms and 2 is linked to whatever is given in 'deposit_terms'.

**Comment by markmacgillivray** [comment]
This is done on dev, but as there is no point showing a [1] and a [2] if there is not a deposit_terms set by the user, I have instead just set it to only show a [1] if there is no deposit_terms value set, and that [1] goes to the OAB terms page. If there is a deposit_terms set by the user, we show [1] and [2] and the [2] will go to the deposit_terms value. Please test and close if happy
