### ISSUE TITLE
zenodo not using deposit statement from ricks

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1447]
I feel like we had this working before, but maybe I'm mis-remembering. Regardless... 

Tried to deposit 10.1063/1.4937158 and got the following sandbox record: https://sandbox.zenodo.org/record/503471#.XlffhxOeTOQ. If that doesn't work, you can replicate with [Test Paper for SYP upload.pdf](https://github.com/OAButton/discussion/files/4262376/Test.Paper.for.SYP.upload.pdf).

The license rick's gives wasn't used (see statement here: https://rickscafe-api.herokuapp.com/permissions/doi/10.1063/1.4937158).

For the description on zenodo, the rule is:

If the length of `authoritative_permission.application.can_archive_conditions.deposit_statement_required_calculated` is >1, use that. 

Otherwise use 

> The publisher's final version of this work can be found at https://doi.org/<<doi>>.

**Comment by markmacgillivray** [comment]
Should be fixed now, please try and can close if as you expect
