### ISSUE TITLE
prettify dates on UI for SYP

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1449]
Instead of what we have now, lets use:

DD MONTH YYYY.

To be clear, the month should be written out in letters, just to avoid international ambiguity.

**Comment by markmacgillivray** [comment]
This is done on dev, although the only date I could find to be relevant was the embargo date. Please test and see if that is sufficient with an embargo one, or let me know if there are other dates you wanted this done for. If all good, this can be closed.

**Comment by JosephMcArthur** [comment]
will plan to just keep an eye out for this
