### ISSUE TITLE
Prettify versions names passed to zenodo

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1450]
Let's make the following changes:

publishedVersion --> Published Version
acceptedVersion --> Accepted Version

Do we use 'AAM' anywhere for zenodo? I feel like we might, but I haven't seen it recently. If we do, lets change it to 'Accepted Version'

Only care about SYP zenodo route here.

**Comment by markmacgillivray** [comment]
This is done and tested, please check on dev and can close if happy

**Comment by JosephMcArthur** [comment]
will plan to just keep an eye out for this
