### ISSUE TITLE
InstantILL metadata tags in emails turning up incorrectly

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1451]
In both our internal emails and user emails I'm seeing odd metadata bumps.

e.g in a recent `ILL CREATED` we got:

```
0:
title

1:
doi

2:
author

3:
journal

4:
issn

5:
volume

6:
issue

7:
page

8:
published

9:
year
```

Which doesn't look right to me, although included in the email are the right values. 

You can see the same thing in the message I just forwarded you:

> ILL request 7RqB8zofaZd9EWMr4

**Comment by JosephMcArthur** [comment]
If, while doing this, we were able to look at: https://github.com/OAButton/discussion/issues/1397 and https://github.com/OAButton/discussion/issues/1379 that would be pretty efficient.

**Comment by JosephMcArthur** [comment]
Note: I have committed code that brings this into line with how we do SYP emails, which may help. 

I haven't synced this though, as I have question about IDs. 

Double note: what I have done here won't fix the internal emails we get, which is likely fine...

**Comment by JosephMcArthur** [comment]
The issue listed here is now fixed, let's just fix #1379 and #1385

**Comment by JosephMcArthur** [comment]
and have {{notes}} come through

**Comment by markmacgillivray** [comment]
Note additional changes needed to email sent to users
