### ISSUE TITLE
set up info wipes itself on shareyourpaper set up

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1459]
At the moment shareyourpaper.org set up info appears to get accidentally wiped as you move through pages in set up, which of course results in embed settings changing undesirably. 

To replicate:

* Go to shareyourpaper.org/setup
* Input a setting on Deposit Preferences. E.g change repo name to cats. Hit save and continue.
* tick the tickbox of: "Turn off the ability to deposit already open access content?". Hit save and continue.
* Refresh your browser
* go to menu, then go to "Deposit Preferences"
* You'll see 'cats' is gone

I did this incog to remove chances of account clashing.

**Comment by markmacgillivray** [comment]
I think this is fixed, I have changed on dev and pushed the change to the dev branch.

@JosephMcArthur please have a look on dev setup and just make sure it is working as you expect. Once confirmed we can push current dev branch to live.

**Comment by JosephMcArthur** [comment]
It's all good!

**Comment by markmacgillivray** [comment]
OK, it is on live
