### ISSUE TITLE
if two meta tags in head, remove the first

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1469]
As discussed. Joe to expand

**Comment by JosephMcArthur** [comment]
For sites like shareyourpaper.org / instantill.org our meta tags like meta description in the head are giving google the wrong info.

It would be good to be able to add specific metatags to specific files and have them overwrite the generic ones in the head.

Note, I will likely also be adding new meta tags.

**Comment by JosephMcArthur** [comment]
@markmacgillivray can you advise on how best to support meta-tags specific to instantill / shareyourpaper sites today? I'd like to put out a fix for this asap.

**Comment by markmacgillivray** [comment]
I've tried adding a change for this, can discuss/test on the call to see if it is what you want.

**Comment by markmacgillivray** [comment]
Or if you just try pushing a meta tag inside a head tag somewhere on one of the pages you want it on, it will try to remove any other meta tag already present in the header if that meta tag is the same right up to the content value that you set. Pushing to develop will run that updated script to attempt it, then you'd be able to see the result on the browser page.

**Comment by markmacgillivray** [comment]
Done, close if happy
