### ISSUE TITLE
samesite cookie issue

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1471]
Investigate what the errors in the console are & fix them

**Comment by markmacgillivray** [comment]
How long should we spend on this, now that it is in 83? 

As far as I can tell the warning are informative and have not blocked any of our functionality. I can continue doing more work if you want to make them go away, but I don't know how long that might take.

Is there any specific problem you have seen associated with the warnings? Have you seen any actual errors? I have not found any.

**Comment by JosephMcArthur** [comment]
Putting in 83 was a mistake, wanted to put in 84 to at least review as the deadline to make changes from browsers had passed.

**Comment by JosephMcArthur** [comment]
This is done, right @markmacgillivray?
