### ISSUE TITLE
If we can’t find the version, assume post-print

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1473]
Currently if we don’t find version evidence we give a score of 0 and say the version is unknown. Instead, now, we should presume it’s a postprint.

Soon, we’ll hopefully bring in more checks that are better at giving positive signals of postprints. However, it seems we’re really good at spotting when things are publisher PDFs, and that should be good enough for now.

**Comment by JosephMcArthur** [comment]
est: 1 hour

**Comment by markmacgillivray** [comment]
Done, if unknown and at least one string check occurred
