### ISSUE TITLE
Colons being ignored in string matching

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1475]
In these checks we’re getting false positives as it appears colons, `:`, are being ignored in string matches. 

`https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Pritchard_E_et_al__Factors_impacting_household....pdf&verbose=true&doi=10.3109/09638288.2014.902508&title=Factors%20impacting%20the%20household%20and%20recreation%20participation%20of%20older%20adults%20living%20in%20the%20community`

`https://dev.api.cottagelabs.com/convert?from=pdf&to=txt&url=https://dev.openaccessbutton.org/static/test-manuscripts/Pritchard_E_et_al__Factors_impacting_household....pdf`

`https://dev.api.cottagelabs.com/service/oab/permissions?url=https://github.com/OAButton/discussion/files/4291932/Test.Paper.for.SYP.upload_downloaded.to.Word.saved.as.PDF.pdf&doi=10.1126/scitranslmed.3008973`

Can we stop this?

**Comment by JosephMcArthur** [comment]
I've removed ones that rely heavily on colons from the file as I'm worried they'll cause false positives on live. They're here:

Title: | string | file | postprint | from: https://zenodo.org/record/3364155/files/McCulloch_and_Loeser_2.10.15_Does_sup_training_work_HERD_Full_as_accepted.pdf
-- | -- | -- | -- | --
Phone: | string | file | postprint | from: https://zenodo.org/record/3364155/files/McCulloch_and_Loeser_2.10.15_Does_sup_training_work_HERD_Full_as_accepted.pdf
Telephone: | string | file | postprint | from: https://zenodo.org/record/3364155/files/McCulloch_and_Loeser_2.10.15_Does_sup_training_work_HERD_Full_as_accepted.pdf
Tel: | string | file | postprint | from: https://zenodo.org//record/3350948/files/Full_paper_v2_submit_to_open_access_button.pdf
DOI: 00.0000/ | string | file | postprint | from: https://zenodo.org/record/3719325#.XnTZP9OeTOQ
fax: | string | file | postprint | from: andre

You can add them back in when you're working on this.

Can you confirm which file we use to check strings on live? I planned it to be: https://docs.google.com/spreadsheets/d/10DNDmOG19shNnuw6cwtCpK-sBnexRCCtD4WnxJx_DPQ/edit#gid=0 at some point, but it's very possible I have forgotten to share that.

**Comment by JosephMcArthur** [comment]
Seeming possible that converting these to regex's that still require the ":" but are more forgiving of spaces will help.

**Comment by markmacgillivray** [comment]
Check the simplification process we run on the text from the doc - change it to keep all chars such as colons so they can match against

**Comment by markmacgillivray** [comment]
See https://github.com/OAButton/discussion/issues/1511#issuecomment-610159818

**Comment by markmacgillivray** [comment]
String matches have been changed to be more exact, content is no longer lowercased or cleaned of non-letters etc. So string matches above will be more precise.

Regex matches were case insensitive, can be changed to be case sensitive. Or spreadsheet could be updated to provide regex settings in another field. Or could assume if the regex has no uppercase letters in it then treat it as insensitive, but if any uppercase letter present, be sensitive to case.

**Comment by JosephMcArthur** [comment]
I need to:

- [ ] test the above links
- [ ] make a new issue
