### ISSUE TITLE
Need a contributors.md

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#148]
Instructions: https://mozillascience.github.io/working-open-workshop/contributing/

**Comment by JosephMcArthur** [comment]
Good example: https://github.com/atom/atom/blob/master/CONTRIBUTING.md

**Comment by JosephMcArthur** [comment]
@jibe-b you've been amazing recently at contributing... anything we could've put in this guide to make your life easier?

**Comment by jibe-b** [comment]
I'd say the most efficient is the reactivity on gitter/github :)

But I guess someone new to OAB may want to know "where the data goes after contribution": a few words on the internal use of the metadata harvested about articles, statistics, etc. Are they regularly released as open data, are they pushed to BASE, etc (this is both something I suggest telling to new people and what I'd like to know).

**Comment by JosephMcArthur** [comment]
Have updated the contributing guide to signal clearly that we'll try and be reactive & how best to talk to us ( in this context ). 

I'm not sure the contributing is the right place for 
> But I guess someone new to OAB may want to know "where the data goes after contribution": a few words on the internal use of the metadata harvested about articles, statistics, etc. Are they regularly released as open data, are they pushed to BASE, etc (this is both something I suggest telling to new people and what I'd like to know).

as I bet others would want to know. @chealsye perhaps a blog? To answer the question, when people give us content we put it in Zenodo.

**Comment by chealsye** [comment]
@JosephMcArthur Do you want a blog post addressing other items? 

This sounds like a FAQ for new team members and volunteers may be useful.

**Comment by JosephMcArthur** [comment]
Closing. We have a basic one and it seems to do the job. Most of the time ideas come via email and product calls!
