### ISSUE TITLE
Can't submit a new request on dev site via website or an embed

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#1488]

**Comment by JosephMcArthur** [comment]
http://www.ascd.org/publications/educational_leadership/mar99/vol56/num06/Grading_in_a_Standards-Based_System.aspx

**Comment by JosephMcArthur** [comment]
These are other papers were I *think* I saw issues yesterday, but I'm not 100% sure. 

https://www.jbc.org/content/268/34/25876.abstract?ijkey=17607d7eae49f4f41b9886530850169f9626a801&keytype2=tf_ipsecsha

https://www.jbc.org/content/271/43/26449.full

https://science.sciencemag.org/content/241/4861/71.abstract

https://science.sciencemag.org/content/204/4389/179.abstract

**Comment by markmacgillivray** [comment]
This has been fixed on dev, assuming all of the above should now NOT return as open. I have tested them all.

We had an issue with the scrape returning the URL that was passed in, due to changes in the layout of the return objects that we made for the new find system, but which were not exactly the same for the old request system. This has now been fixed.

Also, as we had the system go down yesterday, I spent a lot of time reviewing the use of puppeteer and tried to add more code to catch any potential overruns there, in case of it eating all the memory or spiking the cpu. It seems to be impossible to reliably catch it in every situation, but we now have even more ways of killing it in place.

Given that the new stuff only works on DOIs, perhaps it is worth considering how much time you want to spend supporting the old request system, and if so, whether it should still support URLs and other types of IDs that the new code does not explicitly support. If we are going to keep running the old stuff with the title,url, etc support, we must schedule some time to properly refactor that request system, since we didn't do any of the recommended refactoring there last year.

**Comment by JosephMcArthur** [comment]
It is possible to find one of them open, but not from the URL I don't think: https://www.jbc.org/content/271/43/26449.full

See: https://api.unpaywall.org/10.1074/jbc.271.43.26449?email=joe@openaccessbutton.org

However, as long as we're still able to make requests and the plugin will work with these pages we're fine to close this.

**Comment by markmacgillivray** [comment]
Via the API with refresh zero they come back with the correct answer but via the UI they still serve the wrong answer because they are cached. If you want to fix that as well we will need to devise a script that could find ones that were potentially wrongly indicated as open via a URL, and then run that script on both dev and live. That'll take a while though, so depends if you want me to do that or to get the other issues in 83 closed.

**Comment by markmacgillivray** [comment]
If we don't clean up the cache then new searches for new URLs that we didn't yet cache should now create requests as expected, unless there is some other problem stopping that from happening. I'll try deleting some out of dev and check that just now.

**Comment by JosephMcArthur** [comment]
Don't need to cleaned up, can just let it refresh when the rest of the cache does.

**Comment by markmacgillivray** [comment]
OK. Confirmed just now that on dev when removing one of the above specific ones and running it again via the UI, it did proceed to create a request, so all is well there.

**Comment by JosephMcArthur** [comment]
\o/
