### ISSUE TITLE
Embed refactor wishlist

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1493]
Mark, this one's for you. Here we can stash idea for things we'd like to refactor about embeds as we go so we can more visibly see debt build. Happy to boot up similar issues for other systems. 

I'll start:

* Allow embeds to make availability calls ASAP when called with info about the users search in the URL. e.g https://developers.google.com/analytics/devguides/collection/analyticsjs. At the moment, everything has to happen before the call can be made.

**Comment by JosephMcArthur** [comment]
Have seen Mark note that:

> Later come back and fix up the overlapping uses of classes in setup pages.

**Comment by JosephMcArthur** [comment]
Can we consider:

* have better error handling when our servers are down in the embed
* what to do when users have javascript turned off?

**Comment by JosephMcArthur** [comment]
Notes from doc:

- Consider what link resolver implementation takes
- Remove need for config
- Privacy badger says the api is tracking, really?
- User config (e.g choose your own words...)
- Enable Sam to do UI?
- Enable library-fication?
- Generally keep clean and tidy and make maintainable
- Suggest people put them in the head if possible, prefetch oab domain?
- remove jquery

All planned for in our discussion.

**Comment by JosephMcArthur** [comment]
One way or another we need to fix that high performance config doesn't give emails

**Comment by JosephMcArthur** [comment]
Note, I've updated: https://github.com/OAButton/discussion/issues/1493#issuecomment-625230481 which I hope reflects most of what we've discussed I hope.

**Comment by JosephMcArthur** [comment]
Things are looking better, thanks!

With our use of bootstrap, are we making a call to bootstrap/ our server that could be removed by loading just what we need in the main JS file?

Just thinking about our discussion on the sparc microsite about only using the bootstrap we need.

**Comment by markmacgillivray** [comment]
The embed doesn't call bootstrap at all now, nor jquery. It has some css directly written into it, and  that was pulled from bootstrap, for buttons and form elements, and that is all. The embed by default also adds bootstrap button and form classes to those, but they would have no effect unless the site they are on has bootstrap in it already.

**Comment by JosephMcArthur** [comment]
Closing this as everything is being dealt with in #1513
