### ISSUE TITLE
live / pilot timestamps fail and cause loss of logs / caching

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1508]
Need to fix route issue (some missing code somewhere that allows them to save properly) and clean up user accounts.

**Comment by markmacgillivray** [comment]
Code altered to try to control the pilot/live fields at least, for instantill and deposit configs. That code has been pushed into develop, ready to merge to live, but will require other work when that happens.

User accounts on dev have been cleaned with a script, and confirmed it worked and they reloaded with the correct types.

catalogue and find have both been dumped on dev. When we next update the code to live we will also have to dump catalogue, but find will be ok. We will also need to run the users script on live as soon as we do that.

This is all ready to go now for live, but need to confirm with @JosephMcArthur and see if you want anything else tested on dev first.
