### ISSUE TITLE
Remove some fields from deposit(s/ed) CSV export

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1509]
We should remove:

- [ ] References
- [ ] Deposit error message fields

I hadn't anticipated these being in there, and they new a lot of rows, which can make it all a bit unwieldy.

**Comment by markmacgillivray** [comment]
Done and tested, please check to make sure you are happy. For error, I did as discussed last time, it tries to make it a simple useful string like "deposit to zenodo failed", otherwise just deletes it.
