### ISSUE TITLE
Sysadmin and refactoring

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#1510]
There is a huge amount of sysadmin and refactoring that is outstanding now, and it is starting to break everything. We MUST PRIORITISE THIS or the whole system will eventually fail, and we won't know why. This issue will be used to list everything I can think of then other issues can be linked out from here (some probably already exists and can be linked).

I will also throw in rough time estimates but these could get revised (up).

BACKEND

* the new find code has not been properly integrated and tested into the old request code. We never did 40% of the previous recommended refactor. This all needs to get done. 6 days. #1518

* the deposit API dumps a load of permissions junk from sherpa that we no longer need. It is dirtying up the data and we should get rid of it, and clean up the records we have. 1.5 days. #1517

* the permissions and deposit API code is badly written because we kept chopping and changing it with no initial plan, and based on changing deliveries from other people. It needs refactored, and the legacy code it still supports for the old requests system needs removed as well (once they are refactored, as mentioned above). 2 days. #1515 & #1516

* the catalogue of records we have previously seen already has duplicates and bad data in it, because we pushed it to live before it was ready. This now has to be fixed, the bad data has to be cleaned, and duplicates removed. 2 days. #1517

* the instantill API originally had a controlled list of expected variables and it cleaned them up when they came in. This has not been maintained and we now have dirty data in that system. It must be updated, and the data has to be cleaned. 2 days. #1523

* the shareyourpaper API was never properly developed, it was copy and paste from instantill, and has never had any controls on what data it accepts. This is dangerous and is already full of junk. It needs to be properly developed and the data needs to be cleaned. 3 days. #1519

* the pilot/live values on shareyourpaper/instantill have had the code that did set them properly (which I think was in the UI) removed - see above about not properly managing this data. This has also polluted the accounts index because user configs are stored in user accounts. This is very bad, must be fixed, and all data must be cleaned - Immediately this requires instantill/shareyourpaper to at least be altered to bring in the controls that were there in the UI but put them in the backend this time, and the accounts data has to be cleaned. Later we probably also have to go through all the find/availability records and clean them up as well. Now: 3 days. IN PROGRESS. #1508 

* We need to move puppeteer to its own server - it is much better than phantom was, and fairly well controlled since we have added controls to it over time, but can still spike and bring down the API if running on the same machine. This is very bad for stability and must be fixed. This also requires some config changes and changes to how various bits of code try to call puppeteer, in addition to just installing it on its own server. 1.5 days. IN PROGRESS. #1504

* We need another machine in the cluster to handle failover if the main app machine goes down. We do have a cluster machine to do background jobs but it can get very busy when there are background jobs running, which would make a slow UI. So get another one started (for dev and live, ideally, as this is better for testing. 1 day. IN PROGRESS #1505 

* Improve how we can set configs across machines on different areas of the cluster and how we deploy changes across the cluster. This has not been maintained for two years and many of the ways we used to do it were obsoleted and replaced with hacks. 1 day. IN PROGRESS. #1514

* we have never configured any of the status/test/monitoring stuff that the API has, because it has never been prioritised. We have ways to make sure that certain API endpoints still respond as expected, both within our own code and from remote services that we rely on, but we have never set it up. This causes us to make changes as described above, where we don't finish refactoring the old request system, then we push something live which breaks something none of us have reviewed for over a year. This really needs to be done, especially given that it is just sitting there unused. 2 days. #1361 

FRONTEND

* all embed code for shareyourpaper and instantill needs refactored. It was never well designed, and was led by UI design, which changed over time and is not a logical progression. the requirements of the UI design are now different from what they were, and the code has been hacked to death to fit with those. Although these work for now, we waste more and more time whenever we make changes, we introduce more chance of errors, and lots of stuff is being copied across two similar files. Not good practice at all. 4 days. #1493 

* the setup/demo pages for instantill and shareyourpaper are terrible (code-wise; they look nice). It was never clear how the demos were supposed to interact from the designs, and no thought was put into how we should do that, or where certain parts would need to run and where not, and how they should best interact with the UI. These pages need to be refactored from scratch, to keep the same design and workflow, but entirely operationally different underneath (and can include things we now know we want like kicking off a check earlier in the page load, and possibly before config is retrieved). 3 days. #1513

TO BE CONTINUED

**Comment by JosephMcArthur** [comment]
> the catalogue of records we have previously seen already has duplicates and bad data in it, because we pushed it to live before it was ready. This now has to be fixed, the bad data has to be cleaned, and duplicates removed. 2 days.

> the deposit API dumps a load of permissions junk from sherpa that we no longer need. It is dirtying up the data and we should get rid of it, and clean up the records we have. 1.5 days.

Mark, is this much easier now, before we have a bunch of people using it? I think right now it would be fine to just wipe the catalogue for shareyourpaper stuff.

**Comment by JosephMcArthur** [comment]
I've taken some time to turn the above into (stub) issues where I can so that they can be scheduled and discussed individually.

**Comment by JosephMcArthur** [comment]
Moved to other issues, urgent stuff is largely taken care of already / by the end of the week. 

Discussion will continue as part of retro & work on performance / maintainability & stability.
