### ISSUE TITLE
Score not counting up

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1512]
Was doing final testing on: https://dev.shareyourpaper.org/sneakpeak/10.1063/1.4937158

Uploaded [Correct test paper for (3) (5).pdf](https://github.com/OAButton/discussion/files/4408968/Correct.test.paper.for.3.5.pdf)

Got:

>     "file": {
      "archivable": false,
      "archivable_reason": "We cannot confirm if it is an archivable version or not",
      "version": "unknown",
      "same_paper": true,
      "name": "Correct test paper for (3) (5).pdf",
      "format": "pdf",
      "checksum": "WttnPXPMGRz+vG6qX7N26A==",
      "same_paper_evidence": {
        "words_count": 5209,
        "words_more_than_threshold": true,
        "doi_match": true,
        "title_match": true,
        "author_match": true,
        "document_format": true
      },
      "version_evidence": {
        "score": 0,
        "strings_checked": 92,
        "strings_matched": [
          {
            "indicates": "publisher pdf",
            "found": "string Downloaded at",
            "in": "file",
            "score_value": 1
          },
          {
            "indicates": "publisher pdf",
            "found": "string ORIGINAL ARTICLE",
            "in": "file",
            "score_value": 1
          },
          {
            "indicates": "postprint",
            "found": "string Phone: ",
            "in": "file",
            "score_value": 1
          },
          {
            "indicates": "postprint",
            "found": "string Tel:",
            "in": "file",
            "score_value": 1
          }
        ]
      },

It looks like the score didn't count what we found, and so got stuck at 0 and gave the 'we don't know what this is' error.

**Comment by markmacgillivray** [comment]
According to the code we have just now, if it indicates "publisher pdf" then it is a +1. If it indicates anything else it is a -1. Therefore the answer above is correct, it averages out to 0 and we don't know what this is.
