### ISSUE TITLE
refactor cluster config management

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1514]
From: #1510

> Improve how we can set configs across machines on different areas of the cluster and how we deploy changes across the cluster. This has not been maintained for two years and many of the ways we used to do it were obsoleted and replaced with hacks. 1 day. IN PROGRESS.

**Comment by markmacgillivray** [comment]
This will finish tomorrow after I finish reviewing how the new API code across the cluster is doing after the latest release that just happened
