### ISSUE TITLE
strings checked 0 on live

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1521]
Tested a deposit at https://shareyourpaper.org/sneakpeak/10.1063/1.4937158 with https://drive.google.com/uc?export=download&id=1FzHn6U_uFYAXQwBLshDQkEEhopHPuUCv. 

It failed said it was the wrong version, which is unexpected.

The response I got was:

```
  "file": {
      "archivable": false,
      "archivable_reason": "We cannot confirm if it is an archivable version or not",
      "version": "unknown",
      "same_paper": true,
      "name": "Correct test paper for (3) (3) (5).pdf",
      "format": "pdf",
      "checksum": "WttnPXPMGRz+vG6qX7N26A==",
      "same_paper_evidence": {
        "words_count": 5209,
        "words_more_than_threshold": true,
        "doi_match": true,
        "title_match": true,
        "author_match": true,
        "document_format": true
      },
      "version_evidence": {
        "score": 0,
        "strings_checked": 0,
        "strings_matched": []
      },
      "lantern": {}
    },
```

Looks like the strings checked is zero, perhaps the call the gdoc failed and it isn't cached on live yet?

I tried a couple of times, and couldn't get it to work. 

Had the same issue with https://dev.shareyourpaper.org/sneakpeak/10.1126/scitranslmed.3008973 & [this file](https://docs.google.com/document/d/1sNY8x0qCD4vuTikEghn2roSfI5kthJxdYuPJ1KSduEw/export?format=pdf). However, that also said it couldn't get content from the file, although that is expected as this happens on dev too. 

On dev, this issue doesn't appear. There I see:

```
 "file": {
      "archivable": true,
      "archivable_reason": "We believe this is a publisher pdf and our permission system says that version can be shared",
      "version": "publisher pdf",
      "version_standard": "publishedVersion",
      "same_paper": true,
      "name": "Correct test paper for (3) (3) (5).pdf",
      "format": "pdf",
      "checksum": "WttnPXPMGRz+vG6qX7N26A==",
      "same_paper_evidence": {
        "words_count": 5209,
        "words_more_than_threshold": true,
        "doi_match": true,
        "title_match": true,
        "author_match": true,
        "document_format": true
      },
      "version_evidence": {
        "score": 2,
        "strings_checked": 87,
        "strings_matched": [
          {
            "indicates": "publisher pdf",
            "found": "string Downloaded at",
            "in": "file",
            "score_value": 1
          },
          {
            "indicates": "publisher pdf",
            "found": "string ORIGINAL ARTICLE",
            "in": "file",
            "score_value": 1
          }
        ]
      },
```

That looks as expected.

**Comment by markmacgillivray** [comment]
The live file checking rules sheet had not been published, and we can only get content from published files. I changed that setting and it is working now.

For the one where dev is unable to read the pdf content, can you give me the file you are trying to send to it? Are you uploading via the UI or passing it as a URL param direct to /permissions API? Let me know which, so I can test in the same way.

**Comment by JosephMcArthur** [comment]
Works now, and I've updated the live doc. 

> For the one where dev is unable to read the pdf content, can you give me the file you are trying to send to it? Are you uploading via the UI or passing it as a URL param direct to /permissions API? Let me know which, so I can test in the same way.

Let's deal with this later, I have an issue for it already.
