### ISSUE TITLE
depositing with all rights reserved 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1528]
It has been correctly flagged that we're a bit too liberal with applying cc-by licenses in cases where publishers assert copyright over AAMs or have odd terms where it's safer to just say all rights reserved. 

This is a partly a data change, which is ongoing now.

However, we also need to just check that whatever we get back from rick's is something we can get into zenodo, as we know they're a little picky.

The plan is that under authoritative_permission.application.can_archive_conditions.licenses_required we'll put 'all rights reserved'.

Could we do some testing (even without the data being done) like we did last time so that we're sure that when we get the above data done deposit will go smoothly? Hoping we can use the test articles we have now and just feed some mock data...

**Comment by markmacgillivray** [comment]
What would the test be testing?
