### ISSUE TITLE
OAB and ODB Requests Spreadsheet

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#153]
_From @chealsye on July 3, 2016 18:10_

Could I get spreadsheets of both Open Access Button and Open Data Button requests with author emails? OAB requests just since the last update.

_Copied from original issue: OAButton/oab_static#15_

**Comment by JosephMcArthur** [comment]
@chealsye can you talk more about why this would be useful? Wondering if we can build a UI for it via the site rather than handle other ways.

**Comment by chealsye** [comment]
The reason I want author emails from requests is so I can match requests with librarians who can help fulfill requests. Say if there is a request for author@harvard.edu, I have someone I can contact and say, "Hey, we have a request! Want to help fulfll it?" As a scholarly communication librarian I'd love to get that email - it gives me something tangible to go into a consultation with. The need for access is real, not just a problem I'm forecasting for them. It not only is a mutually beneficial collaboration, but it begins a position relationship between libraries and the Button, which can lead into further collaboration and institutional work. And it's something we can do right now - if I can get the emails! 

The spreadsheet would work for now, but this collaboration with libraries is something I've been wanting to do for six months and would reallyreallyreally love to get a small pilot going. I can start it with just a simple spreadsheet like we got for the stories. But longterm a UI would be simpler for ongoing work.

**Comment by JosephMcArthur** [comment]
feels connected to #192

**Comment by JosephMcArthur** [comment]
@markmacgillivray an update on this would be helpful. An export of entries to the find system would also be good or just a way to see them.

**Comment by JosephMcArthur** [comment]
@chealsye may just need the author email associated with a request ID in a sheet, or something searchable.

The best way to shut this would be being able to search the author emails (like the harvard in harvard.edu) via the search box on /request

**Comment by JosephMcArthur** [comment]
This is closed by /export when it's finished. 

@chealsye, can you take a look at that page & let us know any feedback you have.

**Comment by chealsye** [comment]
I disagree that it is the best way to shut this down. It is the simplest way, sure, but it does not get me what I asked for and what I need. Searching on the website is a bandaid/plaster fix. I can do it and it will be fine enough for piloting, but not for longterm goals, efficiency, or finding patterns.

**Comment by markmacgillivray** [comment]
/request is just a search, but /export is a page where you can export all the records into a CSV file that you can use in a spreadsheet.  Isn't that what you wanted? The idea is to provide what you wanted whilst also using that need as a use case to drive development of a web UI ( the new /export page) that enables you to export such data any time you want.

There is still some work to be done on it, but it should already work.

**Comment by chealsye** [comment]
Thanks for the clarification, @markmacgillivray. @JosephMcArthur's comment didn't have any context, I did not know there was an /export page, and went off the information/past two comments within this issue.

**Comment by chealsye** [comment]
What is the difference between requests, availabilities, and supports?

I only get 105 requests. Is this from a certain date? 

I think this spreadsheet feature should do what I need. Thanks.

**Comment by markmacgillivray** [comment]
There are only 105 requests in the dev system, so yes that is all you will get for now. Once we move it to live you would get all of them.

Requests are the requests people have created for access to something.

Availabilities are the records of all the availability checks that have been performed on any URL - this is what happens when you first use the plugin on a page before submitting a request, or when you use the website to try to find an article.

Supports are the records of all the users who support given requests.

I will add some info to the export page to explain these for future reference.
