### ISSUE TITLE
admin upload on some files not working

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1534]
I've been doing quite a few review deposits recently and in a few cases the admin upload appears to have not worked. I can't tell any pattern.

The two affected were:

https://openaccessbutton.org/deposit?doi=10.1515/bfp-2019-2012&confirmed=/I+DNI0jFi+XYYsZFJ59Ew==&email=klausgraf@googlemail.com

https://dev.openaccessbutton.org/deposit?doi=10.1080/17457289.2019.1697880&email=miroslav.nemcok@gmail.com&confirmed=+a1TVAnAUww/z24oaCecIw==

These were both originally deposited on the shareyourpaper homepage, but I ended up doing them via the deposit page.

In the cases where this happened on upload I got on the UI:

![image](https://user-images.githubusercontent.com/4953703/78992719-dc6e8300-7b33-11ea-9f9c-c4281b7e0a1e.png)

and I got emailed another review deposit.

The files needed can be found in the emails.

**Comment by markmacgillivray** [comment]
I have made a new parameter called "confirmed" which is passed to the mail template and it contains the checksum in a url-encoded form. It should be safe to use that one in templates to build links that work.

Longer term, should change the checksum generator to not have / in them, but that is a bigger job and not needed right now.

**Comment by markmacgillivray** [comment]
Discussed and will change to passing an "adminlink" variable which will also avoid any problem with URL params

**Comment by markmacgillivray** [comment]
Closed by creating an adminlink variable instead. The confirmed variable is still there too just in case ever useful, but closing this issue now in preference of testing the adminlink variable instead.
