### ISSUE TITLE
adding items to instantill controls

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1556]
I'm seeing some values in the InstantILL set up not be saved. I suspect they're not being accepted by the backend

E.g ids include:

live
pilot
advancedform

I'm almost certain there are more, I haven't check them all.

**Comment by JosephMcArthur** [comment]
Searching `input id=` gives all the ids on the page

**Comment by markmacgillivray** [comment]
Alter config save on instantill to use the config passed from backend in the first place, augment it with changes made on the page, and send it to save. Also note that some ids are not yet in the backend config, and some values are incorrectly showing the delete param on the frontend.

This is a quick fix to make them usable before we come back round to re-doing the setup and demo pages.

**Comment by markmacgillivray** [comment]
Checked all IDs for instantill. Doing the config save now.

**Comment by markmacgillivray** [comment]
OK I have altered the config save, and tidied some data, on dev. Can you test there to see if you can save and alter all configs that you want now? Once you confirm, I can run the script and then push to live. While you are testing that I will work on getting the notes field into openurl configs

**Comment by JosephMcArthur** [comment]
advanced form + live / pilot worked in my quick test, so I think we're good!
