### ISSUE TITLE
date given by users in InstantILL isn't passed to sheet

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1560]
I've noticed that when users fill in metadata manually when InstantILL doesn't find a match the date doesn't make it to the sheet we're using (see the email I sent you to a public sheet).

To replicate:
* Put jibberish into the search box
* manually input article title / journal / year. I'm only using a year like '2020'.
* check the data, you'll see title & journal but not date
* delete your entry

**Comment by JosephMcArthur** [comment]
'sid' (usually 'InstantILL') also isn't passed when using this method, which is should be

**Comment by markmacgillivray** [comment]
Year wasn't in the list of things you told me you wanted in open URLs, so it did not get added. I have added year to the list now.

You can see what you asked for here:

https://github.com/OAButton/discussion/issues/1511#issuecomment-607807861

Anything else you expect it to send will have to be added to that list. 

This has been done on dev if you want to test.

**Comment by markmacgillivray** [comment]
Btw I did test myself, but just to make sure it is as you expect

**Comment by markmacgillivray** [comment]
This should work on live now. Close once you confirm
