### ISSUE TITLE
when the search is too short allow people to long form

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1561]
As discussed. 

When we'd normally throw "search too short error" instead take people to long form. If they try to submit the form and it's still too short, don't do title search and take them right to page to confirm ill request.

**Comment by markmacgillivray** [comment]
OK, this appears to work as desired on dev. Please test and confirm.

**Comment by JosephMcArthur** [comment]
Generally looking okay. When submitting the wrong form with too short of a title, it seems we may still be firing an OA check, which means we can get odd things back. Here we should let them to the next screen, but not do a search for more metdata / OA, as the likely hood of false positives is too high. Of course, if the user does give us enough info at that point, then we're all good to run the check

E.g 

atitle: G
jtitle: Afd
year: 2020

![image](https://user-images.githubusercontent.com/4953703/80062688-373cad00-852c-11ea-92ac-b98713f6c670.png)


Note to self: alter the error that shows when no thing is entered

**Comment by markmacgillivray** [comment]
Yeah we still need to do a check because we need other info that comes back with it, like the openurl. However I can alter it just now so that it does not actually use the thing that came back if it says it is available

**Comment by markmacgillivray** [comment]
OK that is done now. Also I accidentally just pushed it live, forgot I was waiting for you for feedback on others. They seem to be fine to me though, let me know if any issues. Nothing else was pushed live anyway, just this instantill stuff.

**Comment by markmacgillivray** [comment]
I tested and this works, also it is now on live. Close once confirmed.
