### ISSUE TITLE
Stop duplicate records being submitted

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1562]
Through the forms on: https://rscvd.org we're seeing duplicate submissions. This appears to be because the users are clicking the button multiple times before they get a successful submission. 

You can replicate this by just double clicking the submit button quickly. Given submission can take a couple of seconds, this can happen. 

I think the best fix is likely having the button inactivate while the browser awaits a response (either successful or error!) and / or showing "Submitting..." on the page somewhere like we do with InstantILL.

**Comment by markmacgillivray** [comment]
OK I added a change to the submit and book pages (note it would still be good to move that js to a shared page template somewhere if that is possible in the framework you are using). When you hit submit the button should be replaced with "submitting..."
