### ISSUE TITLE
Stop requests that we know are books or book chapters

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1563]
InstantILL only really works for articles, and at the moment people are putting book requests through it and similar. E.g:

e.g 10.1016/S1569-3767(05)06018-8 & 10.1016/B978-0-12-809597-3.00527-7

This works within the tool, but at the moment it can end up in libraries not having everything they need to submit. Sad times.

I think we should throw an error message when we're giving anything that doesn't match: 

id: "journal-article",
id: "proceedings-article",
id: "posted-content",

in crossref.

If we don't match anything, then we can proceed as now.

If the type is:

* book-section
* book-part
* book-chapter

then say:

"Please make your request through our book form". If the book form is given, then link it to "book form".

otherwise, we can throw an error that says:

"We can only process academic journal articles, please use another form."

**Comment by markmacgillivray** [comment]
OK this is done on dev, please check it is how you want

**Comment by markmacgillivray** [comment]
Pushed to live already, sorry. Looks good to me. Close once you confirm.
