### ISSUE TITLE
Process special characters nicely in google sheet submission

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1564]
Seeing some submissions (below) that we're not handling nicely. Can we support more special characters like the below in our submission?

Was ist deutsch? Adornos verratenes Verm�chtnis (pp. 82-92) | Was ist deutsch?: Adornos verratenes Vermächtnis

was ist deutsch? Aspekte zum Selbstverst�ndnis einer gr�belnden Nation | Was ist deutsch?: Aspekte zum Selbstverständnis einer grübelnden Nation (Wissenschaftliche Beibände zum Anzeiger des Germanischen Nationalmuseums)

Rois, cit�s, n�cropoles. Institutions, rites et monuments en Mac�doine | Rois, cités, nécropoles. Institutions, rites et monuments en Macédoine

**Comment by markmacgillivray** [comment]
I added some more url encoding, try it and see if that has helped. It may not as some of it may be down to how sheets displays them, or how they are provided, rather than how they are passed.
