### ISSUE TITLE
Allow rscvd.org to take information from URL params to fill boxes on screen

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1565]
On /submit I'd like people to be able to see and edit the information we've collected (if they'd like) before they submit. I've built a toggle system to show / hide the info, but it's hidden atm.

It would be great if we could have the form boxes on screen be filled by whatever information we have available in URL params. They may then overwrite and add entries on screen before submission. 

Note: I won't put boxes in for *every* URL param, so I don't think this can be used as a substitute for attaching the url params to submission.

**Comment by markmacgillivray** [comment]
Not done this yet, will do once waking up, in about ten hours.

**Comment by markmacgillivray** [comment]
I have done this and uncommented the section where you had put those fields, and I have tested it on your dev site and it appears to work as you describe. Try it and see.

I have also moved the general code out into the form template.
