### ISSUE TITLE
url field continues to be weird and causes error in openurl

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1566]
Today I was doing a demo and used:

`https://ulib.iupui.edu/services/ILL?title=Ribulose%20bisphosphate%20carboxylase:%20a%20two-layered,%20square-shaped%20molecule%20of%20symmetry%20422`

and tried to submit. This gave me the following OpenURL:

`https://ill.ulib.iupui.edu/ILLiad/IUP/illiad.dll?Action=10&Form=30&sid=OABILL&genre=InstantILL&sid=InstantILL&atitle=Ribulose%20bisphosphate%20carboxylase%3A%20a%20two-layered%2C%20square-shaped%20molecule%20of%20symmetry%20422&rft_id=10.1126%2Fscience.196.4287.293&rft.year=1977&crossref_type=journal-article&aulast=BAKER%2C%20T.%20S.%2C%20EISENBERG%2C%20D.%2C%20EISERLING%2C%20F.&title=Ribulose%20bisphosphate%20carboxylase%3A%20a%20two-layered%2C%20square-shaped%20molecule%20of%20symmetry%20422&issue=4287&volume=196&pages=293-295&issn=0036-8075&publisher=American%20Association%20for%20the%20Advancement%20of%20Science%20(AAAS)&date=1977-04-01&url=http%3A%2F%2Fscience.sciencemag.org%2Fcontent%2F196%2F4287%2F293%2Ftab-pdf%2Chttps%3A%2F%2Fscience.sciencemag.org%2Fcontent%2F196%2F4287%2F293%2Ftab-pdf%2Chttp%3A%2F%2Feuropepmc.org%2Farticles%2FPMC4167664%2Chttps%3A%2F%2Fdoi.org%2F10.1126%2Fscience.196.4287.293%2Chttps%3A%2F%2Fdoi.org%2F10.1126%2Fscience.196.4287.293%20%3Cspan%3E%3Ca%20href%3D%22javascript%3A%22%20style%3D%22top%3A%2016px%3B%20position%3A%20relative%3B%22%3E%3Cimg%20class%3D%22citavipicker%22%20identifier%3D%2210.1126%2Fscience.196.4287.293%22%20src%3D%22data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iRWJlbmVfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiIHdpZHRoPSIxNnB4IiBoZWlnaHQ9IjE2cHgiIHZpZXdCb3g9IjAgMCAxNiAxNiIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgMTYgMTYiIHhtbDpzcGFjZT0icHJlc2VydmUiPjxnPjxnPjxwYXRoIGZpbGw9IiNGRkZGRkYiIGQ9Ik04LjAwMSwxNS41QzMuODY0LDE1LjUsMC41LDEyLjEzNiwwLjUsOGMwLTQuMTM1LDMuMzY1LTcuNSw3LjUwMS03LjVTMTUuNSwzLjg2NCwxNS41LDhTMTIuMTM3LDE1LjUsOC4wMDEsMTUuNXoiLz48cGF0aCBmaWxsPSIjRDUyQjFFIiBkPSJNOC4wMDEsMUMxMS44NiwxLDE1LDQuMTQxLDE1LDhzLTMuMTM5LDctNi45OTksN0M0LjE0LDE1LDEsMTEuODU5LDEsOFM0LjE0LDEsOC4wMDEsMSBNOC4wMDEsMEMzLjU4MiwwLDAsMy41ODIsMCw4czMuNTgyLDgsOC4wMDEsOEMxMi40MTgsMTYsMTYsMTIuNDE4LDE2LDhTMTIuNDE4LDAsOC4wMDEsMEw4LjAwMSwweiIvPjwvZz48cGF0aCBmaWxsPSIjRDUyQjFFIiBkPSJNNi43NDUsMTIuNTg5Yy0wLjIyNywwLjEyMi0wLjQ5NywwLjI0Ny0wLjY4NCwwLjI0N2MtMC4zMTgsMC0wLjUwMS0wLjE2NC0wLjUwMS0wLjQ1MmMwLTAuMjA3LDAuMTQtMC4zNzUsMC41OTUtMC42MjJjMS41NDktMC45MDQsMi41OTQtMi4yNzIsMi41OTQtMy43MjFjMC0wLjgyNS0wLjIyNy0xLjExOS0wLjY4MS0xLjExOWMtMC4xMzUsMC0wLjMyLDAuMjE5LTAuNjM2LDAuMjE5SDcuMTU3QzYuMTAyLDcuMTQzLDUuMzMzLDYuMjY0LDUuMzMzLDUuMjNjMC0xLjE1MiwwLjk1OC0yLjAwNiwyLjI4LTIuMDA2YzEuNzc3LDAsMy4wNTMsMS4zNzMsMy4wNTMsMy40M0MxMC42NjYsOS4yMTUsOS4yMDMsMTEuMjcsNi43NDUsMTIuNTg5Ii8%2BPC9nPjwvc3ZnPg%22%20style%3D%22border%3A%200px%20none!important%3Bwidth%3A%2016px!important%3Bheight%3A%2016px!important%3Bmargin-left%3A1px%20!important%3Bmargin-right%3A1px%20!important%3B%22%20title%3D%22Titel%20anhand%20dieser%20DOI%20in%20Citavi-Projekt%20%C3%BCbernehmen%22%3E%3C%2Fa%3E%3C%2Fspan%3E%2Chttp%3A%2F%2Feuropepmc.org%2Farticles%2Fpmc4167664%3Fpdf%3Drender&pmcid=PMC4167664&pmid=17756097&&notes=Subscription%20check%20done,%20found%20https://www.ulib.iupui.edu/cgi-bin/proxy.pl?url=https://www.sciencemag.org/lookup/doi/10.1126/science.196.4287.293.%20OA%20availability%20check%20done,%20found%20http://europepmc.org/articles/pmc4167664?pdf=render.`

This 404s. 

I've used this article a bunch for testing, so the error here was unexpected.

On investigation, it turns out the `url`  field has two issues:

`url=http://science.sciencemag.org/content/196/4287/293/tab-pdf,https://science.sciencemag.org/content/196/4287/293/tab-pdf,http://europepmc.org/articles/PMC4167664,https://doi.org/10.1126/science.196.4287.293,https://doi.org/10.1126/science.196.4287.293 <span><a href="javascript:" style="top: 16px; position: relative;"><img class="citavipicker" identifier="10.1126/science.196.4287.293" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iRWJlbmVfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiIHdpZHRoPSIxNnB4IiBoZWlnaHQ9IjE2cHgiIHZpZXdCb3g9IjAgMCAxNiAxNiIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgMTYgMTYiIHhtbDpzcGFjZT0icHJlc2VydmUiPjxnPjxnPjxwYXRoIGZpbGw9IiNGRkZGRkYiIGQ9Ik04LjAwMSwxNS41QzMuODY0LDE1LjUsMC41LDEyLjEzNiwwLjUsOGMwLTQuMTM1LDMuMzY1LTcuNSw3LjUwMS03LjVTMTUuNSwzLjg2NCwxNS41LDhTMTIuMTM3LDE1LjUsOC4wMDEsMTUuNXoiLz48cGF0aCBmaWxsPSIjRDUyQjFFIiBkPSJNOC4wMDEsMUMxMS44NiwxLDE1LDQuMTQxLDE1LDhzLTMuMTM5LDctNi45OTksN0M0LjE0LDE1LDEsMTEuODU5LDEsOFM0LjE0LDEsOC4wMDEsMSBNOC4wMDEsMEMzLjU4MiwwLDAsMy41ODIsMCw4czMuNTgyLDgsOC4wMDEsOEMxMi40MTgsMTYsMTYsMTIuNDE4LDE2LDhTMTIuNDE4LDAsOC4wMDEsMEw4LjAwMSwweiIvPjwvZz48cGF0aCBmaWxsPSIjRDUyQjFFIiBkPSJNNi43NDUsMTIuNTg5Yy0wLjIyNywwLjEyMi0wLjQ5NywwLjI0Ny0wLjY4NCwwLjI0N2MtMC4zMTgsMC0wLjUwMS0wLjE2NC0wLjUwMS0wLjQ1MmMwLTAuMjA3LDAuMTQtMC4zNzUsMC41OTUtMC42MjJjMS41NDktMC45MDQsMi41OTQtMi4yNzIsMi41OTQtMy43MjFjMC0wLjgyNS0wLjIyNy0xLjExOS0wLjY4MS0xLjExOWMtMC4xMzUsMC0wLjMyLDAuMjE5LTAuNjM2LDAuMjE5SDcuMTU3QzYuMTAyLDcuMTQzLDUuMzMzLDYuMjY0LDUuMzMzLDUuMjNjMC0xLjE1MiwwLjk1OC0yLjAwNiwyLjI4LTIuMDA2YzEuNzc3LDAsMy4wNTMsMS4zNzMsMy4wNTMsMy40M0MxMC42NjYsOS4yMTUsOS4yMDMsMTEuMjcsNi43NDUsMTIuNTg5Ii8+PC9nPjwvc3ZnPg" style="border: 0px none!important;width: 16px!important;height: 16px!important;margin-left:1px !important;margin-right:1px !important;" title="Titel anhand dieser DOI in Citavi-Projekt übernehmen"></a></span>,http://europepmc.org/articles/pmc4167664?pdf=render`

First, it has four things in it. That's not expected. I believe this is intended as the OA URL. Second, inside this is some real junk with this long javascript tag.

This is really long, and i expect that's what causes the 404. 

Can we look into what's going on here?

**Comment by markmacgillivray** [comment]
This was the same error I came across the other day, same DOI. I thought I had removed that bad result from the live system, but maybe I did not. I had removed it from dev. I have just removed it from live. It is possible I did remove it but the bad result got found again before I pushed a change to live yesterday. I have run it through again myself on live just now, after removing it, and since pushing the latest code to live, which happened last night. It gives correct responses now without the bad URL in it. So I think this can be closed for now, but re-open if you see it appear again.
