### ISSUE TITLE
in some (many) cases notes / 'sid' not passed to openurl

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1574]
I'm having trouble replicating this, but it appears to be happening a lot in the RSCVD Article Requests. You can see the source data for this in the sheet I sent in: "public sheet for #1560"

In 'Articles' in column AA you'll see many are missing 'InstantILL'. I have confirmed in many cases these did infact come through InstantILL (and not /paper) by searching the titles in my inbox and seeing them in 'ILL Created' emails. However, then, my trail goes cold. When I try go through the wrong article form I don't see them missed, and they're not missed when we do match. 

Anything you can think of that could cause this?

**Comment by JosephMcArthur** [comment]
It's AB now

**Comment by markmacgillivray** [comment]
Issue to be discussed at meeting, work has been done.

**Comment by JosephMcArthur** [comment]
So, it's still unclear if we've done what's required to close. To know, we need to have https://dev.rscvd.org/paper submit 'manual' as 'where' into the sheet.

To do that, in our last meeting we tried

`<input class="oabutton_find" id="where" type="hidden" val="manual">
`

and

`<input class="oabutton_find" id="where" type="hidden" value="manual">
`

Neither appears to work. Can we look into why?

**Comment by markmacgillivray** [comment]
I'm not sure how this actually relates to the title of the issue, but I have changed the code to use the correct class name which is oabutton_form, and to use "value" which is the correct attribute. Have a go now and see if it does what you want yet.

**Comment by JosephMcArthur** [comment]
Perfect, works now. Let's sit on this issue a bit until we push live and see what happens.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
this solved the issue, some people are using the manual form, which we can see now.
