### ISSUE TITLE
Create a status point to sync and bounce if necessary

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#1575]
Some of this already exists, but to ensure others can easily restart the system when necessary, create an endpoint that simply triggers it across the cluster. Firstly from within the app itself, then also a separate script on a different domain to ensure it can work if the system is totally down

**Comment by JosephMcArthur** [comment]
To close:

- [ ] have joe's api key able to reset & send url as is

Followed in #1581

**Comment by markmacgillivray** [comment]
I need to check with you what account you want this on, then can finish and close
