### ISSUE TITLE
bulk deposit csv export doesn't work when filtered for files

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1578]
Go to:
* https://dev.openaccessbutton.org/shareyourpaper/setup
* click "Repository"
* click "Manually: bulk upload"
* click "All deposits with files"

the downloaded csv will be empty. We'd expect this to have metadata for zenodo deposits

You'll need to do this on an account with some deposits.

Not urgent as this isn't launched yet.

**Comment by markmacgillivray** [comment]
Fixed, looks like it works to me, please check to make sure I have done the right thing.
