### ISSUE TITLE
finish archiving some policies

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1600]
We have some issues with our archiving workflow temporarily, we need to finish up archiving some policies now we're all good.

**Comment by natalianorori** [comment]
We now have all publisher and journal policies archived. There's only one URL that archive.org is not accepting, I've flagged it on the sheet. I've marked the task as done in my document, let me know if everything seems right and if there's anything else I should do. @JosephMcArthur

**Comment by JosephMcArthur** [comment]
I've just seen that some of them (maybe not even the ones you did) are like this:

https://web.archive.org/save/https://www.wsupress.wayne.edu/pre-print-and-post-print-article-policy

where they're not archive links, they're save links. 

Can you do a control find in 

>/save/

and replace any links there with properly saved links?

**Comment by natalianorori** [comment]
I have now  updated them to archive links.
