### ISSUE TITLE
DOI with en dash doesn't work

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1607]
File this under weird DOI encoding issues...

10.1007/s10711–018–0327–4

Currently the UI just says the service is down. Presumably we should at least be able to process it and say this isn't a real DOI.

The next level would be to be able to actually run a search with it.

Removing the en dashes and using - gives:

10.1007/s10711-018-0327-4

which does respond in crossref

https://api.crossref.org/works/10.1007/s10711-018-0327-4

and I can only presume this is correct.

**Comment by markmacgillivray** [comment]
Moved this one to 89 because it relates to other dirty data work

**Comment by markmacgillivray** [comment]
crossref returns this as not in crossref, because of course it is not. So, it can only be made to work if we do clean the data first.

**Comment by markmacgillivray** [comment]
See #1570

**Comment by JosephMcArthur** [comment]
Just heard back from the person who reported this. It was a DOI from their own site that they formatted to have these dashes as they preferred the look. On their end, they linked it to the real DOI, but forgot about that when putting in our service. 

I don't think this deserves a lot of effort. Likely we just need to make sure it throws a 'this doesn't look like a doi' error, rather than a 'the service is down' error.

**Comment by markmacgillivray** [comment]
Should be done, but see #1570 regarding still needing finishing and testing. Will close this one now though as it is fully encompassed by #1570 now.
