### ISSUE TITLE
some title searches that don’t result in a match cause embed to disappear

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1612]
On: https://josephmcarthur.github.io/playground/instantill_test.html
Search: is a paper that won't find anything at all
Result: Embed will disappear, we should see the wrong article form.

**Comment by markmacgillivray** [comment]
I'm not seeing this, I tried on your page and also on the dev OAB site, putting in that string you provided, and I see the wrong article form. Can you give more explanation, or check to see if you are still seeing this.

**Comment by JosephMcArthur** [comment]
Hmmm. I don't have it in front of me but I tried on my phone and it seemed
okay. It certainly did happen before. Perhaps it was solved by other issues
and or you need to make sure you use a unique (fake) title.

**Comment by markmacgillivray** [comment]
I tried a few totally random unique titles and all showed the wrong article form. Possibly you were seeing an error related to the title blacklisting issue, which I already fixed.

**Comment by JosephMcArthur** [comment]
I **think** I just saw this again. 

I put in:

> this wont find: anything

as I was playing around with weird characters and it went. Then, I tried it again and it worked. 

It's quite hard to replicate given the above, and I've tried a few other characters and it was fine.

Don't suppose you'd be able to pull anything out the logs to see?

**Comment by markmacgillivray** [comment]
I have checked but can't see anything specific. I tried putting in a bunch of titles with many weird random characters and none of them caused the embed to disappear.

**Comment by markmacgillivray** [comment]
Given that the embed will soon be rewritten it is probably not worth spending much time checking exactly how the code works, or how it might be responding to particular strange inputs.

**Comment by JosephMcArthur** [comment]
sure thing

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur
