### ISSUE TITLE
citations being matched badly

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1613]
> We had a patron submit three requests via InstantILL this morning that got matched to the wrong citation (which then attached the wrong journal/ISSN to the ILL request). The original searches appear to have been full-citation -
> 
> Adloff, F. (2009). "What encourages charitable giving and philanthropy?" Ageing & Society 29: 1185-1205
> Khan, Sabith. "New styles of community building and philanthropy by Arab-American Muslims." Voluntas: International Journal of Voluntary and Nonprofit Organizations 27.2 (2016): 941-957.
> (2018). “How do you incorporate charity into your holiday traditions?” America 219(13): 6-6
>  
> They respectively mapped to articles from
> 
> Zeitschrift für Geburtshilfe und Neonatologie (2016)
> Schweizerische medizinische Wochenschrift (1963)
> Pancreas (2015)

I can replicate this on live (although I get different titles), on dev, the embed says the service is down when I give them the citations.

**Comment by markmacgillivray** [comment]
Dev saying system down was a combo of blacklist inappropriately matching titles which has been resolved, and the new cleaner function failing on the bad characters. That has been fixed too. Actual improvements to the matching of the citations that are being passed in is ongoing work.
