### ISSUE TITLE
Email: Struggling to submit request (our ref. no.203104135)

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1615]
As discussed on call / on thread. Would be good to fix. 

Ideally it would be nice to also have some very quick and easy notification for when the form fails, and pass any info possible. Only worth doing if it's fast.

**Comment by JosephMcArthur** [comment]
Mark it looks like the form doesn't support submissions through IE. Anything straightforward we can do about that?

**Comment by JosephMcArthur** [comment]
The original blog we used talks about some possible polyfill routes, but I can evaluate them: https://medium.com/@dmccoy/how-to-submit-an-html-form-to-google-sheets-without-google-forms-b833952cc175

**Comment by JosephMcArthur** [comment]
Noting I got another report of this from "IFLA request - trouble submitting report"

![image](https://user-images.githubusercontent.com/4953703/83844928-d0500d80-a6ff-11ea-90e8-b9cc716157a2.png)

**Comment by markmacgillivray** [comment]
Actual IE or edge??? If people are still using IE we should point them to the fact that it is dangerously outdated (and even when it wasn't, it was shit)

**Comment by markmacgillivray** [comment]
We don't use the same APIs as mentioned in that doc, so I don't think the polyfills are relevant.

But if we are going to have to support IE, then someone with IE is going to have to tell us the error it is causing

**Comment by markmacgillivray** [comment]
@JosephMcArthur looked up the error, we use for var p of params which IE does not support. Change to a loop with an i++

**Comment by JosephMcArthur** [comment]
This was submitted via firefox: https://github.com/OAButton/discussion/issues/1615#issuecomment-639289857. 

So, a few issues here now:

- [ ] IE issue
- [ ] [this](https://rscvd.org/submit?where=InstantILL&doi=10.1016%2FS2352-4642(18)30039-7&atitle=Effectiveness%20of%20Family%20Integrated%20Care%20in%20neonatal%20intensive%20care%20units%20on%20infant%20and%20parent%20outcomes%3A%20a%20multicentre%2C%20multinational%2C%20cluster-randomised%20controlled%20trial&crossref_type=journal-article&aulast=O%27Brien%2C%20Karel%2C%20Robson%2C%20Kate%2C%20Bracht%2C%20Marianne%2C%20Cruz%2C%20Melinda%2C%20Lui%2C%20Kei%2C%20Alvaro%2C%20Ruben%2C%20da%20Silva%2C%20Orlando%2C%20Monterrosa%2C%20Luis%2C%20Narvey%2C%20Michael%2C%20Ng%2C%20Eugene%2C%20Soraisham%2C%20Amuchou%2C%20Ye%2C%20Xiang%20Y%2C%20Mirea%2C%20Lucia%2C%20Tarnow-Mordi%2C%20William%2C%20Lee%2C%20Shoo%20K%2C%20O%27Brien%2C%20Karel%2C%20Lee%2C%20Shoo%2C%20Bracht%2C%20Marianne%2C%20Caouette%2C%20Georges%2C%20Ng%2C%20Eugene%2C%20McMillan%2C%20Douglas%2C%20Ly%2C%20Linh%2C%20Dow%2C%20Kimberly%2C%20Taylor%2C%20Richard%2C%20Monterrosa%2C%20Luis%2C%20Canning%2C%20Roderick%2C%20Sankaran%2C%20Koravangattu%2C%20Bingham%2C%20William%2C%20Soraisham%2C%20Amuchou%2C%20el%20Helos%2C%20Salhab%2C%20Alvaro%2C%20Ruben%2C%20Narvey%2C%20Michael%2C%20da%20Silva%2C%20Orlando%2C%20Osiovich%2C%20Horacio%2C%20Emberley%2C%20Julie%2C%20Catelin%2C%20Celine%2C%20St.%20Aubin%2C%20Lucia%2C%20Warkentin%2C%20Tammy%2C%20Kalapesi%2C%20Zarin%2C%20Bodani%2C%20Jaya%2C%20Lui%2C%20Kei%2C%20Kho%2C%20Guan%2C%20Kecskes%2C%20Zsuzsoka%2C%20Stack%2C%20Jacqueline%2C%20Schmidt%2C%20Peter%2C%20Paradisis%2C%20Mary%2C%20Broadbent%2C%20Roland%2C%20Raiman%2C%20Clare%2C%20Wong%2C%20Charlene%2C%20Cabot%2C%20Michele%2C%20L%27Herault%2C%20Maryse%2C%20Gignac%2C%20Marie-Andree%2C%20Marquis%2C%20Marie-Helene%2C%20Leblanc%2C%20Mylene%2C%20Travell%2C%20Cathy%2C%20Furlong%2C%20Marlene%2C%20Van%20Bergen%2C%20Annette%2C%20Ottenhof%2C%20Maryanne%2C%20Keron%2C%20Heather%2C%20Bowley%2C%20Clare%2C%20Cross%2C%20Shannon%2C%20Kozinka%2C%20Gillian%2C%20Cobham-Richards%2C%20Valerie%2C%20Northrup%2C%20Kelly%2C%20Gilbert-Rogers%2C%20Cindy%2C%20Pidgeon%2C%20Pat%2C%20McDuff%2C%20Kim%2C%20Leger%2C%20Norma%2C%20Thiel%2C%20Cindy%2C%20Willard%2C%20Shannon%2C%20Ma%2C%20Evelyn%2C%20Kostecky%2C%20Linda%2C%20Pogorzelski%2C%20David%2C%20Jacob%2C%20Sherin%2C%20Kwiatkowski%2C%20Kim%2C%20Cook%2C%20Valerie%2C%20Granke%2C%20Naomi%2C%20Geoghegan-Morphet%2C%20Nicola%2C%20Bowell%2C%20Hannah%2C%20Claydon%2C%20Jennifer%2C%20Tucker%2C%20Nicole%2C%20Lemaitre%2C%20Thomas%2C%20Doyon%2C%20Myriam%2C%20Ryan%2C%20Candace%2C%20Sheils%2C%20Joanne%2C%20Sibbons%2C%20Elizabeth%2C%20Feary%2C%20Anne-Marie%2C%20Callander%2C%20Ian%2C%20Richard%2C%20Robyn%2C%20Orbeso%2C%20Jennifer%2C%20Broom%2C%20Margaret%2C%20Fox%2C%20Alexis%2C%20Seuseu%2C%20Jan%2C%20Hourigan%2C%20Jack%2C%20Schaeffer%2C%20Cynthia%2C%20Mantha%2C%20Ginette%2C%20Lataigne%2C%20Melanie%2C%20Robson%2C%20Kate%2C%20Whitehead%2C%20Leah%2C%20Skinner%2C%20Natasha%2C%20Visconti%2C%20Rita%2C%20Crosland%2C%20Deedee%2C%20Griffin%2C%20Kate%2C%20Griffin%2C%20Brandon%2C%20Collins%2C%20Lisa%2C%20Meyer%2C%20Kirsten%2C%20Silver%2C%20Ian%2C%20Burnham%2C%20Britt%2C%20Freeman%2C%20Rachel%2C%20Muralt%2C%20Kristi%2C%20Ramsay%2C%20Cara%2C%20McGrath%2C%20Pawulina%2C%20Munroe%2C%20Michelle%2C%20Hales%2C%20Denise&title=The%20Lancet%20Child%20%26%20Adolescent%20Health&issue=4&volume=2&pages=245-254&issn=2352-4642&publisher=Elsevier%20BV&year=2018&date=2018-02-08&url=https%3A%2F%2Fdoi.org%2F10.1016%2FS2352-4642(18)30039-7&&notes=Subscription%20check%20done,%20found%20nothing.%20OA%20availability%20check%20done,%20found%20nothing.) not submitting
- [ ] whatever is going on (here)[https://github.com/OAButton/discussion/issues/1615#issuecomment-639289857]. issue to be replicated, but likely related to two.

**Comment by markmacgillivray** [comment]
I've changed that loop structure - @JosephMcArthur can you have a look and see how it goes now? Or let me know again where I can see the latest version of the code running? I have pushed it into the master branch of your ill-covid repo already.

**Comment by JosephMcArthur** [comment]
ill-covid → dev.rscvd.org ( http://dev.rscvd.org/ )

ill-covid-live → rscvd.org ( http://dev.rscvd.org/ )

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
OK ta. Well I just checked and the new code works, and I have tried it on browserstack on IE and it works there too. However from your comment above, the "this is not submitting" one still does not work and I can't get browserstack to show the dev tools, so I can't see the error. I would guess it could be because the author string is extremely long. For your third "whatever is going on here" - I don't know what it was that was going on, so if you could have a look and let me know if there is still a problem with whatever that was, or if it is solved by the loop code fix, just let me know what you find.

**Comment by JosephMcArthur** [comment]
> OK ta. Well I just checked and the new code works, and I have tried it on browserstack on IE and it works there too. However from your comment above, the "this is not submitting" one still does not work and I can't get browserstack to show the dev tools, so I can't see the error. 

This is on any browser

> I would guess it could be because the author string is extremely long. For your third "whatever is going on here" - I don't know what it was that was going on, so if you could have a look and let me know if there is still a problem with whatever that was, or if it is solved by the loop code fix, just let me know what you find.

I'm going to have trouble replicating this in any meaningful way as I was only given a screenshot. I expect it was a character escape issue. I think the only thing to do here is to perhaps create a way for the script to fail nicely. Either by allowing us to show an error message, or notifying us with some info (ideally)
