### ISSUE TITLE
Weird metadata grabbed on "Successful Deposit: 10.1007/s11095-018-2379-4"

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1617]
Almost all the metadata is wrong, and it's unclear why. I can't see this on other records at the moment, thankfully! 

This was done on the zenodo record too, but I've updated it so it's no longer incorrect.

**Comment by markmacgillivray** [comment]
Tried to replicate this but can't. Not seeing the same problem anywhere else. Safe to close?
