### ISSUE TITLE
Email: "Review Deposit {{metadata.doi"

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1619]
No idea what happened with this deposit. The DOI has researchgate in the title, is this our blocking system mis-firing by any chance?

**Comment by markmacgillivray** [comment]
This was likely caused by missing metadata, and that meant the template could not fill in properly. This issue should not exist any more because I already changed how that handles when info is missing, whilst working on refactor stuff. So I will close this one, we can re-open if it comes up again.
