### ISSUE TITLE
Make /CottageLabs/api repo more friendly

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#162]
- [ ] What URL can the docs be found at? Readme needs clarifying
- [ ] Mention OAB in the read me, and direct folks to the main readme for info (just incase folks get sent there by someone else)
- [ ] Joe to add more here

**Comment by markmacgillivray** [comment]
Docs, tests, readme etc for CL API are our focus for the summer, so these things should improve in the next couple of months.

**Comment by JosephMcArthur** [comment]
Ace, great to hear, assigning to you! 

Where this affects repo's OAB is using I'm more than happy to help out with Readme's and things like that.

**Comment by JosephMcArthur** [comment]
Not a near term priority, moving from the backlog.

**Comment by JosephMcArthur** [comment]
Code for API is now in /website, so this can be shut.
