### ISSUE TITLE
non-open covid dois

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1637]
> The covid query thing on email has no issue relating to it, so documenting here, since everything else is going on here at the moment :)
> 
> I ran the query to get the values out, but didn't have permissions info, so wrote a script to get those for each record. Haven't added scraping for emails yet as that would make the script take a fair bit longer. However, can rerun with that later. Once the current scripts finishes I'll respond to the email with a link.
> 
> The interesting thing I noticed is that Ricks permissions often responded with failures, and when I checked some manually, it appeared to be because they didn't register them as valid DOIs. Here is an example one:
> 
> 10.3760/cma.j.issn.0578-1310.2020.03.002
> 
> It does dereference, so it does seem to be valid, although it does point to what looks like a chinese publication. Does Ricks not cover all DOIs? Probably doesn't matter, given that we are rewriting that anyway, but something to keep in mind for our own work.
> 
> Issues opened above are being worked on, will update this issue again once they are closed (and the other issue about the main example DOI on the front page).

> Also figshare DOIs failing

Originally posted by @markmacgillivray in https://github.com/OAButton/discussion/issues/1513#issuecomment-668456107_

**Comment by JosephMcArthur** [comment]
Any link yet?

**Comment by markmacgillivray** [comment]
Yeah I sent you both the link last week

https://static.cottagelabs.com/covidpapers.csv

**Comment by JosephMcArthur** [comment]
Oh whoops, thanks.

So, it looks like a bunch of things that are open are here, e.g everything in core, figshare, arxiv, and medrxiv are open. pubmed & europepmc things are also being flagged as closed but that could be right.

Can you just give me Crossref things please? Can you also give me back the `is_paratext: ` value please?

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Ooh, OK, sounds like something must be wrong with that export then, I'll have a look.
