### ISSUE TITLE
automated testing on live

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1643]
I've set up some automated tests that can be run periodically on live:

https://app.ghostinspector.com/suites/5f4e8534003f406cd1401e7b

This is *not* a full suite. They're more sanity checks that our tools are loading and running as we'd expect, and hopefully it's enough to catch small configuration issues that can happen between live / dev and generally completely bring something down or massively change a response (e.g the InstantILL email / link issues yesterday, and the SYP request thing today). 

Currently, they run daily.

To close this, we should:

- [x] have them run when we merge to master on a repo
- [x] review and see if more sanity checks are useful

In the long run, this should also save us time by meaning that once we push we don't need to worry about checking for stuff like this (as we often do!)

**Comment by markmacgillivray** [comment]
Added a trigger from codeship after push to master and after site has finished deploying, the tests will run. Removed the daily schedule.
