### ISSUE TITLE
Fix SYP issues on /deposit

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1644]
See "BUG: Old syp disappears on use"

Opened for tracking.

**Comment by markmacgillivray** [comment]
I've switched this over on dev, looks good to me. @JosephMcArthur please check the response on dev is now the one you would want, and if so, the dev website branch can be merged into master to put it live.

**Comment by markmacgillivray** [comment]
This has been done, @JosephMcArthur please close if all looks well to you on live.

**Comment by JosephMcArthur** [comment]
Coping for chat as I think you've stopped working (and I have for the day)

> 
> I'm still not seeing the config I'd expect in the page
> e.g I don't see Natalia's email in the config
