### ISSUE TITLE
Some infrastructure tidying

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#1650]
At least one of our core machines is running on old Ubuntu OS. It needs to be updated which is a major task, and not as simple as just replacing with a new machine because we have some subscribed services that have to come from that IP, and the IP is not guaranteed to stay the same if the machine is replaced. There are solutions to this such as assigning a static IP, but those will then require re-subscription with the new static IP.

Either way - we have to update the machine, or destroy and replace and resubscribe. This is going to be half a day to a day of work.

We also could do with adding another index machine to the index cluster. This is fairly straightforward to create but needs to be carefully managed to ensure no data loss and that things balance well. Another day of work for this.

Lastly, we need to review our backup procedures as they have not been checked for a long time. This is another half day to a day, if we go so far as ensuring we can recreate from backup, which we should do.

**Comment by JosephMcArthur** [comment]
> At least one of our core machines is running on old Ubuntu OS. It needs to be updated which is a major task, and not as simple as just replacing with a new machine because we have some subscribed services that have to come from that IP, and the IP is not guaranteed to stay the same if the machine is replaced. There are solutions to this such as assigning a static IP, but those will then require re-subscription with the new static IP.
> 
> Either way - we have to update the machine, or destroy and replace and resubscribe. This is going to be half a day to a day of work.

Forked here for discussion: https://github.com/OAButton/discussion/issues/1653. 

> We also could do with adding another index machine to the index cluster. This is fairly straightforward to create but needs to be carefully managed to ensure no data loss and that things balance well. Another day of work for this.

This already exists here: https://github.com/OAButton/discussion/issues/1603

> Lastly, we need to review our backup procedures as they have not been checked for a long time. This is another half day to a day, if we go so far as ensuring we can recreate from backup, which we should do.

Already up in https://github.com/OAButton/discussion/issues/1654 & https://github.com/OAButton/discussion/issues/1547

Split so we can discuss and prioritize independently. Closing.
