### ISSUE TITLE
Placing script above embed div causes embed to not load

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1657]
**Describe the bug**

When scripts are placed above `<div id="instantill"></div>` the embed fails to load. There is an error in the console.

**To Reproduce**

Go to: https://oabutton.github.io/testing-ground/instantill/dev/no-style-flipped-default

Turning off bootstrap removes the error, but doesn't load the embed.

**Expected behavior**

- [x] Mark: It loads.
- [x] Me: We have a test which ensures this continues to be the case as I think this is a regression vs what we did when building

**Additional context**

I found this while installing the embed on rscvd.org as we had last time

**Comment by JosephMcArthur** [comment]
Set up a test here: https://app.ghostinspector.com/tests/5f5fa4da3eaca6724597d6f3. 

It should pass when this is good.

**Comment by markmacgillivray** [comment]
Remove the bootstrap test, if user wants to tell us in config to not use bootstrap we won't, but otherwise put in the bootstrap classes. If this breaks a test somewhere, we will find out what we forgot :)

**Comment by markmacgillivray** [comment]
Add a hack to look for bootstrap on page html content via tags or likely class names

**Comment by JosephMcArthur** [comment]
Discussed over chat. Closed.
