### ISSUE TITLE
set up page doesn't provide new keys to users who already have embeds

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1658]
**Describe the bug**

While setting up RSCVD with new embeds (moving from the old to new system) I logged the relevant account and copied the new code across. However, much of the config didn't work as the keys I got given were the old ones. For instance, I got `saypaper` not `say_paper` as expected [given the config rename](https://docs.google.com/spreadsheets/d/1xmky2uFyAKUd4oECqo76cV8FTOwL4xxxzaLfVEXMOvk/edit#gid=0).

**To Reproduce**

The RSCVD account uses joe+iflav2@openaccessbutton.org. I can set this up so if you use that address to login it'll forward the login email to you to. That means you should be able to login and replicate. Of course, if you have a better way, go for that!

**Expected behavior**

I should get the new keys so that I (and the other users we need to ask to do this) can update to the new system easily.

If this isn't straightforward, then we'll could generate code for others to use some other way and I'll send it in emails to them. Given this is a one off event I'm happy to use a one off method!

** other **

Note to self. When this is fixed I should see:

* 'or use full request form' on wrong page for rscvd
* 'Or use full request form' on full page for rscvd

**Comment by markmacgillivray** [comment]
I've looked at this in various ways but think we need to talk over, I don't see how it can be done whilst also supporting the other requirements of configs for other kinds of user. But having reviewed my thoughts on that when commenting on issue #1655 perhaps part of the problem is that we didn't communicate those requirements well enough. Alternatively, yes, can just change the config for this specific user, but then in that case, like with the Natalia demo account, I'm not sure what the action to do that should be, and why it's not just a case of rewriting the configs on the page you're installing it on to use the new key names.

**Comment by markmacgillivray** [comment]
The user needs to be able to copy their config from the box on setup even if they haven't gone through the page settings again. BUT it shouldn't actually change their config on the system in case they don't go ahead and use it. So add some code to the UI that swaps old names for new names IN the box that is shown to the user, so they can copy/paste easily, and also keep it updated when the user does click the settings on that page.

**Comment by markmacgillivray** [comment]
This should be done now, trying on my account I see the new key names on the copy/paste box even though my backend config still has old key names. Try it and let me know if looks OK to you now.

**Comment by JosephMcArthur** [comment]
Tried to test, but failed for issues explained over email.

**Comment by markmacgillivray** [comment]
Email issues just related to clashing with ongoing changes to the system, should work normal for you now. However if you're stuck in an account you don't want to be in, get the account ID from dev tools and let me know and I'll clear it.

**Comment by JosephMcArthur** [comment]
Okay grand this looks good
