### ISSUE TITLE
Buttons on RSCVD are not responsive to on page styling

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1659]
**Describe the bug**

The buttons on https://dev.rscvd.org/ don't look as expected, which is more like: https://rscvd.org/. 

**To Reproduce**

Go to those we addresses. 

**Expected behavior**

The button should take the color and style.

**Comment by markmacgillivray** [comment]
Your style.css for rscvd.org applies specific styling to buttons with the class oabutton_find. But on dev, the new embed does not have that class on buttons, it uses _oab_find. So I don't think the problem is with the embed, it's with your css styling for rscvd.org.

**Comment by JosephMcArthur** [comment]
Closed. 

Took quite a bit longer than expected. As this was made my copying old class names and putting their styles into the style sheet there were a few things that needed changing / conflicting. 

Sorted those out, and it's good as new now.
