### ISSUE TITLE
set up redirects for new ghost blog

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1660]
**Is your feature request related to a problem? Please describe.**

We have a new blog at oabutton.ghost.io. It's faster, flexible, has a better UX (no medium ads), and is more private.

**Describe the solution you'd like**

We need to redirect old links there. I think we've discussed two big categories:

* Medium ones
* Pre-medium ones

They have a system for redirects at https://ghost.org/tutorials/implementing-redirects/.

Pre-medium ones I have no idea about how to do, although I think there aren't many so many best just done by hand (or maybe nothing needs done).

The current medium ones follow a fairly standard pattern. e.g `https://blog.openaccessbutton.org/supporting-resource-sharing-during-covid-19-with-ifla-41678a89e118`. `41678a89e118` is the only part of the URL that counts, and without it it doesn't resolve so we won't have shared anything without that. Removing that (plus the `-`) should redirect most links easily I think. This is needed because ghost has only given URLs like `https://blog.openaccessbutton.org/supporting-resource-sharing-during-covid-19-with-ifla` so the removal of the code is required but the rest of the slug is fine.

If you know better methods, go for that, just communicating my hunch. 

**other**

I have invited you to the Ghost admin system so you can play, uploading the file can be done here: https://oabutton.ghost.io/ghost/#/settings/labs.

I have set up a repo at https://github.com/OAButton/ghost-blog-theme for managing files associated with the blog.

**Comment by JosephMcArthur** [comment]
- [X] openaccessbutton.org/blog --> blog.openaccessbutton.org
- [ ] move the old nginx ones to the new file in ghost. Then they're all in one place.

`location /blog/new-oab-2016 {
    rewrite ^/.* https://medium.com/@openaccessbutton/take-action-this-open-access-week-with-the-new-open-access-button-e9372c5cb4aa permanent;
  }
  location /blog/open-data-button-is-here {
    rewrite ^/.* https://medium.com/@openaccessbutton/new-app-helps-researchers-share-data-openly-be59437ed6fa permanent;
  }
  location /blog/may-major-updates {
    rewrite ^/.* https://medium.com/@openaccessbutton/open-data-button-launch-update-fd5d7c4e8a74 permanent;
  }
  location /blog/open-data-button-beta {
    rewrite ^/.* https://medium.com/@openaccessbutton/open-data-button-beta-launching-next-week-for-open-data-day-8ab4d0e222a3 permanent;
  }
  location /blog/from_open_access_to_open_data {
    rewrite ^/.* https://medium.com/@openaccessbutton/the-open-access-button-moves-into-open-data-7752f73f7f16 permanent;
  }
  location /blog/standwithdiego {
    rewrite ^/.* https://medium.com/@openaccessbutton/diego-gomez-stands-trial-for-sharing-research-standwithdiego-7bc1f8fadeab permanent;
  }
  location /blog/diego-gomez {
    rewrite ^/.* https://medium.com/@openaccessbutton/support-diego-gomez-an-update-a0e18d0afb96 permanent;
  }
  location /blog/opencon2015 {
    rewrite ^/.* https://medium.com/@openaccessbutton/opencon-applications-are-open-ff694021d72 permanent;
  }
  location /blog/annual-report-2014 {
    rewrite ^/.* https://medium.com/@openaccessbutton/open-access-button-annual-report-2014-90906c2cf12e permanent;
  }
  location /blog/jisc2015 {
    rewrite ^/.* https://medium.com/@openaccessbutton/support-us-in-the-jisc-supporting-technology-startup-project-bfbeec0b50cd permanent;
  }
  location /blog/innovator-award {
    rewrite ^/.* https://medium.com/@openaccessbutton/open-access-button-founders-honoured-with-sparc-innovator-award-22a57e9f5039 permanent;
  }
  location /blog/end-year-team-memo {
    rewrite ^/.* https://medium.com/@openaccessbutton/open-access-button-annual-report-2014-90906c2cf12e permanent;
  }
  location /blog/odb-launch-update {
    rewrite ^/.* https://medium.com/@openaccessbutton/open-data-button-launch-update-fd5d7c4e8a74 permanent;
  }
  location /blog/new-apps-find-free-access-to-scientific-and-scholarly-research {
    rewrite ^/.* https://medium.com/@openaccessbutton/21-october-2014-631d530eb8ca permanent;
  }`

**Comment by JosephMcArthur** [comment]
I've moved the old nginx links above to the new ghost theme. @markmacgillivray can you remove them from the nginx file, confirm the /blog update, and then if all is well push live? Then I can shift the domain at any point.

**Comment by markmacgillivray** [comment]
We can do this in our meeting to co-ordinate DNS changes.

**Comment by markmacgillivray** [comment]
Done my bit
