### ISSUE TITLE
Not urgent sparc site support

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1662]
See email of same title. Here for tracking.

**Comment by markmacgillivray** [comment]
@JosephMcArthur demo solution available at:

https://bigdeal.test.cottagelabs.com/cancel

It doesn't have your site styling, but should work as expected. You can add it to the sparc site to try it out there. Just go to the page where you currently have it, and in the tbody elements where you have sheetsu attributes, take out all those attributes and instead add an attribute called sheet, with the ID of the source sheet (which you can get from the google sheet URL itself or from my demo page linked above). Also for the second table, another attribute called sheetid is needed, and the value should be 2. Then add a js script call to get the js file, which is currently served from https://bigdeal.test.cottagelabs.com/static/cancellations.js

Let me know if you need changes. Once you are happy we can move the script into the OAB repo and you can link it from there.

**Comment by JosephMcArthur** [comment]
This is up: https://sparcopen.org/our-work/big-deal-cancellation-tracking/.

The only thing I can see that's an issue right now is that when you search the header disappears.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
and, can move to and OA repo whenever

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
Greg still seeing issues. See email.

**Comment by markmacgillivray** [comment]
Updated based on email

**Comment by JosephMcArthur** [comment]
Closing this. Going to presume it'll work once the SPARC site is updated so there isn't anything more for us to do.

**Comment by JosephMcArthur** [comment]
Just remembered this is sadly not fixed.

**Comment by markmacgillivray** [comment]
Can you use square brackets instead of curly brackets

**Comment by markmacgillivray** [comment]
I've made the further changes we discussed, the js now inserts an entire table into some divs that have a sheet called "sheet". Those divs should also have the attributes "sheet" and "sheetid" if necessary. You can see how that is done on my demo page, if you put that into the sparc site we should be able to see if it works fine there.

Demo page where you can check the code working:

https://bigdeal.test.cottagelabs.com/cancel

**Comment by JosephMcArthur** [comment]
Still no luck here: https://sparcopen.org/our-work/big-deal-cancellation-tracking/.

Have you considered how much work it would be to reuse: https://sparcopen.org/our-work/big-deal-knowledge-base/.

J

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Unfortunately, if this is still not working, then I really don't see what else we can do apart from abandon the page altogether. If we can't remove all the other things that are running on it and possibly interfering, there's no way we can find what is causing it to fail there - and as it's showing no errors, there's nothing left to explore. We know it works on the test web page. We could do it like the bigdeal page, but I don't see how that would help - it might, as a pure fluke, but the complexity of the bigdeal one is quite a bit higher than what we have for the cancellations one, and the end result is that both of them are some javascript that try to stick a thing in an element on the page. 

So I can go ahead and do it like the bigdeal one if you want, it may or may not have any effect. There's no particular reason why one of them should work over the other one, so it might be a wasted and over-complicating effort.

**Comment by JosephMcArthur** [comment]
Gotcha, I've begun porting it here: https://sparcopen.github.io/cancelations/.

Let it with me for now.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
@JosephMcArthur anything else you need from me on this one? If not feel free to close.

**Comment by JosephMcArthur** [comment]
Can we move the code to a non-test site? I don't mind where, ideally a repo I can see. 

After that this can be shut.

**Comment by JosephMcArthur** [comment]
oh, and FYI I updated the sites location. 

It now lives here https://bigdeal.sparcopen.org/cancellations

**Comment by JosephMcArthur** [comment]
To be clear... I'm looking to move:

> <script src="https://bigdeal.test.cottagelabs.com//static/bundled_a4fa9ea14f4c16107e6c5f579a9b385a.min.js">
</script>

to a live link.

I've adjust the other calls on the page to use live systems already. 

I've added you to the repo, if that is easier.

**Comment by markmacgillivray** [comment]
Bit confused by this one now - you already appear to have moved the cancellations.js file onto that new domain. And the file you reference above, the bundled one, isn't one that I created for this work. I don't know what that is you're importing, or why it would be needed. I'd guess it's the static bundle for the bigdeal site, which if so, you don't need, as far as I can tell. Unless I am misunderstanding what you are trying to do.

**Comment by JosephMcArthur** [comment]
You're right! I don't need it. 

I that case... this is closed!
