### ISSUE TITLE
remove options requests on embed API calls

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1666]
**Is your feature request related to a problem? Please describe.**

The options requests slows down API calls by sometimes 1/2 a second. Less than ideal.

**Describe the solution you'd like**

Would be good to remove them for all calls that benefit from a quick response (e.g files doesn't matters). Ideally we'd do this for everyone, but if not for us would be good.

Using GET when possible to remove need for options seems like the best route ahead. 

**Describe alternatives you've considered**

2nd best may be domain aliasing.

**Comment by markmacgillivray** [comment]
GETs would have been a hassle so instead I altered it to POST with the wrong content type, then the backend re-interprets it. Works well, no OPTIONS checks now.
