### ISSUE TITLE
pilot & live mode don't activate

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1676]
**Describe the bug**

Activating pilot mode should give a pilot key in the config, and update the UI. Currently the config (on a fresh account) is:

```
<div id="instantill"></div>
<script src="https://dev.instantill.org/embed.js"></script>
<script>_oab=instantill({api: 'https://dev.api.cottagelabs.com/service/oab', uid: "B9JCWjKSKWWr9c8QS", config: {"undefined":1600961553561}});</script>
```

Note: **undefined":1600961553561**

Ticking `Have you rolled it out?` currently doesn't change the config I see at all.

**To Reproduce**

See dev / live for syp or instantill. Sign in, then go to https://dev.openaccessbutton.org/instantill/setup#rollout and tick pilot mode or `Have you rolled it out?`, and save.

**Additional context**

My understanding is that we had these generate date stamps so that we could tell when they were / weren't on and generate stats. Now, given the config gets passed into the logs along with the api call... can we let that drive the understanding of what's pilot / live? Maybe that could simplify this?

**Proposed Fix (if available)**
How might we fix this?

**Checklist (For internal use)**

- [X] Take a breath. Bugs are okay.

Process checklist:
- [ ] Do we want a `fast` first, then a `good` fix? A `good` fix likely involves discussion, and may be slower. A fast fix means whoever is available fixes the problem as best they can immediately without too much consideration for the `good` fix.

We can do a `good` fix.

- [ ] Discussion of solution. Remember, our intutative fixs may be different (e.g UI centric, backend centric)
- [ ] Stay clear of hangouts

Post-fix
- [ ] How can we avoid bugs like this in future?

Attempted to suggest something that might make this more like other config options, so easier to maintain... no idea if that's right. 

- [ ] How can we avoid regressions (e.g automated test)

**Comment by markmacgillivray** [comment]
As far as I can see these were just a result of a typo, I've tested a few different ways, seems good to me now on dev. Try it and see.

**Comment by JosephMcArthur** [comment]
Looks good, can you push this live?

**Comment by JosephMcArthur** [comment]
I'll check tests later, so lets keep this open.

**Comment by markmacgillivray** [comment]
done
