### ISSUE TITLE
Shareyourpaper gives 'owner' in config but InstantILL doesn't

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1677]
**Is your feature request related to a problem? Please describe.**

The default InstantILL and Shareyourpaper.org configs differ.

```
<div id="shareyourpaper"></div>
<script src="https://dev.shareyourpaper.org/embed.js"></script>
<script>_oab=shareyourpaper({api: 'https://dev.api.cottagelabs.com/service/oab', uid: "oDTgnXiyNDw298EaW", config: {"owner":"joseph.mcarthur.10+ownertest@gmail.com"}});</script>
```

```
<div id="instantill"></div>
<script src="https://dev.instantill.org/embed.js"></script>
<script>_oab=instantill({api: 'https://dev.api.cottagelabs.com/service/oab', uid: "oDTgnXiyNDw298EaW", config: {}});</script>
```

**Describe the solution you'd like**

I think they both should have `"owner":"joseph.mcarthur.10+ownertest@gmail.com"` as part of the default, no? As there are many InstantILL features that use the email and if it's not in the config presumably it must be fetched.

**Internal Use**

- [ ] Backend plan
- [ ] Frontend plan
- [ ] How will we test it?

I should check the tests for this, and if I don't have one for each config make one.

- [ ] Estimate
- [ ] Can this be fixed easily?
- [ ] Do we know people really want this?

**Comment by markmacgillivray** [comment]
Yep instantill was just missing the default from the backend, I've added it now.

**Comment by JosephMcArthur** [comment]
Looks good, can you push this live? 

I'll check tests later, so lets keep this open.

**Comment by markmacgillivray** [comment]
done
