### ISSUE TITLE
Tune the status alerts for the live system

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#1678]
The live system status alerts throw a few too many emails that we don't really need. Change the daily interpolator to compare against hourly changes from the day before, perhaps.

**Comment by JosephMcArthur** [comment]
Watching & tweaking atm.

**Comment by markmacgillivray** [comment]
Work continued on this, there have been some oddities with certain status alerts not seeming to be aware of the correct count of the previous day, so I'm looking for a fix for that then I think we can close this. But will continue to work on it this week.

**Comment by markmacgillivray** [comment]
I continued watching these closely and checking on them. There is still an error where it does not find counts from the day before of the firefox plugin, for example. I haven't found why this is yet, I'm guessing because of the format of the group name or something like that. However given that it seems we are likely switching to a new infrastructure soon, status alerting will be changing then anyway, so I don't think it is worth spending more time on this one. We are getting useful alerts now, and it is indicating changes that we would hope, such as the other day after running TDM stuff for the demo Joe was doing, it noted that there had been an increase in usage there and warned us about it. So for now we can just ignore the daily over-enthusiastic warnings that it gives us, and at least we will spot when there is actually something going wrong from what it is already able to pick up.
