### ISSUE TITLE
Write up a long term system development plan

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#1679]
We have a lot of useful backend tools running the OAB API and also various other APIs that have been developed as part of my work over the years. We could probably make more effort to develop these into a useful product for our community. There are a range of ways to do that, from just being more public about API docs and feature developments, through to offering dedicated services (API, deployments, software stack, etc) or community building around the tools. Write up these options as part of a long term plan with estimates of level of difficulty in terms of resource consumption, and potential benefit to the project.

**Comment by markmacgillivray** [comment]
Related #1635

**Comment by markmacgillivray** [comment]
There is now a google doc which I'll continue to use to develop ideas, and which can be used as content for some API web pages if appropriate. I'll share that with the team on email soon, and we can continue discussions in our usual meetings. We may want to close this issue, but will keep open until we next talk about what is in the doc.

**Comment by JosephMcArthur** [comment]
@markmacgillivray reopened as there are still a few questions in the doc we should try and answer. Especially re: caching / logs / history.

**Comment by JosephMcArthur** [comment]
If it's easier, we can talk about some of the questions on a call.
