### ISSUE TITLE
do another button sometimes doesn't remove the doi from the URL

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1683]
**Describe the bug**
The do another button sometimes doesn't remove the doi from the URL when clicked 
**To Reproduce**

1. To go: https://shareyourpaper.org/10.1186/1758-2946-3-47
2. Click do another

Process checklist:
- [X] Do we want a `fast` first, then a `good` fix? A `good` fix likely involves discussion, and may be slower. A fast fix means whoever is available fixes the problem as best they can immediately without too much consideration for the `good` fix.

`good`

- [x] Discussion of solution. Remember, our intutative fixs may be different (e.g UI centric, backend centric)
- [x] Stay clear of hangouts

Post-fix
- [x] How can we avoid bugs like this in future?
- [x] How can we avoid regressions (e.g automated test)

**Comment by JosephMcArthur** [comment]
- [ ] can we add a do another button here: https://oabutton.github.io/testing-ground/shareyourpaper/dev/montana.html?doi=10.1186/1758-2946-3-47

**Comment by JosephMcArthur** [comment]
Need to make sure we're testing the restart class on syp & embed.

**Comment by markmacgillivray** [comment]
This was fixed, will leave open for our next discussion to see what we want to do about testing the restart class.

**Comment by JosephMcArthur** [comment]
@markmacgillivray https://github.com/OAButton/discussion/issues/1683#issuecomment-703446556 still needs doing.

**Comment by JosephMcArthur** [comment]
tests made!
