### ISSUE TITLE
Show 'try another' link below 'complete request' buttons

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1685]
**Is your feature request related to a problem? Please describe.**

If you get to a results page, and that's enough, there is no way to go back. 

**Describe the solution you'd like**

Adding a secondary button (like on the #_oab_metadata ) to reset the embed. The text should read "Try another". Note, this needs to be done regardless of if you're submitting by link or by email.

That means it should appear as follows:
![image](https://user-images.githubusercontent.com/4953703/95027322-781a1f80-068f-11eb-9754-6e5b36988885.png)

**Comment by markmacgillivray** [comment]
I've added this, I think it should show where you want it, there was only one "complete request" button on the template and it does show under that now, so this can be closed if you are happy with that.
