### ISSUE TITLE
When search isn't for an acceptable article type search is slow and never stops

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1687]
**Describe the bug**

As above

**To Reproduce**

Click:
`https://oabutton.github.io/testing-ground/instantill/dev/alberta?doi=10.1093/OXFORDHB/9780199282944.003.0015
`
`https://oabutton.github.io/testing-ground/instantill/dev/alberta?doi=10.1016/B978-0-12-815344-4.00016-7`

**Expected behavior**

Search should stop after error is given. I'm also not sure why it took so long, but that's not such a big deal.

**Screenshots / GIF**

http://g.recordit.co/aJlqALyxkt.gif

**Comment by markmacgillivray** [comment]
I didn't see the slowness, and I almost immediately saw the "this isn't something we can process" message however I noticed the ... was still repeating on the button, so I set that not to repeat when this happens. this can be closed unless you can replicate the issue again.
