### ISSUE TITLE
Upgrade elasticsearch

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#1692]
We run a very old version of ES. It runs well, and there's nothing beneficial for us in the newer versions, so this isn't urgent. But the older it gets, the harder it will be to maintain. Setting up a fresh system with old ES is already hard because the java version it relies on is obsolete. So over time, it will become harder to replicate the stack it runs on, and will slowly become an increasing recovery risk.

**Comment by JosephMcArthur** [comment]
Discussed this last week. Copying some chat:

> If we want to update to a modern version yeah I'd follow the amazon one rather than this one now. Having said that, it just makes me even less likely to bother upgrading at all. Instead I'd just do some work finding the most recent version (which may be the one we already use) that works with an acceptable version of java, then offer a repo containing an archive of them both so we can just keep running on the old version.

> looks like installing on linux at least would not be that hard, up to es 1.7.x using java 8.
> we could just make a docker or some virtual machine instance that people could run local for windows etc for the case of making it easy for people to run local.


> Just reviewing old releases, it looks like we could easily go to any 2.x or even the start of 5.x without losing the features we like - they went from 2.x to 5.x which is why it seems we're so far behind. Nothing from 6 to 8 looks better, and starts removing things we prefer. However, whatever we do, if we move from 1.x we have to do a reindex of our data which will be the main chunk of work. Or we just stay on 1.x.

**Comment by markmacgillivray** [comment]
I started this over the weekend. We reached the point of not really having a choice any more. Will discuss more on Wednesday.
