### ISSUE TITLE
Response to 10.1080/1031461X.2010.538419 depends on how you input it

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1703]
**Describe the bug**

When you put `10.1080/1031461X.2010.538419` into Shareyourpaper.org you get told something looks wrong with the DOI and the URL becomes `https://shareyourpaper.org/10.1080/1031461X.20`. Note the URL given isn't the full DOI.

Going direct to `https://shareyourpaper.org/10.1080/1031461X.2010.538419` seems fine.

**To Reproduce**

As above.

**Expected behavior**

The URL reflects the full DOI & entering 10.1080/1031461X.2010.538419 into the search box takes you to what you see at `https://shareyourpaper.org/10.1080/1031461X.2010.538419`

**Checklist (For internal use)**

* Take a breath. Bugs are okay.
* Stay clear of hangouts

Process checklist:
* Do we want a `fast` first, then a `good` fix? A `good` fix likely involves discussion, and may be slower. A fast fix means whoever is available fixes the problem as best they can immediately without too much consideration for the `good` fix.

`good`

- [ ] Discussion of solution. Remember, our intuitive fixes may be different (e.g UI centric, backend centric)

Post-fix
- [ ] How can we avoid bugs like this in future?
- [ ] How can we avoid regressions (e.g automated test)

**Comment by JosephMcArthur** [comment]
Ah, I think it's truncating based on the `10.` which looks like the start of a DOI. I presume we skip that cleaning when it's given via a URL.

**Comment by markmacgillivray** [comment]
OK, fixed on dev, have a look. Pushed to develop branch.

**Comment by JosephMcArthur** [comment]
Seeing the right response. But getting a URL of:

`https://dev.shareyourpaper.org//10.1080/1031461X.2010.538419`

note the `//`.

**Comment by JosephMcArthur** [comment]
(the // happens on any doi)

**Comment by markmacgillivray** [comment]
fixed that too
