### ISSUE TITLE
Move API to cloudflare workers

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1704]
As discussed in other docs. 

Some things to review as we go:

* Documentation
* Retiring / simplifying systems

**Comment by JosephMcArthur** [comment]
This week:

- [ ] get auth working

**Comment by JosephMcArthur** [comment]
Random thought, as we've been discussing what to cache with workers we've mentioned possibly storing exact title searches isn't all that important. I think that, for a short amount of time, it's really nice if we can. E.g while navigating around for #1717 I've noticed that it's really nice if the result loads instantly if you go back and things like that. I'm probably not explaining that well, it's hard to write but easy to show...

**Comment by markmacgillivray** [comment]
I haven't made much progress on this, I'm still at the stage of developing the fundamentals of storage layers and file handling. Discussion for today should include deciding if we're committing significant time to this over the next month or two, it's not been the priority since the first exploratory week or so of work that we did on it back in November. Some things have been tested and suspicions confirmed, but we still have a significant chunk of work to do on this.

**Comment by JosephMcArthur** [comment]
Following up with a few notes from today...

Our goal for January is to:

* finish exploring the approach to coding this up (e.g something about APIs as objects and other stuff that is foundational important)
* construct the core parts of the system (auth, logging, data management) etc using the above (rather than now, which was more for exploring how it all works rather than building a strong foundation).
* have most of our apis running on dev

Some notes on approach:

* We don't expect to change the 'meaty' parts of our APIs here, but some more 'internal' stuff may change (e.g how the find api reports what it hits)
* We're focused here on the API, and being able to start running workers in production without having to support two code bases. We don't mind so much about doing #1692, or having every aspect of "paradigm" ready now. 
* We plan to write up how it works / what it'll do as we go as a way of communicating / discussing this and having docs at the end we can turn into a site

**Comment by JosephMcArthur** [comment]
I think we've said this, but I was wondering about it today so thought I'd comment (and it isn't above).

Can we focus on /permissions, /metadata, and other systems we expect to see active development in thinking about what to prioritize refactoring into the workers format asap please?

Given its possible to do "pass through" for some endpoints (not sure what the right word is... But I'm trying to point to the idea that the workers can simply refer a request to the backend for 'normal' processing) I think that's fine for some legacy systems (e.g /requests). While I've started all the work required to refactor those thoughtfully I don't think you and I have vetted / discussed that enough to commit to building it.

Let me know if this is radically different from what you're thinking. My aim is to help reduce scope here right now and make sure you and I are aligned on what's most important given the assumption not every we want to do will be possible.

I realize the impact of this is that we might not get some of the infrastructure simplification and resilience right away, but my hunch is it would reduce the risk of needing to maintain two code bases for actively developed systems and of being "stuck" doing this and not being able to focus on feature development that's needed by customers in the near future.
