### ISSUE TITLE
blank value for `repo_name` gets saved during syp set up

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1708]
**Is your feature request related to a problem? Please describe.**

As in title

** reproduce **

* Go to: https://dev.openaccessbutton.org/shareyourpaper/setup
* Click `Deposit Preferences`
* Click `save and continue`
* Click  `Go to Menu`
* note that `Share your paper with help from the library in Scholarworks` has become `Share your paper with help from the library in `

** gif **

http://g.recordit.co/yQPaY7Ygdc.gif

**Describe the solution you'd like**

If the value for `repo_name`, and likely all of the configs, is nothing use the default.

**Comment by markmacgillivray** [comment]
OK I think that is fixed, looks like it worked to me. Any config value that is an empty string will not be used in control of what is on the page. You can close if you check and are happy.
