### ISSUE TITLE
Ingesting Crossref

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1711]
**Is your feature request related to a problem? Please describe.**

We want fast local access to Crossref to increase performance and be able to fill holes in data by inferring from that dataset. 

**Describe the solution you'd like**

Set up a daily ingest of Crossref and work back for at least a year initially, but all the way back eventually (maybe using https://www.crossref.org/blog/free-public-data-file-of-112-million-crossref-records/)

**Describe alternatives you've considered**

We may set up other sources alongside this later, but since Crossref is a lot of what we use it's a great place to get started.

**Comment by JosephMcArthur** [comment]
A script is (largely?) written. Need to set it up to run back at least as a test.

- [ ] start ingesting from the dump
- [ ] start crawl back
- [ ] start daily ingest
- [ ] check these

**Comment by markmacgillivray** [comment]
This is done on dev and work to wire it into our lookups is pretty much done too. I'll start a daily update today or tomorrow once I finish testing out a few bits and pieces for what will be best for it. Then this will be ready for live.

**Comment by markmacgillivray** [comment]
Crossref daily index has been running successfully the last couple of days and has now caught up. From tomorrow we should see it staying in sync. Once that happens I'll close this issue.

**Comment by JosephMcArthur** [comment]
Amazing! \o/

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Done
