### ISSUE TITLE
information extraction from citations not working so well

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1717]
**Describe the bug**

DOI and other info not extracted from citation on InstantILL and so wrong response given

**To Reproduce**

* go to https://www.library.ualberta.ca/services/interlibrary-loan
* input 
`Mitchell, K. (2010). Pre-Black Futures. Antipode, 41, 239–261. https://doi-org.login.ezproxy.library.ualberta.ca/10.1111/j.1467-8330.2009.00724.x`
* not we don't match anything

Using: `10.1111/j.1467-8330.2009.00724.x` we do and we get the right response.

My understanding is we should be able to extract DOI's like this. 

Using just `Mitchell, K. (2010). Pre-Black Futures. Antipode, 41, 239–261` you again get nothing. I'd have expected we should at least get things like dates etc.

**Expected behavior**

We extract DOIs when present from strings.
We extract citation info from citations.

**Checklist (For internal use)**

* Take a breath. Bugs are okay.
* Stay clear of hangouts

Process checklist:
* Do we want a `fast` first, then a `good` fix? A `good` fix likely involves discussion, and may be slower. A fast fix means whoever is available fixes the problem as best they can immediately without too much consideration for the `good` fix.

`good`

- [x] Discussion of solution. Remember, our intuitive fixes may be different (e.g UI centric, backend centric)

Post-fix
- [x] How can we avoid bugs like this in future?
- [x] How can we avoid regressions (e.g automated test)

A test for this is needed

- [x] let CJ know

**Comment by JosephMcArthur** [comment]
Note. I have added some info for the citation manually while testing another issue:

> Entering the article title didn't bring up anything. Adding additional information on the "Sorry we didn't find that" screen, the "continue" button didn't do anything.

**Comment by markmacgillivray** [comment]
On dev now this one does work. Previously the DOI in the input was causing the embed to treat the whole thing as a DOI, and if it sends it to the backend as a DOI then the backend doesn't try to parse out a citation from it. Now instead the embed will only treat it as a DOI if it has a DOI in it and also no spaces in it. So this example now gets sent by the embed as a title instead, and the backend does try to extract citation data from a title if it looks like it might contain some. With having just one input box that can potentially receive many different kinds of input, there is always the chance that some input types will clash with others and be hard to identify. But if you try this now on dev, with a refreshed lookup, you should see it working.

**Comment by JosephMcArthur** [comment]
Thanks for this, it's an improvement. 

Why, if we find a DOI do we not extract that and use that to gather metadata / do checks, etc?

**Comment by JosephMcArthur** [comment]
Also, can you commit the code for this? I just want to make sure we can deploy the fix before you go :) Even if the above isn't done quite yet.

**Comment by JosephMcArthur** [comment]
I've bumped this issue to next weeks sprint now, as the urgent part is addressed.

To close, we need tests and I'd like to consider:
> Why, if we find a DOI do we not extract that and use that to gather metadata / do checks, etc?
> Also, if we name match the DOI via a title search can be use the title (&subtitle) that crossref gives in _oab_citation?.

**Comment by JosephMcArthur** [comment]
Test added here: https://app.ghostinspector.com/tests/5fb158bb5f99e6612fea6216

**Comment by JosephMcArthur** [comment]
I would like us to review / discuss: 

> Why, if we find a DOI do we not extract that and use that to gather metadata / do checks, etc?
> Also, if we name match the DOI via a title search can be use the title (&subtitle) that crossref gives in _oab_citation?.

prior to closing. But, it's not urgent and so moving back to 101.

**Comment by JosephMcArthur** [comment]
Fixed on dev!
