### ISSUE TITLE
After pressing do another on a short title search you can't enter another search

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1726]
**Describe the bug**

**To Reproduce**

See Gif. But, shortly.

* go to https://oabutton.github.io/testing-ground/instantill/dev/default.html
* do a short title, e.g in `Pre‐Black Futures`. Complete the fields, `2010`, `antipode`.
* submit the request
* click `do another`
* try and do another request by entering anything into the search box
* you won't be allowed

**Expected behavior**

After you press do another you should always be able to input another request

**Screenshots / GIF**
http://g.recordit.co/HevCL4mTjE.gif

**Checklist (For internal use)**

* Take a breath. Bugs are okay.
* Stay clear of hangouts

Process checklist:
* Do we want a `fast` first, then a `good` fix? A `good` fix likely involves discussion, and may be slower. A fast fix means whoever is available fixes the problem as best they can immediately without too much consideration for the `good` fix.

`good`

- [ ] Discussion of solution. Remember, our intuitive fixes may be different (e.g UI centric, backend centric)

Post-fix
- [ ] How can we avoid bugs like this in future?
- [ ] How can we avoid regressions (e.g automated test)

**Comment by markmacgillivray** [comment]
This is fixed on dev, have a look and we can close this on next push to live
