### ISSUE TITLE
Short titles don't work when given direct via link

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1730]
**Describe the bug**

Short titles don't work when given direct via link

**To Reproduce**

* click https://oabutton.github.io/testing-ground/instantill/dev/default.html?title=Pre%E2%80%90Black%20Futures
* see the error

**Expected behavior**

The `id=#_oab_metadata` should be given

**Comment by markmacgillivray** [comment]
Fixed as per #1726
