### ISSUE TITLE
Integrate new permissions api into syp embed

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1733]
Follows `https://github.com/OAButton/discussion/issues/1516`

TODO:
- [ ] move endpoint to api.openaccessbutton/permissions
- [ ] move SYP to using the new keys

**Comment by JosephMcArthur** [comment]
Mark, I've updated the text above to be much more clear and really just have this be a straight swap of the keys from the old api to a new one. There are other improvements we can make but for now I'd like just to have what it does now done by the new system.

**Comment by markmacgillivray** [comment]
This is done on dev but not tested yet. I see ghost inspector is throwing some errors so I will look into that. Or go ahead and try testing if you get to it before me. It is using the new permissions and I've changed the keys, so I expect the error is either me using the wrong keys or a caching issue.

**Comment by JosephMcArthur** [comment]
If you could take a look an resolve the errors that would be fab, and then I'll take a review 'by hand' to triple check.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
SYP ghost inspector tests pass on dev now. Some have screenshot fails which I don't think are relevant, but you should be able to test it out now and let me know if any remaining issues. Most of it was just because we had never redeveloped the file part to account for the changes to permissions, because we were going to merge that into deposit but haven't done that yet. SInce SYP ends up depositing, they were failing. So I've updated the file part now, but we still need to schedule some time to update deposit and merge the file stuff in there properly. That can probably be done as part of CF rewrites, but just mentioning it just in case. A couple other issues were because we now provide the embargo_end when it is in the past but we didn't before, so I had to add some catches on deposit to check when the end date is, not just if it exists.

**Comment by JosephMcArthur** [comment]
Grand!

At least for this: https://app.ghostinspector.com/tests/5f23dcc15e12c014aeaefb71 the screenshot is showing that some data we'd expect in the emails isn't present so it would be good if you could take a look at that.

What needs to happen for you to be able to handle the files into deposit work as part of CF rewrites? That makes sense to me, and just want to make sure nothing is in the way.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Isn't that just due to the email template config though? I could do that too, but assuming usually you do the templates because it relates to what you want to show users, are all these values going to be relevant to the new data?

**Comment by JosephMcArthur** [comment]
Yes, they'll all be relevant. If you wouldn't mind doing one or two fields at least that would help make sure I know what to do and that it is actually that simple :D. But yes, if you don't have time, I'm happy to do that. If you do have time, I'd appreciate it. Swamped atm.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
I updated the templates on dev and re-ran the tests with the screenshot issues and they pass now. You may still want to have a look at the deposit email templates to see if you want any changes.

There is one SYP test failing now:

https://app.ghostinspector.com/tests/5f22ed7fbfb7c24532f42bd4

It expects the oab_archivable area to be visible, but the result for that DOI includes a permissions_contact email address, and when that is present we currently have the embed coded to show the _oab_permission_required section. Is the test wrong or do you want something changed there?

**Comment by JosephMcArthur** [comment]
On that test we expect the OA policy (set by the ROR in the embed) to override the normal policy and show the ability to deposit.

The API seems to be returning the right answer, I can see `can_archive: true` as the best permission. However, it's possible that in this we've choosen to include the `permissions_contant` address in the response even when it's not longer that important as it's been overridden. 

I think it would be best to show `_oab_permission_required` only when can archive is `false` rather than when `permissions_contact` has a value. I'm fairly sure that template has logic that will adapt to give a good response after that regardless of if an email is available in `permissions_contact`.

Curious what you think though.

**Comment by markmacgillivray** [comment]
OK done, test now passes on dev.

**Comment by JosephMcArthur** [comment]
Another case where this passes but many others fail. Can you keep an eye out for that?

It looks like any using the same doi as the test above now return the same response (even if they don't have the ror applied). A caching issue maybe?

**Comment by markmacgillivray** [comment]
OK, these are all sorted now.

**Comment by JosephMcArthur** [comment]
Cracking, we're all green. Anything else you think need done here?

**Comment by JosephMcArthur** [comment]
Hmm, have you changed something? 

https://app.ghostinspector.com/tests/5f22ed7fbfb7c24532f42bd4 is failing again. 

I could have sworn it was all good yesterday and that I confirmed manually.

**Comment by markmacgillivray** [comment]
I was working on the unexpected caching of RORs and then had to make a change to make sure they pass through on permissions checks, that is working fine now.
