### ISSUE TITLE
apostrophe throws off InstantILL result?

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1740]
I slightly ran out of time to full walk all this through. But, it seems something isn't going quite right here.

**Describe the bug**

Alberta ran the following title:

> YOUNG CHILDREN'S COLLABORATION ON THE COMPUTER WITH FRIENDS AND ACQUAINTANCES

Completed the form, and got:

![image](https://user-images.githubusercontent.com/4953703/99693339-27198b80-2a83-11eb-8fe3-0ba7e4386c94.png)

Presumably, the apostrophe is throwing off something. That's the issue they're concerned about.

Note. The full citation is as follows:

> Yi-Jeng Chen. (2016). Young Children's Collaboration on the Computer with Friends and Acquaintances. Journal of Educational Technology & Society, 19(1), 158-170. Retrieved November 19, 2020, from http://www.jstor.org/stable/jeductechsoci.19.1.158 

In going to reproduce this I think other things may be going on. 

**To Reproduce**

Enter the title into:

* https://oabutton.github.io/testing-ground/instantill/dev/default.html
* https://oabutton.github.io/testing-ground/instantill/dev/not-default.html

In either case, you can see the metadata passed to the form / email. However, I wasn't able to replicate the sort of... cut off issue. They say their form works fine with `'`, but I haven't dug deeply. 

Is it possible *their* system isn't handling the URL encoding properly? We've got access from them if it helps, which I sent separately. 

**Expected behavior**

So... I expected this to take me the wrong form, where I'd fill it out, and it would submit nicely. That didn't happen.

1. I expected it to match in bing (as I presume bing picks up jstor stuff), even if it doesn't have a DOI. That hope was dashed... as a title search in bing returns no matches: `https://academic.microsoft.com/search?q=Young%20Children%27s%20Collaboration%20on%20the%20Computer%20with%20Friends%20and%20Acquaintances&f=&orderBy=0&skip=0&take=10`. This is likely a bing issue, as it is in bing, you just need to search by author and year.
`https://academic.microsoft.com/search?q=Yi-Jeng%20Chen&f=&eyl=Y%3C%3D2016&syl=Y%3E%3D2016&orderBy=0`. I expect a good fix for this is ingesting MAG.
2. I hoped we would get some metadata automatically when searching by citation, given the year is in there as is a clear 'journal of...', pages (###-###), etc. I keep having a sense that our information extraction from citations doesn't really do what I expect, and so maybe you and I reviewing the code together would make sense so I have my expectations right.
3. At first, you should get the wrong article form as there isn't enough metadata found automatically. But, that didn't seem to happen for me. Instead, when I submitted the loan I saw some odd behaviour where it wouldn't let me submit, presumably as it didn't have all the required info after the missed form. Is it possible that what looks like it might be an encoding issue is actually something to do we us mixing up the data before sending it?
4. When I actually got it to submit, I got a link like this `https://dev.rscvd.org/paper?sid=InstantILL&atitle=YOUNG%20CHILDREN%27S%20COLLABORATION%20ON%20THE%20COMPUTER%20WITH%20FRIENDS%20AND%20ACQUAINTANCES&rft.year=2016&title=Antipode&notes=Subscription%20check%20done,%20found%20nothing.%20OA%20availability%20check%20done,%20found%20nothing.` So, things got passed fine. (note the incorrect citation data was added by me manually).

3&4 are probably the parts worth focusing on here. But again, I'm sorry, I haven't had a chance to chase these down to perfect clarity. If you could take a peak and see if anything is obvious to you, that would be great.

**Checklist (For internal use)**

* Take a breath. Bugs are okay.
* Stay clear of hangouts

Process checklist:
* Do we want a `fast` first, then a `good` fix? A `good` fix likely involves discussion, and may be slower. A fast fix means whoever is available fixes the problem as best they can immediately without too much consideration for the `good` fix.

`good`

- [ ] Discussion of solution. Remember, our intuitive fixes may be different (e.g UI centric, backend centric)

Post-fix
- [ ] How can we avoid bugs like this in future?
- [ ] How can we avoid regressions (e.g automated test)

**Comment by JosephMcArthur** [comment]
This one also gets cut off at the apostrophe, fwiw.

> Margaret Hostetler. The Value of Impoliteness in Octavia Butler’s Xenogenesis Trilogy. International Journal of Applied Linguistics and English Literature. 2019;8(5):61-71. doi:10.7575/aiac.ijalel.v.8n.5p.61

They flagged that it wasn't found OA for them, even though it's in the DOAJ too. That's fixed on dev.

**Comment by markmacgillivray** [comment]
citation extraction improvements, and checking we handle the apostrophe OK ourselves, are done. Final step is seeing where it disappears once passed to their system. That step probably to be delayed until after crossref work (separate discussion ongoing).

**Comment by JosephMcArthur** [comment]
See my email. I think we're likely blocked on exploring the connection with their form until we can get a login for the system that actually mediates the connection.

**Comment by JosephMcArthur** [comment]
We're unblocked now : )

**Comment by JosephMcArthur** [comment]
- [ ] where did / does https://www.ds.unipi.gr/et&s/journals/19_1/14.pdf come from (find or sub?)

**Comment by markmacgillivray** [comment]
This can be closed once we push to live, I haven't done that yet because done a bunch of fixes to other open issues in this milestone and also in the next one - if you have time for a quick look over, let me know if this is all good and then we can push the whole lot to live and close all the bugs.
