### ISSUE TITLE
rider deposits not going into their zenodo community

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1743]
See:

> Share Your Paper- Zenodo Issue

I'm pretty sure deposit to certain communities works, as we do it for: 

https://shareyourpaper.org/journals/icjr
https://zenodo.org/communities/icjr?page=1&size=20

So would be good to know what's happening here.

Their page is at: https://guides.rider.edu/syp

**Comment by JosephMcArthur** [comment]
It seems likely this was due to a lack of `uid` in the embed, even though the owner email was present. Can we consider if that is required, or if owner email alone could be used.

**Comment by markmacgillivray** [comment]
This has been changed on dev to allow deposits with no UID provided. Give it a go and let me know if there are still any problems. It looks to me like it does what it should, looks for an owner email in a provided config or falls back to a UID as it used to.

**Comment by markmacgillivray** [comment]
See #1722
