### ISSUE TITLE
rider not getting deposit emails

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1744]
See:

> Share Your Paper- Zenodo Issue

Their page is at: https://guides.rider.edu/syp

**Comment by JosephMcArthur** [comment]
It seems likely this was due to a lack of `uid` in the embed, even though the owner email was present. Can we consider if that is required, or if owner email alone could be used.

**Comment by markmacgillivray** [comment]
Fixed as per #1743
