### ISSUE TITLE
Get MAG working

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1755]
Stub. Discussed elsewhere.

**Comment by markmacgillivray** [comment]
Still to be completed, not much progress since before christmas.

**Comment by JosephMcArthur** [comment]
Work needed:

- [ ] Getting the MAG data we have running
- [ ] Decide how to actually keep it up to date

**Comment by JosephMcArthur** [comment]
You asked for some ways we might use MAG...

* When users do a search on InstantILL, we might use it to:
  * match and provide the required metadata on papers without DOIs (and do so much faster)
  * enrich metadata passed with requests for papers with dois

* For SYP...
  * Use the extra abstracts, affiliation info, and other metadata to enhance our deposit records
  * Match the affiliations to RORs, and use those apply permissions in the permissions system. 

Is that what you need to know?

**Comment by markmacgillivray** [comment]
When finding RORs, the RORs relate to the affiliation of the authors. So a given paper can have more than one ROR. Should all RORs be used to check for permissions, or only the first one? MAG attempts to indicate which author is first author.

I have more feedback about this but not time to finish just now, will update you more next week :)

**Comment by JosephMcArthur** [comment]
all

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
OK, fuller review:

Papers: ~250m
Papers with DOI: ~93m
Papers related to Journal: ~90m
Authors: ~265m
Journals: ~50k
Journals with ISSN: ~37k
Affiliations: ~25k (they look like mostly or all institutions)
Affiliations with GRID ID: ~19k
Affiliations with ROR: 0

MAG has been hooked up on dev to our find system. It gets searched for DOI or title if we have either. We now don't search Bing unless we've already searched MAG and found nothing - we may want to think about if this is worthwhile long term, if something is not in MAG our Bing searches may just be always unsuccessful, thus a cost for no gain. We can review in a few months.

MAG does give us some metadata - not more than we could get before, but it's a good useful additional source. Especially for title searches - we have 250m papers, only 93m have DOIs, so about 150m we can find by title search. However, note that many of these may not be in English; also, there are only about 90m papers in MAG that are related to a journal, so a lot of the rest could be books, etc. Would you be happy for us to return anything we find in MAG, or only those related to a journal? For example we only return journal-article types from crossref.

I haven't yet loaded MAG abstracts. The abstracts are not in the same file as the other paper metadata and are of course quite big compared to other metadata fields. There are abstracts for about 140m papers. Also technically we don't have the original abstracts - MAG don't publish them. We have a copy of their inverted index - this is an internal database thing that is the count of all words relative to a given ID, for text searching. Inverted indexes can also contain word location which the MAG ones do, so we can rebuild the original abstract structure from the index - but we probably won't have all the punctuation, just a stream of words. Storing abstracts will take probably another day to load, and around another 300gb so I would need to add more disk to the index again first. Note also that providing abstracts as metadata for instantill/deposit etc may cause issues as we pass the metadata as URL query params. There is a maximum length to URLs, so a long abstract may end up getting chopped or causing an error anyway. Other than instantill/deposit metadata, I don't think there is any other use for abstracts in our system yet.

As MAG is connected to find, it is now also used by permissions. This is working well, and we can now get more author metadata via MAG, such as author affiliations. MAG author affiliations have GRID IDs and we can look those up in Wikidata to switch them for RORs. Then we can lookup those RORs in our permissions data tables - this has been shown to work already. There are about 95k RORs and 97k GRIDs in Wikidata, so we should keep Wikidata up to date to keep track of those. Or we can import all of ROR, which we think also contains the related GRIDs - note though, it does mean that just MAG on its own does not solve our problem here.

While crossref sometimes has author affiliation data it rarely has IDs of any kind, and we have not yet bothered doing institution title searches against wikidata to find related RORs. We could do this at a later stage, although it's likely MAG has better affiliation coverage than crossref anyway, so may not be worthwhile.

I have not loaded the extended attributes for MAG records, but I have checked through them. Unfortunately none of the key metadata values or the extended attributes appear to tell us anything about funders. Also the abstracts look like just the abstract string - not things like thanks, funder recognition, etc. So I don't see any evidence of there being funder data in MAG. It is possible some of the affiliations are funders, but so far it looks like they are author institutions (which may ALSO be funders, but I've not seen a way to tell if that is the case).

If you want to review the data schema here:
https://docs.microsoft.com/en-us/academic-services/graph/reference-data-schema

And below the schema diagram there is some info on the extended attributes available, and links to FAQs. I've already gone through these though, and there is nothing about funders.

We have no automated way yet to update this data. We are waiting to see if the data dumps we get via azure contain incremental updates or not - suspect not. Reloading from scratch every time would be too slow - it takes about about four days. We can of course speed it up, but only if we pay more on hardware, maybe double. We may be able to search through and only upload new records though. Also we have no way to know when a new dump is put into azure yet - we may get an email when that happens, but for now just checking manually. We can probably set up a poller to check the azure page daily or something, and let us know when there are new files.

As we saw on the first go-round, it costs about $60 to get this "open, free" resource via Azure. That is the cost of it landing there, then us downloading it, then deleting it so we don't build up even more Azure storage costs. Azure is the only way to get the full data. The full MAG is quite different from the OAG, and OAG only updates once a year or two. We don't know yet how often MAG updates - they say every few weeks, but the one we just got was from 21st December but the README only listed updates up to September.

The full MAG index, once loaded into our system, is about 500gb without abstracts. Abstracts are another 300gb or so. Each 100gb costs another $10 of disk space per month. It is unlikely to grow very fast though.

**Comment by JosephMcArthur** [comment]
Thanks for this Mark. A couple of questions:

* What's your plan for abstracts? Want to schedule this as future work? That's fine with me.
* Anything else quick we can do to make use of this data now?
* Anything you want to do before we close this?

**Comment by markmacgillivray** [comment]
My plan for abstracts is "what's YOUR plan for abstracts"? :) I can do the loading of them as described above, was just wanting to update you to check if you're happy with that extra work for the return we get from it. If so just let me know and I will do it. It can during this week while I do other stuff, but may cause slight delays keeping an eye on things, reviewing results, etc.

Nothing else right now comes to mind, I'm sure interesting things will pop up though.

Nothing else I want to do before closing this.

**Comment by JosephMcArthur** [comment]
Given this work took a little longer than expected, and we want to have workers done asap, I'd say let's leave abstracts for now if it'll take a day.

**Comment by markmacgillivray** [comment]
OK. It's easy to come back to later and not as useful as the main metadata. Also we'll come back to MAG some time next month anyway once we see what happens with their next update. So can review it all next month when that happens, and yes for now can focus on CF stuff.

**Comment by JosephMcArthur** [comment]
Did we end up getting MAG into production?

**Comment by markmacgillivray** [comment]
Yes but then I disabled it on both due to performance issues. It'll prob stay that way until ES is upgraded (I've made an issue for that and started it already, more to discuss on Wednesday)

**Comment by JosephMcArthur** [comment]
Gotcha, no problem.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
Can this be closed @markmacgillivray ?
