### ISSUE TITLE
Title searches go straight to results even when they've not matched

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1762]
**Describe the bug**

See issue title

**To Reproduce**

See https://app.ghostinspector.com/tests/5fbb7eb89b2cf775c48a0263

**Expected behavior**

When we don't find a match straight away we send the user to the wrong form to give us enough info to make an ILL.

**Screenshots / GIF**
Add to help explain your problem.

**Comment by markmacgillivray** [comment]
OK, changed, passes now on dev

**Comment by JosephMcArthur** [comment]
Yes, but it has caused a bunch of other tests to fail. 

It's so fast to go to the page that I'm presuming it's not even trying to find info, just defaulting to the form like we do when the title is too short (so, we think running the search is pointless). In this case, we should still process the search, but if it doesn't bring back metadata we need then go right to the wrong form.

**Comment by markmacgillivray** [comment]
OK, I think this is sorted now too, have a look
