### ISSUE TITLE
Provide stats for SYP embeds

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1769]
We currently provide per-embed stats for InstantILL. It would be good to do the same for SYP.

Those stats should include:

* UID
* date of first use
* embedded URLs
* the total (now) for each deposit type (e.g zenodo, redeposit)

This only needs to be done via the API. I’m using that to ingest figures into a sheet.

Mark, can you let me know if this is a big job? Otherwise it would be great to get done this month.

**Comment by markmacgillivray** [comment]
OK if you go to the bottom of the /stats endpoint you will find a new key called syp. In that object each key is a user ID, and each points to an object containing the date of first use, a list of any embed URL locations, and the count for each deposit type, if any.

**Comment by JosephMcArthur** [comment]
Any chance of being able to get total 'searches', i.e any entry of a DOI in that embed (even if it doesn't result in a deposit?)

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
OK added
