### ISSUE TITLE
Permissions not picking up ISSNs as expected

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1773]
**Describe the bug**

For `https://api.openaccessbutton.org/permissions?doi=10.1056/NEJMms1900864` we only find one ISSN. However, there are two ISSNs given at the DOI level in both Crossref & Unpaywall. We should be finding these.

This is meaning we give the wrong answer in this case.

**To Reproduce**

See:
* http://api.crossref.org/works/10.1056/NEJMms1900864
* http://api.unpaywall.org/v2/10.1056/NEJMms1900864?email=joe@openaccessbutton.org
* https://api.openaccessbutton.org/permissions?doi=10.1056/NEJMms1900864 or https://api.openaccessbutton.org/metadata?doi=10.1056/NEJMms1900864

**Expected behavior**

We get two ISSNs.

**Comment by markmacgillivray** [comment]
Fixed on dev, see:

https://dev.api.cottagelabs.com/service/oab/permissions?doi=10.1056/NEJMms1900864
