### ISSUE TITLE
Feb 2nd downtime not caught by uptimerobot

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1784]
**Is your feature request related to a problem? Please describe.**

Today we had 4 minutes of down time recorded by updown, and confirmed by me (looking directly at the API) and cloudflare. However, status.openaccessbutton.org doesn't reflect this as it should. The good news it, it seems the system recovered on it's own (or, Mark did it and didn't tell me).

Given uptime robot powers the status page and I believe internal systems that are meant to have our servers recover faster, it's important it accurately records downtime.

**Describe the solution you'd like**

I'd like to understand why it didn't spot the downtime, and if we can do anything to fix that.

**Describe alternatives you've considered**

As we rebuild systems on CF workers, perhaps we might change systems to use updown rather than uptimerobot.

**Comment by JosephMcArthur** [comment]
Screenshot of the confirmation, in case it's helpful

![Screenshot_20210202-111226](https://user-images.githubusercontent.com/4953703/106597723-b8f74780-654e-11eb-826e-0fb7e43ce7ba.png)

**Comment by markmacgillivray** [comment]
I don't know about the status page, but it definitely did work. I got the notifications from uptimerobot about system errors and fixed it at the time. Maybe it's too short a duration to show up on the status page?

**Comment by markmacgillivray** [comment]
status page shows 99.997% on the API. That's probably representative of the downtime. The site was not down, neither was the blog, so they're accurate at 100%

**Comment by markmacgillivray** [comment]
Also the whole API was not totally down, just queries to the index were slow. So uptimerobot status page may not fully indicate that, as it could still have been getting pingbacks from the main API page during that time. But as mentioned above, the warnings did trigger and I fixed at the time.

**Comment by JosephMcArthur** [comment]
First off, thanks for fixing it so fast :)

Second, that leaves me more confused tbh. I went into the uptimerobot backend and it doesn't show any issues ( today , the 99.997% is from previous downtime, and they'll display downtime even if only for a minute so it's not that) and I'm subscribed for alerts. Are the alerts you got triggered by uptimerobot or some other system?

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
The OAB API itself never went down it just went slow. It was still able to respond, and for some parts would have continued to respond completely fine. The index itself went slow, slow enough for uptimerobot to pick that up. It's not an OAB monitor, it's a general index monitor, and that alerted me. You probably don't get those ones.

**Comment by markmacgillivray** [comment]
Do you see all the monitors in the backend? Can't remember what you have access to. I can see small downtimes on Noddy API cluster health and Noddy API Index

**Comment by JosephMcArthur** [comment]
Ah, okay. Yes I have access but I indeed don't get notified / know to look at the noddy status ones. I've set up notifications for myself on those now.

So, probably updown is being more aggressive than uptimerobot in classifying slowdowns as "downtime". And, I can see that your noddy alerts fire not based not only on downtime (like updown) but also system reported status changes, so those cause the degradation that our OAB downtime monitor didn't (because it wasn't totally down).

I understand now. Thanks for walking me through it.

The next question is, why was the service degraded and does it matter right now as we move to CFW? Anything you'd like to get done to prevent this in future?

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
It wasn't entirely unexpected, and related to why I've already gone ahead with the index stuff. We've just got too much stuff now for the index to keep up with when it's also trying to update. There was still a question around whether it was MAG or crossref that was causing more problem, I think now it's MAG that put us over the limit the system could handle, but when it's just sitting there responding to queries it's fine - however when the crossref tries to daily import at the same time, that potentially cause slowdowns. So there's nothing else new we'd need to get done, the necessities are already in progress. We'll discuss tomorrow - are we still meeting tomorrow?

**Comment by JosephMcArthur** [comment]
Excellent, I guessed as much but thought I'd ask.

Yes we are meeting.

I'm happy to close this if you are. LMK.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
yeah can close
