### ISSUE TITLE
Linkouts on SPARC cancellations tracker broken

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1786]
**Is your feature request related to a problem? Please describe.**

On `https://bigdeal.sparcopen.org/cancellations` the linkouts under `Institution/Consortium` are broken. 

**Describe the solution you'd like**

The code is here: https://github.com/sparcopen/cancellations and I'm pretty sure we just need to [tweak the javascript in this file](https://github.com/sparcopen/cancellations/blob/main/cancellations.js) that generates the links.

The raw data is [here](https://docs.google.com/spreadsheets/d/1xHQ4cw3zLndjlkT5cGrOmK5cS2Q4jUXN-fQVV_aQhaw/edit#gid=0).

@markmacgillivray any chance either of you could take a run at this early next week? I'm hoping it's a very easy fix.

**Comment by markmacgillivray** [comment]
I just committed a change to that direct in the github UI, into main. No idea what is deploying that if anything, or if you wanted it in main, but hopefully yes :)
