### ISSUE TITLE
InstantILL 'wrong' hits not being recorded in stats

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1791]
It seems around October last year we stopped recording when users hit "This is not the article I searched" in stats.

Would be good to get this working again. I suspect it's a caching problem.

To reiterate, the expected behaviour is that:

* User hits `This is not the article I searched`
* A ping records this (for that embed)
* A total of how many times this has happened can be seen in stats.

Currently, the number doesn't go up.

**Comment by JosephMcArthur** [comment]
is this live? If yes I can let some folks know.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
yes
