### ISSUE TITLE
Can't setup subscription url in InstantILL set up

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1792]
**Describe the bug**
Above

**To Reproduce**
1. Go to `https://dev.openaccessbutton.org/instantill/setup#subscription`
2. Set up a fake link resolver
3. Hit save & continue
4. To go `https://dev.openaccessbutton.org/instantill/setup#embed` 
5. You won't see the detailed you entered

**Expected behavior**

You should see your info in the embed code

**Comment by JosephMcArthur** [comment]
@markmacgillivray could you look at this asap please? Got a major institution who needs this fixed.

**Comment by JosephMcArthur** [comment]
@markmacgillivray I tried to set this up by hand to see off the users issue, but I hit issues again.

I set up a page in our testing ground too look at this:

`https://github.com/OAButton/testing-ground/blob/master/instantill/live/udel.html`

What's there is the embed from their current page:

`https://library.udel.edu/static/test.html`

Plus, the relavent subscription keys from:

`https://oabutton.github.io/testing-ground/instantill/dev/iupui.html`

I subbed in IUPUIs link resolver for udels, which is:

`https://cx2ef4jw8j.search.serialssolutions.com`

They have us a test DOI which should be successful, but I haven't been able to make it work:

`10.7755/FB.118.4.4`

It looks like in the `lookup` key, we're not passing the say sort of info we do for UDEL as we do for IUPUI... but I can't tell why.

i.e

1. https://oabutton.github.io/testing-ground/instantill/dev/iupui.html?doi=10.7755/FB.118.4.4
2. https://oabutton.github.io/testing-ground/instantill/live/udel?doi=10.7755/FB.118.4.4

Looking at the find request, you see that for 1 you get


```
"ill": {
    "terms": "https://url.org/cat",
    "openurl": "https://ill.ulib.iupui.edu/ILLiad/IUP/illiad.dll?Action=10&Form=30&sid=OABILL&genre=InstantILL&sid=InstantILL&rft_id=10.7755%2FFB.118.4.4&atitle=Distribution%2C%20relative%20abundance%2C%20and%20reproductive%20output%20of%20spawning%20female%20blue%20crab%20(Callinectes%20sapidus)%20in%20offshore%20waters%20of%20the%20Gulf%20of%20Mexico&crossref_type=journal-article&aulast=Kemberling%2C%20Adam%20A.%2C%20Darnell%2C%20M.%20Zachary&title=Fishery%20Bulletin&issue=4&volume=118&pages=346-358&issn=0090-0656&publisher=NMFS%20Publications%20Office&rft.year=2020&date=2020-12-01&url=https%3A%2F%2Fspo.nmfs.noaa.gov%2Fsites%2Fdefault%2Ffiles%2Fpdf-content%2Ffish-bull%2Fkemberling.pdf&",
    "subscription": {
      "findings": {
        "serials": "https://spo.nmfs.noaa.gov/content/fishery-bulletin/distribution-relative-abundance-and-reproductive-output-spawning-female"
      },
      "lookups": [
        "http://rx8kl6yf4x.openurl.xml.serialssolutions.com/openurlxml?version=1.0&genre=article&&Action=10&Form=30&&sid=InstantILL&rft_id=10.7755%2FFB.118.4.4&atitle=Distribution%2C%20relative%20abundance%2C%20and%20reproductive%20output%20of%20spawning%20female%20blue%20crab%20(Callinectes%20sapidus)%20in%20offshore%20waters%20of%20the%20Gulf%20of%20Mexico&crossref_type=journal-article&aulast=Kemberling%2C%20Adam%20A.%2C%20Darnell%2C%20M.%20Zachary&title=Fishery%20Bulletin&issue=4&volume=118&pages=346-358&issn=0090-0656&publisher=NMFS%20Publications%20Office&rft.year=2020&date=2020-12-01&url=https%3A%2F%2Fspo.nmfs.noaa.gov%2Fsites%2Fdefault%2Ffiles%2Fpdf-content%2Ffish-bull%2Fkemberling.pdf&"
      ],
```

Look ups is as expected. However, for 2, we do:

```
  "ill": {
    "openurl": "https://login.udel.idm.oclc.org/login?url=https://udel.illiad.oclc.org/illiad/illremoteauth/illiad.dll?Action=10&Form=30&sid=InstantILL&rft_id=10.7755%2FFB.118.4.4&atitle=Distribution%2C%20relative%20abundance%2C%20and%20reproductive%20output%20of%20spawning%20female%20blue%20crab%20(Callinectes%20sapidus)%20in%20offshore%20waters%20of%20the%20Gulf%20of%20Mexico&crossref_type=journal-article&aulast=Kemberling%2C%20Adam%20A.%2C%20Darnell%2C%20M.%20Zachary&title=Fishery%20Bulletin&issue=4&volume=118&pages=346-358&issn=0090-0656&publisher=NMFS%20Publications%20Office&rft.year=2020&date=2020-12-01&url=https%3A%2F%2Fspo.nmfs.noaa.gov%2Fsites%2Fdefault%2Ffiles%2Fpdf-content%2Ffish-bull%2Fkemberling.pdf&",
    "subscription": {
      "findings": {},
      "lookups": [
        "http://cx2ef4jw8j.openurl.xml.serialssolutions.com/openurlxml?version=1.0&genre=article&&url=https://udel.illiad.oclc.org/illiad/illremoteauth/illiad.dll"
      ],
```

The lookup looks off, and that's likely we don't get the correct answer.

Manually making a more correct lookup (by splicing query params we give on one into two) gives a reasonable looking return:

`http://cx2ef4jw8j.openurl.xml.serialssolutions.com/openurlxml?version=1.0&genre=article&&Action=10&Form=30&&sid=InstantILL&rft_id=10.7755%2FFB.118.4.4&atitle=Distribution%2C%20relative%20abundance%2C%20and%20reproductive%20output%20of%20spawning%20female%20blue%20crab%20(Callinectes%20sapidus)%20in%20offshore%20waters%20of%20the%20Gulf%20of%20Mexico&crossref_type=journal-article&aulast=Kemberling%2C%20Adam%20A.%2C%20Darnell%2C%20M.%20Zachary&title=Fishery%20Bulletin&issue=4&volume=118&pages=346-358&issn=0090-0656&publisher=NMFS%20Publications%20Office&rft.year=2020&date=2020-12-01&url=https%3A%2F%2Fspo.nmfs.noaa.gov%2Fsites%2Fdefault%2Ffiles%2Fpdf-content%2Ffish-bull%2Fkemberling.pdf&`

So, hopefully if we can fix the query we're in business.

**Comment by JosephMcArthur** [comment]
@markmacgillivray... Sigh, pressed enter too soon. Can you take a look at this on your Friday?

**Comment by markmacgillivray** [comment]
Ok this should be as you expect now, I've tried on instantill setup page on OAB dev site on my account and it works if I put in the udel link you have above.

**Comment by JosephMcArthur** [comment]
I see the lookups issue mentioned in my previous comment still. Any chance you can look at that too?

**Comment by markmacgillivray** [comment]
Not sure what you mean. Have you tried resetting the config and re-running it? I've done it with a fresh reset of config on the instantill setup page on my account, and after I change it and run the preview, the "lookups" value in the find response is this:

http://cx2ef4jw8j.openurl.xml.serialssolutions.com/openurlxml?version=1.0&genre=article&&sid=InstantILL&rft_id=10.1126%2Fscitranslmed.3001922&atitle=Uroporphyrinogen%20Decarboxylase%20Is%20a%20Radiosensitizing%20Target%20for%20Head%20and%20Neck%20Cancer&crossref_type=journal-article&aulast=Ito%2C%20E.%2C%20Yue%2C%20S.%2C%20Moriyama%2C%20E.%20H.%2C%20Hui%2C%20A.%20B.%2C%20Kim%2C%20I.%2C%20Shi%2C%20W.%2C%20Alajez%2C%20N.%20M.%2C%20Bhogal%2C%20N.%2C%20Li%2C%20G.%2C%20Datti%2C%20A.%2C%20Schimmer%2C%20A.%20D.%2C%20Wilson%2C%20B.%20C.%2C%20Liu%2C%20P.%20P.%2C%20Durocher%2C%20D.%2C%20Neel%2C%20B.%20G.%2C%20O'Sullivan%2C%20B.%2C%20Cummings%2C%20B.%2C%20Bristow%2C%20R.%2C%20Wrana%2C%20J.%2C%20Liu%2C%20F.-F.&title=Science%20Translational%20Medicine&issue=67&volume=3&pages=67ra7-67ra7&issn=1946-6234&publisher=American%20Association%20for%20the%20Advancement%20of%20Science&rft.year=2011&date=2011-01-01&pmid=21270338&url=https%3A%2F%2Fdoi.org%2F10.1126%2Fscitranslmed.3001922&

Which looks like it is probably correct to me, as it also gives a found serials URL:

https://library.udel.edu/static/proxy.php?https://stm.sciencemag.org/lookup/doi/10.1126/scitranslmed.3001922"

**Comment by JosephMcArthur** [comment]
Yes, I changed the embed code on my page and looked again. Take a look at https://github.com/OAButton/discussion/issues/1792#issuecomment-806640563 and let me know if you see what I see.
