### ISSUE TITLE
Integrate InstantILL with Alma / Primo Link Resolver

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1793]
**Is your feature request related to a problem? Please describe.**

Alma / Primo is a popular library management system and many people would like InstantILL to be able to work with it.

We need to be able to find out if a library does / doesn't subscribe to something, provide a link to full text, and enable the library to set this up (ideally without our intervention).

Montana State is working with us on this.

**Describe the solution you'd like**

I've been doing some research here already to flesh this out.

We can't use the link resolver directly, however, it is easy enough to find an xml path via another system.

The first working URL I got looked like:

`https://trails-msu.userservices.exlibrisgroup.com/view/uresolver/01TRAILS_MSU/openurl?ID=doi:10.1515%2Fcerce-2017-0005&genre=article&atitle=USING%20GELATIN%20TO%20PRODUCE%20HONEY%20JELLY%20FROM%20CITRUS,%20CLOVER%20AND%20COTTON%20LIQUID%20HONEY.&title=Agronomical%20Research%20in%20Moldavia%20%2F%20Cercetari%20Agronomice%20%C3%AEn%20Moldova&issn=03795837&isbn=&volume=50&issue=1&date=20170301&au=ELHAMID,%20A.%20M.%20ABD&spage=57&pages=57-64&sid=InstantILL&vid=01TRAILS_MSU&institution=01TRAILS_MSU&url_ctx_val=&url_ctx_fmt=null&isSerivcesPage=true&svc_dat=CTO&response_type=xml`

There are a lot of keys there, but I think it can be shortened to:

`https://trails-msu.userservices.exlibrisgroup.com/view/uresolver/01TRAILS_MSU/openurl?svc_dat=CTO&response_type=xml&sid=InstantILL&ID=doi:10.1108%2FNFS-09-2019-0293&genre=article&atitle=Impact%20of%20processing%20and%20packaging%20on%20the%20quality%20of%20murici%20jelly%20%5BByrsonima%20crassifolia%20(L.)%20rich%5D%20during%20storage.&title=Nutrition%20&%20Food%20Science&issn=00346659&volume=50&issue=5&date=20200901&au=Da%20Cunha,%20Mariana%20Crivelari&spage=871&pages=871-883`

That's formed of:
* a `base url`, in this case `https://trails-msu.userservices.exlibrisgroup.com/view/uresolver/01TRAILS_MSU/openurl`. 
* an `sid`, which we'd want to set to `InstantILL`
* some special modifiers `&svc_dat=CTO&response_type=xml` from https://developers.exlibrisgroup.com/alma/integrations/discovery/xml-openurl/. These seem fixed.
* article metadata passed in what looks like the usual openurl format. I don't know exactly what is required, just a doi isn't enough. Likely... passing as much bibliographic metadata as we can as usual is a good thing.

I think making these should be quite straightforward. On the set up page / system we'd need to have a new link resolver option for alma / primo, a place to put that base URL, and configure the system to add the modifiers and use the right params.

Once we're generating queries:

* `full_text_indicator` will tell us if full text is / isn't available. There seem to be many responses returned, likely if any is true we can say true.
* `resolution_url` should give us a URL to point the user to. Likely we should use the first `resolution_url` where `full_text_indicator` is true.

These URLs can be passed into our existing templates for full text.

**Describe alternatives you've considered**

None

**Internal Use**

- [ ] Backend plan
- [X] Frontend plan
- [ ] How will we test it?

We'll hook up tests via testing ground and ghost.

- [ ] Estimate
- [ ] Do we know people really want this?

Yes, many requests for this.

##### No Access:
* https://msu-primo.hosted.exlibrisgroup.com/primo-explore/openurl?ID=doi:10.12187%2F2020.04.003&genre=article&atitle=Development%20of%20grape%20jelly%20and%20optimization%20of%20its%20technical%20formula.&title=Journal%20of%20Light%20Industry&issn=20961553&isbn=&volume=35&issue=4&date=20200701&au=GE%20Zhenzhen&spage=16&pages=16-22&sid=EBSCO:Academic%20Search%20Complete:145479374&vid=01TRAILS_MSU&institution=01TRAILS_MSU&url_ctx_val=&url_ctx_fmt=null&isSerivcesPage=true
* https://msu-primo.hosted.exlibrisgroup.com/primo-explore/openurl?genre=article&atitle=Cooking%20Up%20Quince.&title=Early%20American%20Life&issn=15342042&isbn=&volume=51&issue=5&date=20200901&au=ROSS,%20WINFIELD&spage=58&pages=58-63&sid=EBSCO:Academic%20Search%20Complete:145921283&vid=01TRAILS_MSU&institution=01TRAILS_MSU&url_ctx_val=&url_ctx_fmt=null&isSerivcesPage=true
* https://msu-primo.hosted.exlibrisgroup.com/primo-explore/openurl?ID=doi:10.1063%2F1.5066852&genre=article&atitle=Development%20of%20calibration%20models%20to%20predict%20texture%20and%20total%20soluble%20solids%20in%20jelly%20using%20hyperspectral%20imaging.&title=AIP%20Conference%20Proceedings&issn=0094243X&isbn=&volume=2030&issue=1&date=20180921&au=Poonnada%20Onnom&spage=020211-1&pages=&sid=EBSCO:Academic%20Search%20Complete:133017654&vid=01TRAILS_MSU&institution=01TRAILS_MSU&url_ctx_val=&url_ctx_fmt=null&isSerivcesPage=true
##### Available: 
* https://msu-primo.hosted.exlibrisgroup.com/primo-explore/openurl?ID=doi:10.1108%2FNFS-09-2019-0293&genre=article&atitle=Impact%20of%20processing%20and%20packaging%20on%20the%20quality%20of%20murici%20jelly%20%5BByrsonima%20crassifolia%20(L.)%20rich%5D%20during%20storage.&title=Nutrition%20&%20Food%20Science&issn=00346659&isbn=&volume=50&issue=5&date=20200901&au=Da%20Cunha,%20Mariana%20Crivelari&spage=871&pages=871-883&sid=EBSCO:Academic%20Search%20Complete:145170609&vid=01TRAILS_MSU&institution=01TRAILS_MSU&url_ctx_val=&url_ctx_fmt=null&isSerivcesPage=true
* https://msu-primo.hosted.exlibrisgroup.com/primo-explore/openurl?ID=doi:10.1515%2Fcerce-2017-0005&genre=article&atitle=USING%20GELATIN%20TO%20PRODUCE%20HONEY%20JELLY%20FROM%20CITRUS,%20CLOVER%20AND%20COTTON%20LIQUID%20HONEY.&title=Agronomical%20Research%20in%20Moldavia%20%2F%20Cercetari%20Agronomice%20%C3%AEn%20Moldova&issn=03795837&isbn=&volume=50&issue=1&date=20170301&au=ELHAMID,%20A.%20M.%20ABD&spage=57&pages=57-64&sid=EBSCO:Academic%20Search%20Complete:123136403&vid=01TRAILS_MSU&institution=01TRAILS_MSU&url_ctx_val=&url_ctx_fmt=null&isSerivcesPage=true

### How to get XML response

https://developers.exlibrisgroup.com/alma/integrations/discovery/xml-openurl/

### Montana Base URL

https://trails-msu.userservices.exlibrisgroup.com/view/uresolver/01TRAILS_MSU/openurl

### Working Montana XML link

https://trails-msu.userservices.exlibrisgroup.com/view/uresolver/01TRAILS_MSU/openurl?ID=doi:10.1515%2Fcerce-2017-0005&genre=article&atitle=USING%20GELATIN%20TO%20PRODUCE%20HONEY%20JELLY%20FROM%20CITRUS,%20CLOVER%20AND%20COTTON%20LIQUID%20HONEY.&title=Agronomical%20Research%20in%20Moldavia%20%2F%20Cercetari%20Agronomice%20%C3%AEn%20Moldova&issn=03795837&isbn=&volume=50&issue=1&date=20170301&au=ELHAMID,%20A.%20M.%20ABD&spage=57&pages=57-64&sid=InstantILL&vid=01TRAILS_MSU&institution=01TRAILS_MSU&url_ctx_val=&url_ctx_fmt=null&isSerivcesPage=true&svc_dat=CTO&response_type=xml

**Comment by JosephMcArthur** [comment]
@markmacgillivray we've been asked if we can do this on an accelerated timeline for Montana. 

Could we try and do this just for Montana, and a little later circle back to generalizing this (e.g getting it on the setup page, etc). I can just ask them to update their embed code with whatever we tell them.

I know you said yesterday you were maybe able to make some changes to code while testing other things. If you think this falls into that bucket ace, if not, no worries just lmk.

**Comment by markmacgillivray** [comment]
Working on dev, exlibris can be provided as a URL on instantill/setup. Tested with the DOI in the top example link you gave above, it worked for me.

**Comment by JosephMcArthur** [comment]
Thanks Mark! I've sent this off to them.

## notes

DOI's for testing:

Have:

10.1515/cerce-2017-0005
10.1108/NFS-09-2019-0293

Have not:

* 10.1063/1.5066852
