### ISSUE TITLE
Permissions returning no information for journal in DOAJ

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1801]
**Describe the bug**
`https://api.openaccessbutton.org/permissions?issn=1998-9563` returns no information, even though ISSN appears to be [providable by DOAJ](https://doaj.org/toc/2224-7955?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22terms%22%3A%7B%22index.issn.exact%22%3A%5B%221998-9563%22%2C%222224-7955%22%5D%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22size%22%3A100%2C%22sort%22%3A%5B%7B%22created_date%22%3A%7B%22order%22%3A%22desc%22%7D%7D%5D%2C%22_source%22%3A%7B%7D%7D)

**To Reproduce**

Click https://api.openaccessbutton.org/permissions?issn=1998-9563

**Expected behavior**

We return some information in line with it being an OA journal

**Comment by JosephMcArthur** [comment]
A second, maybe related example is here:

`https://api.openaccessbutton.org/permissions?issn=2574-1306`

Here, we find some information but not the licence the DOAJ says it has (`cc-by-nc-nd`).

**Comment by JosephMcArthur** [comment]
Another, slightly different, but seemingly related:

US: `https://api.openaccessbutton.org/permissions?issn=1020-4989`
DOAJ: `https://doaj.org/toc/1680-5348`

**Comment by JosephMcArthur** [comment]
`https://api.openaccessbutton.org/permissions?issn=1459-6067` is in DOAJ, and adding this as it seems interesting that `meta` has clearly related info without actually having it in the main response.

**Comment by markmacgillivray** [comment]
All resolved on our new dev system, and the discrepancy again down to differences between what we have on dev and JCT project being slower to go ahead with things onto their live system. So we were using queries to our own old dev system, which had been updated for their dev, and were waiting for that to become live. To be resolved in future by the already-created issue of putting together our own index of journals.
