### ISSUE TITLE
Deposit into OSF via the API

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#191]

**Comment by markmacgillivray** [comment]
I doubt this will be completed this sprint, but can have it as a hanging enhancement to keep working on as we discuss with them - until there is the API endpoint on their side, this cannot be completed on our side.

**Comment by markmacgillivray** [comment]
Moved this out to further milestone

**Comment by JosephMcArthur** [comment]
Leaving this here as a note on what Metadata we should try and make sure gets submited: https://twitter.com/jaclark/status/768510585990361088

**Comment by markmacgillivray** [comment]
Moving to next milestone as it keeps going

**Comment by JosephMcArthur** [comment]
Certainly need to reengage with them on this.

**Comment by markmacgillivray** [comment]
We do, but no time in this sprint to make it happen, and it will work as is for the time being. Moving to next sprint.

**Comment by JosephMcArthur** [comment]
Can you reach out to them again and remind them what we need at the least
please?

**Comment by JosephMcArthur** [comment]
@markmacgillivray have we reached out to them again? Would be good to do in this sprint.

**Comment by markmacgillivray** [comment]
Discussion is ongoing. I have pinged into slack again and asked for clarification on how to use the API to upload a file as Open Data Button and then to add the author as a contributor. I have asked for a reply via email, but if they have to do it via slack I will check there when I get alerts. Moving on to next sprint to continue discussion.

**Comment by markmacgillivray** [comment]
Discussion continues. Moving to next milestone.

**Comment by JosephMcArthur** [comment]
No longer doing data work, no capacity. Focusing on articles to build plumbing and hoping to return to data later.
