### ISSUE TITLE
Getting feedback from users - is this the thing you wanted?

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#194]
We have gone round a few different ideas of how to get feedback from users regarding whether or not the thing we send them to is the content (article, data, whatever) they wanted, and/or gives them access to the thing they wanted (google scholar search page, etc). This has become confusing, because we want to do as little user tracking as possible, and because sending them to a page where they MAY find something is not the same as sending them to a page where we believe the content to be (which we could possibly be wrong about, but this is not the same problem)

We considered triggering the plugin to open, for example, when we send people either from a request page or from the plugin to a google scholar URL by either appending a nonce param to the URL that the plugin looks for or by always popping the plugin open on specified domains (such as google scholar). The problem with this though is that it is then not clear what the functionality of the button is in certain situations, to a user - is it going to pop open, is it not, am I saying I CAN find something on this page, or HAVE found something on this page, and if I HAVE, is that thing EXPECTED or not.

Also, even just looking for a nonce param would change our level of invasiveness - we would have to at least look at every URL a user types in, although we would not have to save that info or send it anywhere; but still, we would be looking. Given the preference of oabutton as a project to be about openness, and therefore not about illicit tracking of what people do (although not a correlation I personally believe in), we should minimise our need to "follow" what users do.

So I propose that the best way to get feedback from users would be to make the action explicit - and for it to be a clearly defined additional function of the plugin.

That is, when the user opens the plugin, they should select which of TWO things they want to do:
- search/check for content, getting back the links we hold and/or open requests, and the ability to start their own requests (this is the function the button already has)
- feedback/submit content, e.g. when a user IS on the page of some content (article, data, whatever) they can click the button and choose to submit that content to oabutton, thereby creating a "content record" which will fulfil any requests that are open for that content (and could or could not be cached for future matches even if there are no currently open requests, although this is not necessary and may complicate matters)

We should then be clear in the instructions / usage walkthrough - that the oabutton is for TWO things - finding content, and also SHARING the location of content with others.

This would also provide an additional way for authors to submit content - the email they receive could prod them to install the button themselves, and if their content is already online somewhere that they know of, all they would have to do is install the plugin, go to that location, click it, and choose to submit the URL, thus satisfying the open request.

This idea is unambiguous, unlike our earlier thoughts. It still allows us to prod users on request pages or on the plugin to go to google scholar, figshare, or wherever we want, and to ask them to go there and search for stuff, and WHEN they find the relevant stuff to then open the plugin and submit it.

It is also just a few lines more for the instructions, and is far easier to understand than "on this page or that page the plugin may ask you x or y, and you can answer x or y in these situations, but only on these sorts of pages, and maybe you can answer z on these other pages"

The extra complexity required for the plugin development is one pre-step to current functionality where the user is asked "do you want to search or submit" and then if they choose submit, we just submit it and say "thanks!" (matching it to open requests will happen behind the scenes on the server, and can email the user to congratulate them on closing any requests, if their submission did so - which could also be a user incentive - become a "closer" and have a rank of how many requests you helped to make successful).

@JosephMcArthur @Steven-Eardley thoughts asap would be useful, it does not block what Steve is doing, but if we can decide sooner we can get that extra "submit" loop in along with the other plugin dev, by end of next week, I would think.

**Comment by JosephMcArthur** [comment]
@markmacgillivray Do we need to deal with this in this sprint, or can it wait till the next?

**Comment by markmacgillivray** [comment]
We have the permission from the plugin to see the URL. So DO send a check request - if the URL is of a page we have a request out for, ask the user if the content is there.

**Comment by JosephMcArthur** [comment]
Part of me feels like I've only just understood this, or the broad implications of it. Judging by more current discussions

> feedback/submit content, e.g. when a user IS on the page of some content (article, data, whatever) they can click the button and choose to submit that content to oabutton, thereby creating a "content record" which will fulfil any requests that are open for that content (and could or could not be cached for future matches even if there are no currently open requests, although this is not necessary and may complicate matters)

doesn't seem to be happening. Which, I think right now is a good thing. I think we should fulfil this functionality through request pages (in #229 I think). Not 100% opposed to doing this via the plugin at some point, but I don't think we can do it now.

Moving into backlog for now, and we can revisit when we want too.

**Comment by markmacgillivray** [comment]
I think if this happens or not is beyond a technical question, and is something that would rely heavily on the copy we decide for it. I would say it should go on the request page, not the plugin itself. For now will unassign me and assign Joe so decision can be made in later sprints, then assign to whoever has to deal with it first

**Comment by JosephMcArthur** [comment]
Rather than implementing this via the plugin I think we can handle it by:
* surfacing an link on /request/new where we can do this more simply
* making it easy via the bug reporting form to submit links where we don't give an appropriate response (e.g pointing to a paywalled thing or the wrong thing)
* surfacing a link on successful requests

This would mean it would be hard for a user to do this via the plugin, but I think that's okay for now. Having this implementing would make me feel a lot better about pushing ahead with #68. I think all we need to grab is the article URL & user email & perhaps a tickbox response of what issue it is (wrong paper, not found an oa version). 

Fwiw, I think we should implement this via the API. We should be notified by email of the link.

That would close this issue as I originally thought about it.

**Comment by JosephMcArthur** [comment]
This is closed mostly by #10

**Comment by JosephMcArthur** [comment]
@chealsye, when you find there is a bad linkage between what you searched for & what we delivered, as a user, how would you go about reporting it?

I can't imagine how to do it smoothly, so, help would be appreciated. My current best idea is that when you press on a "article" availiable link on /find, we could change the page (or just that button / area) to a *broken link?* style button that would take you to http://oab.test.cottagelabs.com/feedback#wrong (with most the info about the broken link already provided).

**Comment by chealsye** [comment]
Hmm. Honestly, I likely a) wouldn't report it b) tweet about it. I think an average user is likely not to say anything when they encounter a problem and perhaps not use the Button again. 

However! now that the little orange help Button is there I, as a user, might be inclined to actually click it. (I was quite excited when I saw it while reviewing the dev site!). 

>  My current best idea is that when you press on a "article" availiable link on /find, we could change the page (or just that button / area) to a broken link? 

I'm confused. What do you mean by that? Change the link after they click it? The Button website opens a new window when a user clicks "This article is available!" to add a way of reporting an incorrect link below the results.

**Comment by JosephMcArthur** [comment]
Okay, from above I'd suggest:

- [ ] move the help box onto all pages - @markmacgillivray 

With my suggestion, apologies it was poorly written & now I think probably not valid (since we're changing the workflow generally). But, your feedback is helpful none the less in understanding how you'd think about reporting.

**Comment by markmacgillivray** [comment]
This was on all pages, then moved to just account and response pages at request of @JosephMcArthur. Please confirm where help is supposed to appear. Either I can move it, or anyone who can edit the content can move it.
