### ISSUE TITLE
Investigate use of Microsoft Academic as an alternative to Scholar

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#196]
They have an API that's usable under an NC licence. Potential replacement for scholar?

**Comment by JosephMcArthur** [comment]
This system can be found here: https://academic.microsoft.com/ and I think this is the API: https://www.microsoft.com/cognitive-services/en-us/academic-knowledge-api. 

I spoke to the guy who was trying to build this and he said that it should be able to go from a title or DOI to an article link (de-duped from sources, with it knowing if that was available or not) soon. That was months ago. 

I've taken a glance, but it's over my head in term of what is actually happening. @markmacgillivray sending your way for an evaluation from someone who knows a thing.

**Comment by markmacgillivray** [comment]
There may now be a graph search option we can use to look for an article. Have another look.

**Comment by markmacgillivray** [comment]
Not of immediate concern, pushing back to backlog

**Comment by JosephMcArthur** [comment]
Note, this has recently been updated to V2

**Comment by JosephMcArthur** [comment]
Note, it has some clear examples of picking up works potentially legal works (not RG anyway...) that we miss. e.g http://aip.scitation.org/doi/pdf/10.1063/1.1349893

**Comment by markmacgillivray** [comment]
MS academic title search is now working on dev. search by DOI is not yet possible - they don't appear to allow extended metadata attributes as search parameters. Title search is enough to close this now though.
