### ISSUE TITLE
Optional "give us more info" form as part of a request page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#208]
All optional:
- [ ] ORCID's for corresponding author
- [ ] Name for corresponding author
- [ ] Disipline of paper
- [x] Email of author

**Comment by markmacgillivray** [comment]
This is now coming up in a few different places - what metadata is actually necessary? Asking for more, even as options, may seem good but it also complicates the UI, hides true functionality, and makes it more obvious when we do NOT have certain information.

All we actually need is a URL to the article, an email address to send requests to, and an article title and request stories to humanise things a bit. Identifiers, author metadata, keywords - what is the actual requirement that having any of them solves? (Needing them for a more complex UI with more filter options is not a requirement, it is an over-design.)

We know that users want to request certain articles (or data) and they can add force to those requests by supporting them. But why do we think they would care about searching on our site by author, keyword, etc? I do not think this is an obvious use case - they will be searching by other means, then want to issue a request when they find something somewhere else that they cannot access. At that point they need to know if a request already exists (and if content is already available, of course) - but that requires only the URL.

**Comment by JosephMcArthur** [comment]
As per discussion, moving this back into the backlog. All of the above is useful - but not essential.

**Comment by markmacgillivray** [comment]
Unassigning myself as nothing for me to do right now, more of an issue for later, already in backlog.

**Comment by JosephMcArthur** [comment]
we are doing this, but as needed for specifics. This isn't really needed.
