### ISSUE TITLE
Integrate doai.io?

### ISSUE THREAD

**Issue by wetneb** [OAButton/discussion#210]
Hi there! :-)
I wonder if you would consider adding doai.io to your sources? We cover many sources now, including ResearchGate :-) We're working on a new version by the way, with a proper API, to be launched later this year. It would be great if we could point people to the OAB for an extension that supports doai.io.

Anyway, I'd be happy to work with you on backend-related issues. Is there an up-to-date description of 1/ how you're currently scraping paywalls 2/ how you try to find full texts for them?

Antonin

**Comment by markmacgillivray** [comment]
What do you mean by scraping paywalls? I don't think we do that at all. The button is triggered by the user, when they are on a page that they want to use it on - which is probably a paywall, but we don't identify it as such. We actually already have a doai-type service of our own, although as I understood it, Joe was going to talk to you about that and it has not been advertised to anyone yet. We do use dissemin to check for access to articles, among other sources, so would using doai make any further difference? I'd imagine, given the way our own OA resolver works, that doai would provide the same access to OA versions as dissemin does, right?

Regarding working on backend-related issues, I'd be happy with that, but I think we have a problem before that, which is organisationally we are doing the same things. That dilutes both of our ability to provide a useful service to the wider community. So it would be good to come to a better understanding of how oabutton / CL / dissemin / doai overlap, and where we could start doing the same things. Then we could probably just use the same services, but we would have to decide which to keep working on, or where the overlaps are such that we benefit from keeping both going.

**Comment by wetneb** [comment]
About scraping: I thought at some point you were using quickscrape to retrieve metadata from the page where the users pushed the button. I remember seeing quickscrape logs in the UI, but maybe that was something else?

doai.io includes ResearchGate whereas dissem.in does not (and that's quite a big difference in terms of coverage). We did not want to include it in dissem.in because we wanted to encourage a better OA than the one provided by social networks (but we might include it eventually, as users keep complaining about that…).

**Comment by markmacgillivray** [comment]
@JosephMcArthur is this oadoi now? If so, can close, it is integrated

**Comment by JosephMcArthur** [comment]
Nope, this isn't oadoi. However, unless I'm wrong it's largely the same source (base). Talking to Antonin about Researchgate offline.

**Comment by markmacgillivray** [comment]
Yeah, sorry, I know it's different, I mean is it solved by oadoi.

**Comment by nemobis** [comment]
I took a random DOI from https://zenodo.org/record/54799, 10.1017/S0954102008001144: doai.io quickly redirects me to https://openresearch-repository.anu.edu.au/handle/1885/27693, while https://openaccessbutton.org claims it's not available and suggests to ask the author. Bug? False negative?

**Comment by JosephMcArthur** [comment]
@nemobis yeah we probably just don't show that as it's not actually readily available.
