### ISSUE TITLE
Wording of the open data requests doesn't allow requests not from articles

### ISSUE THREAD

**Issue by hemprichbennett** [OAButton/discussion#224]
Currently the ODB is worded entirely for seeking data from a specific publication. Though likely the most common sort of data request, it isn't the only type. E.g.:

I was after information from a constantly-updated public dataset which hasn’t been tied to a specific publication, although I’m sure many papers have been written off of it in the past. The format of the ODB template inherently implies that I’m after a dataset that was used for a previous paper, but this would be misleading as I’m interested in data from this open database thats so recent it won’t have any papers written about it yet. As such if I was to use the ODB it would probably confuse the recipient of the request: 'please give me the 2016 data that was used in your 2013 paper’ makes no sense.

**Comment by JosephMcArthur** [comment]
Hi Dave, thanks for this! We'll have a think about how we could support this and leave any thoughts here.

**Comment by JosephMcArthur** [comment]
No longer doing data work, no capacity. Focusing on articles to build plumbing and hoping to return to data later.
