### ISSUE TITLE
Allow user submitted links to fulfil requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#229]
We've discussed this briefly, but time to make an issue. We've discussed using request pages to ask folks to manually search sources (like author pages & data repos) to help find things where current automatic search falls down. 
#### Articles
- Immediately (i.e before moderation) we have a call to action on request pages for searching Scholar and Google for versions on author pages. We can give them a nice link to do this. 
- Once link is clicked, buttons for submitting a link or "I can't find this" become visible.
- Link could be checked (or not) by a moderator and against Sherpa Romeo (for legality)
- Link is sent to requester, link-giver is thanked each time it's used. 
- Link is requested for Archive by the Internet Archive (like how references are automatically archived on Wikipedia) and we release the linkage as Open Data (somehow). 
#### Data
- Similar to the above, except less need to Archive (assumings it's found in a data repo) & check legality.

**Comment by JosephMcArthur** [comment]
Realising this is functionally similar to what we allow authors to do already.

**Comment by markmacgillivray** [comment]
There is a question here then around who we let fulfil a request - does it
even need to be the author?

**Comment by JosephMcArthur** [comment]
As discussed, Data - no. Article, yes.

**Comment by JosephMcArthur** [comment]
@chealsye if we ran this through legally checking workflow I've sent you (for links only, with articles) does this seem like a good path forwards?

**Comment by chealsye** [comment]
@JosephMcArthur Yes!

**Comment by JosephMcArthur** [comment]
We are now allowing this, with the legality checks in place. Closing!
