### ISSUE TITLE
"For Institutions" Page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#235]
To showcase our ideas & plans around OAB for institutions we should put together a page for it. 

We need to get:
- [ ] Copy (@chealyse / Joe )
- [ ] Design (Joe)
- [ ] Code

&
- [ ] feedback on the product of the above from the target

**Comment by chealsye** [comment]
@JosephMcArthur What info do you want this page to initially cover?

**Comment by chealsye** [comment]
@JosephMcArthur *nudge* ^ 

I can get this done on Sunday.

**Comment by markmacgillivray** [comment]
Unassigning me for now, no obvious code requirement yet, just tracking what I have to do right at the moment. Can reassign me later if needed.

**Comment by chealsye** [comment]
@JosephMcArthur *second nudge* I need what information you want to be included. Not sure how much we are saying.

**Comment by JosephMcArthur** [comment]
Let me get back to you on this.

**Comment by JosephMcArthur** [comment]
Okay, moved this out of the launch milestone as I'm just not going to be able to turn around the info required.

**Comment by chealsye** [comment]
@JosephMcArthur Where are we at one this? Do you have some drafts for Imperial that I could use to inform a draft for this?

**Comment by chealsye** [comment]
@JosephMcArthur *poke* for when you got Imperial drafts I can go off of

**Comment by chealsye** [comment]
@JosephMcArthur Can we do this now in this next few weeks now that we will announce?

**Comment by JosephMcArthur** [comment]
V1 of this is up now, seems to be performing well. Closing this for now.
