### ISSUE TITLE
rename /backend, /unified-extension and /oab_static to be non-dev friendly

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#246]
Will help facilitate contributions & have them accurately reflect what they do. Assume it will also break many links and maybe code though. So interested in assessing how much of a pain it is.

**Comment by JosephMcArthur** [comment]
@markmacgillivray what happens if I do this? Will lots of stuff break?

**Comment by markmacgillivray** [comment]
It won't break stuff terribly, but autodeployment from oab_static would stop working. That is easy to reconfigure though. However anyone with remote repos trying to push back to github would find it no longer works if the name has been changed. That is only really relevant to us anyway, and is not a huge problem either, but would be better not to do it when there is lots of development going on. oab_static could just be called website and unified_extension could just be called extension or plugin, or whatever names you want, really. As long as you let me know when you want to change those names, and we co-ordinate a little bit, they can be changed.

**Comment by JosephMcArthur** [comment]
Assinging @markmacgillivray as he is more likely to know what this will mess up. 

I'd suggest:

- [ ] oab_static --> Website and Emails
- [ ] backend --> Discussion
- [ ] unified-extension --> Plugins

**Comment by markmacgillivray** [comment]
Done, called "website", "discussion", and "plugin".

I have changed the deployment configs.

Note @JosephMcArthur @chealsye if you are doing any work at the moment on oab_static you should change whatever local patterns you are using to edit the content to work on "website" instead.
