### ISSUE TITLE
Take down teambutton.org

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#255]
We need to take down teambutton.org since we are discontinuing the initiative. Should it re-route? Or just go ahead? Put up a notice?

**Comment by chealsye** [comment]
@JosephMcArthur - have you added it as blocked copy because you think it needs to have a notice? On the current site or a redirect?

**Comment by JosephMcArthur** [comment]
I think the site itself needs a note about it being decommissioned, and
being worked directly into the main site.

**Comment by JosephMcArthur** [comment]
We also need some comms for people who signed up.

**Comment by JosephMcArthur** [comment]
I have moved this to the launch clean up milestone. This site can be easily edited to display a message, and it shouldn't hold up other work on getting the new site out the door.

**Comment by JosephMcArthur** [comment]
@markmacgillivray can we use the same approach here as in #251?

**Comment by markmacgillivray** [comment]
I have never had access to teambutton.org so first someone would have to point that domain at my server IP

**Comment by JosephMcArthur** [comment]
What's your server IP?

**Comment by markmacgillivray** [comment]
178.62.93.81

**Comment by JosephMcArthur** [comment]
but once that happens it would work?

**Comment by markmacgillivray** [comment]
Once teambutton.org points to my server, and once we push the dev changes to live, then teambutton.org pages will redirect onto openaccessbutton.org.

**Comment by JosephMcArthur** [comment]
@markmacgillivray what's the best route forwards here given what happened with opendatabutton.org?

**Comment by markmacgillivray** [comment]
Still the same - the first step is point teambutton.org to my IP and let me know. Then it depends what the security settings were on the teambutton domain - either it can redirect easily, or I will point it to a page that tells the user to please go to the new site.

**Comment by JosephMcArthur** [comment]
I have asked for the address to be moved twice, no luck yet.

**Comment by JosephMcArthur** [comment]
Continued to ask, am bumping this fowards

**Comment by JosephMcArthur** [comment]
Teambutton.org now directs to the site. However, no message shows right now.

**Comment by JosephMcArthur** [comment]
I remembered you can evoke this just by using the URL on the test http://oab.test.cottagelabs.com/?team=true. I have now done this. Closing, but @chealsye if you'd like the copy changed please go for it.
