### ISSUE TITLE
Allow individual users to make bulk requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#269]
## Notes
- This should probably be via the website, rather than the plugin (see #268 )
- Would address #174 
- Could work by having multiple URL's pasted into a box, with one story supporting those. 
## Use case
- A researcher doing a systematic review or looking at a bibliography wants to find access to all articles because to cite their OA versions or simply read them.

**Comment by meganwaps** [comment]
This would be especially useful for someone using an online system such as Mendeley to manage their research or bibliographies. If they've compiled a list but cannot get access, they could hopefully export that list and make bulk requests. This could also potentially provide us with exceptional data about what categories/subjects our users need the most.

**Comment by JosephMcArthur** [comment]
this is being discussed full in #440 - closing here
