### ISSUE TITLE
Provide new Button usage stats

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#273]
I received a question on Twitter asking how many paywalls we've recorded and in how many countries. I was able to answer the first question, but not the second. I'd like to be able to provide this information as well as any other updated usage stats.

When things slow down a bit - can we get updated stats? Number of paywalls/requests, countries, articles, data.

**Comment by markmacgillivray** [comment]
What does country mean? We record the location of a user where we can, but
that does not mean that the service they are trying to access is in the
same country as them.

**Comment by chealsye** [comment]
It may not always be accurate, but we can give a decent estimate based on where they are accessing from. Where the Button is being used is important information. Since we no longer have a working map this is information that users (particularly those that are wanting to promote the Button, which is the case for the person who asked the question) are interested in and cannot find themselves.

**Comment by markmacgillivray** [comment]
OK so it is the country of the user, not the country of the paywall. We can
get that.

**Comment by JosephMcArthur** [comment]
We may want to do this in #192

**Comment by JosephMcArthur** [comment]
General stats can be found at /stats.

**Comment by JosephMcArthur** [comment]
Closing in favour of other issues on topic. E.g #548 & the many other stats issues.
