### ISSUE TITLE
Auto email: Sign up without first use in a month

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#293]
[All email drafts here.](https://docs.google.com/document/d/1zdBpebZ64WsJ9T1-4xxuN8o4Ob0qRiWwFVW1Ig2eAdE/edit#)

This is the copy for the email that should send when users sign up for the Button, but do not use it within a month.
## 

**SUBJECT:** Get Research with your Open Access Button

Hi, there!

Thanks for signing up for the Open Access Button. We've noticed you haven't used the Button yet. 

Do you have an article or dataset you need access to? Give the Open Access Button a try and request access! If you don’t have an article you need right now, you can also test out the Button with a sample article. [Try this one!](http://science.sciencemag.org/content/293/5530/629)

You can give the Button a test run by using the Button in [your browser](http://openaccessbutton.org/request/new) or by [downloading the plugin now](https://openaccessbutton.org/account). 

We look forward to getting you access to research,
The Open Access Button team

**Comment by JosephMcArthur** [comment]
@markmacgillivray if you have to move #295 back then move this back too please

**Comment by markmacgillivray** [comment]
This one is in milestone 6 already, which seems sensible, given that it is to contact people after a month of sign up. And if we do auto email next sprint, can configure this one in the sprint after. If we delay further, can then move this one back further too.

**Comment by JosephMcArthur** [comment]
Still not ready to turn this on, moving into the backlog.
