### ISSUE TITLE
Auto email: Haven’t used in 1-2 months

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#294]
[All email drafts here.](https://docs.google.com/document/d/1zdBpebZ64WsJ9T1-4xxuN8o4Ob0qRiWwFVW1Ig2eAdE/edit#)

This is the copy for the email that should send when users haven't used the Button in 1-2 months.
## 

**SUBJECT:** Use your Open Access Button again!

Hi, there!

We noticed you haven't used the Open Access Button in a couple months. How was your previous Button experience? 

The next time you find an article or dataset you need access to, give the Open Access Button another try. Don’t have an article you need right now? You can [support another request](https://openaccessbutton.org/request) instead. We're constantly working to connect users to more research - your request will help increase research access for everyone. 

We look forward to getting you access to research,
The Open Access Button team

**Comment by JosephMcArthur** [comment]
@markmacgillivray if you have to move #295 back then move this back too please

**Comment by JosephMcArthur** [comment]
Still not ready to turn this on, moving into the backlog.
