### ISSUE TITLE
Auto email: When someone supports a request, but doesn’t download for 3 days

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#295]
[All email drafts here.](https://docs.google.com/document/d/1zdBpebZ64WsJ9T1-4xxuN8o4Ob0qRiWwFVW1Ig2eAdE/edit#)

This is the copy for the email that should send when a user supports a request, but does not download/use the Button for 3 days.
## 

**SUBJECT:** Try the Open Access Button

Hi, there!

Thanks for recently supporting an Open Access Button request. It's people like you that help make the Open Access Button successful and encourage authors to make their work accessible.

You can get your own Open Access Button that will help you get access to research articles and data that you need. [Download the Button now](https://openaccessbutton.org/account) or find and request research in [your browser](http://openaccessbutton.org/request/new)!

If you don’t have an article you need right now, you can also try out the Button with a test article. Give the Open Access Button a try with [this sample article.](http://science.sciencemag.org/content/293/5530/629)

We look forward to getting you access to research,
The Open Access Button team

**Comment by markmacgillivray** [comment]
Note there is no /download route on the website, so the link in this email
would not work. Download currently happens from the account page, which is
at /account

**Comment by chealsye** [comment]
OK. Corrected.

**Comment by JosephMcArthur** [comment]
@markmacgillivray am I correct that since we can't do automatic emails right now this isn't a quick fix. If not, then we'll need to push this back to a later milestone (the backlog in this case)

**Comment by markmacgillivray** [comment]
Yes we need to decide when to turn on auto-emailing. So push this back to the next sprint at least, then can see if we want to turn that on yet or not.

**Comment by markmacgillivray** [comment]
As previous discussion in comments above indicates, we have yet to decide when to turn on auto-emailing, and we need to turn them on at the same time (or decide which ones we are not going to do, and how to make them separate from the ones we are going to do). This needs further discussion / planning, and the other auto-email issues are still further out in milestone 6, so it makes sense to push this out to milestone 6 too.

**Comment by JosephMcArthur** [comment]
Still not ready to turn this on, moving into the backlog.
