### ISSUE TITLE
Systematically testing the find system

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#301]
*\* Moving over from email *\* 

I think we should aim to test about 250 articles. Those articles would come from:
- the 20 top journals, measured by Impact Factor (Chealyse will get us the list) & high profile/volume journals that might be get caught by this. E.g PLOS one, eLife.
- 20 Open access journals & 20 closed access journals from each of the top 5 publishers

and in that group we need to have:
- A % of old articles (that might lack DOI's & old metadata schema)
- A % of new articles (that have DOI's & current schema)
- A % of articles we know should be able to find from Base / Core

The definition of success for the system is as follows. 
- If the article is available in Base / Core - success is finding that article
- If that article isn't available in base / care - success is finding the title. 

To track this we need a spreadsheet that lists article URL's, their availability (paywall vs oa / free), their publisher, their journal, their year of pub, presence of doi, their availability in base / core & if we meet each bar for success.

Once we have that Google Sheet:
- [x] Add in URL's we all tend to test - @chealsye @markmacgillivray 
- [x] Have the plugin process those on the fly - @markmacgillivray

**Comment by JosephMcArthur** [comment]
Here are 100 great articles to test: https://www.authorea.com/users/8850/articles/125400/_show_article

The article list can be found here: https://www.authorea.com/users/8850/articles/125400/master/folder/Raw%20table%20data

**Comment by meganwaps** [comment]
I'm on it, should I add these to the existing technical testing guide?

**Comment by JosephMcArthur** [comment]
We can also get a random list of doi's to test against here ropensci/rcrossref

**Comment by JosephMcArthur** [comment]
Okay, talking with @markmacgillivray is may be easier to do this by grabbing a bunch of DOI's from Crossref that are behind paywalls & various years. Then, we can just run them against the find API & see how it goes. That will give us a success figure.

**Comment by markmacgillivray** [comment]
Once I load the old blocks as availability checks, and then run them through the system to see if they ARE available, then all we need for this is to show on the stats page second sentence that X availability checks were made, and Y of them were found.

Longer term, it may also be useful to run every DOI published every day by crossref and see how many are findable.

**Comment by JosephMcArthur** [comment]
Following up from a discussion with @markmacgillivray today. The point of this issue was to:

* see how successful we are now
* monitor changes we make & how they affect our success
* monitor changes in the ecosystem & how they affect our success

While we went into this thinking we needed to systematically build a list, that's actually a lot of work. Instead, we're going to use our actual usage as the baseline for this and we can generate the numbers needed there. That saves on having to create & maintain the list, and the computing power / scripts needed to do it are already in progress from #192 & #333. So, in short, we're just going to do that. 

In the stats page we can do what Mark has said above, but we should aim in future to be able to compute the above stats for different points in time & for different changes (i.e ask ourselves if a feature we've implemented is actually helping with finding research & how much it helped). 

Anywho, the long & the short of this is that the real extra work this issue entailed over and above other work is now not needed. However, I'll leave it open until we finish the end goal.

**Comment by markmacgillivray** [comment]
Run the Imperial DOIs as part of testing too.

**Comment by markmacgillivray** [comment]
Given the stats / export capability, and the favourable  Imperial DOIs test, this issue could probably be closed now. @JosephMcArthur do you agree?

**Comment by JosephMcArthur** [comment]
I'd like to see us run our own backlog through this first. The Imperial
test was useful but totally different to what was intended here.

**Comment by markmacgillivray** [comment]
Isn't that what issue #333 covers though, running our own backlog every week?

**Comment by markmacgillivray** [comment]
Regarding what this issue needed, we had 16500 DOIs that we knew were open but that may not be in BASE or CORE, and I'd say we learnt quite a lot by finding 83% of them. BASE search was improved by realising many of them could be in there but do not have DOIs. CORE may be similarly improved, but has not been done yet, as the majority are found in BASE first anyway. We know we had no errors in the 16500 records, the system performed well within limits, and took 3.5 hours to process all 16500. I can give you counts of how many were found where, if you like.

I think there could be value still in the original proposal of this test, which was a specific managed list of articles that we know more about, and that we can check what we discover for - but we then changed that to be a random set collected by me, which I now think is less valuable, as the Imperial set is better than that.

If we can go back to someone building a set of articles with a lot of specific info, like this issue initially started as, then that would perhaps have further value. But in that case, it is not something I can do, we would need someone with the time to build that set (in a spreadsheet / csv / google sheet would do, then I can run it through the system - and also provide spreadsheet upload capability to admins too, once that feature is ready).

**Comment by JosephMcArthur** [comment]
If we're prepped to cover these points:

> see how successful we are now in linking users to copies they can read
> monitor changes we make & how they affect our success
> monitor changes in the ecosystem & how they affect our success

through those other issue then please feel free to shut.

**Comment by JosephMcArthur** [comment]
Hmm, actually can we run this: https://www.authorea.com/users/8850/articles/125400/master/folder/Raw%20table%20data in the same way we've run the Imperial data?

**Comment by markmacgillivray** [comment]
Yes, we could run that sheet.

**Comment by JosephMcArthur** [comment]
When you get a moment, please go ahead

**Comment by markmacgillivray** [comment]
will do. May not be today, got some other things to do. Maybe tonight.

**Comment by markmacgillivray** [comment]
Also run the real data before/after updates to the system for reverse lookup, title lookup

**Comment by JosephMcArthur** [comment]
Before the sprint team meeting could we get a quick update on progress here, and if anything is blocking us moving forwards?

**Comment by markmacgillivray** [comment]
Progress is still the same. I think this one could potentially be closed, what is outstanding is running a particular job, which we have an issue for as batch job submissions.

**Comment by JosephMcArthur** [comment]
there are a few things left in this issue:
# 1 

> I'd like to see us run our own backlog through this first. The Imperial

# 2 

- [ ] running https://www.authorea.com/users/8850/articles/125400/master/folder/Raw%20table%20data

# 3 

> Also run the real data before/after updates to the system for reverse lookup, title lookup

Not sure what this means
