### ISSUE TITLE
Run weekly check on all requests via the find system

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#333]
This is so that we pick stuff up that becomes available on the fly, and can deliver it to users

**Comment by JosephMcArthur** [comment]
Why:
* "Search once, looks forever" (or, nicer wording) feels like an appealing feature
* can help turn non-sign up users into signed up users
* deals with embargo's well (minor)
* reduces load on request system (minor)

**Comment by markmacgillivray** [comment]
@JosephMcArthur a script has been done to run weekly for all outstanding requests.

What do you mean by availability requests tied to signed in users? Do you not want to check availability for requests for people not signed in? If so, not signed in when? At the time the script runs? (Which will be some odd time in the middle of the UK night.)

The email to users, that would be the same as an email for any usual request success, or do you want it to be different in some way?

What sort of way do you want them to see what we're looking for for them? They can see what open requests they have, so if we just write somewhere "we will check every week for you" then is that it? Or do you have something else in mind?

**Comment by JosephMcArthur** [comment]
When I first thought about this, I thought that regardless of if someone
made a request, if they looked for something while signed in we'd just keep
looking for it. There would be no action required for this & we'd just
integrate it into messaging. If they searched while signed in, then made an
account, we'd continue to look for it.

The email should be a little different for this I expect. Assign me for
that for now.

In terms of how people see what we're looking for automatically, I think
right now we can give that a miss. It'll just confuse things, so I think
it's fine not to build until we get requests for it.

On Wed, 16 Nov 2016 at 15:41 markmacgillivray <notifications@github.com>
wrote:

@JosephMcArthur <https://github.com/JosephMcArthur> a script has been done
to run weekly for all outstanding requests.

What do you mean by availability requests tied to signed in users? Do you
not want to check availability for requests for people not signed in? If
so, not signed in when? At the time the script runs? (Which will be some
odd time in the middle of the UK night.)

The email to users, that would be the same as an email for any usual
request success, or do you want it to be different in some way?

What sort of way do you want them to see what we're looking for for them?
They can see what open requests they have, so if we just write somewhere
"we will check every week for you" then is that it? Or do you have
something else in mind?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OAButton/backend/issues/333#issuecomment-261065387>,
or mute
the thread

**Comment by JosephMcArthur** [comment]
@chealsye can you write an email that can be sent to users when we find them something through the means above? Just needs to be really short and sweet & have a link to the paper.

**Comment by JosephMcArthur** [comment]
Hmm, @markmacgillivray we also need to close a request if we find it via this method. Not sure if that's in the script.

**Comment by markmacgillivray** [comment]
@JosephMcArthur yes the weekly script will close a request the same way a normal submission of URL for it would close it. However, we do need to know what to say to the user as the request is found in a different way, and also should we say something to the author, who may have already been asked for the content but did not actually provide it, so the normal email confirming receipt from the author would not make sense. Once I know what you want sent in these cases, if anything, then I can complete the weekly script.

**Comment by JosephMcArthur** [comment]
Okay, @chealsye can you write something for the author too

**Comment by JosephMcArthur** [comment]
@chealsye nudge on this, thanks!

**Comment by chealsye** [comment]
Sorry for the delay on this, @JosephMcArthur. I'm a little confused though.

Here's a draft of the user email, but let me know if this isn't what is intended. Would this also apply for datasets? Or we assuming just articles?

> 
>  SUBJECT: We found the research you needed!
> 
> Hi, there!
> 
> You previously searched for research with the Open Access Button, but unfortunately we were not able to find it for you then. But good news: we have it now! 
> 
> You can get access to [ARTICLE TITLE] here: [LINK]
> 
> Thanks for using the Button,
> The Open Access Button team

And what exactly do you need for the author? Is this different because they aren't getting a full request and story? Do we need just a someone is looking for your research email?

**Comment by JosephMcArthur** [comment]
>SUBJECT: We found a paper you needed!
Hi, {{username}}!
You previously searched for "{{article title}}" with the Open Access Button, but unfortunately we were not able to find it for you. But good news: we have it now!
You read the article here: {{articleurl}}
Thanks for using the Button,
The Open Access Button team

In this case the author may have been emailed a request, but it has been completed by finding something that's already available. So, we want to notify them their request has been marked as successful.

**Comment by chealsye** [comment]
@JosephMcArthur Hmm okay. I'm definitely confused then. How exactly is it working? Does the author need to receive a link to the successful request page?

Draft:

> Hi, {{author}}!
>
> You previously received a request for "{{article title}}" from a Open Access Button user. We have found an accesible copy and the request has been marked successful.
>
> Cheers,
> The Open Access Button team

**Comment by JosephMcArthur** [comment]
This system will pick up if we find an article in a repository after a user
initially made a request ( regardless of if they make a request ). It will
then let them know we found it for them (assuming they're logged in). This
means a single user action will make us search on their behalf for the life
of the project. As things come out of embargo, or things are deposited
independent of us, or we add more sources, this will mean users end up
finding more. This actually happened with one of our old requests. Let me
know where that explanation doesn't make sense - this is a totally new idea
for us. A catchy tagline for this feature, like, "you search once - we'll
look forever" would be good.

Where a request had been made, we just need to let the author know not to
worry about the request. The only edit to the above I might give is to make
clear no user action is needed.

I wonder if we could just handle this through page copy on the requests
page though, now I think about it? Since we won't always have emails this
feels like the more bullet proof approach.

**Comment by chealsye** [comment]
Ahhh this all makes more sense now. Thanks, @JosephMcArthur! Embargo expiration makes a lot of sense. I think it makes sense to have this short email when we do have an author's email - but yes, also handling it through page copy is smart.

I like "You search once - we'll look forever." 

How about this?

> Hi, {{author}}!
> 
> You previously received a request for "{{article title}}" from a Open Access Button user. Great news: we have found an accessible copy! The request has been marked successful and there is no longer any action needed from you for the request.
> 
> Cheers,
> The Open Access Button team

or

> Hi, {{author}}!
> 
> You previously received a request for "{{article title}}" from a Open Access Button user. Great news: we have found an accessible copy! The request has been marked successful and you don't need to do anything for the request.
> 
> Cheers,
> The Open Access Button team

**Comment by JosephMcArthur** [comment]
Haven't been able to look yet, but if you agree about page copy can you
suggest something for what could go on the received page?

**Comment by chealsye** [comment]
Hmmm... the page copy could be as simple as stating: "This request has been successfully fulfilled. There is no more action required fromthe author(s)."

**Comment by JosephMcArthur** [comment]
Sounds good. Is the first sentence a header & the second  the sentence
after?

**Comment by chealsye** [comment]
Yeah, that's fine.

**Comment by JosephMcArthur** [comment]
Have now added the email needed for this to dev:
* emails to author
* email to user if they just searched
* email to user(s) if they requested

@markmacgillivray we need an email merge tag for the article url we're sending people to close this, though. Previously we've just sent folks to request pages and here they may not have made a request.

**Comment by markmacgillivray** [comment]
Pulling up to latest sprint I'm working on.

**Comment by JosephMcArthur** [comment]
@markmacgillivray do we have records of what old users (pre oa-week) have searched for & can they be rolled into this?

**Comment by JosephMcArthur** [comment]
Also @chealsye do we want a little nod to this feature on the website anywhere or on the plugin / /request/new pages themselves.

**Comment by markmacgillivray** [comment]
We can run the weekly check on every request we have, so that now includes
all old blocks / requests that have been loaded into the live system.

**Comment by JosephMcArthur** [comment]
Oh yeah... I think I knew that! Haha sorry!

**Comment by chealsye** [comment]
@JosephMcArthur Yeah, should do. I'll add it as a to do.

**Comment by markmacgillivray** [comment]
I don't think there is action for me here at the moment, so I am unassigning myself and moving to the next milestone, until we are ready to turn it on.

**Comment by JosephMcArthur** [comment]
Sorry @markmacgillivray, didn't make the above clear:

- [ ] we need an email merge tag for the article url we're sending people to close this. Previously we've just sent folks to request pages and here they may not have made a request.

**Comment by markmacgillivray** [comment]
Need a handlebar template tag for the email template searcher_success to insert the URL of the found available article. Then we can turn on the cron job for the weekly find, and send these email templates when things are found.

Look at testing this on the dev site - make sure any open requests have our own contact email addresses (poss delete all the dev requests).

**Comment by JosephMcArthur** [comment]
Any progress here @markmacgillivray ?

**Comment by markmacgillivray** [comment]
This is ready, but needs testing. Probably have to do that via dev, and delete all old dev records and create some that won't accidentally email real people, then @natalianorori can try testing it (this and the admin submission should trigger the success email). There are some questions around why the email templates need to differ at all, we can discuss later.

**Comment by JosephMcArthur** [comment]
How would you suggest testing the automatic finding bit here? The rest seems straight forwards.

**Comment by markmacgillivray** [comment]
If we clear out the dev site of all test requests and create a couple of new ones where we're sure natalia or someone in our team is the contact, then we can safely turn on the weekly check. Also, natalia can try uploading a file to a test request as admin, and have it automatically trigger the email to the "requestor" (which should of course also be natalia or someone on our team). As long as we know that is working as expected, we just trigger the weekly check script to run at a time of our choosing, and have it find something, and then we will see the automatic email come from that as well. To have it find something we just have to create a request on the dev system for a thing that IS actually available, so it will be found when the check runs.

**Comment by JosephMcArthur** [comment]
Okay, we may need to set up a few hours next week to do this then while we test. 

How will we create a requests for things which are availiable, in order for them then to be found by the weekly check?

**Comment by markmacgillivray** [comment]
Anything sent to /request?url=BLAH (or doi=... etc) should create a request without checking availability.

**Comment by JosephMcArthur** [comment]
How then will the weekly script pick up a "newly available copy" to close
the request? Will you just make up a bunch?

**Comment by markmacgillivray** [comment]
If we create a request on dev for something that is actually available, when the script runs it will find that thing. So that will close the request. Isn't that the idea of what we want the weekly script to do?

**Comment by JosephMcArthur** [comment]
I think I've just understood your comment about "/request?url=BLAH". Okay,
this makes sense then.

**Comment by JosephMcArthur** [comment]
@natalianorori can you read & work with mark to test this during the week

**Comment by JosephMcArthur** [comment]
Today...

@markmacgillivray, can you delete all requests on dev?
@natalianorori can you fill the dev site with requests for open access articles using the url:
dev.openaccessbutton.org/request?url=<<URL OF OA ARTICLE>>. You'll need to do this with your account & with your email natalianorori+1@gmail.com as the author email.

**Comment by markmacgillivray** [comment]
@JosephMcArthur @natalianorori all old requests have been removed.

**Comment by JosephMcArthur** [comment]
Some other things to consider here before shipping to live:
- [ ] error handling (should we add a line to the email or deal with it on the page, probably the later.)- Me
- [ ] get we get a report of what will happen before notifications get sent to users? Like we did with the old request deletion? That's handy for sanity checking & making mistakes here will probably be costly to fix. - @markmacgillivray

**Comment by JosephMcArthur** [comment]
>  how will we measure our success here vs success through directly asking authors

I'd close it, but automatically add a tag in comments as we'll allow in #587.

**Comment by natalianorori** [comment]
I have added a handful of requests in different status to the dev site. They are all under my name as the author. Some of them have stories and others don't. Let me know if you need me to add more.

**Comment by JosephMcArthur** [comment]
@markmacgillivray this looks about ready for the script to run!

**Comment by JosephMcArthur** [comment]
- [ ] @markmacgillivray implement tagging of request on closing as suggested [here](https://github.com/OAButton/discussion/issues/333#issuecomment-298389111) as a way to track success here vs other methods.

**Comment by markmacgillivray** [comment]
Await #739

**Comment by markmacgillivray** [comment]
It is ready to be turned on to check all requests every week, and where a request is found to now be available, it is set as being received and we set the URL of where it was found, and record that it was found by the weekly cron job rather than a user or an admin.

It also will send a particular email, currently set as the one called searcher_successviafind.html - however this could be disabled.

It could then be possible to search for requests that indicate they have been found by the cron task, and it could be possible to filter those to within a given date range, so an administrator could see requests that were recently closed and decide how they wish to inform requesters, supporters, and authors about that.

Let me know if this sounds acceptable, and if so reassign to me and I will implement it (possibly not until July though)

**Comment by JosephMcArthur** [comment]
@markmacgillivray so to test this before releasing onto live we could disable the email initially & run the job. Then, on the live site @natalianorori or someone else could filter for requests closed via this & chose on a case by case basis whether to send the notification. 

If that's correct, that's great & I'd say let's do that as a first step. Then, if we're happy, we can have the relevant emails be sent automatically. 

What have you done about [this](https://github.com/OAButton/discussion/issues/333#issuecomment-269971900)?

**Comment by markmacgillivray** [comment]
OK will add articleurl as a variable and enable the weekly check but with emailing turned off, then yeah you can test by searching for requests that were successful by the cron job - I can add a button to filter by that to the UI.

**Comment by JosephMcArthur** [comment]
Okay. Then when you've done at @natalianorori can you look through the resulting requests & review what's been found? Then, if all is well, **just email the requestors saying we've found their stuff**.

**Comment by markmacgillivray** [comment]
I was just finishing the bulk upload spreadsheet format and thought of an alternative here - it could be possible to run a check on all outstanding items as a bulk job, and then just show the results in the bulk jobs admin area. Then you could review the results it says it would get BUT it would not have actually changed any requests. We would then just need some addition to the admin area where the admin could "approve" that bulk job to actually update the records.

This would be quite easy to do now that we have bulk uploads via the admin area, but note it would still be all-or-nothing - if you were happy with the results in the bulk job for a given week they could easily be approved, but if you wanted to be able to select certain results and ignore others, we would need to add some functionality to make it possible to indicate that sort of thing, which would take a bit longer.

**Comment by JosephMcArthur** [comment]
Not sure if it makes sense for the long-term implementation of this to work this way - but seems sensible to test like this - no? That'll do a basic job of testing some old requests, just in case. Then, the next thing to worry about would be if the emailing to people works as expected. 

@markmacgillivray can you start the job anytime if I set up a bunch of tests on the dev site?

**Comment by markmacgillivray** [comment]
OK there is now an option on dev admin to generate a job from any requests that have not yet been received, between two dates which default to start of current week and today (and can be edited before submission). Please try using this to test some batch jobs on old requests on dev. If happy, and if bulk jobs are generally working OK, we can enable them on live soon, then you can try this on live. Once we are happy that it is working OK, I can add a way for you to "validate" a generated bulk job so that the requests themselves will be updated with any discoveries.

I had to strip titles down to simple ascii to avoid a crash problem on some foreign titles, so the titles it displays in csv output may not be exactly right for foreign works, but is close enough for info.

**Comment by JosephMcArthur** [comment]
Thanks @markmacgillivray. 

I'm going to:
- [ ] Run a batch of old request via the system
- [ ] test that data via mturk to see where we get answers wrong
- [ ] add incorrect links to the blacklist
- [ ] re-run & hope that those links are filtered
if yes: we're good to run. 

This can then be repeated weekly, or however often we'd like and we'll know we're only sending top quality stuff.

**Comment by JosephMcArthur** [comment]
archiving
