### ISSUE TITLE
search bar doesn't pick up paper keywords

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#347]
### Expected Behavior

_What did you expect it to do? - remove this note before posting_ 
- searching grinding should pull out this request: http://oab.test.cottagelabs.com/request/58fLBjEhMkmTPtpmd

as grinding is one of it's keywords 
### Actual Behavior
- doesn't come up
### Steps to Reproduce this bug
- go to /request
- search grinding

**Comment by JosephMcArthur** [comment]
Search on the new /reqeust page seems better, how're we doing here @markmacgillivray

**Comment by markmacgillivray** [comment]
It is still the same issue - if we have the keyword, the search will find it, but if we were not able to extract the keyword in the first place, search will not find it. So you can only search on keywords we know. Now that there is a filter option, that may help make it more obvious which keywords can be searched, so perhaps we can close this anyway.

**Comment by JosephMcArthur** [comment]
this is much much better now, closing
