### ISSUE TITLE
redirect /contact to /about#contact

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#354]
this allows us to delete /contact, which is currently confusing.

**Comment by markmacgillivray** [comment]
@JosephMcArthur  Why redirect? Is there anything at /contact that you want to keep? If not, can't we just delete it?

**Comment by JosephMcArthur** [comment]
/contact has existed for a long time, and I'm just cautious about deleting
such a standard page. There is nothing there I want to keep. Happy to be
told this is silly and just have it deleted.

**Comment by markmacgillivray** [comment]
Anyone doing copy can do this

**Comment by JosephMcArthur** [comment]
only links to this I can now see are from our own site on archived pages. deleting!
