### ISSUE TITLE
Use of Analytics in the chrome plugin

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#388]
I have the option to add analytics, not sure if we need them. To close this issue we need to be aware if we need them.

**Comment by meganwaps** [comment]
@JosephMcArthur , would these be analytics for us to use or would they be analytics for all to see?

**Comment by JosephMcArthur** [comment]
Us too use I'm guessing. Worth looking up.

**Comment by meganwaps** [comment]
@JosephMcArthur just done a brief Google search, and if it would help us understand how users interact with our website, it would make the user testing process and our user experience *much* easier. This could also potentially help with the issue you and I discovered regarding people requesting the login email multiple times. As you said, the more data we have for that, the better.
