### ISSUE TITLE
Explore more directions for making a request?

### ISSUE THREAD

**Issue by meganwaps** [OAButton/discussion#403]
Hi all, 

I was unsure what to title this issue since it's a question as to the users making the requests. 
Many of the requests have links which we cannot access, such as log-ins to university libraries and the like. 

Should we explore adding new instructions or maybe an infograph as to what makes a good link for us to be able to find their article?
 
I'm thinking this should fill into the 5th milestone. Thoughts, @markmacgillivray, @JosephMcArthur ?

**Comment by JosephMcArthur** [comment]
Can you give us some example requests to see this please?

**Comment by meganwaps** [comment]
Apologies for the severe delay in answering this question. I am linking the old location monitoring chart I was using, since some of the requests I mentioned above are no longer appearing on the 'Support Requests' page. 
https://docs.google.com/spreadsheets/d/1GKk_Y3wzeXLisMaC-mdS3Zx3tu_uhAoG-q05dKVjZJw/edit?usp=sharing

Look specifically at a request received on November 12th, where the user uploaded a link from, what appears to be, their university's library site. The end result is that they gave us a link which required we log in through that University. @JosephMcArthur @markmacgillivray

**Comment by JosephMcArthur** [comment]
@natalianorori are you seeing significant issues with folks not submitting the right kind of stuff?

**Comment by natalianorori** [comment]
I don't think this is a significant issue at the moment.  closing
