### ISSUE TITLE
Form to ask people who're uninstalling why

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#411]
Code to evoke this is here: https://developer.chrome.com/extensions/runtime#method-setUninstallURL

idea stolen from: https://medium.com/axiomzenteam/i-almost-lost-10-000-users-369fe9e60abc#.x797t3g9r

**Comment by JosephMcArthur** [comment]
To close add http://oab.test.cottagelabs.com/feedback#uninstall & above code to the chrome plugin

**Comment by markmacgillivray** [comment]
Wouldn't we be better adding this when it is on the live site and using a URL to the live site?

**Comment by JosephMcArthur** [comment]
Sorry, dur, that's what I mean! https://openaccessbutton.org/feedback#uninstall

**Comment by markmacgillivray** [comment]
Added to plugin code
