### ISSUE TITLE
Feels too hard to release things on an ongoing basis

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#417]
We need to have a clearer process around releasing things on an ongoing basis. We have lots of closed issues that haven't made it to users yet, but we can't ship changes to pages because they have changes that haven't been tested. 

How do we ship more regularly to users?

**Comment by JosephMcArthur** [comment]
Options:
*Perhaps at each sprint meeting we should just have an agenda item about what is ready to be released? This fails when we need faster releases though. 
*Perhaps a label would also be useful? We can tag issues that are ready for release as such when we shut them? Then, when we do a release go back and remove those issues? This feels a bit arduous, though. 
* Can we use the releases tagging framework for individual pages on github?

Deffo:

- [ ] improve this text: https://github.com/OAButton/oab_static#how-to-edit-via-github-web-ui-needs-work so that anyone feels comfortable doing a release (not just Mark, and maybe me)

Open to more ideas!

**Comment by JosephMcArthur** [comment]
Another thought. It's harder to release than it should be when we have multiple changes happening on a page at once. If one change finishes before the other we have to wait for everything to be ready on a page before we can release. Ways to address this are:
* working on only one thing at once per page (quite unrealistic I think)
* making a branch for each change (can we then spin up dev sites for each?)

**Comment by JosephMcArthur** [comment]
updated readme in static

**Comment by markmacgillivray** [comment]
Working on one thing at once per page is too restrictive, we would be crawling.

A branch for each change is possible if that helps the person doing the change - but running sites for every branch is not. If you really wanted to do this, everyone could learn how to run the site on their own laptops for dev purposes. This seems a bit too much when everyone apart from me are just doing text changes anyway though, right? I would not have thought it is too complex to see how the words affect a page whilst working on them, and they can be pushed to dev branch at any time which does update the dev site, so anyone changing content can see the actual effect at any time just by going through the dev push process.

I mentioned on the issue about milestones and monitoring and soon that it could be useful to run parallel milestones. This may slow us down a bit too, but if it helps make clearer for everyone what we are working on, then maybe it is worth it. In this case I'd think something like the following:

* every two week sprint we can have multiple milestones running

* the first time, we would look for content needing done, and put that in a milestone in the current two week sprint

* after the content milestone is complete, if it then needs dev to achieve the aims of the milestone, it can then become a dev milestone in the following sprint

* after the dev milestone is complete, it becomes available to be a testing milestone in a future sprint

* after a milestone completes testing, then at the end of that sprint is when it releases

* if a milestone requires no dev, or no content, or no test, then those could be skipped, and we go straight to what is needed

* this means that any simple change takes two weeks to release if it needs just one kind of sprint done to achieve the milestone, but would take at least six weeks for anything that requires some content, some dev, and some testing. It also introduces more opportunity for delay (more bottlenecks appearing where a particular type of resource is not available to follow up on something)

* ideally, such complexities of process are best avoided, to achieve highest turnaround. But, if we need more process to keep the team working smoothly, then the definitive trade-off is longer timelines on everything. This is never avoidable. (the argument that more process leads to more efficiency is only true if inefficient in the first place)

**Comment by JosephMcArthur** [comment]
We could also just have an issue for each release? And not things that need to be released on it. Since releasing it actually sometimes work this makes sense.

**Comment by JosephMcArthur** [comment]
Okay, here is what I'd suggest. I don't think any of the above is workable or fixes the problem. 

Instead, I'm going to do a weekly check our develop vs master on branches (on Monday's) & either release or wrangle what's needed to move us closer.
