### ISSUE TITLE
Update login UI with email status

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#424]
Once we can send mail via POST instead of SMTP, we can possibly poll the mailgun events API for specific message IDs, then it should hopefully be possible to update the login UI every few seconds with a status of how the login email is doing. If the events API indicates the message has failed, we can direct users to email us at some help address.

**Comment by JosephMcArthur** [comment]
I would like to see us do this. I'm still seeing a lot of people sending multiple emails, probably as they're confused. To implement it seems we need to see if:
- [ ] the approach mark outlines above will work @markmacgillivray 
- [ ] build backend functionality for above @markmacgillivray 
- [ ] decide on phrasing / design for the UI @chealsye 
- [ ] test - Me

Is this about right?

**Comment by markmacgillivray** [comment]
Given that the aim here is to encourage people to check their email and find their code rather than keep hitting for a new code which we have seen them do, it may also be an idea to note in the cookie that they have already requested a code, and prompt them to check instead of showing them the login box again if they refresh the page.

**Comment by markmacgillivray** [comment]
Like a five minute timeout to get their code. After that it reverts to letting them request a code again.

**Comment by JosephMcArthur** [comment]
The above is now deemed the way forwards for this issue, IDed one issue causing multiple emails as "I sent several login because I couldn't get access with the passwords that have been sent to my email.".

**Comment by chealsye** [comment]
I'm confused about this and what I need to do. I can copy, but not sure where it is needed/what's happening.

**Comment by markmacgillivray** [comment]
I think this one is fine with some timeouts and a simple message that says something like "email sending / email sent". I'll build that in, then once you see it if it doesn't suit the language style you want, it can then be changed.

**Comment by markmacgillivray** [comment]
Done, on dev.
