### ISSUE TITLE
Should we always cc users in request emails? 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#426]
Suggested in #412 for a new system, but should we do it for everything?

**Comment by chealsye** [comment]
My instinct is no. A user may use private email address, they may not want to be so clearly known by an author, the user may then follow up our email with their own message, and the email thread may not get a reply all and we lose tracking the conversation. Seems that someone might be readily just attach a copy of the article to a reply, which yes, can solve it (and maybe this is a reason to include the emails), but then it won't meet our goals and give everyone access.

**Comment by natalianorori** [comment]
+1 with Chealsye

**Comment by JosephMcArthur** [comment]
Seems like no! closing
