### ISSUE TITLE
After making a new request invite a user to send an email to an author immediately

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#427]
Building off #412 

Seems like what we need to do to allow users send the emails themselves is:

- [ ] Build an action area in the request page (I'd suggest we think about this as a more generic "action area" since we'll probably want them to do other things at different stages) and put a "email author" button in it - @markmacgillivray 
- [ ] Decide if we need to alter plugin copy to make it clearer there is stuff to do - @chealsye 
- [ ] Alter our request emails to something that would be better sent by the user (via us) - @chealsye 
- [ ] Move email sending / editing functionality from the admin page to the request page - @markmacgillivray 
- [ ] Build ability for users to start emails from our server - @markmacgillivray 
- [ ] Build a UI to facilitate users sending - @markmacgillivray 
- [ ] Find ways to monitor use of the feature - @markmacgillivray

**Comment by chealsye** [comment]
Yes, we will need to add some additional copy in if we are doing this -- both the basic nudging them to do it, but also suggested text to use. I have concerns about users sending emails, which I believe I noted in another issue.

**Comment by markmacgillivray** [comment]
Please decide copy / design changes for this. Technical capability already exists. Reassign me once ready and planned into a milestone.

**Comment by chealsye** [comment]
We never reached an agreement that this should happen. Either way this copy is the request system and no longer mine to write. @natalianorori, do you want to take it? Can @JosephMcArthur confirm that there's been an executive decision to try this out?

**Comment by JosephMcArthur** [comment]
if moderation time is short, as we're now working on, this isn't required.
