### ISSUE TITLE
Soon & Monitoring Milestones to fix small issues in workflow?

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#430]
Hi @OAButton/team, 

Some alterations to our workflow I'd suggest & would like some feedback on:

## Monitoring

Currently, in Milestone 7 we have at least 5 issues that are just us doing minor work to bugs others to push things forwards for us (this has been happening consistently for a while now). That's about 20% of what's actually in the sprint and it's likely that we won't be able to close them as they're out of our control. This stops up estimating work properly, creates busy work just moving issues and makes it harder to focus on what actually needs attention. 

I'd suggest we move issues like this to a "monitoring" milestone, so that our sprints more accurately reflect where we're able to move forwards. The alternative fix here is to use a label, this may be worth doing anyway (e.g blocked: partner) to signify where this may happen at the start of an issue. 

## Soon

Right now when an issue gets made it either goes straight into the backlog (backlog = everything we ever want to do ever) or, when I make it & want to see it happen soon, into the next milestone. However, when putting it into the next milestone I short circuit what should otherwise be a more thoughtful team decision about where our focus should lie. I don't put it into the backlog for fear of it being forever lost. 

I've made a "soon" milestone that can now act as an alternative for these situations. That means that as well as our deeper backlog we have a place where folks can see what's on the nearer term horizon & begin to think / discuss. The alternative fix here is to use a label like "priority" in the backlog to signify these. 

## Summary

These changes also help address things highlighted in retrospective comments thus by far:
* giving a clearer medium term picture of what's happening
* giving folks more direction on what to be doing when I'm away
* helping show priority & avoid blocks

Do folks like these changes? If so I need to:

- [ ] document the milestones
- [ ] update the readme
- [ ] update issues

**Comment by markmacgillivray** [comment]
A monitoring milestone makes sense. Better than a tag.

Remember too we can run parallel milestones, which may also help with the problem of knowing when to release things - every two weeks we can have a dev milestone going, and a test milestone where stuff that was dev'd in the last milestone group is ready to test. Then release happens at the end of the test milestone. If desired, there could be parallel copy milestones too, and things may not go to dev sprints until after they have gone through a copy sprint previously.

I'm not sure of the value of the soon distinction. I think of the backlog as the soon stuff, and issues that are not even in the backlog are just there to be considered at some point. So the backlog is where we look for things that we put into the next sprint. The fact that you sometimes put things into the next sprint yourself does not bother me - I assume these are your ideas, not your demands; if something goes into the next sprint that I think makes no sense, or if when we review the start of that sprint and we don't have enough time or something is inappropriate, then we just push it into backlog again for consideration at the next sprint review. This seems to work fine to me. Is anyone having particular trouble with how this is currently done?

**Comment by JosephMcArthur** [comment]
I've added a few to monitoring to give more of a taste here.

**Comment by JosephMcArthur** [comment]
I'm not a big fan of parallel milestones for all types of work, it would make it a bunch harder to track what we're doing & creates a relatively artificial distinction about how we do work. 

I'm wavering on the idea of a soon milestone. I think it makes the backlog less clear & using a "priority" label mimics what we do with sprints.

**Comment by chealsye** [comment]
Priority label sounds good. I don't have a strong opinion either way on this matter though.

**Comment by JosephMcArthur** [comment]
Okay, closing soon. will use priority.
