### ISSUE TITLE
Is anyone still using Zenhub

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#431]
@OAButton/team is anyone still using Zenhub? The thing I used it for is now done by Github natively (essentially "projects") and would suggest we just use that (to simplify workflows & provide more transparency to externals) unless someone is loving it.

**Comment by markmacgillivray** [comment]
I'm using zenhub less and less. would make no difference to me if it stopped being there.

**Comment by chealsye** [comment]
I never really used it.

**Comment by JosephMcArthur** [comment]
okay, to close this I need to:
- [ ] move all epics to projects

**Comment by JosephMcArthur** [comment]
Okay, projects is missing some really basic functionality right now

* search by things not in projects / what is in a project
* assigning to projects from an issue

which means it can't replace Zenhub for an important part of my workflow. 

Moving this to monitoring.

**Comment by JosephMcArthur** [comment]
Can do all the above now. All github epics are now issues. No longer using zenhub.
