### ISSUE TITLE
Forward all domains to openaccessbutton.org

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#439]
@markmacgillivray you have access to my godaddy account, can you forward all oab domains there to .org. Especially .io.

**Comment by JosephMcArthur** [comment]
When doing this can we do the below from #214:

Hi Joe,

Thanks for your interest in setting up a custom domain for your Medium publication.

Included below are instructions for setting up your custom domain:

blog.openaccessbutton.org

This screencast will help you through the process as well: https://youtu.be/mBY7OL7T8yk

IMPORTANT NOTE: If you're planning to migrate content from another platform using the same domain that you're setting up on Medium, you should migrate the content into your Medium publication PRIOR to setting up your custom domain on Medium. If you don't migrate the content first, permanent redirects from the old content will not be set up correctly. Read more about migrating content here: https://help.medium.com/hc/en-us/articles/218572107-How-to-move-to-Medium

The process will look a little different for each domain registrar. We will give you general instructions, followed by links to more detailed information for several popular registrars. If you still have problems, don’t hesitate to email us back for further support.

Getting Started

Log into your web hosting or domain registrar’s member area or control panel. Find the section where you can add or edit DNS record information. If you cannot find this DNS management area, we recommend contacting the company where you registered the domain to ask them where you can add CNAME and A records for your domain. 

What to Modify

To set up a custom domain with Medium, you will be adding a CNAME and twelve A records, provided below. This information will enable your domain or subdomain to point to Medium servers with an SSL certificate which we will furnish at no cost to you. 

Note: Do not modify your actual NS records (nameserver).  

CNAME

Your new CNAME record has two parts: a domain and a target. Together, the domain and the target values create one record which will enable us to order an SSL certificate for your domain or subdomain.

CNAME Domain (may also be called “Host” or “Name”): 71185d652cd50e97a917ae8c799d513d.blog

If adding the entire string with the domain name doesn’t work, try just adding the alphanumeric string (token) before your domain. (If using a subdomain, try as "token.subdomain", and leave off the domain.) For example, Namecheap, Google domains, and Gandi all follow this token-only or token.subdomain pattern.

CNAME Target (may also be marked “Points to” or “Value”): 6c015df96f292b0ee8a41ec1b492478c3d48d5ac.comodoca.com

Please add that CNAME record above and all the following twelve A record values to your domain or subdomain.

A Records:

52.0.16.118
52.1.119.170
52.1.147.205
52.1.173.203
52.4.145.119
52.4.175.111
52.4.225.124
52.4.240.221
52.4.38.70
52.5.181.79
52.6.3.192
52.6.46.142

If you are prompted to add a “Name” for the above values, you will enter either the “@” symbol (no quotes), or the domain or subdomain name of your site.

Please note, your domain or subdomain with the “www” prefix will not work by default. If you’d like to have visitors be able to use the “www” prefix in addition to using your domain or subdomain directly, you will have to create a new CNAME record with a domain/host/name of “www” (no quotes) and a target/points to/value of the domain or subdomain you will be using.

When you’ve successfully entered these new values, it generally takes 4 to 24 hours for your domain to begin working with Medium. It's normal for you to see a certificate error or a redirect to medium.com while the certificate is being provisioned.

Examples & More Info

For a screenshot of these values correctly entered for an example domain on an example registrar, look at the following post in our Help Center: 

https://help.medium.com/hc/en-us/articles/213474588

Below you can additionally find help documentation about how to add CNAME and A records for some of the more popular registrars:

Namecheap: https://www.namecheap.com/support/knowledgebase/article.aspx/319/78/how-can-i-setup-an-a-address-record-for-my-domain
Godaddy: https://www.godaddy.com/help/manage-dns-for-your-domain-names-680
Gandi: https://wiki.gandi.net/en/dns/zone/a-record
Google: https://support.google.com/a/answer/2579934?hl=en:

If your registrar isn’t on the list, you can try a Google search for “update CNAME and A records” and the name of the company where you registered the domain. If all else fails, contact customer support at the company where you bought the name for information about where and how to edit these records. 

If you’ve done all the above and it’s still not working after 24 hours, reply to this email with details and we’ll help you find the solution.

Thanks and we’re looking forward to having you on Medium!

Thanks,
Berik
User Happiness

**Comment by markmacgillivray** [comment]
OK, these settings have all been done. May take a while to propagate, so assigning to Joe who can then follow up with medium again if necessary, in a day or so.

**Comment by JosephMcArthur** [comment]
@chealsye our medium URL is now https://blog.openaccessbutton.org/. 

tested openaccessbutton.io, redirects perfectly. 

We're all done here!
