### ISSUE TITLE
Making the results page more clear that an article is available

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#441]
A Button user reported on Twitter that the Button could not locate the article even though it could. The way the search result page is set up was not clear to him that the article was available and that he could click through the view the article. @meganwaps Have you come across this problem in user testing?

![screen shot 2016-12-30 at 10 01 19](https://cloud.githubusercontent.com/assets/9299248/21562299/3729a9c6-ce78-11e6-8848-7f131663fbbd.png)

![screen shot 2016-12-30 at 10 01 28](https://cloud.githubusercontent.com/assets/9299248/21562303/3b8ed842-ce78-11e6-80c2-07ce5314df7f.png)

His suggestion is to simply add "Click here." However, I do not think that is enough. I think if someone read that line there is a good chance they'd hover and the link does change colors from blue to orange -- the bigger problem is someone's eyes scanning over it, seeing a request for the data, being confused and thinking it isn't available. I'd like to discuss how we can improve this page, the user experience, and how we communicate results.

**Comment by JosephMcArthur** [comment]
Thanks so much for the great report Chealyse. I've had a hunch this page isn't designed as well as we could but hadn't seen any issues - so didn't bring forwards. Considering it's both theoretically (as our front page) and actually (from stats) getting a lot of use vs the plugins we should invest more time here. 

We can go two routes, work on it internally with this as our base (there are several changes I think would be good or ask our designer to rethink the page from scratch (as we did with the plugin) and use that to compare / contrast our thoughts. My preference, given the importance, is to pull in some designer time to aid our thinking process. 

There are also some more "features" I think we'd do well to implement here, essentially I think improving this page could be the equivalent of a whole sprint.

**Comment by JosephMcArthur** [comment]
Can you let Richard know that we're going to make some improvements here, and that if he'd like to be looped in on them we'd love to have him give thoughts.

**Comment by markmacgillivray** [comment]
This is done on dev, it now mimics the plugin

**Comment by JosephMcArthur** [comment]
@chealsye you can now see the new find page. If you're happy to close this please do so.
