### ISSUE TITLE
send a query to other library catalogues if possible / allowed

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#455]
By @markmacgillivray from #419

**Comment by markmacgillivray** [comment]
This is possible but does not appear to be allowed. There are options in the primo search where it seems institutions can have access to do primo searches and remote searches, but I don't seem to get anything useful back from those searches, so perhaps are not allowed.

If we have another library use our tool though, and if we are whitelisted to query their catalogue, then we could query across libraries that use us.

Keeping this open as possibly useful later, but unassigning and moving to backlog
