### ISSUE TITLE
Better bug form

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#458]
Headstart: https://gist.github.com/jksdua/8540578

Need a brief discussion on this.

**Comment by JosephMcArthur** [comment]
I feel like we want a few specific forms, 
* general bug form
* form for when we point people to the wrong site 
* #438 
* uninstall form #411

**Comment by JosephMcArthur** [comment]
For some of these forms I'd advocate us having different ones as it seems like each could be quite different. Part of me thinks we shouldn't use gforms since for some of this being able to associate it with the URL of the page (or request / user ID) seems critical.

**Comment by JosephMcArthur** [comment]
Will be working on the content to close this issue here: https://docs.google.com/document/d/1F0E-nqLjjbE3yKKYtf0FxxeB_BhCxb1IoXl8qDBajYw/edit

Have started, but not completed.

**Comment by JosephMcArthur** [comment]
Okay, there is significant progress here that should help @markmacgillivray work on the code needed.

**Comment by JosephMcArthur** [comment]
Assigning @chealsye to refine copy

**Comment by markmacgillivray** [comment]
@JosephMcArthur is it still worth having this AND the zendesk help functionality? I may leave this for now, but then if we decide not to stick with zendesk, can implement this (and probably any useful zendesk features) if we set some time aside for it.

**Comment by JosephMcArthur** [comment]
We still need this I think.

**Comment by markmacgillivray** [comment]
ok

**Comment by JosephMcArthur** [comment]
To make clear why, an easy 

>  form for when we point people to the wrong site

makes me happy closing #107 which is important.

**Comment by markmacgillivray** [comment]
The bug form page is functionally in place, and I have made the dnr form as the first example. I will complete the others from the google doc soon. it is extensible, so now you can fairly easily add new forms by just copying the structure in the page.

I have made the DNR page itself just do only the email DNR, but then it says thanks and asks if the user will complete our survey. If they click through, then they get the DNR form.

@JosephMcArthur what is supposed to happen with the form data? Do you want it sent in to zendesk, or to an email address? Let me know so I can complete the functionality.

**Comment by markmacgillivray** [comment]
The bug form page is now complete, any further editing or new forms can now go direct in the /bug page. All I need to know now to close this issue is what is supposed to be done with the bug data once we receive it.

**Comment by chealsye** [comment]
@JosephMcArthur @markmacgillivray Sorry for not getting to this issue earlier. Do you need me to read through the form to double check copy?

**Comment by JosephMcArthur** [comment]
Yes please @chealsye. Feel free to suggest extra / fewer Q's, options, and of course copy changes. 

- [ ] copy approved

@markmacgillivray this is wonderful progress, but I don't think quite ready to ship today. Some questions. In the current set up:
* can we link directly to a form type (e.g via url #). This allows us to close #411 
* can these forms be embeded in other pages so folks like authors don't need to click off a page to complete it? I'm specifically thinking of "a form about why you can't share something" here. 
* can these forms be hidden from a user on /bug (so they can't chose them, and we'd only be able to directly link to them)

To answer your question Mark, the _ideal_ is to deposit in a gform with some ability to notify (which can be done via the gform). However, an email with content would be fine, we can ifft to a form & format.

We may want to change the "file a bug" page to "feedback" since it'll do feedback & bugs for all users. Thoughts on that @chealsye / @svmelton?

**Comment by markmacgillivray** [comment]
yes you can link directly to a form type, it explains how in the comments on the bug page.

The forms cannot be embedded in other pages - you should link to the form you want from a given page, using the form type as the #, and passing any necessary params as url params. Also explained in the comments of the bug page.

Particular forms can be hidden, they don't have to appear in the select bar, but will still be accessible directly via the url # 

The ideal seems weird - why make forms just to submit to google forms? You could have just made more google forms. Why not submit the forms into github issues or zendesk, plus an email alert to wherever you want it sent?

If this is not ready to go live yet then I will just make the bug page back to how it was and move the new functionality to a page called feedback, as you also suggest naming it that anyway. Then later once complete the bug form page can redirect to the feedback page.

**Comment by JosephMcArthur** [comment]
Based on what you said above (helpful info, thanks):

- [ ] can we display the #<page> in the URL for users. 
- [ ] hide remove your email from list
- [ ] hide browser extention uninstall from list
- [ ] hide you can't share from list
- [ ] submit general feedback / uninstall / dnr feedback to zendesk
- [ ] submit general bug reports to github issues & notify help@openaccessbutton.org (to make it easy to follow up and thank)
- [ ] submit "wrong link" info to github issue & notify help@openaccessbutton.org (to make it easy to follow up and thank)
- [ ] send a notification about "why you can't share something" to requests@openaccessbutton.org.  & save data alongside request data in request system 

Good idea on just moving to /feedback for now. When ready to push (on approval of copy) lets:
- [ ] forward /bugs to /feedback
- [ ] replace links in plugin / site with /feedback

- [ ] Are we getting a general bugs form back too?

**Comment by markmacgillivray** [comment]
For the general bugs form, it just needs a bug form added to the feedback page and the user can select submit a bug" as one of the form options.

**Comment by markmacgillivray** [comment]
How do I submit to zendesk? Is there an email address I can just send the JSON object to?

**Comment by JosephMcArthur** [comment]
For zendesk, you can send stuff in through help@openaccessbutton.org. They also have an API if you'd prefer that: https://developer.zendesk.com/rest_api/docs/core/introduction

**Comment by JosephMcArthur** [comment]
I've updated the content here

**Comment by JosephMcArthur** [comment]
are these responses going somewhere right now?

**Comment by JosephMcArthur** [comment]
On https://dev.openaccessbutton.org/feedback#wrong we need a box to actually tell us the URL the user was sent to, or the article the searched for. 

I thought this was just grabbed automatically, but it's not actually present at all.

**Comment by JosephMcArthur** [comment]
Currently /feedback#bugs has a submit bar at the bottom (but it's a gform). My prefered way to fix this is to just have the form be properly done.

**Comment by JosephMcArthur** [comment]
@markmacgillivray the content here is fine, but there are some questions I have above

**Comment by markmacgillivray** [comment]
The feedback form is hooked up to send emails to help@openaccessbutton.org. It does not send anything to github issues yet, but should be testable and if issues are required, they can be made by whoever receives the help address email.

I have changed the google form to an actual form on the page - the idea is you copy the other forms already there to make new ones.

For feedback#wrong has anyone decided yet where that is going to be linked from, what the content around it will be, how the user will be using it? If that is known, then the wrong URL can be passed in the link that sends the user to the feedback page.

**Comment by JosephMcArthur** [comment]
> I have changed the google form to an actual form on the page - the idea is you copy the other forms already there to make new ones.

Thanks! I thought that was the case but wasn't sure as the idea for this one was we'd be grabbing as many things as we can from the browser, not the user. 

> For feedback#wrong has anyone decided yet where that is going to be linked from, what the content around it will be, how the user will be using it? If that is known, then the wrong URL can be passed in the link that sends the user to the feedback page.

They'll be coming primarily from the homepage search box. So, if we can show a box with what they searched, what we sent them to, then the Q's we have now that would be perfect. I'd suggest we always show these boxes, but, just fill them with the content if we have it (perhaps grey them out or something like that). That tells the user we know, and allows manual filling if needed.

**Comment by markmacgillivray** [comment]
Can you put the question in place where you want it to be with wording / positioning etc, then I will make it link to the feedback form properly

**Comment by JosephMcArthur** [comment]
Should be syncing / deploying now

**Comment by JosephMcArthur** [comment]
Will now autopopulate!
