### ISSUE TITLE
stories export this week

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#459]
@meganwaps and I need a sheet (or something convertable too) of:
- [ ] all stories + user type + username + type (data / article) + article link for all of time
- [ ] the above since oaweek relaunch
**by the end of the week**

Ideally, a way to do this via the UI would be great in the long term.

**Comment by JosephMcArthur** [comment]
Note, I've updated the request above

**Comment by markmacgillivray** [comment]
Done, sent to Joe
