### ISSUE TITLE
Increasing Full Text link-through

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#461]
We still regularly link to splash pages instead of real full text (HTML or PDF), clearly, this isn't ideal. We assume users would prefer just to go straight through. Having discussed how to do this with @markmacgillivray we noted that:

* While this only affects a subset of papers it is none the less has been a significant proportion in our usage. I.e this feels worth doing if possible. That said, this doesn't actually find users MORE open work, it just makes it easier. 
* Doing this would increase the time needed to find articles
* The way to do it would be regex, or set of regex's, that would look for links to PDFs & full text on the page. This is fine in principle, but in practice will backfire as we're likely to miss times when it would be possible as we've got the wrong regex or go to links that aren't right. The way this has been addressed previously is to maintain a list of domains for each domain. Usually, this has been a manual effort where someone basically maintains the right regex for the right domain. 

In thinking about this after approaches to this could be:
* recognising this effort would benefit many & try and have others help in this effort or at the least make the information easily reusable
* brute forcing this by using scaleapi or mterk style services to track them periodically via an API. This might cost some money but would probably be easier.

**Comment by markmacgillivray** [comment]
Note that the maintenance of a list of regexes for domains does not have to be a technical effort - all it needs is a google spreadsheet where anyone with admin skills just has to manage a list of regexes per domain, and even the regexes can be extremely simple, and in many cases probably just a normal human readable string.

Brute force approaches are unlikely to get round the problem - to achieve them, we would need a definition of what it means for the regex to correctly identify a link that goes to the right content, and that is what the hard part is; we could automate a check that the right strings still exist in the pages where we expected them to exist, and that they go to pages that can be accessed and that do return a long document that appears to be a full article, but we could not do things like find new strings that lead to the right things, or find changes to strings, or identify where strings that are in links actually take us to content that appears right but that actually is not. Over time, we can certainly reduce the human intervention as far as possible, but there will probably always be some degree of human oversight.

**Comment by JosephMcArthur** [comment]
Not, one librarian suggests that a rate <90% isn't acceptable here.

**Comment by JosephMcArthur** [comment]
From chat yesterday:
- [ ] Cross reference repo list we pull from against opendoar to find the tech underlying each - then match against repo-redirect sheet

By doing this we can scale our error avoidance & full text dramatically.

**Comment by JosephMcArthur** [comment]
This issue is now about scaling what's done in #560. 

## Previously suggested in #642 

from #592 

> What are our options for catching login repo's before they get reported to us? Right now, we have a responsive solution (we find a login wall & we fix it). I've highlighted a base page which we can use to be proactive (manually) in another issue. That's helpful, but still pretty work intensive.
> 
> In terms of trying to avoid login walls & link to full text more automatically, proactively, can we implement a version of the oadoi script, or other methods, to catch these errors more? Perhaps, for example, if we can't do this on the fly (because it would add too much load time on search for a user) before we've seen a repo we could run the script for the repo after the first time a user lands there (similarly to how we cache results now)? This stops us needing to spend ages building our own local copy initially, but helps us get better over time still.
> 
> So, the logic here would be:
> 
> user searches
> user lands on a repo page we've sent them to, probably a splash page (maybe a login page).
> we save the url we sent them to
> ... later
> (if we don't already have a redirect) we go to the URL & take a copy of the page locally
> we run a script over it to see if we can grab a .docx / .pdf file (perhaps by checking commonly used metatags we've built up manually)
> if yes, we add a redirect telling us to do this on the fly. We could also tell it to not send a user to a domain that doesn't look like a .pdf / .docx (or, generally, things that look like login pages)
> if no, flag for manual review\

### Mark's response

> I think this is a pretty flaky approach. How will you know if you have found a link to a pdf or a docx? They don't necessarily end with those suffixes, or any suffix at all. And even if you find the link, you don't know it is accessible unless you try to access it. And even if you do access it, how do you know you're getting the full article and not just a paywall stub? Some services may properly return the item as a pdf or docx and specify that they are returning that kind of content, but many will not.
> 
> That's the problem - what LOOKS like a login page?
> 
> We could use the oadoi script to pre-flag a bunch of domains just like we are doing now, and build on that approach to flag places we think require login - but even then, how flaky is their script, and how accurate is it? Does it blacklist entire domains, or specific pages on those domains where things may or may not be available with or without login? Of course we can investigate their script to find out more detail, but that in itself would have to be the first time consuming step.

> We will need a specific review of the spreadsheets we are using to track the various kinds of sites we want to block, and how we want to block them - the use cases we envisaged have already come up short in terms of how people have actually used them. And then we will need to decide how to proceed with those ways of flagging inaccessible content, and also how to review them - e.g. if they are embargoed and become unembargoed, as well as having a look at the oadoi script and deciding how its results fit with our desires.
> 
> There is really a fair bit of work involved here, and we should expect it to take an entire two week sprint at least, and the real difficulty is scheduling that in along with everything else we want to do. As we are focusing on what Natalia needs for the next four weeks, that means this is unlikely to see any progress until May at the earliest, so I'm dropping it out of the current milestone, as it is beyond the original scope.

# Path forwards

Scaling our human moderated approach with https://github.com/OAButton/discussion/issues/461#issuecomment-301752843. 

To do that I need to:
- [ ] test dataset with a mix of DOI's, URLs, title as inputs. In that I also need to look at data that shows a tradeoff between recall and accuracy. 
- [ ] look at opendoar dataset #823 and try and automatically generate redirect links that work at a small scale
- [ ] See how to handle bugs in the above due to likely poor opendoar data
- [ ] respond to previously flagged issues in mturk & from users
- [ ] set up redirects for all repo systems (~20)

@markmacgillivray we'd also want to consider a split between dev / producation on the redirects sheet as I expect we'll want to test things on dev before pushing to live.

**Comment by JosephMcArthur** [comment]
Completed, closing.
