### ISSUE TITLE
Searching for accounts by email no longer works on /admin

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#462]
For example:
* joe@righttoresearch.org
* natalianorori@gmail.com 

no longer pull up their addresses for me, but searching their account names does. Interestingly, searching part of their email address seems to work.

**Comment by JosephMcArthur** [comment]
@markmacgillivray is this fixed by new search?

**Comment by markmacgillivray** [comment]
Fixed as long as quotes are used around the email address
