### ISSUE TITLE
System logs admins out and changes cannot be saved while managing the request system

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#463]
After about 15-30 minutes in the system, the system logs me out automatically and I cannot save anything in the request system.

**Comment by markmacgillivray** [comment]
I've seen this too, I need to add a check to the page refresh to get it to properly check that the current user has admin rights before showing the admin controls. It's not a security issue though, just a UI experience that needs improved. Will prioritise if it's now affecting other people needing to use admin functionality.

**Comment by JosephMcArthur** [comment]
I haven't seen it, but anything we can do to make the ability to manage requests easier I count as high importance. 

Would consider adding to 8. Will let you chose how to handle from here @markmacgillivray

**Comment by JosephMcArthur** [comment]
@natalianorori a temporary fix right now is to log in & out right?

**Comment by natalianorori** [comment]
@JosephMcArthur  yes that usually fixes it, and if logging in and out doesn't work restarting the web browser does it

**Comment by markmacgillivray** [comment]
this has been fixed
