### ISSUE TITLE
Reject "author email" if it matches any emails supporting or making the request

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#467]
* Idea from @natalianorori. 
* We'd need to run this against our backlog of requests. 
* Will need a simple user visible response / advice -@chealyse @markmacgillivray. Often I think people do this to "test" the system, our advice should take this into account.

**Comment by markmacgillivray** [comment]
Why would an author email match any emails supporting or making the request though? This can only be the case if the request creator or a supporter manually entered their own email address in that field. If users are doing this, then the priority should be to find out why they are doing so rather than blocking them from doing so. I suspect if they are doing so, it is because they wonder why requests exist but do not appear to get processed.

**Comment by JosephMcArthur** [comment]
I think it's partly because users get confused (the field used to be just
called "email", which I changed but didn't correct any errors), partly
because they want to test the system (as I'm often told people so this) &
probably a handful of other reasons - of which yours could be one too.

Either way, this feels like a point at which we can put a safe guard in
place (and reduce time needed to check for this error while managing the
system) & educate users on what the system is doing.

**Comment by markmacgillivray** [comment]
Perhaps, but we should still focus on why users feel the need to test the system - maybe we are not giving them enough info on how it works, what happens after they create a reqeust, etc. I still think we could do with a lot more info around that, one of those gif/screengrab things we discussed, that explains that after they create a request and provide an email address, that we will then moderate then email that address and ask the author to provide the content.

**Comment by JosephMcArthur** [comment]
Lets do both. Simple safeguards like this are useful - but in no way a
substitute for making sure we're properly explaining things in the first
place. I'll make an issue for what you're suggesting.

- [ ] make an issue

**Comment by natalianorori** [comment]
just a note in here,

most of the requests with the same email in both author's and user's fields
are from June 2016 and earlier, this means, before our major update. At
that time, our users might have not been clear about the button and felt
the need to test the tool more than they do now and perhaps that's why they
entered their same email adress, to see if the system worked.

**Comment by markmacgillivray** [comment]
Done, on dev. If an email being entered into the request page matches the address of the current user, the address of the creator of the request, or the address of anyone who supports the request, or the address is on our blacklist, when the save button is pressed no save happens and the email address is removed. A help message appears below the email box saying one of:

Sorry, {{EMAIL}} matches the creator of this request, so this cannot be the author email address we should contact

Sorry, {{EMAIL}} is your email address! We need an address where we can contact the author. Are you the author? If so, please see below

Sorry, {{EMAIL}} matches the address of someone who already supports this request - as such, they cannot be a suitable author to contact to request access

Sorry, {{EMAIL}} was added to our block list on {{DATE}}. We cannot send email to this address';

Note this also relates to issue #482 which also checks emails are valid.

Note too that any old requests that are already in the system with a wrong email address will still exist - you'd have to go through them and fix those. However I have added a button that allows you (an admin) to blacklist an email address, and then after that no new requests will exist with that email address and anyone trying to type one in will get the blacklist msg.

I think this closes this issue, but maybe you want to review.

**Comment by JosephMcArthur** [comment]
Passing over to @chealsye to approve / edit copy

**Comment by chealsye** [comment]
Suggested edits:

> Sorry, {{EMAIL}} matches the creator of this request, so this cannot be the author email address we should contact.

Just added the period.
 
> Sorry, {{EMAIL}} is your email address! We need the author's email. Are you the author? If so, please see below.

 Side question: What is "please see below" referring to?

> Sorry, {{EMAIL}} matches the email of someone who already supports this request. They cannot be a suitable author to contact to request access. 

> Sorry, {{EMAIL}} was added to our block list on {{DATE}}. We cannot send requests to this email.

Punctuation change.

**Comment by markmacgillivray** [comment]
OK, copy changed. Please see below refers to the note further down the page that says if they are the author to please contact us.
