### ISSUE TITLE
When mailgun notifies us of failure to send to author - note in request system

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#468]
Note, the fix for this could be a line on a spreadsheet - not built into back end (at least at first)

**Comment by JosephMcArthur** [comment]
- [ ] v.1 of this is just to send a notification to natalia

**Comment by JosephMcArthur** [comment]
Note: no failure email currently send for logins / requests to authors

**Comment by JosephMcArthur** [comment]
Current thoughts here. If we get an error from mailgun for a request we should revert it to "help". Somehow, we need to flag for an admin that the original email failed. For this #477 is needed.

**Comment by JosephMcArthur** [comment]
@natalianorori for now checking the logs here: https://mailgun.com/app/logs/mg.openaccessbutton.org?skip=0&search=requests%40openaccessbutton.org&token=W3siYSI6IGZhbHNlLCAiYiI6ICIyMDE3LTA0LTEyVDA5OjU5OjI0LjM0OCswMDowMCJ9LCB7ImEiOiBmYWxzZSwgImIiOiAiMjAxNy0wNC0xMlQwOTo1OToyNC4zNDgrMDA6MDAifSwgWyJ4IiwgImYiXSwgInJlcXVlc3RzQG9wZW5hY2Nlc3NidXR0b24ub3JnIiwgW1siYWNjb3VudC5pZCIsICI1NzA2NjY0OTc4ZmExNjEwMmYwMzQ4ZWQiXSwgWyJkb21haW4ubmFtZSIsICJtZy5vcGVuYWNjZXNzYnV0dG9uLm9yZyJdXSwgMjUsIG51bGxd might be a way to go about this.

**Comment by JosephMcArthur** [comment]
@markmacgillivray is it possible to get v.1 working for @natalianorori quickly?

**Comment by markmacgillivray** [comment]
This is done on dev, will start emailing from live as soon as api is updated
