### ISSUE TITLE
Add dev badge to dev environments

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#470]
I can't be the only one who mixes up our dev / production environment while testing (or using) our stuff from time to time. 

There is a suggested fix for chrome plugins here: https://textslashplain.com/2016/10/03/useful-resources-when-developing-chrome-extensions/. Extract:

>The code to add to your background.js file is straightforward and works even if the background page is not persistent:

> // Our background page isn't persistent, so subscribe to events.
 chrome.runtime.onStartup.addListener(()=> { init(); });
 > // onInstalled fires when user uses chrome://extensions page to reload
 chrome.runtime.onInstalled.addListener(() => { init(); });

` function init()
 {
   // Add Badge notification if this is a dev-install
   chrome.management.getSelf( (o)=>{
     if (o.installType === "development") {
       chrome.browserAction.setBadgeText( {text: "dev"} );
     }
   });
 }`

Would be nice to add similar images to the dev site & bookmarklet images

**Comment by markmacgillivray** [comment]
Our dev and live sites and plugins already have similar code so that they know which API to talk to. So I can add something to that to show a dev badge when on dev.

**Comment by markmacgillivray** [comment]
Please decide content / imagery to be used here then reassign once available.
