### ISSUE TITLE
Importing story rating into our dataset

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#473]
We now how nearly 1000 stories from our database rated. These ratings could be used to dynamically generate content on the site (i.e we can show a daily story on the front page, and know it'll be good). Or, generally do some quite interesting things. 

We have a sheet of stories & their ratings here: https://docs.google.com/spreadsheets/d/1vLiIwVwAEnTDKKsx0OFQwQX8O5T06DbLPY7xzD2vLqQ/edit#gid=1377153233. Can this be imported into our main database?

**Comment by JosephMcArthur** [comment]
We should also have a box for story rating as part of moderations. If a story is good, we'll display on /request

**Comment by markmacgillivray** [comment]
trying to match the stories back to records is unfortunately difficult by story - I have run it on live, but it could only match 507 of them. A fuzzy query could be used, but risks putting the wrong rating on some stories, if indeed it manages to find more. There are nearly 1000 rated stories, so there must be nearly 500 not matching.

Unfortunately, as the "what makes a good story" exploration was not intended to be used to feed back into the system, there may be little we can do about this. However, the UI has been updated to have a rating box that admin users will be able to see, and edit, so whenever we make the latest dev UI live, it would be possible for ratings to be added manually, and for new ratings to be added directly to requests.

For now though, I think this may be all we can do.

@JosephMcArthur - what rating is sufficient to count as a good story? Is it a rating of 3 and above? Also, if a request does not have a story rated 3 or above, should that request show up on /request at all? If yes, what should it show in place of the story? We did talk about not showing them, or boosting up the rankings those that have better stories, but if we do that it may be a bad user experience for people creating stories - if they go to look at the list on /requests it would not be clear why their request is not appearing at all. So, I think some sort of placeholder text is necessary, like "Access requested - story needed". If you can let me know what would suit there, then I can add that to the dev UI updates, and we can push it live soon.

**Comment by JosephMcArthur** [comment]
A fuzzy query would probably be okay, surely if it's close that's okay? 

> what rating is sufficient to count as a good story? Is it a rating of 3 and above? \

Yes

> Also, if a request does not have a story rated 3 or above, should that request show up on /request at all?

Yes

>If yes, what should it show in place of the story? 

Not sure, your call. We just shouldn't show it. 

> We did talk about not showing them, or boosting up the rankings those that have better stories, but if we do that it may be a bad user experience for people creating stories - if they go to look at the list on /requests it would not be clear why their request is not appearing at all. 

Yes, we have to show something. I think right now we can't just "boost" good stories to the top. 

> So, I think some sort of placeholder text is necessary, like "Access requested - story needed". If you can let me know what would suit there, then I can add that to the dev UI updates, and we can push it live soon.

I don't think we can request stories after the fact.

**Comment by markmacgillivray** [comment]
A fuzzy query might be ok, but it would take a lot of testing to find out. It would probably be more efficient to just type in the 500 ratings to their related requests manually, if someone has the time.

For the other points, I can update the request listings

**Comment by JosephMcArthur** [comment]
Got you, we'll just re-rate.

**Comment by markmacgillivray** [comment]
OK, stories rated 3 or greater, will now show their story as the big quote, but if less than three, it just does not show the story - still shows title and info about the user, etc, so that works OK. For now too, while not many stories are rated, it will also show stories that have no rating - this can be changed any time.
