### ISSUE TITLE
Searching from citation

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#474]
For a while I've thought that searching from citations might be a nice addition to our front page box. Ian Mulvany just wrote a blog that would be helpful with making this happen I expect: https://medium.com/@ianmulvany/reverse-doi-lookups-with-crossref-ae2d9b671999#.r3l22xlhi. 

It's worth figuring out when we think someone might put a citation in the box before implementing this, but, leaving a note for discussion.

**Comment by markmacgillivray** [comment]
We do already have the crossref API in our box of tricks, so doing this would be very easy. The question rests on the use case - would anyone ever copy and paste a whole citation into that box? Also, we have no idea how accurate it would be, and how much it depends on the format or completeness of the citation that the person pastes.

**Comment by markmacgillivray** [comment]
This is possible but requires design and content decisions for surfacing it on the UI

**Comment by JosephMcArthur** [comment]
this is shipping & seems okay (from my limited testing). Has error management, and will hot-fix where needed.
