### ISSUE TITLE
How should we manage requests without story?

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#475]
Many requests submitted before our last story don't have a background story on them, how should we handle these requests? Authors will always want to hear why their articles/ data are needed

**Comment by JosephMcArthur** [comment]
It's worth noting that requests like this will almost certainly be pre-oa week 2016 too.

**Comment by JosephMcArthur** [comment]
Okay, so, I'd suggest that we send requests without them and use this as a way to test if stories are ACTUALLY important for authors. We've always assumed they are, but lets get some empirical evidence. Other groups (e.g researchgate) don't use stories. 

We'll need a new email template that tests this & allows requests to be sent without a story. This can also be used where the story is weak. 

Assigning @chealsye  / @natalianorori to work on this.

**Comment by natalianorori** [comment]
I agree with this. I will work on a template and send it to you both @chealsye @JosephMcArthur

**Comment by chealsye** [comment]
Thanks, @natalianorori.

**Comment by natalianorori** [comment]
here is the draft: https://docs.google.com/document/d/1JiEQR0vI1kNPsSIIICStN_Tvx13ibrZAi7dz15Py6jc/edit 

It's almost the same as our original email, minus the story. It's already on the email's folder at the drive for you to review it


@chealsye @JosephMcArthur

**Comment by natalianorori** [comment]
@JosephMcArthur nudging you on this since I am blocked and currently managing old requests (which often don't have a story)

**Comment by JosephMcArthur** [comment]
I'd suggest shipping the new author email ASAP (even if not 100% happy, it
looks good) and then using that as the basis for this.

**Comment by JosephMcArthur** [comment]
Just reopening to be sure here, has it been decided & copy uploaded for an email that is similar to the new first email but just doesn't have the line about the story? 

Closed if so

**Comment by chealsye** [comment]
@natalianorori said in a document comment, I believe, that she would simply remove that sentence from the new email to the author. It is an easy edit for her, so the problem is currently solved but we may discover another route in the future.

**Comment by natalianorori** [comment]
@chealsye yes, that's right. This is my suggestion and from my point of view, the easiest solution at the moment. We could see how this works and re-evaluate it in the future.

**Comment by JosephMcArthur** [comment]
@natalianorori is it helpful to make a template for this too? Just so you don't need to remove the line each time! Will only take a second. :)

**Comment by natalianorori** [comment]
yes !! here is the template
https://docs.google.com/document/d/1C3asYRSbm0a1hww1yAsi9q2R4w7LU2Dwd95fnJNCuf0/edit

thank you Joe

**Comment by chealsye** [comment]
@JosephMcArthur is this up?

**Comment by JosephMcArthur** [comment]
this is now up, needs syncing. 

@natalianorori please check it does what you expect
