### ISSUE TITLE
Need to find a way to track the time it takes to handle each request 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#476]
Any ideas on ways to track this,  would be very helpful for management of the request system. 

Hi! Thanks for filling an issue! Here are some tips on writing great issues. 

### Expected Behavior
*What did you expect it to do? - remove this note before posting* 

### Actual Behavior
*What's it doing? - remove this note before posting*

### Steps to Reproduce this bug
*Please include any info about the version of the tool you're using and your system. - remove this note before posting*

* Hardware versions:
* Software versions:
* Steps to reproduce:

## Feature request

For a great feature request note:

* Be specific
* Make why you'd like the feature clear
* Make clear when you'd consider a feature "done"

## Use case template
* **Person** wants to **do something** because **reason** *

A blog on ace issues: https://www.zenhub.com/blog/best-practices-for-github-issues/

**Comment by markmacgillivray** [comment]
What do you mean by the time it takes? The time the system takes to run something? Or the time from when the request is created to when it is closed? Or the time you spend doing work related to a particular issue?

**Comment by natalianorori** [comment]
The time I spend doing work, specially from changing a request from help status to progress, which is the hardest part of working with the system. I figure a good time tracking software would do the trick. This is mostly to enhance my performance and learn how to be quicker while managing the system. 

Although it'll also be interesting to see how long it takes us to close a request in the future

**Comment by JosephMcArthur** [comment]
Discussed this with Natalia last night in our 1:1. I suggested a line on a spreadsheet would probably be just fine for now.

**Comment by JosephMcArthur** [comment]
Are we good to close this @natalianorori

**Comment by natalianorori** [comment]
yes! closing
