### ISSUE TITLE
track request history

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#477]
Do we track / monitor changes to a request over time. I'm having trouble explaining this, but, can we say that (for example):
* Request X target was changed from [email] to [email] at x by Z.
* Request X was moderated by Y at 12:01.
* Request X was received at 13:01. 

I think at some point we should expose this (alongside email text we're sending / receiving) kind of like a issue history but for right now I'm wondering if we can track & export this type of data for our own use.

**Comment by JosephMcArthur** [comment]
The original comment here is extremely close to #587. Let's focus this issue less on data collection and more on visualisation. 

In my user test with @natalianorori she highlighted several times (in different ways) that understanding the history of a request would be helpful. She wanted to understand what had happened at different points (rather than referring to her file) and sometimes just double check that something had infact happened. 

I'd suggest, on individual request pages we have a "history" list, currently just for admins, that showed all the activity around a request. This would detail everything that happened for a request, from:
* moderation & sending to authors
* adding of support
* data on a request being changed

Eventually, I'd like to see all users be able to see this. But, lets refine by keeping with admins for now.

**Comment by markmacgillivray** [comment]
This won't fit in the current milestone, so unassigning until it can be fit into a later one.

**Comment by markmacgillivray** [comment]
Also add a "notes" box to each request, which should be editable in the admin area of a request page, and changes to which should also be tracked.

**Comment by markmacgillivray** [comment]
Backend for recording changes to requests is in place (on dev) - but how do you want it surfaced to users? What do you want to be able to do with it? I think this has to become a @natalianorori / @JosephMcArthur discussion, then let me know, then can reassign back to me and I can implement on the dev UI.

**Comment by natalianorori** [comment]
I think that this "history visualisation"should only be available for admins to see. The reason why I need this is because It would give me the ability to see all the changes and history and emails that we have sent through the system with each request, more accurately than the spreadsheet lets me do it. The "notes" box on each request would allow us to write specific changes that we later can get back to whenever we follow up with the request. I mentioned to Joe that using the request system data spreadsheet where we used to track everything is not as efficient anymore because a) it takes a lot of time to be tracking everything down and b) a lot of human errors can happen (forgetting to add data, etc) and c) we have managed hundreds of requests and if we plan to do bulk, the spreadsheet just won't do it. 
Having a history of 
- emails sent and dates/hours when we sent them
- mailgun dropped emails
- email responses
- changes on requests status and time and dates where these changes happened
- a box to add notes
would be enough at the moment. This would replace the need for a spreadsheet and save us time

Once we push all changes currently being developed with the system to live, we can move forward with this issue, since I know this process might be complicated and take some time.

**Comment by allanaaa** [comment]
@natalianorori and I were just chatting about stats, and I have some ideas to bat around: I would love to use this data for blog posts, or perhaps an annual report? 
I don't think we *need* to offer any of this in-site, as long as we can just grab a dataset as required - just throwing this out there as a use case.
I think we could report on our general average, or as a comparison over time (e.g. improvement over 1 year), essentially depending on what tells the best story.

I'd want the following metrics (most of which I think we can already calculate):
- Our success rate (% of completed requests that are available vs. refused or unable)
- Our processing times (time from submission to completion), as well as broken down (average author response time, average time needed to fix a "needs help" request)
- Rates of false positives & false negatives
- A collection of author responses when items are made available (especially if we inspire authors to archive other publications than just the one we requested)
- Our rate of DNR and/or of uncontactable authors
- Rate of "support" on requests
- Things that may correlate with success rate: using the authors' name, # of followup emails sent, length of story, keywords in story, type of email (gmail vs. .edu?), type of user, & other unproven hypotheses I have
- A text-mining set of all stories could be useful (I promise not to generate any wordclouds).

**Comment by JosephMcArthur** [comment]
Thanks for this @allanaaa. I'm going to move your comment over to discussion over to #587. This request really focuses on visualising requests history, rather than what to track in aggregate. 

So, with that done, I'm looking at Natalia's comment: 

> I think that this "history visualisation" should only be available for admins to see.

I agree. And I think this can be fairly simple. Long term, I'd like this to be public for everyone to see, but for now (while we tweak and explore the usefulness) lets limit. 

I feel like what Github does around updating issues is pretty close to what I'm imaging. So, we might expect a single line on the admin UI for a individual request to show:

Email was changed from "bob@gmail.com" to "bob2@gmail.com" by <<user>> at <<time>>
Email was sent to "bob2@gmail.com" by <<user>> at <<time>>
Email was received. 

And essentially this could just stretch down the page endlessly (with the more recent change up top). We may need a little "request history" header somewhere. 

For now, lets have that UI show whatever we're tracking, and in other issues can make clear what needs to be tracked. However... that is still a lot of info here in this issue about the broader use case & what is actually useful to track. In short, not just changes in request data, but also the actions taken (e.g email sent) is useful to track. 

@markmacgillivray please let me know asap if this is what you need here.

**Comment by markmacgillivray** [comment]
Implement with #739

**Comment by markmacgillivray** [comment]
Request history is now being recorded on dev changes. However, laying out the history on the admin page in a useful way will take a bit more work.

**Comment by markmacgillivray** [comment]
Currently dev site will display a simple JSON object showing changes. But does not succeed in recording which user made the changes.

**Comment by JosephMcArthur** [comment]
I can live with not know _who_ made changes. @natalianorori my understanding is that even the current "prettyness" of the system is okay. Therefor, I think this can be shut. 

My assumption is, going forwards, anything that we figure out we want to track in #578 can be displayed here

**Comment by natalianorori** [comment]
@JosephMcArthur I would like to know who made changes in the future, but due to the limited amount of dev time we have right now, I wouldn't focus on this now.

**Comment by JosephMcArthur** [comment]
Got you, makes sense @natalianorori. I've made stub issues for points not covered by this but can be dealt with later - so closing.
