### ISSUE TITLE
Is there a way for the "author's email" field to only accept email addresses? Sometimes users put names instead of email addresses, or random letters. 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#482]
@markmacgillivray @JosephMcArthur

**Comment by markmacgillivray** [comment]
Yeah, to some extent, we can verify that it is an actual email, but it is harder to know if it is an email that actually goes anywhere. It won't take long to do this, but we're about to be quite busy with Library stuff, so should schedule this in to a milestone in a few weeks.

**Comment by JosephMcArthur** [comment]
We'll need a bit of copy to provide feedback to the user on their error here

**Comment by chealsye** [comment]
Where is this copy going?

**Comment by JosephMcArthur** [comment]
Somewhere around the email box on request pages I expect.

**Comment by markmacgillivray** [comment]
This has been added on dev, and now it will not accept an email address that is invalid, including if it does not actually go anywhere, or if it is on our blacklist. When someone tries to save, the email address is checked, and if invalid it will be removed and the save will not happen and a message under the email box will say:

Sorry, {{EMAIL}} is not a valid address.

In addition, if it looks like the email address is a misspelling of a well known domain, it will say 'Did you mean BLAH?'

I think this closes this, but will leave open for review.

**Comment by JosephMcArthur** [comment]
On to @chealsye to review copy for these

**Comment by chealsye** [comment]
Both Sorry, {{EMAIL}} is not a valid address. and 'Did you mean BLAH?' are fine and friendly.
