### ISSUE TITLE
What if I can't find the authors email, but I have their office phone number? 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#487]
would it be innapropiate to call and ask their secretary for their email address? as a last resource perhaps? @JosephMcArthur

**Comment by natalianorori** [comment]
this is the same as #490

**Comment by JosephMcArthur** [comment]
Right now, yes. In future, probably not. Lets hold off on doing this now but systematically track how often we can find it vs their email (i.e we need a box in the spreadsheet we can tick when we find it)

@natalianorori let me know when this is built into our docs & I'll move this into our backlog to consider in 1+ year.

**Comment by natalianorori** [comment]
I updated our documentation and added a note on this.  https://docs.google.com/document/d/1AG8PcZ19yNmILGIPH_bBJC9eAtJlH-oDdjMLOxw4eTY/edit

**Comment by JosephMcArthur** [comment]
Yay \o/
