### ISSUE TITLE
Update of API documentation

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#489]
- [x] simplify some copy on the page - Me
- [x] add in DOI / PMIC / Title? / Citation ? info - @markmacgillivray 
- [x] give an example doi / url / etc to use to test

**Comment by JosephMcArthur** [comment]
How can we make it easy to find help? Github issues maybe?

**Comment by JosephMcArthur** [comment]
- [ ] I think we should consider making copy on the page narrower, it's a bit wide to read comfortably.

**Comment by markmacgillivray** [comment]
Page content, not my area of ownership. Please assign me when there are specific technical questions I can answer

**Comment by JosephMcArthur** [comment]
@markmacgillivray when you get a few minutes can you document how to use our other inputs here on dev?

**Comment by JosephMcArthur** [comment]
- [ ] Put down how to make requests via the API

**Comment by markmacgillivray** [comment]
What does "how to use our other inputs" mean? Which inputs?

**Comment by JosephMcArthur** [comment]
DOI's / titles etc

**Comment by JosephMcArthur** [comment]
Did you put in how to make a request via the API?

**Comment by markmacgillivray** [comment]
Yes

**Comment by JosephMcArthur** [comment]
everything done here, closing
