### ISSUE TITLE
Alternatives to finding author's emails 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#490]
As you know, I’ve been working with the request system daily for almost a month. During this time, I have learned a lot about the system and have found different alternatives that could help us handle requests more efficiently.

One of the main challenges we face while handling requests is finding author’s emails. Some times we can be lucky enough to find the email easily by just doing a google search of the author’s name and the institution where they work. However, most of the times it is not that easy. This is why I consider it important to write a summary about different ways in which we can come up with author’s emails. 

### Most institutions follow the same algorithm when assigning emails. 
If we figure out the format an institution uses to assign emails (ex. First name initial + Last name @ institution dot edu ) we could easily guess emails.

After guessing the email, we could use http://mailtester.com or http://emailbreaker.com (both free) to verify if the email actually exists on the server. nd if our guess is wrong the system will always send us an email failure alert. 

### There are websites that specialize on finding people’s emails 

There are different websites, such as rocketreach.co and https://www.toofr.com (they’re free at first but you have to subscribe later) that specialize in helping you find someone’s email, if you have their full name and the institution where they work. They usually find this info through the person’s LinkedIn or other social media accounts. Others, such as https://snapbird.org (free) find people’s email by doing a quick search through their Twitter profiles. 

I am pretty sure there are other alternatives to this. But at the moment, these are the best ones that I’ve find. 

### While we are looking for emails, it is essential to notify our users that their request is being managed.

Finding emails is the main reason why our requests stay in “help” status for a long time. We created a new copy email in order to notify our users about the status of their requests. This way they will know that even though it is taking us longer, we are still working on it. 

If you have any ideas or contributions to ways in which we can improve the system, please leave it in the comments. 

@JosephMcArthur

**Comment by natalianorori** [comment]
adding a note to this, 

there are some journals that only give you author's initials, or their last name with their first name initial. This makes it harder to track down their emails since we don't even have their name

**Comment by JosephMcArthur** [comment]
Okay... here goes a brain dump of ideas, good & bad. 

### Mterk pages where we can't scrap author emails

By using humans (at scale) we can find emails not accessible to scraping. 

### #529 

### Make searching manually faster

@natalianorori, what searches do you always run to get these emails? Can we make that faster by giving you links for those searches pre-made (e.g running title through google)\

### Twitter / Facebook

Can we search twitter for the DOI & URL to see if the lab / author tweeted it, or similar?

### Using librarians at the institution as a way to contact authors

This is what Chealsye has been working on. However, currently it goes via 

### Reaching out to the journal / funder for author info

Can we simply ask the journal if the have the author info?

### Having contacts with a "well connected" person for a field

Are their people who "know everyone", and might be able to provide contact info? Can we get them on side and engaged in the system? 

@OAButton/team any ideas on how we can help solve this problem are really helpful!

**Comment by chealsye** [comment]
If you know the author's institution, why couldn't you locate their email and have to guess it?

**Comment by natalianorori** [comment]
I found the best way to locate an author's email is using email hunter https://hunter.io
They give you the format institutions use for emails by monitoring the domains, and sometimes they can even give you the exact email address of the person you're looking for. I've tested it and it works.

Otherwise, the manual search I input on google is usually " name + lastname + email" or name + last name + institution where they work + email" 

side note: I think journals won't be willing to give us author's info easily so we shouldn't be trying this method of approach at the moment

@JosephMcArthur

**Comment by JosephMcArthur** [comment]
So, @natalianorori, how often are you able to find folks emails now, how much easier is using hunter than it was before?

What I'm trying to understand is how big of an issue this still is, and how much priority it should be getting. Clearly, there are many options, deciding how far to invest is the key!

**Comment by natalianorori** [comment]
at the moment, my first option is to use google and find the email through there, if the author is not on google, then I use hunter to come up with the institution's email format and double check it at emailtester.com , however, sometimes the address hunter gives me is invalid and I end up with no options (which is the case of most emails that are marked on the spreadsheet). 

Another thing I'd like to point out is that many journals, such as De Grutier and Pubmed only publish author's initials, which makes it almost impossible to track them down (because they also don't put their institutions). 

So my biggest issue right now comes when I run out of alternatives and have no other methods to finding emails. I don't know if journals would be willing to give that information to us.. 

One of the things that makes it easier now is that our users are actually taking the time and filling the emails by themselves, which was not the case of old requests

**Comment by natalianorori** [comment]
So what I would say is that hunter helps in some cases, but it does not fix the problem 100%. Our real problem is that many journals do not give us enough information to track down authors even though we have the means to do so

**Comment by JosephMcArthur** [comment]
Just looking at the stats (72 emails missing /~200 requests managed) this is still one of our major roadblocks in processing - would you agree?

**Comment by JosephMcArthur** [comment]
Note: After using hunter.io 72 went down to 46

**Comment by JosephMcArthur** [comment]
Okay, on a call we just devised a method for using pubmed & other search places to find out authors more recent publications & finding affiliation info.

**Comment by natalianorori** [comment]
new technique discovered by Joe, If you can only find initials or the name and you are on a search email, find the author’s name and see the most recent publication from them, that will get you to their most recent institution and probably their email address.  (This works with Pubmed)

**Comment by JosephMcArthur** [comment]
@natalianorori 

 - [ ] run this new technique over our current missing email requests & report back.

**Comment by JosephMcArthur** [comment]
Other ideas here include:

# Trying to reach out to authors on twitter

For example, by searching the paper DOI / URL on twitter we may find it's possible to see author's who've tweeted it. 

# Posting in pubmed / pubpeer / hypothesis / scienceopen comments or places

Essentially, are there places that we could post a request link where authors (or people who know them) would stumble upon them (or, even get notified?). 

# Having them find it via Google

see #183 

# recruiting the power of the internet

Can we try tweeting requests where we can't find emails and seeing what happens?

**Comment by JosephMcArthur** [comment]
This is obvious, but hasn't yet been mentioned. 

## emailing co-authors

**Comment by alexgiann** [comment]
Indeed! And in some fields like biology, or physics and math, this could be a long list! Authorship rules especially in physics are crazy.

**Comment by markmacgillivray** [comment]
Actually emailing co-authors was already considered. The chosen approach was to email the first author first, and then if they refused or could not provide, the request can be moved on to email someone else. This has never happened though.

**Comment by JosephMcArthur** [comment]
@natalianorori can you try, on some requests that we've totally failed to find emails for, to post a comment about the request on:
* scienceopen
* pubmed commons
* pubpeer
* hypothesis comments

I'd say try it with about 30 requests where we absolutely can't find the email.

**Comment by natalianorori** [comment]
I'm adding this to my weekly tasks. On a side note, just wanted to say that
I am currently emailing co authors whenever I can't find the main authors
email. sometimes co authors have verified emails on google scholar which
makes them easier to approach than the corresponding author. We've actually
received requested articles from co-authors in the past.

**Comment by JosephMcArthur** [comment]
Gotcha, didn't realise that, but I think it's positive!

**Comment by JosephMcArthur** [comment]
@natalianorori & I discussed a number of additions to the moderation workflow that would make tracking down emails a bunch simpler. However, since Mturk work is going well #648 it makes sense to focus efforts on this problem there. 

- [ ] once #648 closes reassess need for additions here. See https://docs.google.com/document/d/1C9wxvxZj0DDyjS4y5zOPx07JpPsWCU42WR7_YZoVBLw/edit# - @ me.

**Comment by natalianorori** [comment]
a note on this, Joe and I tested hunter.io and saw that the results we got from their site were only about 40% accurate, so it's probably not a good alternative to finding emails anymore.

**Comment by JosephMcArthur** [comment]
Thanks @natalia. Anything hold this up: https://github.com/OAButton/discussion/issues/490#issuecomment-292940081

**Comment by JosephMcArthur** [comment]
this is a big, now out of date issue. Broken off other peices into smaller issues.
