### ISSUE TITLE
Flag request if usertype is other

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#491]
This will cause issues with emails that're sent, we should add a flag here for a moderator.

**Comment by JosephMcArthur** [comment]
There is a broader thing to think about here. 

"other" is a significant usertype for us (as seen in user states), is there a way we can reframe this catch all in a more compelling way? I don't really have ideas but I'm hoping @OAButton/team does!

**Comment by JosephMcArthur** [comment]
FYI, institutions associated with other are: 

ASBMB (1)
Anna University, Chennai (1)
Beacon Medical Group (1)
Captain (1)
Crystal Palace Physio Group (1)
Curoverse (1)
Curtin University (1)
Disney (1)
Escola Superior de Gestão e Tecnologia de Santarém (1)
Euromonitor International (1)
Glocalize (1)
Great Ormond Street Hospital (1)
Hipertextual (1)
Imperial College London (1)
Independent (1)
Jisc (1)
MYREN Network Sdn Bhd (1)
Mani Wapi (1)
NCM (1)
Narrated Results LLC (1)
Newspeak House (1)
Nonr (1)
North Carolina State University (1)
Northwestern (1)
Open Access Button (1)
Open by default (1)
Pittsburgh Post-Gazette (1)
Postmates (1)
Research Europe (1)
San Bernardino Sheriff Dept (1)
Sartonet AS (1)
Tony Holroyd Ltd (1)
UC Davis Library (1)
UNC-CH (1)
University of Northampton (1)
University of Strathclyde (1)
University of Torino (1)
Veteran (1)
Yotsuya Gakuin (1)
veeveegeeID (Intelligent Design) (1)

**Comment by chealsye** [comment]
I imagine the best thing to do is replace "other" with something general like user - or potentially have another email draft with a differently structured opening sentence.

**Comment by svmelton** [comment]
+1 for user. I think those types of institutions are too diverse to capture them accurately.

**Comment by markmacgillivray** [comment]
profession of type "other" will now be automatically substituted with "user" when substituting values into email templates.  I think this closes the issue, so will unassign myself, but leave open for you all to review.

**Comment by JosephMcArthur** [comment]
Should probably be email templates & the website, is this the case?

**Comment by markmacgillivray** [comment]
I have more programmatic control on the website, so where the profession is other it just does not show it (e.g. on the request search results and on the request page itself, where it was just added for the issue where you asked for it to be shown, it does not show if other)
