### ISSUE TITLE
Add an example url on the homepage & /request/new

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#492]

**Comment by markmacgillivray** [comment]
This does not make so much sense now that the placeholder text says the user can provide a URL, DOI, PMID, etc and soon also citation - an example of all would be messy, and an example of a url would hide the fact that the others can be done too.

However on the /find page (which was the /request/new page) there is a blurb in orange on the right that says "search for what you need........" - perhaps below that we could list some examples of what the different kinds of input can be.

As this is a copy decision and does not require technical intervention, I will unassign myself.
