### ISSUE TITLE
Make sure request system emails come from requests@ourdomain

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#495]

**Comment by JosephMcArthur** [comment]
I've seen requests coming from "donotreply" addresses, this shouldn't be the case. How do we fix that?

**Comment by markmacgillivray** [comment]
The settings have that address in them, I have changed it for requests to be requests@oab - what about other emails?

**Comment by JosephMcArthur** [comment]
login emails and other notification style emails (e.g weekly check) should come from donotreply
