### ISSUE TITLE
Changes to the received page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#498]
## 1

- [x] change

> It's best if the URL goes directly to the web page where the article full text can be found, rather than to a journal splash page for example. However, we'll take whatever works best for you! 

to

> It's best if the URL goes directly to the web page where the article full text can be found, rather than to a journal splash page for example. 

approved @chealsye ?

## 2

- [x] Can we suggest what a good publically accessible URL is? For example, a copy on your author page or pre-print or something in a repo - @chealsye 

## 3

- [x] Shall we split the page in two along the following lines:

1. If the article is online somewhere. This can take the first paragraph (and some of the second) with the URL box. We can top this with a header too.

2. If the article isn't online somewhere.  This can take the second paragraph (and some of the second) with the URL box. We can top this with a header too.

Assigned to @markmacgillivray 

## 4 

- [x] If it's good, can we show the user story more prominently on this page (see #473 ) - @markmacgillivray 

## 5 

- [x] we need to include more information on why this is worth doing for an author - @chealsye 

## 6 

- [x] we need to make it easier to ask a question from the page - @chealsye 

## 7 

- [x] make the info textbox better - @chealsye 

## 8 

- [x] move the whole page onto the normal request page header - @markmacgillivray 

## 9

- [ ] include some language about licencing / and that the person depo'ing is the author (perhaps a tickbox)

**Comment by chealsye** [comment]
@JosephMcArthur Does this page currently exist?

**Comment by JosephMcArthur** [comment]
Yup, it's as discussed in #337 & some emails. It's the page that everyone on the team finds hard to get to because only authors get the link. To reach it go to any request (in admin), go to details & then hit responder. That'll take you to the page for that request. 

Here is what it currently looks like:
![image](https://cloud.githubusercontent.com/assets/4953703/22456939/302fc47e-e78d-11e6-93d7-a1eb6a961059.png)

**Comment by chealsye** [comment]
Sorry this got lost in the bottom of my inbox :(

I am working on new paragraphs of copy, but first a couple questions/comments:

@JosephMcArthur, how should users ask questions from the page? Should there be another form? Just email?

## 1
> It's best if the URL goes directly to the web page where the article full text can be found, rather than to a journal splash page for example. 

I think journal splash page is jargon we should avoid. Working on it.

**Comment by JosephMcArthur** [comment]
Thanks for the work here @chealsye. Saw the boxes ticked! 

Ah, yes, @chealsye that little help box you saw will also be on these pages once we push the above changes. So, that'll be one route. I'd be interested in your "on campus" experience here, when getting authors to submit to repos what are the most common stumbling blocks & questions. How can we most efficiently answer those?

**Comment by markmacgillivray** [comment]
Please reassign me once content and page design are confirmed.

**Comment by chealsye** [comment]
Sorry it took so long to get back to this on my to do list. I've revised the copy I previously saw and copied, which is below. Unfortunately, I am unable to view these pages though and cannot complete suggestions exactly for how to make it easier to ask a question from this page (unless you simply want to give instructions to email), or see the author view and how they share the url. 

_Article request response page copy_
**Thank you for responding to our request**
To complete the request we need to know where we can find the content that has been requested. If it is already publicly available online somewhere that anyone can access without restriction, all we need you to do is provide us with the URL address where we can find it.

It's best if the URL goes directly to the web page where the article full text can be found, rather than to a journal splash page for example. However, we'll take whatever works best for you! 
If you don't have the article publicly online anywhere yet, you can upload it to us and we will send it to Zenodo on your behalf for safe keeping, where it will be hosted, preserved, and made available to others under a CC-BY licence.

New copy

> **Thank you for responding to our request**
> 
> Let’s help more people get access to your research. 
> 
> Is your article already available publicly online? That’s great! Just give us the URL address. A good publicly accessible URL is a link to the full-text on a repository or your website. 
> 
> If the article isn’t publicly available, you can deposit it to your institutional repository and then share the link with us, or you can upload it now. We’ll send it to [Zenodo](https://zenodo.org/) where it will be preserved and publicly accessible under a CC-BY license. 
> 





_Data request response page copy_
**Thank you for responding to our request**
To complete the request we need to know where we can find the content that has been requested. If it is already publicly available online somewhere that anyone can access without restriction, all we need you to do is provide us with the URL address where we can find it.

If you don't have the data publicly online anywhere yet, you can upload it to us and we will send it to the Open Science Framework. The Open Science Framework will host and preserve your data, and make it available to others under a CC-0 licence (the recommended licence for sharing data).
We’ll use the paper title and abstract to provide initial metadata, which you can edit below. 
Once you submit the data, we'll ask our community to validate it. When they've checked it's what they need, you'll receive an Open Data Badge. 
If you have more than one file, or a folder of files, please zip them first

New copy

> 
> **Thank you for responding to our request**
> 
> Let’s help more people get access to your research. 
> 
> Is the request data already available publicly online? That’s great! Just give us the URL address. A good publicly accessible URL is a link to a repository record. 
> 
> If the data isn’t publicly available, you can deposit it to a repository and then share the link with us, or you can upload it now. We’ll send it to the [Open Science Framework](https://osf.io/). OSF will preserve your data and make it publicly available under a CC-0 license, the recommended license for sharing data. Once you submit the data we’ll ask our community to validate it. If you have more than one file, please create a zip folder to upload.
> 
> Need some help curating your data first? Ask your library if they have a research data management specialist. 
> >

**Comment by JosephMcArthur** [comment]
@markmacgillivray I've just moved this to the current sprint. Seemed to be what you were discussing doing.

**Comment by markmacgillivray** [comment]
@JosephMcArthur before this gets done isn't there supposed to be some decision on what it is meant to say in relation to Sherpa Romeo lookup?

**Comment by JosephMcArthur** [comment]
Hmmm, don't think so. I suggested shipping the changes in this issue &
while that's done I'd go and firm up what needs to happen with Sherpa
stuff. I didn't want to have they technical side of that slow this down.

**Comment by JosephMcArthur** [comment]
Before the sprint team meeting could we get a quick update on progress here, and if anything is blocking us moving forwards?

**Comment by JosephMcArthur** [comment]
Me: think about improving the UI here, not wholesale moving the page over the the request template

**Comment by markmacgillivray** [comment]
Language as above appears to be what is in use, moved around slightly to fit new two column layout as requested. Header simplified more like other site pages. I think that is all the requirements listed in this issue.

**Comment by JosephMcArthur** [comment]
Thanks @markmacgillivray. I'm getting a build failure so leaving notes here for us. 

- [ ] Fix that the below doesn't look like a starting line for both sections. 
> Thank you for responding to our request. Let’s help more people get access to your research.

- [ ] allow an author to refuse a request from this page. Can you tell me the URL I need to link on the page that will allow that? 
- [ ] make each section a bit more eye catching

**Comment by markmacgillivray** [comment]
I'm done working on it now and have committed so you should be able to change and build. You may have to redo changes as I may have overwritten some of them on the response page.

**Comment by JosephMcArthur** [comment]
Okay, done a bunch of work here, to finish it off:

- [ ] @markmacgillivray there is a new section where an author can actually refuse a request. Somewhere in the mix this got lost. Can you add back in the URL (this use to be in emails) that allows that? 

- [ ] @allanaaa can you take a look at my copy & suggest changes where needed. I've managed to remove some of what Chealsye suggested by having clearer formatting on the page itself.

FYI: two requests that I've been testing with:
* https://dev.openaccessbutton.org/response/tHgrLXCt3eMBdZiKf
* https://dev.openaccessbutton.org/response/2kNsAmPWGAa4mBY65

**Comment by allanaaa** [comment]
I'd love us to say "If your article/data isn't in a repository, please consider uploading it instead." 
It aligns with our values, and perhaps avoids Google Drive links or similarly unwieldy non-preserved things.
We should also write a blog about "The advantages of putting your research and data in a repository" that we can then link to from these pages, in case people have more questions.....

**Re: Data**, is .zip the only archive file we/OSF can take? .rar, etc.?

I don't love the word "curating" - a more accessible option might be "Need some help cleaning up your data first" or "organizing your data first."

Proposed:

> Is the requested data publicly available online? That’s great! Just give us the URL. We suggest a link to a repository record. If your data isn't in a repository, please consider uploading it instead.
> 
> If you want to upload your data, we’ll send it to the Open Science Framework. OSF will preserve and make it available under a CC-0 license, the recommended license for sharing data. Once you submit the data we’ll ask our community to validate it. If you have more than one file, please upload a ZIP.
> Need some help organizing your data first? Ask your library if they have a research data management specialist who can help.

**Re: Article**, I like the idea of suggesting file formats (i.e. PDF or HTML).

Proposed:

> Is the requested article publicly available online? That’s great! Just give us the URL. We suggest a link to the full text on a repository or your website, preferably a PDF or HTML version. If your article isn't in a repository, please consider uploading it instead.

> If you want to upload your article, we’ll send it to Zenodo. Zenodo will preserve and make it available under a CC-BY license.

Titles and other copy look great!

**Comment by JosephMcArthur** [comment]
So, I have uploaded all of this. However, I've hidden the text requesting folks use repos, so far I'm not aware of folks giving us drive links or things like that (cc @natalianorori) & I'd like to keep this as simple as possible. If they give us personal site links, my preferred method there is to do the work on our end to archive that via the internet archive (automatically). 

Otherwise, take a peek @allanaaa and let me know if the copy appears as you'd hope otherwise. 

for the tech details of what we can accept, as @markmacgillivray.

**Comment by allanaaa** [comment]
Looks great!

**Comment by natalianorori** [comment]
@JosephMcArthur you are right, we have never gotten drive or links like that, so I agree with you on keeping things as simple as possible. I'd like for authors to understand this page easily

**Comment by markmacgillivray** [comment]
I don't think there is anything I can do here. The response page still includes the code to show a refuse section. It is in the email templates that you all maintain that you choose which links to put in- a link to refuse should just be a link to the response page with ?refuse=true added to the end. Then the response page will record the refusal and show the div with the id "refuse" - so put whatever new text you want the user to see when refusing into that section. It is still there in the code of the dev site response page, as far as I can see.

**Comment by markmacgillivray** [comment]
About what file types we can receive - I don't know. We can receive any file type you want to be able to receive, and that OSF or Zenodo will accept from us. I don't know of any restrictions placed by them.

**Comment by JosephMcArthur** [comment]
Tried adding:
`/?refuse=true`
in the href on the page to power this, but couldn't push to dev.

**Comment by markmacgillivray** [comment]
I had already done it with ?refuse=true, our updates conflicted, fixed now and merged.
