### ISSUE TITLE
New request system embeds

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#499]
![image](https://cloud.githubusercontent.com/assets/4953703/22428739/15e9714c-e700-11e6-9c52-86a1d42c2e36.png)

- [ ] remove logo
- [ ] make story focused / tell a embeding users story
- [ ] make a light tone generally

Perhaps something like:

> I need access to <title> because <story> | can you support me?

**Comment by chealsye** [comment]
Where do these appear? I haven't seen one in ages.

Are you pulling in me for light tone copy? Can I suggest design changes?

**Comment by JosephMcArthur** [comment]
You can currently get them from request pages, there is an "embed" button.

At this point both design and copy changes are super helpful.

**Comment by chealsye** [comment]
Finally returning to this. Honestly, I say bring Sam in for the design. It needs a big redo to be pleasing. 

If I were to copyedit this though I'd cut most of it. Instead making the embed say, 

2 people have requested access to the article/data related to title

Add Your Support


Open Access Button does not need to be anywhere, but if it does a strip at the bottom could work.

**Comment by JosephMcArthur** [comment]
don't really think we have time or capacity for this
