### ISSUE TITLE
Continue to work on new /request

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#500]
The idea of this rebuild it to:
- [ ] incorporate the mapping & tie to reqeusts
- [x] centre the page about our now good user stories
- [x] properly highlight what the request system is
- [x] make it clearer how others can support the system & requests
- [x] set the stage for a faster moderation workflow
- [x] close #444 
- [x] Set the stage for request communities
- [x] make the page prettier
- [ ] merge /export
* improve search generally

current draft lives on link passed round on group chat (not putting here incase user data is linked that we can't)

**Comment by markmacgillivray** [comment]
I think done.

**Comment by JosephMcArthur** [comment]
okay! 7 / 9 done here! Good show.
