### ISSUE TITLE
Submit request button not clear

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#501]
The button to submit requests is not clear to all users.

The problem was originally reported on Monday by Rickypo on Twitter.

![screen shot 2017-01-30 at 18 33 36](https://cloud.githubusercontent.com/assets/9299248/22446481/f9e8ab1e-e71a-11e6-94a6-0d63d39fc245.png)

At first I thought it might be a bug and went to re-create it, and even though I was able to click the box and submit it did not feel intuitive. He didn't realise that he needed to type a story in order to submit, and even when I did I didn't feel like I needed to click that dialogue box. This isn't clear to all users and we should discuss ways to improve it.

Do we add a second SUBMIT box? Change the dialogue a bit? (I'd like to anyways). Thoughts?

**Comment by JosephMcArthur** [comment]
Let's move forward on changing the dialogue. Thanks again for flagging. 

We're probably going to make this page look more like the plugin too, which should help.

**Comment by chealsye** [comment]
- [ ] @chealsye communicate to Rickypo how we improved this for more clarity once we do

**Comment by JosephMcArthur** [comment]
currently not planning to ship a change to the submit button text in Monday's release BUT, we've removed about 70% of the page content. So... should be clearer for sure.

**Comment by chealsye** [comment]
I don't think any of the changes (although good for user overall) do not improve the clarity for the submit button.

**Comment by JosephMcArthur** [comment]
Can you suggest updated copy for the button then please?

**Comment by chealsye** [comment]
The problem reported by RickyPo was that he didn't know where the submit button was. He typed a 5 word story, another word or even a space would have made the button yellow and perhaps singled him to keep writing. However, it didn't. He thought there wasn't a submit button. 

The button copy here has not changed. 

![screen shot 2017-02-20 at 19 21 29](https://cloud.githubusercontent.com/assets/9299248/23147323/0da01b00-f7ac-11e6-9ea6-c4247d86ba90.png)

![screen shot 2017-02-20 at 19 21 35](https://cloud.githubusercontent.com/assets/9299248/23147325/10147c46-f7ac-11e6-8448-824c7966807f.png)

![screen shot 2017-02-20 at 19 21 47](https://cloud.githubusercontent.com/assets/9299248/23147328/12d5e230-f7ac-11e6-8622-eec71544b583.png)

There's two main routes to fix this
1) Add a submit button below
2) Tweak the copy

But I really don't see an obvious way to change the copy + communicate it is a submit button without it being a lot of words.

I'd really love to discuss ways to fix this since it isn't obvious to me. @svmelton @meganwaps @natalianorori any thoughts?

**Comment by JosephMcArthur** [comment]
To throw my 2 cents in, just looking at his story there is good reason he shouldn't have been able to submit - it wasn't very good. In that sense, we succeeded here on some level. 

To throw one idea out, we use a lot of words in that submit button communicating how many words are left. We could move that out into more of a character count style counter? That could free up words. 

We could also opt for much much simpler copy. e.g
> Write 5 words to submit your request
> Click now to submit, or, make a better story in X words.

Are there any icons folks associated with submit style buttons? Perhaps we could put one in?

Also, @natalianorori you're going to need to monitor any change we put in place here through the reqeuest system. 
- [ ] set up monitoring system
- [ ] establish how often we current have to reject things as they're poor stories.

**Comment by chealsye** [comment]
Returning to this... maybe "Write X words then click here to submit your request." Some people don't know you click there. Or it could just change to Click here to submit once they hit the words?

**Comment by JosephMcArthur** [comment]
this is now much clearer, but for the wrong reasons :) closing this for now.
