### ISSUE TITLE
we should get a new "status" for requests that fail, but are not necessarily "refused" 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#504]
currenlty, the only way to close a request is by marking them as either "received" or "refused"
It would be good to get a new status to close requests that were not refused, but  couldn't be processed for other reasons (no email, dead author, etc.)

I am keeping failed requests on "help" status until we figure out the appropiate way to close them.
@JosephMcArthur

**Comment by JosephMcArthur** [comment]
This is essentially the same as #480

**Comment by natalianorori** [comment]
should I close this ones and move my comments to #480?

**Comment by natalianorori** [comment]
We should also get a new status to differentiate our "help" requests that have not been managed yet from the ones that have been managed, but haven't find the author's email. 

for example, once we notify the user that we can't find the author's email and that is the reason their request is taking longer, changing their request status from "help" to something else would be useful to avoid confusions.

**Comment by JosephMcArthur** [comment]
- [ ] @markmacgillivray can we make a new status for "closed"

Natalia moving your other comment to #528

**Comment by markmacgillivray** [comment]
OK, I have added this on dev, to the request page, where "closed" can now be selected as a status param by an admin. I will unassign me for now, if you later decide what actions it should cause, reassign and I can progress.

**Comment by natalianorori** [comment]
Closed status could be use when 
- The author is deceased
- The request is for something the oa button cannot get (ebooks, subscriptions to websites)
- none of the co authors can be found after a few months

This is all that comes to my mind at the moment, but as we continue managing requests new situations may emerge

**Comment by JosephMcArthur** [comment]
Is this in the management document?

**Comment by natalianorori** [comment]
It is now

**Comment by JosephMcArthur** [comment]
Yay! \o/
