### ISSUE TITLE
bcc requests@openaccessbutton.org on all request system emails

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#505]
Simply to make it easier to catch errors in actual use

**Comment by natalianorori** [comment]
@JosephMcArthur we need to find or open another email address to bcc this too, since @chealsye is getting all these emails and it can get confusing.

**Comment by markmacgillivray** [comment]
With the next update you can actually control this from the email template - if you put in a {{BCC someone@oabutton.org}} then it will go to that bcc address - so you can pick the address you want it to go to, and pick what email templates you want a bcc on as well. I will remove myself from this issue, and leave it to you to decide.

**Comment by JosephMcArthur** [comment]
We'll set up a new requests email account to remove confusion for chealsye & go from there. I need to do that.

**Comment by JosephMcArthur** [comment]
done this!
