### ISSUE TITLE
All request system emails look as though they're coming from test system

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#506]
Openaccessbutton.io is being sent as oab.test.cottagelabs.com. 

This was first noticed today (after pushing new email updates). Happens on the new emails & others that weren't changed by updates. Can't confirm yet if this was changed by updates made on Sunday though.

**Comment by markmacgillivray** [comment]
Sorry, should be fixed @JosephMcArthur plz try again

**Comment by JosephMcArthur** [comment]
okay, we're back! @natalianorori 

@markmacgillivray, is there anything we should be putting in place to stop this happening again (& any any idea of the damage?) 

We know broken emails when out to at least 4 folks. @natalianorori , can you drop them a note to say sorry?

**Comment by markmacgillivray** [comment]
No it is just a convenience I had put in for testing and not changed when we did the switch on Sunday night. Probably when the new email templates were uploaded it then did not match properly. There is now a check in place so it will only send that way on dev, and not on live.

**Comment by JosephMcArthur** [comment]
Okay great, thanks @markmacgillivray / @natalianorori for quick flagging / troubleshooting & fix.

We're operational again.

**Comment by natalianorori** [comment]
Great! Thanks for fixing this fast Mark! I'm gonna get back to work after lunch and apologize to our 4 users for the mix up
