### ISSUE TITLE
improved bookmarklet install instructions

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#507]
The install instructions & gif here (http://www.spritzlet.com/) is pretty great, mainly point 1 is what we can learn from. 

Can we make this bit right for us?

>Where is my bookmarks/favorites bar?
>Your bookmarks bar may be hidden. It looks like a list of links underneath the URL text box. Here's how to show it:
>Chrome, Safari, Opera, Internet Explorer: Control (Command on a Mac) + Shift + B
>Firefox: Control (Command on a Mac) + B

Also useful for #469

**Comment by JosephMcArthur** [comment]
@chealsye this might be a small copy change we can make that would make a big impact!

**Comment by chealsye** [comment]
I made a few copy tweaks and added more installation instructions based Sprintzlet, but I think it is just a temporary improvement and want to discuss further improving it / what we could include. I think we could do something similar to Sprintzlet's full directions including with gifs (not on that one page, but if people need further help).

**Comment by JosephMcArthur** [comment]
This is better, but I agree it's not there yet. 

We need:
- [ ] a title of the section that clearly shows this is how you get installed - @chealsye 
- [ ] an install gif - me

at least. 

I think they're easy to ship, and we can probably do by the end of the week.

@chealsye what questions would you like discussed (the more specific the better) & how would you like them discussed. We can flag this on next weeks agenda or just tag everyone in a github comment.

**Comment by JosephMcArthur** [comment]
- [ ] stratify install instructions by browser

**Comment by JosephMcArthur** [comment]
Small changes suggested by @BaronBlackmore (aka, Sam) to reduce a bit of information on this page (which helps the user focus on what is needed, like getting the bookmarklet):

- [ ] remove "use the button in your browser". This is now the front page & in the header. 
- [ ] hide "view your requests" until you've made requests

Also, minor copy change

> Some information is missing. Please confirm you have completed all the fields and checked the boxes. Then save again.

to:
 
> Some information is missing. Please confirm you have completed all the fields. Then save again.

- [ ] done

**Comment by JosephMcArthur** [comment]
Right. Attached is a design for the account page suggested by @BaronBlackmore. It's much tidier. 

Except the instructions, which aren't finished, and the inclusion of instructions for how to show your bookmarks bar I think it's wonderful.

[image](https://cloud.githubusercontent.com/assets/4953703/23331801/5b2b1246-fb65-11e6-9ec3-b48a041b7b8c.png)

**Comment by JosephMcArthur** [comment]
Note, here are two draft gifs too:

![image](https://cloud.githubusercontent.com/assets/4953703/23331833/d2b9fe30-fb65-11e6-9a0b-bcdf55eb978d.png)

![image](https://cloud.githubusercontent.com/assets/4953703/23331836/d62c29bc-fb65-11e6-9fb9-e39bf42f9fc2.png)

**Comment by markmacgillivray** [comment]
OK, but we also still need to change the button and instructions depending on browser type, and device type - so the complexity of the design is how it looks good in each different case.

**Comment by markmacgillivray** [comment]
Ah, I see there is more that shows up when viewing the issue directly than in the email - that was a bit confusing. Makes more sense now. gifs are good too.

**Comment by JosephMcArthur** [comment]
Yes... the github email view sometimes is a let down.

**Comment by chealsye** [comment]
Proposed changes and gifs look good.

**Comment by JosephMcArthur** [comment]
Okay, implemented many of the suggestions giving by @BaronBlackmore here. Mainly just taking stuff away.

**Comment by JosephMcArthur** [comment]
@markmacgillivray tiny things, can you 

- [ ] change username --> first name on the account page? 
- [ ] put first name & last name next to each other (as shown in Sam's mockup)

**Comment by markmacgillivray** [comment]
Don't know what you mean. The account page already shows first name if known, otherwise username if known. I have moved the firstname/lastname boxes next to each other though.
