### ISSUE TITLE
How to handle (often good) stories with typo's

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#508]
This seems to happen a fair bit & it's a shame! Often these stories are actually good ( e.g https://openaccessbutton.org/request/F4hgxMEGSgNQgrNke ) and correcting a few words would make a big difference I expect. 

I could be wrong, but Natalia, I'd imagine fixing this wouldn't need much time (especially if your browser has a spell checker). However, do we have the rights to fix this, do we need to notify folks when we do, can we make it easier etc.

**Comment by natalianorori** [comment]
This is a struggle I had as well. We wouldn't be changing the idea, nor the words its just a typo,  so I am not sure if it's necessary to notify the users unless bigger changes to the story need to be made.

It is important to note that we have people from all over the world using the button, people who's first language is not English so typos will be pretty common in future requests.

So I'd say that if it is just a typo, we wouldn't have to notify anyone, but if bigger changes need to be made then maybe we could create a template to notify our users

**Comment by chealsye** [comment]
Just chiming in - I agree that if it is just a typo it can be corrected without notification.

**Comment by JosephMcArthur** [comment]
Okay, so, we've decided we'll change them.

The next question is, if / how we correct them en-mass (for past ones, at least since oaw2016)? 

@markmacgillivray if we edit stories in a sheet (with ID's) and give them to you to upload will they overwrite?

**Comment by markmacgillivray** [comment]
Yes

**Comment by JosephMcArthur** [comment]
@natalianorori can we make sure to document this as our policy in the handbook.

**Comment by JosephMcArthur** [comment]
@meganwaps, while you're doing the buik story rating, can you try and catch some of the very worst typos in stories that are 4 & above?

**Comment by natalianorori** [comment]
@JosephMcArthur It is already documented in the handbook
