### ISSUE TITLE
2 Instances of find system point folks to the wrong article

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#509]
# 1 

From: http://dl.acm.org/citation.cfm?id=1710138&dl=ACM&coll=DL
To: http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.433.6725

Why: ???

# 2

From: http://science.sciencemag.org/content/347/6221/500
To: http://scholarworks.gsu.edu/phy_astr_diss/55/

Why: Same title, but the first was a news article

**Comment by JosephMcArthur** [comment]
One idea, would doing a comparison of abstracts (where possible) be a useful way to catch issues?

**Comment by markmacgillivray** [comment]
For the first one, BASE reports it as being the same thing by DOI match. So it is wrong in BASE. Nothing we can do about this, our sources will occasionally be wrong.

The second one works fine now.
