### ISSUE TITLE
Validating a data / article smoshing page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#510]
@svmelton has all the details. The general idea here is to surface our ability to link articles their corresponding datasets via a page on the site that doesn't require use of the whole request system workflow.

**Comment by JosephMcArthur** [comment]
Note: MVP for this might just be a google form.

**Comment by markmacgillivray** [comment]
But wouldn't this just be the "find" page? If you put an article in there, and we find some data, it says we found data.

**Comment by JosephMcArthur** [comment]
This is to create those linkages, rather than expose them.

**Comment by JosephMcArthur** [comment]
@svmelton any progress here?

**Comment by svmelton** [comment]
@JosephMcArthur Not yet—I'd like to chat about this a little more because I'm a little fuzzy on it

**Comment by JosephMcArthur** [comment]
No longer doing data work, no capacity. Focusing on articles to build plumbing and hoping to return to data later. Closing this for now to keep the repo clean.
