### ISSUE TITLE
following up with author emails

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#511]
The request system has been active for over a month, and it is getting important to talk about how we will be following up with authors that haven't replied to our emails (according to our workflow, that's something that we should already be doing). 

I checked our drive and the github emails folder and there is nothing there yet, I don't know if we have drafts of these emails in other locations.

we could chat and re evaluate on how our workflow will be adapting to the actual system to start moving forwards with unanswered requests

@chealsye @JosephMcArthur

**Comment by JosephMcArthur** [comment]
@natalianorori you found the drafts for this right?

**Comment by natalianorori** [comment]
yes, here: https://docs.google.com/document/d/1fJQojk_xma7DV2SQfJfJEbRSRM79Z6APBUFwFQDsfQI/edit

**Comment by chealsye** [comment]
Is there any documentation about the request workflow?

**Comment by JosephMcArthur** [comment]
Yup: https://github.com/OAButton/discussion/blob/master/Design%20%26%20Management%20docs/Request%20System%20Management.md. 

If some you need isn't there, or clear, let us know & @natalianorori will work on it. This'll also be worked on in the next sprint.

**Comment by chealsye** [comment]
I think for follow up emails we should try two styles:
1) Friendly nudge by Natalia, short, sweet, friendly
2) Joe's "testimony" about why he created the Button - an email suggestion that Natalia included in her ideas

**Comment by natalianorori** [comment]
I'd go with the friendly nudge, and what we can do is try sending the nudge
from my personal OA button email address ( natalia@openaccessbutton.org )
So that the author's can see we are actually real persons

**Comment by JosephMcArthur** [comment]
For now, can we try and do follow up with authors who got our original first email (the long one) with something a lot like our new first email? I'd like to get that message out to as many authors as possible.

**Comment by chealsye** [comment]
Ooh! That's a good idea, Joe! I'll draft something tonight and share it if
that works?

**Comment by JosephMcArthur** [comment]
Please!

**Comment by natalianorori** [comment]
thanks Chealsye!

**Comment by chealsye** [comment]
Hey Natalia and Joe,

Apologies for not sending this along last night - I've created a new rule
for myself with no Button work after midnight and I didn't get to the email
in time!

Here's a draft of the email, which will be used to follow up with authors
who received the original and longer request email:
https://docs.google.com/document/d/1k3z6GOp9Cgk-KQWE3JxGuNE6EWYuJDVyhPYVegqx8bY/edit

Best,
Chealsye

**Comment by natalianorori** [comment]
Hi Chealsye,

Thanks for the draft! I agree with the email content. However, based on Sarah's feedback, I think we should explore and discuss different options for the email title. It's important to call author's attention and avoid being confused with spam. Authors like to know the importance of their work and our title should show them that we think it is really important! 
So some suggestions for titles that come to my mind are: 
-Someone is interested in your work!
- don't forget we are interested in your research  
- your article is important, Share it to increase your impact

Any other ideas for titles? Anything that calls their attention and leaves them wondering so that they open our email should work. 

Best 

Natalia

**Comment by chealsye** [comment]
Could you add comments to the document instead?

**Comment by natalianorori** [comment]
It's in the comments now :)

**Comment by chealsye** [comment]
@JosephMcArthur Can you overview the proposed text? I think we're good to go unless you have suggestions and we can go with @natalianorori's subject line suggestion.

**Comment by natalianorori** [comment]
Joe,

could you get this up for me? I want to start this follow-up tomorrow and
having the template will make it so much easier
thanks,

N

**Comment by JosephMcArthur** [comment]
this is up! plz test @natalianorori
