### ISSUE TITLE
We need an email that's "the request system doesn't do that"

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#513]
for ebook requests, and subscription requests like the one we got today: : https://openaccessbutton.org/request/wmd8LwAsmyofdS4Jy

@chealsye @JosephMcArthur

**Comment by JosephMcArthur** [comment]
Once this email is sent, a request should be closed. 

@chealsye is it okay if @natalianorori takes a first draft here?

**Comment by chealsye** [comment]
Okay, fine...

**Comment by natalianorori** [comment]
https://docs.google.com/document/d/1WMN9mXqAm4oLJJmlEg1-R8WvOd-28AuiO_uNZRS81ts/edit

I created a first draft here with some comments, it still needs your opinions and feedbacks. Once it is ready we can move it to the email's folder

thank you! 

@JosephMcArthur @chealsye

**Comment by JosephMcArthur** [comment]
Give a few comments. Leaving the rest to @chealsye. Happy to upload when everyone is happy.

**Comment by chealsye** [comment]
@natalianorori can you review the comments and make any needed edits and then let @JosephMcArthur know when its good to upload?

**Comment by natalianorori** [comment]
@chealsye @JosephMcArthur I made some edits. If everyone is happy with it I think its good to go

**Comment by JosephMcArthur** [comment]
this is up now!
