### ISSUE TITLE
Understand / conceptualize how we enable communities to manage / personalize the request system

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#514]
Here a community can be thought of as any group that has a specific interest in a subset of requests or users in the system. For example:
A library wanting to manage it’s users who can request any type of research
A groups of librarians from different institutions wanting to free research in library journals
A journal wanting to manage requests involving its journal (especially from any widgets we’ve given them)
An open access advocate who wants to watch all requests in their field

Communities should be able to:
- [ ] Be recognised as such by our system (e.g group accounts). There should be the ability for communities to make admins of their system (at /admin) and create new accounts.
- [ ] Automatically have requests assigned to their system based on their particular interest. For example:
 * If request is from user x, assign to community y.
 * If request is in field y, assign to community x. 
- [ ] Filter out and interact with requests they care about on /request. They should be able to set their own rules about if the system runs automatically or manually. 
- [ ] Alter email copy and in future sender copy to suit their needs
- [ ] Filter out and interact with stats they care about on /stats

**Comment by JosephMcArthur** [comment]
Okay, have split this issue out into several smaller ones.

**Comment by JosephMcArthur** [comment]
@markmacgillivray this issue is the one for discussion right now!

**Comment by JosephMcArthur** [comment]
To close this we want to:
- [ ] have @markmacgillivray layout questions that would be helpful for the team to answer
- [ ] have @OAButton/team feed into the conceptualisation of the group system
- [ ] write up the above as issues like those already done (but with more info)

Hopefully:

- [ ] speak with some external groups about that they'd want (e.g library group) - Me
- [ ] speak with folks who've wanted notifications about what else they'd like to be able to do from that - @chealsye 

Also, on the call we noted that there is a clear parallel between #523 & this work. #523 may one route towards a larger "group" which would manage requests on a subject.

**Comment by chealsye** [comment]
@JosephMcArthur What are you asking the 'library group'?

**Comment by chealsye** [comment]
I spoke with the librarian who made the request/suggestion for a request system, he said, "Simple email notifications like you describe would be fine. If the notifications could include a link to the OAB record and perhaps some information about the work being requested, that would be ideal. I don't think we'd need any additional functionality beyond that."

**Comment by JosephMcArthur** [comment]
Closing to clean repo of older ideas.
