### ISSUE TITLE
Search not picking up SSRN copy, DOI search sending to wrong article

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#518]
I ran into a problem with a request from 2013 (came across it when tracking down uni requests for a librarian). 

[The Button request](10.1016/j.bushor.2011.01.005) appears normal. However, there are problems when searching for both the url and doi from the Button. The doi (10.1016/j.bushor.2011.01.005) says the article is available, but it actually sends you to a whole different article with a different doi. Then when searching by the [url](http://www.sciencedirect.com/science/article/pii/S0007681311000061) it says there's already a request and to join it. The article is available in [SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2519365).

i wanted to flag this largely because the doi mixup is concerning.
But also - if there is an OA copy out there, how can I tell the system?

**Comment by markmacgillivray** [comment]
UI decisions required here. No technical progress possible.

**Comment by JosephMcArthur** [comment]
@chealsye I'm struggling to find this request and the link you gave seems to go to github. Don't suppose you have it to hand.  

Searched on the DOI and this time it sent me to the right article, but a paywalled version. Network analysis suggest BASE is at fault

```
{
  "status": "success",
  "data": {
    "match": "https://doi.org/10.1016/j.bushor.2011.01.005",
    "availability": [
      {
        "type": "article",
        "url": "http://www.sciencedirect.com/science/article/pii/S0007-6813(11)00006-1"
      }
    ],
    "requests": [],
    "accepts": [
      {
        "type": "data",
        "conditions": {}
      }
    ],
    "meta": {
      "article": {
        "doi": "10.1016/j.bushor.2011.01.005",
        "source": "BASE",
        "title": "Social media? Get serious! Understanding the functional building blocks of social media"
      },
      "data": {}
    }
  }
}
```

If there is an available version we can log that from the admin side if a request has been made. That's why I'm keen to track this request down!

**Comment by markmacgillivray** [comment]
Nope, the BASE response says it is available, and says it is in repec, but gives us back the science direct link. There is nothing else to show where it should actually be. All we can do is report it back to BASE as an error, there's no other fix I could apply to errors like this one...

**Comment by JosephMcArthur** [comment]
Can't replicate these issues on new api. Closing.
