### ISSUE TITLE
Do we need a distinction between researcher / academic? 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#526]
For my taste they're similar enough to be simplified down to researcher, objections @OAButton/team?

**Comment by svmelton** [comment]
I think we should simplify them, particularly because there are a number of non-tenure track researchers who do the same work but might not be considered "academics" by their institutions.

**Comment by alexgiann** [comment]
Also all academics are researchers as part of their job description so it's not false to call them that.

**Comment by chealsye** [comment]
+3 researcher is a best catch all. We need as few options as possible and academic can be an, erm, loaded term at times.

**Comment by natalianorori** [comment]
+4 , let's stick with researcher

**Comment by JosephMcArthur** [comment]
Assigning @markmacgillivray to make the required change.

**Comment by JosephMcArthur** [comment]
changed on dev, shipping asap
