### ISSUE TITLE
PMID's & Requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#527]
## Original ticket

When making a request via the link: https://openaccessbutton.org/request/new and filling in title and reason that I need the article I press submit and the request comes up as "untitled" and also the title field is suddenly blank.

Any idea why this happens? I am usinf google chrome on a windows computer.

Also my situation is that I don't have the authors' email or DOI for some of the studies I need. I only have title, author names and sometimes the journal. I am a bit in doubt if the Open Access button can automatically find the email of the authors and email them or if I should should try and find the authors' contact details manually ?

Some suggestions:
Could you add an option to delete a request and also an option to change the title of the request?

I had to make a new request as my first request came up as "untitled article" - I think it would be a nice option to be able to change the title of the request or simply be able to delete it and make a new request - Is this possible to implement?

Might it be a good idea to add a field for authors when making a request? 

## Natalia's extra info

So we got a ticket yesterday (A ticket (#211) by Frederik Martiny has been received. It is unassigned.) In which the user says that their request ID leads to an invalid link. I checked this requests today, and when I try to press on it, I get the " Sorry, we can't find a request with ID" message, which is ODD because the system did catch the title of the article, since it displays correctly. However since there is no DOI, I have no other way to access the paper and can't proccess the request.

This is the case of the three request Frederik submitted. 

https://openaccessbutton.org/request/Dp9cRpwKrfuM9PRax
https://openaccessbutton.org/request/nwzE2pvaw583WF74S
https://openaccessbutton.org/request/fDrfBoxAdajePXaMK

I don't know if this is a bug, but we definetly need to ask the user to submit the requests again

## Mark's response 

They are not exactly bugs, but they are a result of more recent features.

I would guess that this user is creating requests after searching for title or PMID - the third one on that list has a value of 70395722 which looks like a PMID, whereas the first two just have titles. 

However, our request pages show the title (or untitled article where we could not find a title) as a link to the URL where the article was requested - BUT in the above cases, and possibly in any future cases where a user creates a request via the website and provides a title or PMID or PMCID or some other string OTHER THAN a URL, indeed we will not have URLs to look up for those articles.

I can easily change the request page to not show the title as a link if we do not have a URL to link it to - that will stop the click on the title leading to an apparently missing page.

But there is a further question as to what you want to do with these cases - how you want to follow them up. Probably this needs to be an issue, and you and Joe should think of what actions may be required in such cases.

**Comment by markmacgillivray** [comment]
Note that although this is assigned to me, I can't do anything until operational decisions are made about how we should handle this in our request management workflow. But once you decide that, just let me know what to do -  I will unassign myself for now as I can keep better track of what I need to do that way, and just assign me once there is action I can take.

**Comment by JosephMcArthur** [comment]
If it's not possible to have URL's, then we shouldn't show links on the request page. However, are we not able to track down / guess a URL? If we are, we should, if we're not, then don't show the link. 

Is that the only decision needed here?

**Comment by JosephMcArthur** [comment]
My thoughts here are that if we can build any url from a PMID that points to the right article (even if that actually goes not to the page the person was coming from) that's probably okay.

**Comment by JosephMcArthur** [comment]
Is this another example of the same issue? 

https://openaccessbutton.org/request/FqFEW4nJg7Xjdrxkm

**Comment by markmacgillivray** [comment]
yes

**Comment by markmacgillivray** [comment]
In dev, if we have doi, pmcid or pmid we will build a link to the resource from that. If we appear to have title or citation, the link will just not work.

**Comment by JosephMcArthur** [comment]
Can we have it not display a link if we don't have one

**Comment by markmacgillivray** [comment]
Done
