### ISSUE TITLE
When loading, if user tries to close bookmarklet will hang

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#530]
Note, I've replicated this in the past, it's a relatively common thing to see. 

> GET PDF message > loading message> We’re looking! Give us a moment. There is an issue with the “Get PDF” pop up window when we try to close it while it is “looking”. For example, it will not close and will freeze.

**Comment by markmacgillivray** [comment]
Fixed this one, updated the demo page change log
