### ISSUE TITLE
Update version notes / download page with changes

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#532]
Need to update index with improvements / issues etc 

One note, including this success case would good:

> O'Connor and O'Hagan 2015 doi:10.1080/03075079.2014.1000292 - we don't have a sub and OAB finds it at the author's repo - this was surprising and delighting! https://ulir.ul.ie/handle/10344/5352

**Comment by markmacgillivray** [comment]
What does this mean? I don't know what "update index" refers to.

**Comment by JosephMcArthur** [comment]
Have updated the issue title. I was just talking about the homepage / download page we have for the bookmarklet.
