### ISSUE TITLE
Improve bookmarklet accessibility through colour use 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#534]
Issue:

> OAB window availability section. Can the background be less blue. Can available has a link to library search?

Obviously this will start to move away from our live version if we change it. Perhaps a white background with _just_ the icon color changing could be a good thing to test?

**Comment by markmacgillivray** [comment]
Yes, available can link to library search - we actually also get more info about where the thing is, but that was removed from what the bookmarklet displays. To link to the library, all I need to know is the URL of their library search.

For the icon colours, they can basically be absolutely anything they want. Probably have to decide if we're going to keep the bookmarklet looking as is for this or the normal one anyway - as we are now pushing more functionality to the site pages, I'd actually prefer to have the bookmarklet pop a page open on our site, then we can provide a lot more info and next steps, as well as a library search right there on our page, and potentially with more functionality than their current search.

I think this is a separate demo though, but it is what I will look at doing next - a different bookmarklet approach that pushes to our site with more info there. But this won't be ready for the current reply to Imperial - all we need to say at this stage is ask them what URL they want, and to say that design stuff like colours can be easily configured, but not done yet, as we are currently reviewing our own design anyway.

Assigning to @JosephMcArthur to get back to the library about this.

**Comment by JosephMcArthur** [comment]
this looks like it: primo.hosted.exlibrisgroup.com/primo_library/libweb/action/search.do?vid=ICL_VU1&reset_config=true

**Comment by markmacgillivray** [comment]
I can't reach that URL - does it work inside Imperial?

**Comment by JosephMcArthur** [comment]
I got it from here, erm, just google imperial library catalog & click
about. That's how I found this.

**Comment by markmacgillivray** [comment]
OK, but do you know if that URL works from inside Imperial? WHen I try to open it, it does not work, from the web connection I'm on.

**Comment by JosephMcArthur** [comment]
not done in new design
