### ISSUE TITLE
Add "powered by" statement & bar

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#535]
Issue:

> Can imperial and/or OAB logo be added?

This is seen in mockups, but lost in actual bookmarklet. It's something we should have. 

Perhaps, "powered by the Open Access Button & Imperial Library". Would suggest inclusion of the library as obviously their systems are powering much of it!

**Comment by markmacgillivray** [comment]
Added as statement on the bottom, with bold names that are links as well. Can add as logos, but as we need to probably do a full redesign of UI, for now this demonstrates it can be done easily enough, and looks reasonable as is for now.
