### ISSUE TITLE
bookmarklet click through not working

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#536]
> In this particular case the click-through doesn't work, I get a 410 Gone error message with a URL of http://journals.sagepub.com/doi/abs/10.1177/undefined and I don't know if that is the OAB not having developed it, or a bug.

**Comment by markmacgillivray** [comment]
Unfortunately this can't be fixed without further info - the DOI in the URL is incomplete, so I can't tell what the original source was meant to be. The doc from Imperial doesn't say either. If it was wrong on sagepub, there is little we can do. But if we can find out the source, I can check to see if it was us extracting it wrong.

Putting this issue back to @JosephMcArthur to ask in the email to go to Imperial

**Comment by markmacgillivray** [comment]
Update - found this one during testing of the DOIs that had failed to find a sub, and I think this problem should not come up any more. When we find the sub, the blue button now just tells the user to sign in to the page they are looking at to get sub access via their library, and clicking the blue button just closes the bookmarklet. So, this can be closed as fixed, but will leave open for you to review in your email.
