### ISSUE TITLE
Find system picking up wrong article

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#537]
> Crenshaw 1991 doi:10.2307/1229039 This is free-to-read on Philpapers (not sure if OA). The OAB says "Open article" (blue) but links to the wrong thing: https://ojs.uv.es/index.php/RELIEVE/article/view/6832 – ?!

**Comment by markmacgillivray** [comment]
Has been fixed during the various source updates. Now links to the correct item at http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.695.5934
