### ISSUE TITLE
How to deal with "non-articles"

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#538]
Issue from testing:

> The OAB flow needs to deal with "non-articles" of various types, because users can ILL all sorts of stuff.

I realise we're not able to be able to add significant functionality to really interact with other types of media powerfully, however, perhaps changing the copy of our "this isn't an article" type responses could be useful. For example, suggesting they use the full ILL system? 

I think how to handle this is an open question.

**Comment by chealsye** [comment]
Could we deal with it separately public Button vs uni service? And wouldn't it also depend how thorough of a service a uni has?

**Comment by JosephMcArthur** [comment]
We can certainly do it differently depending on public vs uni. And yes, it
probably would depend on the ILL service we're dealing with.

**Comment by chealsye** [comment]
Hmm okay. I think we're going to have to have multiple different forms of it. Depends how integrated the uni service is. If the uni has ILL, what system they are using, if we can still send the info or the person then has to interact with the ILL system themselves (which if this is their first time using the uni Button there's a good chance they wouldn't again if it wasn't a positive experience). 

You said that for example, suggesting they use the full ILL system. I might have an incorrect understanding of the institutional service, but I thought we'd be able to provide details to an ILL system. I understand if someone is wanting to request some rare book or a DVD, but what if they are looking for a book? How does the Button handle that? Would the user have to then also interact with a second system?

**Comment by JosephMcArthur** [comment]
Old, and not needed. Closing.
