### ISSUE TITLE
Switching out username for email

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#541]
> Should it be Imperial username instead of email address? What happen if the user enter a private email address?

As expected, they've suggested this. What they're suggesting makes sense for final version, but perhaps not for testing (as we need emails for debugging by _us_)

I think we should just update documentation here to speak to that. 

I think this will be closed by #532, but I know we'd discussed this in depth before so wanted to make a separate issue to allow more discussion.

**Comment by markmacgillivray** [comment]
Added as comment to the change log on index page
