### ISSUE TITLE
How to deal with OA articles

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#543]
> For a scenario where the article is open access, not in Spiral and not somewhere that Imperial subscribe to: OA window > Open article: The open article link open the link in a new window to the Article page not the PDF.
> If this is expected behaviour for the “Open Article” link, the user might think that it will open a full PDF version of the Article.  In this example, being directed to the same page make cause confusion (the user might think the OAB is not working.) Should there be a short text to say something like “this article is OA you can download it from the article page”

This is essentially a version of the same question we've had for a long time, i.e, what to do when an article someone is clicking on is open access. Considering CL has all the tech in-house to solve this issue is it time to brought this to bear on things like the above? Obviously, the benefits for the public version would also be pretty nice.

Fwiw, I expect all that would be too much work to do in this sprint, but we can discuss a bit.

**Comment by markmacgillivray** [comment]
Presumably solved by checking DOAJ, but see #575
