### ISSUE TITLE
How can we make data requests more attractive?

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#546]
Here is a list of things that researchers say would motivate them to share data, so, how can we align what we're doing here (or, where are we already aligned)!?

![image](https://cloud.githubusercontent.com/assets/4953703/23095298/5b177a4e-f5ff-11e6-9a64-95f63d95d56f.png)

Cite: https://twitter.com/emckiernan13/status/822127545927815170

**Comment by JosephMcArthur** [comment]
Nudge theory would suggest we should just try and convey it as cool / normal: http://freakonomics.com/2013/04/03/the-tax-man-nudgeth-full-transcript/. 

Therefor, we should find a way of saying stuff like "most researchers share their data, it's expected!"

**Comment by svmelton** [comment]
Seems like this could be another place to strategically partner with libraries, since a lot of the motivation seems to come from wanting assistance preparing data. Not every library has a data management person, but increasingly more do.

**Comment by chealsye** [comment]
+1 Sarah
We cannot cover most of these incentives, but we could do our best to partner with librarians.

How many data requests do we even presently have? I'd say having a solid story where someone wants to make use of the data and is citing is will be a greater incentive, but it'll have to be a more powerful story than an average article request. At the very least I think we need a different request email for data that highlights data specific bits about funders who support and benefits of data citation.

**Comment by JosephMcArthur** [comment]
No longer doing data work, no capacity. Focusing on articles to build plumbing and hoping to return to data later. Closing this for now to keep the repo clean.
