### ISSUE TITLE
Article is already available button linking to wikilist rather than archived article

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#547]
When 10.1016/j.lisr.2010.12.002 is entered into the Button's search it says the article is available. However, "This article is already available!" button links to https://en.wikibooks.org/wiki/Introduction_to_Library_and_Information_Science/To_Do_List, which is a wikibooks list of LIS books. The result should instead be linking to http://www.oclc.org/content/dam/research/publications/library/2011/connaway-lisr.pdf, which is found in the list.

**Comment by JosephMcArthur** [comment]
have added https://en.wikibooks.org/wiki/Introduction_to_Library_and_Information_Science/To_Do_List to the blacklist. So it won't show. 

However, @markmacgillivray how on earth are we linking through a wikilist?

**Comment by JosephMcArthur** [comment]
This is in base, that's why. Just weird. Seems unlikely that we'll find stuff here so closing.
