### ISSUE TITLE
Receiving two verification emails after signing up

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#549]
Yesterday and today I was using the dev site. When I signed up for an account instead of receiving a single verification email I received two. I only hit 'enter' one time. This happened again tonight.

![screen shot 2017-02-19 at 22 22 14](https://cloud.githubusercontent.com/assets/9299248/23110930/e71b9d6a-f6f2-11e6-9ba8-069add0398c6.png)

**Comment by JosephMcArthur** [comment]
@chealsye have you seen things like this before, or seen it on the live site?

**Comment by JosephMcArthur** [comment]
Just got this on firefox 51.0.1 (64-bit) on the live site. 

![image](https://cloud.githubusercontent.com/assets/4953703/23159401/8a7c37bc-f81a-11e6-8466-83976ce75af3.png)

**Comment by JosephMcArthur** [comment]
@markmacgillivray with the new site live the mailgun logs will be able to tell us if these double emails are requested by users or are sent even on one request. That'll be helpful here. I wonder if this was something to do with the switch from io to org. The timing seems right.

**Comment by chealsye** [comment]
Ah damn after our chat on the dev call yesterday I was hoping it was just going to be the dev site.

This happened in both Chrome and Firefox - I believe. Definitely Firefox the first time and I think the second time in Chrome but I'm not 100% positive.
Computer: OS X Yosemite 
Chrome: Version 56.0.2924.87 (64-bit)
Firefox: 51.0.1 (64-bit)

**Comment by markmacgillivray** [comment]
No further progress possible, re-open if more evidence found.
