### ISSUE TITLE
Dev site frontpage search redirecting to find page, not completing

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#556]
I searched for an article on the dev site. I expected it to search for the article, perhaps not be able to find the article and/or data and prompt a story. However, instead of the search starting and being told whether the article and data was available I was redirected to /find. The search worked correctly when I resubmitted the url on /find rather than the front page. 

![screen shot 2017-02-20 at 18 07 58 1](https://cloud.githubusercontent.com/assets/9299248/23144788/19d4a576-f798-11e6-9b60-0a65ea1f7d66.png)

You can view the bug in a short video here: https://drive.google.com/file/d/0B3zC2zJzpxoISlZnYi1ua0Y2SUk/view?usp=sharing

This happened in both Chrome and Firefox.
Computer: OS X Yosemite (I know, I know update it, Cheals)
Chrome: Version 56.0.2924.87 (64-bit)
Firefox: 51.0.1 (64-bit)

**Comment by markmacgillivray** [comment]
Fixed
