### ISSUE TITLE
When scrolling down on live /request, options overlap with footer

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#557]
![image](https://cloud.githubusercontent.com/assets/4953703/23158128/e452a2bc-f815-11e6-9498-30605e35c64c.png)

kicking this into the current sprint, it's a pretty unsightly bug & I think might happen a fair bit as people explore.

**Comment by markmacgillivray** [comment]
The options will continue to overlap the footer because they are fixed so they don't slide away. However I have added a white background to the div htey are in so it overlaps neatly and does not show the footer text through it.

**Comment by JosephMcArthur** [comment]
Ah I see, that's certainly better and we should push it live.

However, would it also not be possible to have the page understand that the
bottom of the footer bar shouldn't overlap with the footer, and stop it?

**Comment by markmacgillivray** [comment]
I've already put it on live. There is no straightforwardly simple way that I could do without wasting a lot more time on it.

**Comment by JosephMcArthur** [comment]
Understood. We'll keep it closed then!
