### ISSUE TITLE
Creating direct links to request keywords and/or custom request searches

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#558]
Just now I shared a [medium piece about doctors not being able to access cancer research reported in the news](http://bit.ly/2lJuVDM). My instinct was to share a link to OAB requests with that included cancer (193 of them!) or ones marked as keyword cancer (45!), and invite people to support requests. But I cannot get direct links to that search. Could we add that as a feature? It may not be doable for any search, but at least for keywords we know, perhaps https://openaccessbutton.org/request/keyword/cancer for the keyword list. 

I think this enhancement will further enable productive sharing and could be used to increase request support.

**Comment by JosephMcArthur** [comment]
We used to have something like this I think, hopefully we can bring it
back! Certainly seems helpful here, great idea!

**Comment by markmacgillivray** [comment]
@chealsye I have just enabled the full search url state in the request page on live. This means that you can do any search on the page you want, then the URL of the page will update and you can copy/paste it to get the URL to that same result set again. It is not a tidy url like you wanted though, but it is an easy way to direct link.

Also, you can do a more tidy version by using some of the underlying functionality directly. For you example, if you want a keyword search on cancer, make a link like this:

https://openaccessbutton.org/request?q=cancer

This will give you a link to the a general search term on "cancer".

it is supposed to be possible to do a search like q=keyword:cancer to only use the term in the keywords, but that does not seem to be working right now, so don't do that.

**Comment by markmacgillivray** [comment]
@chealsye I have fixed the keyword search url params too, so actually you can do it BUT note my example above was wrong, the field is called keywords. So try this:

https://openaccessbutton.org/request?q=keywords:cancer

**Comment by chealsye** [comment]
Thank you! And so speedy!
