### ISSUE TITLE
Bookmarklet still asking for location on live

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#559]
Thought we had this taken out of everything but plugins

**Comment by markmacgillivray** [comment]
No, location was disabled on the site, but still on bookmarklet and plugin. Maybe it should have also been disabled on bookmarklet and I missed that, but I have disabled it on bookmarklet now. Will change when we next update live site.

**Comment by JosephMcArthur** [comment]
Do you mean you've updated & it's waiting to ship, or that you'll update it next time we update?

**Comment by markmacgillivray** [comment]
It's updated, waiting to ship

**Comment by JosephMcArthur** [comment]
@svmelton can you test on dev please?

**Comment by markmacgillivray** [comment]
A dev system bookmarklet will still use the live bookmarklet code - testing it won't show the difference. Making that change is harder than it is for other pages.

**Comment by JosephMcArthur** [comment]
Ah! Okay, then can you notify when we next ship & we'll live test.
