### ISSUE TITLE
The Button not telling me to sign in before prompting a request

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#561]
I went to search/request an article. I was told the article was not available and was prompted to start a request. I submitted the request with story and the Button wheel just turned and turned.

Turns out I wasn't signed it -- but I should have received this instead of being prompted to do a request:
![screen shot 2017-02-23 at 21 20 08](https://cloud.githubusercontent.com/assets/9299248/23287863/05f9dbb6-fa0e-11e6-9f93-bdbd8746266d.png)

Instead I was prompted to submit and did not know I was not signed in/that it was a problem. I made a [video](https://drive.google.com/file/d/0B3zC2zJzpxoIb0dBTDJuUHZJQms/view?usp=sharing) of the problem.

Google Chrome Version 56.0.2924.87 (64-bit) 
OS X Yosemite 10.10.5

Worked fine in Firefox 51.0.1 (64-bit)

**Comment by JosephMcArthur** [comment]
FYI, this feels important so I'm bumping to the current sprint

**Comment by markmacgillivray** [comment]
Yeah, things labelled as bug that I assign to myself are getting worked on anyway, regardless of sprint plans.

**Comment by markmacgillivray** [comment]
This was solved on the dev branch, but has never yet gone to live. When we do push to live, that should fix. Unassigning and moving out of sprint but keeping open just in case
