### ISSUE TITLE
Redirected to /find page when prompted to enter in my account details

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#562]
After #561 I quickly logged in and went to make a request. I noticed that my user details were gone (which side note: SUPER annoying as a user and I wonder how many of current users will be irked by that) but was curious if I could still proceed to make requests. I clicked to start a request.

Received this error as expected:
![screen shot 2017-02-23 at 21 28 41](https://cloud.githubusercontent.com/assets/9299248/23288056/20f441bc-fa0f-11e6-98e2-8d8e5d60e15d.png)

it flashed to the sign in, then account page, then "the page has moved. You should be redirect, but if not, click her to /find" and was brought to the /find page. I did not make any clicks or touch keys after I clicked "Complete your account details"

I made a [video](https://drive.google.com/file/d/0B3zC2zJzpxoIZ0FTX2xnN1cxalU/view?usp=sharing) of the problem.

Google Chrome Version 56.0.2924.87 (64-bit) 
OS X Yosemite 10.10.5

**Comment by markmacgillivray** [comment]
The "complete your details" even though you already have will be a mismatch between what we used to ask for and what we now ask for - I'll look into that. However, regarding your user details being gone, it looks like they were still there - the only missing ones were first name and last name, which are new fields we never asked for before.

**Comment by JosephMcArthur** [comment]
@markmacgillivray can we split the data we have for full names so that it works with first / last name & people don't have to re-file in these details. 

I'm very happy to do that by hand if needed, I know it might be tricky to catch edge cases. I thought this was the plan, so think we should make it a priority to fix. This would be super annoying :'(

**Comment by JosephMcArthur** [comment]
FYI, this feels important so I'm bumping to the current sprint

**Comment by markmacgillivray** [comment]
Well, on accounts where we have the full name I could split it at first whitespace and assume the first part is first name and the second part is second name, or if no second part that we just have first name, and then still prod the user for second name. But then we may make mistakes with peoples names - is it more or less annoying to be asked your name, or to be told your name is wrong? Alternatively, you can export the list of user accounts and manually go through them all and separate them out into separate fields in a csv. As long as you keep the account ID as a column, then firstname and lastname as columns, I can import that back in. There are 7-8000 user accounts.

**Comment by JosephMcArthur** [comment]
- [ ] /export is giving me all the fields needed. Needs first / last name fields.

**Comment by markmacgillivray** [comment]
Unassigning me, I cannot progress it until decision made on firstname/lastname content, and sheet provided. Please move to appropriate future milestone once ready.

**Comment by JosephMcArthur** [comment]
Have sent @markmacgillivray data to close this

**Comment by JosephMcArthur** [comment]
@markmacgillivray I think it's really important we get this fix up tonight. Just a little nudge as we're displaying a lot of emails when that's not needed.

**Comment by JosephMcArthur** [comment]
@markmacgillivray did you run this yesterday?

**Comment by markmacgillivray** [comment]
Yes, and I have checked that the accounts were updated.
