### ISSUE TITLE
we need a new template to notify users when we find  the missing author's email

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#564]
so that they know the request is in progress
@JosephMcArthur

**Comment by JosephMcArthur** [comment]
Can you take a first stab at this please? Good catch. 

cc @chealsye

**Comment by chealsye** [comment]
@natalianorori Is there a draft of this?

**Comment by natalianorori** [comment]
here https://docs.google.com/document/d/1i3_mURvK626qAQVLGcnIqOs8XjGXiNHbSRLuUUkqKQo/edit
@chealsye

**Comment by JosephMcArthur** [comment]
this is up! edits still welcome, just let me know
