### ISSUE TITLE
Duplicate Student and student categories for filter by user

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#565]
Student and student are listed under filter by user on the request page. Would it be possible to merge student with Student?

![screen shot 2017-02-24 at 22 34 20](https://cloud.githubusercontent.com/assets/9299248/23327833/8dd9510a-fae1-11e6-82db-732dd0590197.png)

**Comment by JosephMcArthur** [comment]
+1, same with researcher, Researcher, and academic.

**Comment by JosephMcArthur** [comment]
I think I can do this from /export, so will!

**Comment by markmacgillivray** [comment]
@JosephMcArthur this would be an easy one to solve programmatically, so no point you wasting time doing it manually. I can just replace the undesired ones with the desired ones.

**Comment by JosephMcArthur** [comment]
Okay, 
- [ ] other + undisclosed + advocate = "other" (or whatever our current capitalisation is from sign up)
- [ ] merge both students into whatever we're currently using
- [ ] merge researcher + Researcher + Academic into whatever form of researcher we're curently using
- [ ] doctor --> health professional here

Are there really no "patient" requests?

**Comment by markmacgillivray** [comment]
There are 18

https://api.openaccessbutton.org/requests?q=user.profession:patient

**Comment by JosephMcArthur** [comment]
Doesn't look like they're coming up in the dropdown. Also, the entire sidebar filters seems to be gone on live.

**Comment by markmacgillivray** [comment]
Ah, that is because it maxes out at 10, but now that there are misspellings there are more than 10. I will fix that now, and the fact that they are not displaying at all...

**Comment by markmacgillivray** [comment]
Ha ha, I increased the size now there is all kinds of junk showing up in it... one of the older users has called themselves a minor deity.

**Comment by markmacgillivray** [comment]
Script written, and outcome being tracked in #598

**Comment by JosephMcArthur** [comment]
Our upload of old data seems to have reverted this.

**Comment by markmacgillivray** [comment]
New script ready, to run tonight on live.
