### ISSUE TITLE
Ways on improving the first contact email we send to authors 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#566]
we are not getting many responses from authors and we have already been managing the system for over two months. The first email we send to them is the first approach they get from the bottom, Joe and I have researched some email contact techniques here https://docs.google.com/document/u/1/d/1NhF_YAtF_0PFtBtt70s093_RllL1uirFOQ2TMWhCETE/edit

and have come to the conclusion to:
- [x] add the author's name to the email 
- [x] remove bad stories ( use #475)
- [x] remove the "Open Access Robot" signature

any ideas or comments on this issue would be helpful @OAButton/team

**Comment by JosephMcArthur** [comment]
@markmacgillivray do we need to update our current template to handle the first / last name change?

**Comment by markmacgillivray** [comment]
It won't be possible to do that via template because some user accounts are going to have first names and some are not. This whole name thing is becoming a bit of a problem, really, and it is still not clear why we seem to swing from being strongly pro-anonymity to asking people for their names in even more detail, and to use in even more specific ways. But anyway, the only way round this is you'll have to just keep using username in the template, and I'll have to alter the template system to prefer firstname over username where available. Would that be acceptable?

**Comment by JosephMcArthur** [comment]
Yes, that makes sense. So, a name tag an email would use the following logic, prefer:

[first name] + [last name], then if not available
[full name], then if not available
[username], then if not available
[email]

**Comment by chealsye** [comment]
@natalianorori That doc requires permission. Could you put it into the OAB folder?

I agree with the Open Access Robot removal. 

Aren't we currently *requiring* users to provide first and last names before being able to make a request?

**Comment by natalianorori** [comment]
sorry! the doc is already on the OAB folder

**Comment by chealsye** [comment]
@natalianorori I don't have permission to view the file, so I don't believe the doc is already in the OAB folder.

**Comment by natalianorori** [comment]
@chealsye can you check again now? Sorry!

**Comment by chealsye** [comment]
Now I can, thanks!

**Comment by chealsye** [comment]
How are we going to gather the author's name? Is this realistic to gather with requests?

**Comment by natalianorori** [comment]
Author's name are easy to find when we have the paper, there are only a few
cases in which we only get initials, but last names are almost always
there. Most of them have professional email addresses in which the name is
shown.

However, adding the author's name would have to be a manual process at the
moment

**Comment by chealsye** [comment]
OK - lots of individual, manual doing. It certainly is doable, but not sustainable with large growth. I think it would be worth trying now and see if it works while requests are manageable. Hopefully shortening the email and doing the personalized touch will contribute to positive requests.

**Comment by markmacgillivray** [comment]
Please do not reassign me until agree within a starting milestone.

**Comment by natalianorori** [comment]
I agree with you Chealsye, once the system gets more request, adding the name manually will be an issue. 

Since we agreed on removing the Open Access Button Robot signature, can we change it to "sincerely, the Open Access  Button" or "sincerely, the Open Access Button team" on the templates displayed by the request system so I don't have to delete the word "robot" manually?

**Comment by chealsye** [comment]
Natalia, I left comments on the proposal doc you wrote for changing the way we message requests. One of the suggestions was to actually sign our names. So, instead of the robot or team, it'd be you! Of course as a standard it may not be you -- someone else will eventually need to help on requests (although tbf there could be two drafts with different signatures). But it could be a way of being more friendly, getting you some external recognition, and them knowing there's a real person on the other side. Of course as long as that is something you're comfortable with. A majority of companies have 'real' names attached to their emails, so it may be a strategy worth trying.

Sincerely is rather formal. I personally only use it in cover letters. Perhaps we could explore using another word that better matches with what will be the new tone?

Are you able to edit the templates on github?

**Comment by natalianorori** [comment]
Chealsye, 

yes, I totally agree with signing with a name (in this case, my name). So I can start doing that if its ok with @JosephMcArthur . We can stick with Kind regards instead of sincerely, or if anyone has other ideas of closure phrases I am open to sugestions. 

I am not sure if I can edit the templates, lets wait til Joe wakes up to see what he thinks

again, a billion thanks for helping me with this!

**Comment by chealsye** [comment]
Great! Yeah, the text can always be adjusted. What's your title? Might be worth including as context (or adjusting it a tad). I also commented on your idea of having emails from Joe - I think it could be a great, compelling follow up email that he signs. So, maybe we can get 'persona' emails going that come in at different stags; Natalia, the awesome request system manager that excites authors with the benefits of sharing their research, Joe the founder with his compelling testimony. Might be a strategy to engage and follow up with authors without it being static. 

Okay, if you're unable to and need adjustments I'm happy to help at other times.

**Comment by JosephMcArthur** [comment]
Changing from what we have now to names is fine. We can eventually have it input the name of the person sending it (and their title) automagically. Happy to do the actual edit on github if people aren't comfortable (but it's possible for everyone to!). 

My suggestion with author names in the email is if we can do it now, lets do it (as we think it'll be nicer). If we can't do it later, we'll change it. 

FYI: I haven't seen other email drafts yet, so not commenting on this, just the issue of opening / closing.

**Comment by chealsye** [comment]
There have been no email drafts yet. I'm happy to do the first draft, but I thought I wasn't supposed to.

**Comment by JosephMcArthur** [comment]
In terms of this first email I asked @natalianorori to do some general research / idea gathering on email writing & what others are doing. This was with the idea we might follow a radically different route if that makes sense, or test many alternatives. 

@chealsye please always feel free to rewrite / draft things if you think they need improvement - including in this case

I'd suggest that if we have agreement on the changes in the first issue, that we implement them. There is no harm in doing that as far as I know, and if we think they're improvements there is no reason to wait.

**Comment by natalianorori** [comment]
@chealsye  @JosephMcArthur  yes, The document was just general research and you are always welcomed to edit it, maybe in the future we can come up with a new template. 

at the moment, I am going to start implementing the changes we agreed with, Greeting the author by it's name and signing with mine or whoever handles the request. I tried it yesterday with a few requests and got the quickest response ever recorded by an author yay! 

My job title is Operations Assistant, but I don't know if it makes sense to sign with that title or if it should be changed a little just for request system email purposes, any input here is welcomed

**Comment by natalianorori** [comment]
@JosephMcArthur I tried to make the changes to the templates on github but I got a message saying that I must be on a branch to make those changes.
Could you do the edit on github for me? thanks!

**Comment by svmelton** [comment]
@natalianorori @chealsye I'll be working on author tests the next couple of weeks. Let me know if you have a draft ready to go and would like me to test and get feedback on.

**Comment by chealsye** [comment]
@svmelton Thanks for the heads up, Sarah! I have 'write a draft' on my to do list tomorrow, so between back and forth editing I imagine we'll have a solid new email within a week.

**Comment by chealsye** [comment]
A first draft of the email is here: https://docs.google.com/document/d/1BJ-6BvCTsB2KGqaUtYnWVJylrVQSSY64UK4i6_Tz-pM/edit.

Would love feedback on it, especially @natalianorori if you think the new phrasing works with the request system as you know it. I think it would be a good idea to have a tweaked version for data.

**Comment by natalianorori** [comment]
I don't know why I can't access it, is this on the OAB folder?

**Comment by chealsye** [comment]
@natalianorori It is in the Open Access Button folder under the copies (Comms and Advocacy > 2016 - Present > Copy Drafts > Emails) ... but you aren't listed as a person with access to the item, which is very weird. I've added you, but I think we need to double check your ability to view the whole OAB folder and it subfolders because something funny is happening...

**Comment by natalianorori** [comment]
I am now able to, I was before but don't know what happened during the last days, weird but fixed now:)

I added comments on the email which by the way I think is such an improvement and will definetly help increase the response rate we get from authors. any comments and thoughts from everyone else are appreciated. @OAButton/team 

Thank you for doing this copy @chealsye

**Comment by natalianorori** [comment]
I think the template is ready, both me and @chealsye left comments and we seem to be on the same page. @JosephMcArthur can you please give us your feedback asap? so we can start using this as soon as possible

**Comment by JosephMcArthur** [comment]
Look great, need me to upload?

**Comment by natalianorori** [comment]
yes please!

**Comment by chealsye** [comment]
@JosephMcArthur Did this get up?

**Comment by JosephMcArthur** [comment]
Yup! I think this can be closed, for now.
