### ISSUE TITLE
Requests made by undefined

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#569]
Seen a few of these: https://openaccessbutton.org/request/FqFEW4nJg7Xjdrxkm

In this case I could check their account and they weren't being asked for more details

**Comment by markmacgillivray** [comment]
There is a fix for this ready on dev

**Comment by markmacgillivray** [comment]
This is no longer on dev. Let me know the priority of it and which milestone it should be completed within.

**Comment by JosephMcArthur** [comment]
is this now on dev again?

**Comment by markmacgillivray** [comment]
Not as far as I can see

**Comment by JosephMcArthur** [comment]
Should be fixed, will re-open if not
