### ISSUE TITLE
/sources

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#571]
@markmacgillivray has made a pages on our sources: http://dev.openaccessbutton.org/sources 

This has a similar role to: #484 , but may be a way to keep it more up to date. 

Assigning Mark to keep editing / writing until he feels like the info required is on the page. Then @chealsye and others can edit / rewrite where is required.

**Comment by markmacgillivray** [comment]
The info required is already on the page. The only bits needing filled in are which of the underlying sources you would like to specifically mention at the "such as..." part, and links to the full source lists of the aggregators we use.

**Comment by markmacgillivray** [comment]
Removed from dev. Please make strategic decision if sources page is required or not, and if so please let me know what technical content is required.

**Comment by chealsye** [comment]
Noting that this edit is being used for the new Copywriter and Communications Assistant application test and not being done by me. We should have copyedits within a week.

**Comment by JosephMcArthur** [comment]
I have taken some key parts of this and moved onto about, closing now
