### ISSUE TITLE
Unable to copy sample DOI in /find box to test the Button

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#572]
Was the intention of adding a sample DOI to the /find box to allow users to test the Button out? This was my impression because an example url was requested and this appeared with the latest update, so I thought it was for that (but I could be wrong!)

![screen shot 2017-02-27 at 19 44 35](https://cloud.githubusercontent.com/assets/9299248/23386586/3d16133e-fd25-11e6-9390-f6fd4fe3bd87.png)

However, you can't copy this text and use it to test. 

So, questions:
Was the DOI simply added there for a visual example, @markmacgillivray? And if so, @JosephMcArthur, do you want an example for users to play with as well?

**Comment by markmacgillivray** [comment]
The dev site already has clickable examples, solving this issue.

**Comment by chealsye** [comment]
Ah okay, sorry, thanks.
