### ISSUE TITLE
Search box UX improvements from blog

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#573]
This seems like a helpful set of tips around creating search boxes. Do they provide any guidance for how we should design our system? 

https://uxplanet.org/design-a-perfect-search-box-b6baaf9599c#.yemqz9ggg

**Comment by markmacgillivray** [comment]
The only extras there that we do not have are an actual search icon - we've tried different search icons in the past and currently don't have one at all. I would rather have one, and am happy to use the traditional one if this is going to be acceptable to everyone.

The only other thing is autosuggest. Our search functionality already has autosuggest capability, and a lot more besides, but we have never managed to get far enough into developing the search and visualisation features to even explore what sorts of search to have. I am feeling frustrated by this as there IS a lot more we could be doing here, but every step forward feels like it is followed by two steps back at the moment.

**Comment by markmacgillivray** [comment]
Interestingly the front page of google does not use a search icon at all...
