### ISSUE TITLE
Tweet @ Button

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#574]
Moved from #560.

@markmacgillivray if it's easy to do this, lets go for it. It'll be fun! 

> We have also previously talked about the API automatically tweeting things, but it has not made progress. The functionality is there, and I could have it tweet certain numbers, I just need to know what you want it to say and when.

> Also, the API can respond to tweets too - if someone tweeted at oabutton #find SOMETHING then we could respond with a link or a request page. Again, just need to know what you want it to monitor to respond to, and what you want it to say in return.

**Comment by nemobis** [comment]
It would be nice to add the research field as hashtag and/or cc an institution/potential author. From https://api.elsevier.com/documentation/retrieval/affiliationRetrievalResp.json I don't see Twitter handles.
ORCID has Twitter account names but of course you first need to get the ORCID in some way.

**Comment by wetneb** [comment]
@nemobis if you want to connect ORCID institutions to Twitter handles, I recomment Wikidata for that. ORCID uses Ringgold identifiers for institutions, and we have imported a lot of them into Wikidata.

Here is what we currently have for institutions: http://tinyurl.com/ycolmx4c
and for researchers (not a lot!): http://tinyurl.com/yb8qq6e4

Join us at https://www.wikidata.org/wiki/Wikidata:WikiProject_Universities to improve that :)

**Comment by JosephMcArthur** [comment]
We've now got a chatbot on Facebook messenger, and could probably port this to twitter fairly easily. That would allow us to close this, although I agree that adding in hashtags and things like that would be very cool (we often get the discipline of the paper, and could just manually curate the list for some to see if it even matters)

**Comment by JosephMcArthur** [comment]
Archiving older issues, including this one!
