### ISSUE TITLE
filtering requests by date

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#576]
or by year range, this would simplify managing old requests. This is not urgent or needed immediately, but would be good in the future

@JosephMcArthur

**Comment by markmacgillivray** [comment]
This is the sort of feature that is already possible in the code we have, and which I have tried to introduce at various points on dev. But we have never got to the point of having agreement on feedback as to how to move dev experiments to live, and as we know from recent experience, these attempts often do not go well with the team.

So, this is just a note to confirm this is easily done, and all we need is team agreement on what functionality to have on the requests page, and how it should look, and how it should be described. I won't be making further experimental developments of these sorts of feature until after such decisions are made, so I guess this sort of issue will sit open until we prioritise with the team and tackle them in a particular milestone.

@natalianorori there are some "power-user" ways of typing text commands directly into the search bar, but we've also never documented these in the content of the site. If you want to know what they are, let me know and we can discuss directly. Also, where you have a particular need for a command, such as you do here for searching by date / year range, that could probably be added to the text commands for you without us having to worry about how it impacts the site UI or content for other people.

**Comment by natalianorori** [comment]
Hi @markmacgillivray ,

Just following up with what we've talked through email here. 
Basically, the main reason for me to being able to filter requests by using different commands is to prioritize requests with good stories, prioritize requests by year range or by date (newest come first). at the moment, commands that would help me would be:

- filtering requests by date
- filtering requests by story rate or filtering requests with no story

I am aware that the system already knows  how to filter requests by user's type, professions, journals and even know I haven't used this filters as widely, I think they are a going to come in pretty handy when we get to the point of experimenting with the response rate we get from people from different fields. 

I'd appreciate if you can share the existing commands with me so that I can find ways to implement them in my work as the request system manager, thanks!

**Comment by JosephMcArthur** [comment]
So, I know we tried to implement this on live but we hadn't been able to do this in a clean way. In a case like this, I'd suggest we implement for admins if we need to ship quickly. 

Seems like the power - user search might work, or, we can bring in almost any implementation for admins.

**Comment by markmacgillivray** [comment]
Added a slider to the bottom of the left hand dark blue list of filter options - slide it to alter the date range of requests on display. Only shows up for admin users. Once there is time to think more about a decent admin display, or giving more of this functionality to all users, this slider can be more appropriately positioned and contextualised. Will push to live shortly (requires no API udpate)

**Comment by JosephMcArthur** [comment]
@natalianorori shout if this doesn't work / isn't what you need.

**Comment by natalianorori** [comment]
This works! And looks nice. Just tested it today.
