### ISSUE TITLE
Need a new email "we saw you tried to make a request but the link you sent us is broken".. etc

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#579]
For when requests link to invalid websites, or to nowhere

**Comment by JosephMcArthur** [comment]
@natalianorori can you take a first draft & then send to @chealsye for review

**Comment by natalianorori** [comment]
https://docs.google.com/document/d/1CZTN4OYmljk9zGxd0UV77_oCK4uQ1r6WTcHSkUbpiG0/edit first draft here @chealsye @JosephMcArthur

**Comment by JosephMcArthur** [comment]
@natalianorori currently we have a template for "invalid" requests which I believe is for book requests, and things like that.

> {{SUBJECT}}:Sorry, we are unable to process your request
> 
> <p>Hi,</p>
> 
> <p>We have received your request for "<a href="{{url}}">{{title}}</a>". Unfortunately, we are unable to help with this request. The Open Access Button only requests research articles and data.</p>
> 
> <p>Since we are unable to help you with this request, we will close it. We hope you’ll submit a research request in the future.</p>
> 
> <p>Thank you for using the Open Access Button.</p>
> 
> <p>Kind regards,</p>
> <p>Natalia</p>
> <p>Open Access Button Request Manager</p>

What is this for exactly? Is this for when the link they've given us doesn't work? If so, being a bit clearer about that might be good.

**Comment by natalianorori** [comment]
I accepted your suggestions in the document, thank you for pointing this
out. I changed the doc name to broken link email to avoid confusions

**Comment by JosephMcArthur** [comment]
done! on dev soon. please test before sending
