### ISSUE TITLE
Creating anonymous requests via the plugin

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#582]
Now that we can allow anonymous requests, it could also be possible to allow anonymous requests via the plugin, and even remove all need for identification in the plugin.

So that is a decision to make.

**Comment by JosephMcArthur** [comment]
This would allow us to show the bookmarklet without needing an account, right?

**Comment by markmacgillivray** [comment]
Well, the bookmarklet is separate from the plugin, but yes the same is true there. If from bookmarklet or plugin we open a page to the new request, then users who are signed in would get their request assigned to (owned by) them automatically, and users not signed in or not yet with an account would still see the new request and the prompt to sign in / sign up to take ownership of it. Then the plugin and the bookmarklet could both be simplified and function without needing to know the user details.

**Comment by JosephMcArthur** [comment]
done in the new version 💯
