### ISSUE TITLE
System fails to identify the last characters of email addresses

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#583]
at first I thought this was a problem with old requests only, but I had to manage requests with missing characters again today. see attachments 
![screen shot 2017-03-20 at 4 32 12 pm](https://cloud.githubusercontent.com/assets/20844934/24122819/b435ee8e-0d93-11e7-9fcf-c380c9add76e.png)
![screen shot 2017-03-20 at 4 32 31 pm](https://cloud.githubusercontent.com/assets/20844934/24122820/b47760c6-0d93-11e7-87ff-1af984f0f494.png)

@JosephMcArthur @markmacgillivray @chealsye

**Comment by JosephMcArthur** [comment]
today, or http://science.sciencemag.org/content/355/6331/eaal3729 it just have me a "g". That's the first character.

**Comment by JosephMcArthur** [comment]
have we lost email validation on the new site too?

**Comment by markmacgillivray** [comment]
Was just working on it and admin functionality. Try it again now. I'll just push my changes so you can push changes to dev too, it seems you may be trying.

**Comment by JosephMcArthur** [comment]
okay, validation seems to be at least partly back! asdf doesn't work
anymore :)

**Comment by JosephMcArthur** [comment]
is the last character stuff fixed?

**Comment by natalianorori** [comment]
this is still an issue, at least with the requests I moderated today.

**Comment by markmacgillivray** [comment]
I have re-ordered how emails are searched for and filtered, and put longest ones first, and dropped any that appear to be parts of others. This means that overall we should get full addresses more often, but occasionally we will just get the wrong address - or get nothing at all, in testing just now it looks like sciencedirect is blocking some of my requests again.

So I will close this for now, I think it is about as good as we can get it for the time being, you should see improvements on future requests.
