### ISSUE TITLE
When I scroll down on the request page, the side bar used to filter requests isn't displayed correctly.

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#584]
I've tested this in both chrome and safari. when you scroll down the side bar used to filter request isn't displayed completely, which makes it hard to filter requests when you're halfway through the list. see screenshots 
![screen shot 2017-03-21 at 9 31 42 am](https://cloud.githubusercontent.com/assets/20844934/24155325/e5582996-0e29-11e7-87db-306decd9b621.png)

@JosephMcArthur @markmacgillivray

**Comment by markmacgillivray** [comment]
No longer relevant, unfixed the side bar.

**Comment by JosephMcArthur** [comment]
But we've lost infinate scroll here, right? Which will end up re-opening
another bug. Doesn't need to be done instantly. I don't know what the
various trade offs here are in implementing a solution, but this one
doesn't seem workable.

**Comment by markmacgillivray** [comment]
I don't know what you mean. How have we lost infinite scroll? All I have done is just unfixed the sidebar. You just have to scroll back up to see it again. Trying to keep the sidebar fixed led to multiple problems like this one, and the one of it going under or over the footer. If the users screen is just not big enough, this is hard to avoid without also making the sidebar itself separately scrollable, which is not very usable. And also it does not work on mobile, where the user screen is not large enough to show it as a sidebar anyway.

**Comment by JosephMcArthur** [comment]
Sorry... I mistook loss of infinite scroll for running out of requests on dev *finds embarrassed emoji*
