### ISSUE TITLE
set up email alerts for whenever the system gets a new request 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#588]
to manage them as fast as possible 
setting them up for my personal email ( natalianorori@gmail.com) would be the best

**Comment by markmacgillivray** [comment]
Done on dev, will move to live as soon as we update

**Comment by JosephMcArthur** [comment]
@natalianorori let us know if you're not getting these.

**Comment by natalianorori** [comment]
I am definitely not getting this

**Comment by markmacgillivray** [comment]
Damn I got your last name wrong - have updated on dev, will push to live later tonight. Sorry about that.

**Comment by JosephMcArthur** [comment]
closing again!

**Comment by natalianorori** [comment]
thanks Mark!
