### ISSUE TITLE
The responder's page on the website is not working

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#589]
This is really important and is a big block for the request system right now. authors are trying to deposit their links and they are redirected to an invalid URL, we have received complaints about this on zendesk. I know that the there have been some improvements on the dev site, but we need them live asap. any help on this would be useful! 
@JosephMcArthur @markmacgillivray @chealsye

**Comment by markmacgillivray** [comment]
Yes there are improvements coming from the dev site, but looking at the recent zendesk complaints it appears that the URL the users are now being given in the emails are to the request page and not to the responder page at all. We had discussed merging those two pages but that has not been done yet, or even decided as the best strategy, and even once we do this it will still be necessary for the author url to have the responder code string in it somewhere. Also there used to be URLs for the author to delay submission by one week, two weeks, etc, and those do not appear to be present any more either.

So, the solution for now is to fix the email template back to one that is compatible with functionality.

**Comment by markmacgillivray** [comment]
Seeing the response to zendesk from user called Katherine just now, I checked the link to confirm, and it does just go to the request page, not the responder page. So the email template has definitely gone wrong somewhere. Also, as the user says, the request is actually for data, but she has been asked for the article, this could be a template or procedural error, but is not an error being generated by the code.

**Comment by natalianorori** [comment]
Mark, 

good catch. I just fixed the link in the email's folder on the drive. We still have to re upload the email because there is a typo.  What I am going to do is send around apologies to everyone contacted with the wrong link and ask them to either respond to my email with a URL to their article, or deposit in in the receiver's page. 

@chealsye and I worked on a new template to reduce the quantity of things author's have to click on, a more precise and personalized one and It has been showing better results. So for the moment, I will be following up with author's directly, that's why the delay submission links are not present anymore in our new template. All of this was done after researching email approaching techniques. 

and as for Katherine's response, that was a procedural error on my end, since our data template is not up yet, I was just managing article's requests and I must have missed applying the "request type" filter  when contacting her. 

If there's anything that I could do to help in bringing our receiver page to live, please let me know! I'll be happy to help.

**Comment by JosephMcArthur** [comment]
okay, fixed uploaded. Will need someone to re-sync emails on the admin page. 

@natalianorori, whenever we push an email from now on can you test links to make sure they work?

**Comment by natalianorori** [comment]
I just tested the original receiver's link we had in our first author's
request email on my own email address, and the receiver link sends people
to the same box I mentioned earlier and gives them no option to upload
anything. So I definetly can't keep send that to authors. The momentary
solution is to ask them to send their url to me so that I can upload them
to our website manually once the receiver's page is up and running.

**Comment by natalianorori** [comment]
The last time we received an article through the system was on March 6.
https://openaccessbutton.org/request/2co9GGfTncpmoNDKc

**Comment by markmacgillivray** [comment]
They appear to be fine on the live site and on dev (although will be changing how they work). It is possible the links were down temporarily for some other reason, but looking now, I can see them. Here is one

https://openaccessbutton.org/response/gWbiqdKKjaoyaYJhX

**Comment by natalianorori** [comment]
I just tried it and it seems to be working fine now. I will add a reminder
to myself to try these links at least once a week, to avoid this from
happening again.

Please keep me posted about any future changes, thanks for your help Mark!

**Comment by natalianorori** [comment]
I just tested this, and new templates still have a broken link. What's the
exact code to go to the response page?
https://openaccessbutton.org/response/%7B%7Breceiver%7D%7D this is the one
we have and its leading me to a broken URL: You can do both <a href = "
https://openaccessbutton.org/request/wgNTZbXGgCmi6PF5X">here</a>.</p>

**Comment by JosephMcArthur** [comment]
Okay, fixed again. Please refresh templates & test

**Comment by natalianorori** [comment]
Checked and tested
