### ISSUE TITLE
need improved email thanking authors for depositing their article

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#590]
note to self. I'll draft it and share with @chealsye when ready

**Comment by JosephMcArthur** [comment]
Deffo seems worth doing!

**Comment by natalianorori** [comment]
https://docs.google.com/document/d/1PmD5Oriec5ID86jdlRhmReqAujTWXdYZ3NKm20BDv_k/edit heres a first draft! needs some suggestions @chealsye @JosephMcArthur

**Comment by natalianorori** [comment]
Chealsye already checked this and I accepted her suggestions, @JosephMcArthur I think this is ready to be up, if you approve

**Comment by JosephMcArthur** [comment]
on dev soon, please check before sending
