### ISSUE TITLE
Putting up a field for author's name in the request system 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#593]
We are now mentioning author's name in emails, and we have received a better response while doing so. I am currently recording author's names in the data spreadsheet, but would be helpful to have a field for this in the system as well.

**Comment by JosephMcArthur** [comment]
the field should revert of Colleague if the name isn't filled.

**Comment by JosephMcArthur** [comment]
We should move this forwards for use

**Comment by markmacgillivray** [comment]
There won't be time for this in the current sprint. Also it is not clear who would be asked for this, or when, given the points already raised about whether or not we are going to ask users for the author email address, or which author name it is that they are giving, and whether or not it has to relate to the email address being contacted, and what that means for when the email address changes.

**Comment by JosephMcArthur** [comment]
For now, I'd suggest showing this only to admins. This would be in the admin box we currently have. I think if admins manage this for now, and see it's effectiveness (and work out the complexities) then we can decide if we ask users for it.

**Comment by natalianorori** [comment]
i think this should only be showed to admins at all times. It's really
important to not make mistakes when calling someone by their name (wrong
names, spelling), and I wouldn't' trust this task to our users.  I
currently record author's names on the spreadsheet, but having the option
to record this in the system would be super helpful and save me a lot of
time.

**Comment by JosephMcArthur** [comment]
Note, this is currently being requested on the m-turk form

**Comment by markmacgillivray** [comment]
Which author name do you expect to be able to edit? And is it supposed to be related to email addresses? We do already scrape author names from metadata sometimes where available, but we don't do anything with that information. Being able to see and edit all the author names is more complex, and being able to relate the author names to the email address being contacted is also potentially hard - some email addresses bear no resemblance to name. However if all you want here is a box to enter an author name that should correspond to the author email currently in use, that could be added to the admin area of a request page, so only admins can change it. But, you would also have to be sure to change/remove that author name any time you change the author email, otherwise you may email an author and use the wrong name for them. Lastly, if you want such a box in the admin area, do you want just "author name" or do you want "author first name" and "author last name", and if the latter, which of those do you want to be used in email templates?

**Comment by JosephMcArthur** [comment]
> However if all you want here is a box to enter an author name that should correspond to the author email currently in use, that could be added to the admin area of a request page, so only admins can change it.

That was my intention with this issue, yes. 

> do you want just "author name" or do you want "author first name" and "author last name", and if the latter, which of those do you want to be used in email templates?

I think @natalianorori uses first names in emails, she can confirm. My suggestion would be to just have a box that is used for anything though. What actually goes in that box can just be edited, at least for now.

**Comment by markmacgillivray** [comment]
Author name box added on dev, you can put whatever you would like to put in it. You can see it in the admin area and use it in email templates as the {{name}} variable.

**Comment by natalianorori** [comment]
tested it! This is great. Thank you.

**Comment by JosephMcArthur** [comment]
How did you test @natalianorori? We need to make sure this turns up in emails correctly, but can't do that on our current templates (as they'd go straight to live without the box to fill it). 

I've set up a template called author_request_article_v2_fortagtesting for testing in actual emails. .

**Comment by JosephMcArthur** [comment]
Have documented this

**Comment by natalianorori** [comment]
I just tested the box, I tried sending out templates but the system is not sending them out. More on this on #669

**Comment by natalianorori** [comment]
Ok update, 

I tested this on the templates with/without stories. It is displaying the name correctly in the templates with stories only, The email got sent to me when I did this manually. It is not displaying the name on templates WITHOUT stories, but because the template doesnt have the <p>Dear {{name}},</p> on it, it just has Dear colleague, so in order to test the template without stories we might have to update the template @JosephMcArthur

**Comment by JosephMcArthur** [comment]
Great, this is ready to ship then. We just have to push the actual author box / API changes to live. Once that happens we can update all the emails with the right box!

**Comment by JosephMcArthur** [comment]
@natalianorori all templates are now updated with  {{name}}. You'll need to sync, then it should work!
