### ISSUE TITLE
Request page UI changes

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#594]
**issue not completed yet, expecting mark to see tomorrow**

# loading screen

Was a looooooooong wait. Need to get those phrases in asap

# Landing, logged out

<img width="1215" alt="screenshot 2017-03-29 18 50 25" src="https://cloud.githubusercontent.com/assets/4953703/24470120/bbc59c66-14b5-11e7-8e8e-09bc294b3b21.png">

- [ ] remove "are you the author"
- [x] switch out the box for an email box (better to engage them in the action here)
- [x] have button size closer to length of text

# Asking for stories

<img width="1280" alt="screenshot 2017-03-29 18 51 39" src="https://cloud.githubusercontent.com/assets/4953703/24470122/bdc02eb4-14b5-11e7-9d81-0e67bc0f660c.png">

- [x] As I expected when discussing this, I found myself unsure if I needed to give both the story & email as a user. We should be clear, just a story is needed at this point (e.g what if they can't find the email!). The box asking for emails should come up later (as it currently does if you don't provide it)
* can we bring in the word counter system? This time I'd keep it separate from the submit button, and perhaps just be a little counter that changes color? 

# Complete

<img width="1218" alt="screenshot 2017-03-29 19 28 03" src="https://cloud.githubusercontent.com/assets/4953703/24470155/dc696e98-14b5-11e7-8dd3-068d95457c2e.png">

- [x] remove "I actually wanted the data". This should only be allowed while you're making the request
- [x] remove embed, it still looks really bad and no one uses it
- [x] hide "1 person supports this request" if only at one. 
- [x] remove "data for" by the title, the header should make this clear
- [ ] have the facebook button align with notify button, and shift twitter button left to suite

# success!

<img width="1199" alt="screenshot 2017-03-30 08 27 42" src="https://cloud.githubusercontent.com/assets/4953703/24492291/c99d8a02-1522-11e7-96df-59e980a470e2.png">

- [x] remove share buttons (as they'd have the wrong text currently)

**Comment by markmacgillivray** [comment]
Have not removed "are you the author" as it is not possible to clearly identify the case where this should be removed, and it may always be possible that the author is on the page.

Also have not aligned the facebook / twitter buttons with the notify button, as they are embedded from remote sites and are fiddly to size / control, and the notify button is not always present, and I don't have time to sort it.

Otherwise done.
