### ISSUE TITLE
couldn't save a story on firefox + windows 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#600]
http://science.sciencemag.org/content/355/6331/eaal3729

**Comment by markmacgillivray** [comment]
What happened when you tried?

**Comment by JosephMcArthur** [comment]
Nothing, it didn't save, no error, no response. nothing.

**Comment by markmacgillivray** [comment]
Can you try again with a new request?

**Comment by markmacgillivray** [comment]
And let me know which is the new request once you make it.

**Comment by JosephMcArthur** [comment]
Okay, that worked. this was the request 345cb9e

**Comment by JosephMcArthur** [comment]
Same issue on chrome / android. Tested on http://dev.openaccessbutton.org/request/cFHK67riqgCPCRuXo?1=2

**Comment by JosephMcArthur** [comment]
Hmmm, I'm not being kept sign in on mobile. Could that be the issue?

**Comment by JosephMcArthur** [comment]
Even a page refresh is currently logging me out on Dev, android) chrome. Logged out of live site.

**Comment by markmacgillivray** [comment]
I see you're using http rather than https. Are you also logging in/out of the live site at any point? On https and not using the live site, login to the dev site is working fine for me on chrome and firefox on desktop and mobile.

**Comment by JosephMcArthur** [comment]
Okay, using https fixes both the login issue & the submission issue it seems. My phone must still have our dev site defaulting to http from before we switched.
