### ISSUE TITLE
page size a bit odd on some pages

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#605]
Would be more pleasing if the footer stayed at the bottom & the blue extented down on pages like this. 

<img width="1226" alt="screenshot 2017-03-31 13 40 10" src="https://cloud.githubusercontent.com/assets/4953703/24550837/cfcbd1c2-1617-11e7-9e60-7adbb6faaf90.png">

**Comment by markmacgillivray** [comment]
Added footer pusher and lower dark blue. Will cause jumping on some pages, unavoidable, it seems.
