### ISSUE TITLE
false positive for http://science.sciencemag.org/content/293/5530/705

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#606]
search: http://science.sciencemag.org/content/293/5530/705
went to: http://ir.lib.hiroshima-u.ac.jp/en/00017201 (fulltext: http://ir.lib.hiroshima-u.ac.jp/files/public/1/17201/20141016130650436399/diss_ko3577.pdf)

Why: looks like title similarity

**Comment by markmacgillivray** [comment]
I just put this in dev and it started a request for me

https://dev.openaccessbutton.org/request/QMbwZygaP5p2XbanJ

**Comment by markmacgillivray** [comment]
Did you already add the URL to the blacklist sheet?

**Comment by JosephMcArthur** [comment]
No, don't think so! That's odd. The actual reason was probably because the DOI for the IR record is the journal article. 

I think this thesis may actually be closely related to the paper (as in, the paper is part of the thesis). Feels like quite a tricky case to avoid (similar title, doi mentioned on IR page, same authors etc).
