### ISSUE TITLE
"Welcome to our improved site!" banner cutting off page text

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#608]
The banner on the dev site that reads, "Welcome to our improved site! If you have any feedback, or notice an issue let us know here. Read about the updates here." is blocking top text on pages. On the home page it just lowers down the top links, so it is OK enough.

Would it be possible to remove this header from all pages, except the homepage?

**Comment by JosephMcArthur** [comment]
yes, done this now. I had a good reason why I wanted it on all pages, but, I can't remember so it clearly wasn't good enough & there are problems with my suggested fix for having it on all pages.

**Comment by chealsye** [comment]
Totally fine to have on all pages if it can be done to not cut off text.

**Comment by JosephMcArthur** [comment]
Tried to get this message to display on just the homepage but couldn't do it (without breaking stuff) @markmacgillivray the note currently is hidden in the header file. Can you make it display on just the homepage please?

**Comment by JosephMcArthur** [comment]
on now! Just on homepage
