### ISSUE TITLE
full text in pmc, but we miss it

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#609]
# 1 

Article: https://www.sciencedirect.com/science/article/pii/S019701861200006X?np=y&npKey=0265c897cb5d8dab4f556bbb8f1ecc64e3502f9b8811d395b0e8cd471529613c

PMC link: Pharmacological Modulation of NMDA Receptor Activity and the Advent of Negative and Positive Allosteric Modulators

# 2

paywall: https://www.sciencedirect.com/science/article/pii/S0014299911009733
full text: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3220411/

**Comment by markmacgillivray** [comment]
Fixed - new blacklisting and disabling of BASE doi search led to a blacklisting of the BASE title searches. Works now.
