### ISSUE TITLE
false positive: base fuzzy title match

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#610]
response says it came from base.

searched: http://onlinelibrary.wiley.com/doi/10.1002/ncr.187/abstract?systemMessage=Wiley+Online+Library+will+be+unavailable+on+Saturday+25th+March+from+07:00+GMT+/+03:00+EDT+/+15:00+SGT+for+4+hours+for+essential+maintenance.++Apologies+for+the+inconvenience
we found: https://dr.ntu.edu.sg/handle/10220/25927

**Comment by markmacgillivray** [comment]
Fixed. It turns out that BASE quoted title match is not an exact match, just a substring match. So now I only accept a BASE title match if the title of whatever they return is actually exactly the same (lowercase a-z whitespace, at least) as the title we sent them.

**Comment by JosephMcArthur** [comment]
What are the changes of this change having negative effects on picking up
things that might have seen before with subtly different titles? Do we know
how important that is? I know we've had complements on our fuzzy title
matches so don't want to ruin a good thing!

**Comment by markmacgillivray** [comment]
It will make us less likely to find some things, but if their title search is just a substring match, it is too inaccurate. I doubt we would previously have been successfully matching much via that query that we won't still (correctly) match, but it is possible for some articles - like if someone thought the article title was "My lovely article" and actually it was "Not my lovely article" then we won't find that any more. This is better though than finding substrings within titles, that leaves us open to matching far too much junk.

**Comment by JosephMcArthur** [comment]
Okay great, appreciate the explanation!
