### ISSUE TITLE
Accessibility test results

### ISSUE THREAD

**Issue by svmelton** [OAButton/discussion#611]
I ran the site through an accessibility checker, and there are a few things we probably want to take care of:
http://wave.webaim.org/report#/http://dev.openaccessbutton.org/

In addition, I checked the contrast of the background and the header links, and we aren't in compliance with AA or AAA:
![screen shot 2017-04-02 at 6 48 48 pm](https://cloud.githubusercontent.com/assets/7232545/24591685/57a05280-17d5-11e7-96d5-02eecd789aec.png)

I think we definitely want to make sure the header links are legible before launching.

**Comment by JosephMcArthur** [comment]
made black, closing
