### ISSUE TITLE
Finish admin panel on new site and merge response page into request page

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#612]

**Comment by JosephMcArthur** [comment]
linked to #498

**Comment by markmacgillivray** [comment]
Admin panel finished.

**Comment by natalianorori** [comment]
on a side note, I just tested the page and I am able to deposit content, however, after depositing I cannot see the link I added. I tried on this request: https://openaccessbutton.org/response/43cRrjv3CLpr68xoi#

**Comment by natalianorori** [comment]
Mark, another note on this: I tried uploading this paper as an author, from the normal site and it seemed to have worked: https://openaccessbutton.org/response/t63rpKZGmPKwMZ2GM I got the link from the email the system sends to the authors. 

however, I tried uploading a paper as an author to this link and it did not work, I only got to see the article's title and a link to the request: 
![screen shot 2017-04-11 at 12 42 35 pm](https://cloud.githubusercontent.com/assets/20844934/24925022/e7e9d6ea-1ec4-11e7-9a21-90ade3a5070c.png)
https://openaccessbutton.org/response/6RKTghnQQP6g3Azou 

I tried this in Chrome and Safari

**Comment by markmacgillivray** [comment]
@natalianorori @JosephMcArthur In the case of the last article you link to there, where it does not show you a way to upload anything, that is because the status of the request has already been changed to received even though no content has been provided for it. As status can only be changed by an admin, I assume one of us did it, or there is a security issue to explore. If you want to upload something to the request, it has to have a status that comes before received.

Continuing with the work of merging the response page into the request page (which won't affect the above situation) and file upload issues being investigated in issue #644

**Comment by markmacgillivray** [comment]
Relates to #498 for new content

**Comment by natalianorori** [comment]
Thanks for the clarification Mark, Its good to know that I wasn't aware
changes couldn't be made to requests on received status, still learning!

**Comment by markmacgillivray** [comment]
No problem, just change the status back to "progress" or something, and you should be able to see the upload options again.

**Comment by JosephMcArthur** [comment]
Before the sprint team meeting could we get a quick update on progress here, and if anything is blocking us moving forwards?

**Comment by markmacgillivray** [comment]
#498 is taking forward the functionality of the receiver page and not moving it into the request page.
