### ISSUE TITLE
Getting "request undefined" when trying to support a request 

### ISSUE THREAD

**Issue by svmelton** [OAButton/discussion#614]
When using the Chrome plugin to support a request, I was taken to this url: https://openaccessbutton.org/request/undefined

**Comment by JosephMcArthur** [comment]
Seeing the same when asking to be notified from the site when logged out. 

Get sent here: https://openaccessbutton.org/request/4H63Wx3wAB8kqnBnK%3Fsupport%3Dtrue by the redirector (when I should be https://openaccessbutton.org/request/4H63Wx3wAB8kqnBnK)

**Comment by markmacgillivray** [comment]
This should be fixed for the support link. Don't know about from the chrome plugin though, we will have to review that when we decide to simplify the plugin, but that is not scheduled for this sprint so unallocating for the time being.

**Comment by JosephMcArthur** [comment]
on new plugin, this will no longer happen!.
