### ISSUE TITLE
big decrease in the number of requests on the site

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#615]
Currently at 2889, we were over 6k. 

I'm guessing this is to do with how we decided to hide them, no?

**Comment by markmacgillivray** [comment]
Yes, we're not showing requests that don't have stories.

**Comment by JosephMcArthur** [comment]
I can still find ones like this though:
* https://openaccessbutton.org/request/HpNh3yvvc7smq9fez
* https://openaccessbutton.org/request/RbnmkNQzB4MqhLztN

just scrolling down /requests finds many.

**Comment by markmacgillivray** [comment]
Those ones technically do have a story, but the story is "". There weren't any like that on the dev system so I didn't filter them that way. I can alter the query to remove them as well if you want.

**Comment by JosephMcArthur** [comment]
makes sense if we're not showing requests without stories. 

We may need to show _everything_ to admins, as @natalianorori would like to do tests of requests without stories. Can that be done?

**Comment by JosephMcArthur** [comment]
Just gut checking myself here for future joe & others. This means that we'd only be showing higher quality requests on the site, but as a team we could see _all the things_. This makes sense now, as even if we decide to process requests without stories in future just because we process doesn't mean we have to advertise & ask others to help.

**Comment by markmacgillivray** [comment]
I could change what admins see if you want. I could also leave the count as being the big number, even though people would never see the requests without stories. @JosephMcArthur let me know, and I will make the change for admins and the count change if you want it.

**Comment by JosephMcArthur** [comment]
This seem ideal. Leave count big, and allow admins to see all.

**Comment by markmacgillivray** [comment]
OK, have changed so that a logged in admin sees all requests. Everyone, logged in or not, admin or not, sees the full count of requests.
