### ISSUE TITLE
System is using email instead of name

### ISSUE THREAD

**Issue by svmelton** [OAButton/discussion#616]
Even though I'm identified by name on my account, the request page identifies me by email:
![screen shot 2017-04-03 at 7 02 57 pm](https://cloud.githubusercontent.com/assets/7232545/24637082/5ef94dde-18ac-11e7-9220-2548aa4779e8.png)
![screen shot 2017-04-03 at 8 26 06 pm](https://cloud.githubusercontent.com/assets/7232545/24637085/63804970-18ac-11e7-85a1-31584cc0bae6.png)

**Comment by markmacgillivray** [comment]
Old requests made before we updated the system (this weekend) will still show as being made by whatever username we had at the time - for your account, "Sarah" is in the firstname, but you had no username. Firstnames do now get picked up, so future requests you make should have that shown, but your old requests will still only know you by email.

All old requests could be updated with new data, but this is something we would need to schedule into the next sprint, probably.

**Comment by JosephMcArthur** [comment]
We'll definitely want to update these requests asap, early in the next sprint if that's when there is time. @markmacgillivray does it make sense to do with cleaning from #598? Just wondering if we can do a "batch job" of cleaning.

**Comment by markmacgillivray** [comment]
These have been updated.
