### ISSUE TITLE
searching whole titles on /request doesn't pull out that request, but parts of title do

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#617]
Not sure if this a bug or feature request, but as a user I'd expect searches for titles / dois / urls to pull out requests about those things. 

E.g:
Request: https://openaccessbutton.org/request/Nt7t9kixbzqqKeKR8
Seach for whole title: https://openaccessbutton.org/request?source={%22query%22:{%22filtered%22:{%22query%22:{%22bool%22:{%22must%22:[{%22match_all%22:{}}]}},%22filter%22:{%22bool%22:{%22must%22:[{%22exists%22:{%22field%22:%22story%22}},{%22term%22:{%22The%20Nature%20and%20Origins%20of%20Misperceptions.exact%22:%22%20Understanding%20False%20and%20Unsupported%20Beliefs%20About%20Politics%22}}]}}}},%22from%22:0,%22size%22:500,%22fields%22:[%22status%22,%22type%22,%22user.profession%22,%22user.affiliation%22,%22_id%22,%22url%22,%22created_date%22,%22createdAt%22,%22title%22,%22email%22,%22user.username%22,%22user.firstname%22,%22user.email%22,%22location.geo.lat%22,%22location.geo.lon%22,%22story%22,%22count%22],%22sort%22:[{%22createdAt%22:%22desc%22}],%22facets%22:{%22status%22:{%22terms%22:{%22field%22:%22status.exact%22}},%22user%22:{%22terms%22:{%22field%22:%22user.profession.exact%22}},%22type%22:{%22terms%22:{%22field%22:%22type.exact%22}},%22keyword%22:{%22terms%22:{%22field%22:%22keywords.exact%22,%22size%22:1000}},%22journal%22:{%22terms%22:{%22field%22:%22journal.exact%22,%22size%22:1000}}}}
search for parts of title: https://openaccessbutton.org/request?source={%22query%22:{%22filtered%22:{%22query%22:{%22bool%22:{%22must%22:[{%22query_string%22:{%22query%22:%22*understanding*%20*false*%20%22}},{%22query_string%22:{%22query%22:%22*beliefs*%20%22}}]}},%22filter%22:{%22bool%22:{%22must%22:[{%22exists%22:{%22field%22:%22story%22}}]}}}},%22from%22:0,%22size%22:500,%22fields%22:[%22status%22,%22type%22,%22user.profession%22,%22user.affiliation%22,%22_id%22,%22url%22,%22created_date%22,%22createdAt%22,%22title%22,%22email%22,%22user.username%22,%22user.firstname%22,%22user.email%22,%22location.geo.lat%22,%22location.geo.lon%22,%22story%22,%22count%22],%22sort%22:[{%22createdAt%22:%22desc%22}],%22facets%22:{%22status%22:{%22terms%22:{%22field%22:%22status.exact%22}},%22user%22:{%22terms%22:{%22field%22:%22user.profession.exact%22}},%22type%22:{%22terms%22:{%22field%22:%22type.exact%22}},%22keyword%22:{%22terms%22:{%22field%22:%22keywords.exact%22,%22size%22:1000}},%22journal%22:{%22terms%22:{%22field%22:%22journal.exact%22,%22size%22:1000}}}}

**Comment by markmacgillivray** [comment]
I don't understand the links and they don't seem to work. What exactly did you try putting in the search box?

**Comment by markmacgillivray** [comment]
I've updated the search to use AND by default on multi term searches, maybe that solves your problem?

**Comment by JosephMcArthur** [comment]
1 link was: "The Nature and Origins of Misperceptions: Understanding False and Unsupported Beliefs About Politics". 2nd was "Understanding False and Unsupported". 

Not sure why those links didn't work... just copied from the URL bar

**Comment by JosephMcArthur** [comment]
I think it may be the ":" that's not helping. On dev currently title search works except when 

e.g 

"ANIMAL BEHAVIOR: New Data Reveal the Sisterhood of Lions" for http://dev.openaccessbutton.org/request/LNyezcHiw48eqrgWq

The Earthquake Network Project: Toward a Crowdsourced Smartphone‐Based Earthquake Early Warning System for http://dev.openaccessbutton.org/request/so89jBy9Znvj52Rvz

**Comment by markmacgillivray** [comment]
Yes : is a special character - I have added some checks to treat it as not special, and remove anything not in usual a-z alphabet from simple text searches. So 

animal behavior: new data

and variations on it should now work.
