### ISSUE TITLE
http://doi.org/10.3933/ApplRheol-27-15001 leads back to paywall

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#619]
Full report: https://openaccessbutton.org/feedback#wrong?searched=10.3933%2FApplRheol-27-15001&given=http%3A%2F%2Fdoi.org%2F10.3933%2FApplRheol-27-15001

Response from API:

```
{
  "status": "success",
  "data": {
    "match": "http://doi.org/10.3933/ApplRheol-27-15001",
    "availability": [
      {
        "type": "article",
        "url": "http://doi.org/10.3933/ApplRheol-27-15001"
      }
    ],
    "requests": [],
    "accepts": [
      {
        "type": "data",
        "conditions": {}
      }
    ],
    "meta": {
      "article": {
        "doi": "10.3933/ApplRheol-27-15001",
        "source": "oadoi"
      },
      "data": {}
    }
  }
}
```

Seems oaDOI is throwing us off here. @markmacgillivray what would you suggested course of action be here? Anything we can fix or should we send over a report to Impactstory? 

- [ ] I can add this to the blacklist, but I need the separate list for that

**Comment by markmacgillivray** [comment]
Nothing we can do, if we find it somewhere we treat it as open (except the places we blacklist). We could of course add the URL to our blacklist, and potentially the whole domain, if everything they serve requires login, and that would stop us serving it to our users even if oadoi reports it as open.

But as to why oadoi reports it as open in the first place when it needs login, I guess we should just report to them - they've said they don't count things behind a login as open, so they'll probably want to fix it.

I don't know what their reporting mechanism is - perhaps @jasonpriem will let us know what best to do with such things?

**Comment by JosephMcArthur** [comment]
Not an option to blacklist the whole domain, some articles are OA. Need to ship #604 before I can add to the blacklist.

**Comment by markmacgillivray** [comment]
OK will unassign myself from this for now, will move on #604

**Comment by JosephMcArthur** [comment]
Another, same deal. Pinging @jasonpriem. 

```
{
  "status": "success",
  "data": {
    "match": "https://doi.org/10.2307/2946696",
    "availability": [
      {
        "type": "article",
        "url": "http://qje.oxfordjournals.org/cgi/content/short/110/3/681"
      }
    ],
    "requests": [],
    "accepts": [
      {
        "type": "data",
        "conditions": {}
      }
    ],
    "meta": {
      "article": {
        "doi": "10.2307/2946696",
        "source": "oadoi",
        "title": "corruption and growth"
      },
      "data": {}
    }
  }
}
```

Side notes:
- [ ] I can blacklist after #604 
* I think I've seen this domain qje.oxfordjournals.org throwing up issues before. Just a note to self.

**Comment by JosephMcArthur** [comment]
Can't replicate on oadoi v2. Huzzar!
