### ISSUE TITLE
Getting a blank screen when searching for an article

### ISSUE THREAD

**Issue by svmelton** [OAButton/discussion#620]
When searching for the article at dx.doi.org/10.1080/0361526X.2014.939324 on Chrome, I got this page:
![screen shot 2017-04-04 at 1 17 45 pm](https://cloud.githubusercontent.com/assets/7232545/24669708/70796444-1939-11e7-8156-0ccb90603db6.png)

The color indicates the request is successful, but no information shows up on the screen.

**Comment by markmacgillivray** [comment]
Hmm, what chrome version, on what OS? It works fine on chrome on my linux machine

**Comment by svmelton** [comment]
Chrome 42.0.2311.90 on El Capitan. I'm trying to replicate it with other requests and haven't so far, but it was definitely weird.

**Comment by markmacgillivray** [comment]
Appears to work on chrome on osX too.

**Comment by markmacgillivray** [comment]
Hmm my chrome is 56.0.2924.87. We may not be able to do much unless we see some more examples. Is that on live or dev? Can you try the same DOI on dev (if you already tried on live, or vice versa) and see if you see the same error?

**Comment by svmelton** [comment]
I originally tested it on the live site. I just tried the same DOI on the dev site, and on Firefox I was given this screen:
![screen shot 2017-04-04 at 1 39 44 pm](https://cloud.githubusercontent.com/assets/7232545/24670498/45472b14-193c-11e7-872d-ae2ee4aedb0e.png)

On Chrome, I got this one:
![screen shot 2017-04-04 at 1 39 36 pm](https://cloud.githubusercontent.com/assets/7232545/24670504/4e8e4202-193c-11e7-8505-2d01ee484484.png)

**Comment by markmacgillivray** [comment]
That would make sense, the first time you try it on dev you would create the request, then when you try on chrome you'd get told it already exists.

Occasionally you'll get errors on any web page if there is some sort of network timeout - from your wifi, your ISP, intermediary servers, or our server... it's possible that first time you tried it on live that you just didn't get the response object back.

Keep the issue open for a while longer anyway, in case you find any more examples.

**Comment by markmacgillivray** [comment]
Keeping this open to keep track just in case, but unassigning myself as no action at the moment.

**Comment by JosephMcArthur** [comment]
FYI couldn't replicate. Not hearing of a broader issue. Closing, reopen if needed.
