### ISSUE TITLE
Send request system emails from our server vs a "personal" account

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#634]
Aiming to establish the complexity of doing this, and if it is helpful. Almost certainly will increase open / success rates. The next issue becomes if this "scales" and is easy enough to make work. 

The complexity is in how we track metrics for these emails, and make them easy enough to send quickly.

**Comment by markmacgillivray** [comment]
isn't this already possible? Isn't this why the admin page has a "send email" functionality?

**Comment by JosephMcArthur** [comment]
But that sends via our server / mailgun right? Those messages appear different in peoples inbox than ones sent via a personal gmail.

**Comment by markmacgillivray** [comment]
Hmm so do you mean you DO want them to come from personal address? I'd think that makes people less likely to trust it - surely some random Gmail or outlook or whatever account is less likely to seem legit than one from the service that is asking you to do something? And if you just want it to seem more personal, just change the name of the requests account to Jane.

**Comment by JosephMcArthur** [comment]
So, when I say personal address I mean that we send them from within our @openaccessbutton.org gmail account interface. So, like we'd send normal email, however, the text would've been generated by our backend. All this would be trying to do is not have our email come from a mailgun or systems like it, as that mail is flagged as from "bulk" servers.

**Comment by markmacgillivray** [comment]
In what way is mailgun flagged worse than a Gmail server email? The whole point of mailgun and services like it is that they are supposed to validate as well as any other mail system. The way it validates should be the same as the way a Gmail email appears to validate.

Also, we don't have to use mailgun at all - we can just configure our own mail server and probably even forward that through the Gmail account servers. However, I'd be surprised if that came out looking more valid than sending via mailgun.

**Comment by nemobis** [comment]
> In what way is mailgun flagged worse than a Gmail server email?

I don't know because I've not studied how mailgun handles [stuff](https://support.google.com/mail/answer/81126), but for one thing their mailservers are not currently considered legit for sending messages with @openaccessbutton.org in From header, according to your SPF:

```
$ dig TXT openaccessbutton.org +noall +answer
; <<>> DiG 9.10.4-P8-RedHat-9.10.4-5.P8.fc25 <<>> TXT openaccessbutton.org +noall +answer
;; global options: +cmd
openaccessbutton.org.   3552    IN      TXT     "v=spf1 include:mail.zendesk.com include:_spf.google.com ~all"
```

**Comment by JosephMcArthur** [comment]
Thanks @nemobis. Assigning @markmacgillivray to take a look here.

**Comment by markmacgillivray** [comment]
Our emails are sent via a subdomain which mailgun is configured to send from - mg.openaccessbutton.org. I don't think there is anything else that can be done here.

**Comment by natalianorori** [comment]
I'm not sure about my assignment here

**Comment by JosephMcArthur** [comment]
We've done this, yay!
