### ISSUE TITLE
Use [name]@openaccessbutton.org for requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#636]
Yet another way to make requests more personal! Credit to @markmacgillivray for the thought.

**Comment by JosephMcArthur** [comment]
@markmacgillivray natalia@openaccessbutton.org exists as an alias in our gmail accounts. What would needed to send this via mailgun?

**Comment by markmacgillivray** [comment]
I just change the config of the system to send to natalia instead of to requests.

**Comment by markmacgillivray** [comment]
Obviously someone then has to monitor the natalia@openaccessbutton.org account inbox

**Comment by JosephMcArthur** [comment]
it's monitored

**Comment by markmacgillivray** [comment]
Done

**Comment by JosephMcArthur** [comment]
@natalianorori note that this is a thing now!
