### ISSUE TITLE
How to handle half-finished requests 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#640]
The new ones, without a story and without an author's email that the system is automatically creating on "help" status

**Comment by JosephMcArthur** [comment]
* so they're only shown to admins. 
* I've just pushed changes to help us figure out why people aren't completing them. Hopefully we'll get emails with question / concerns ( + usertesting)
* most of them are anonymous

Issues here are that:
* natalia get's an email every time a half-baked request is made
* natalia can't see the requests she should be working on

My suggested fixes
- [ ] only sending emails when a request has a story
- [ ] allowing admins to filter requests to only show those with stories.

**Comment by markmacgillivray** [comment]
OK, API updated to only send a request notify to Natalia if it has a story (will go live when live API next updates), and added a link to filter requests by having story or not if admin.

**Comment by JosephMcArthur** [comment]
perfect!
