### ISSUE TITLE
new email notifying users when their requests are made available 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#641]

**Comment by natalianorori** [comment]
@JosephMcArthur I wrote a first draft. @chealsye can you please check this for me whenever you have the time?  https://docs.google.com/document/d/1-yZ-KV7gtUTHG6s27hl5RjJdaHMZhaAUGWZqguy4NlA/edit

This is only for articles. We already have a good email for data requests

**Comment by chealsye** [comment]
Just made some tiny suggestions!

**Comment by natalianorori** [comment]
thank you! Joe, I think this is ready.

**Comment by JosephMcArthur** [comment]
I've pushed updated copy for the body of this onto dev (needs to be synced). Let me know what you think of my title suggestion.

**Comment by JosephMcArthur** [comment]
done! @natalianorori sync the emails an it'll be there
