### ISSUE TITLE
Tiny CSS change needed on /request

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#647]
I'm trying to adjust this statement, and give us a way to get data on why people aren't always starting their requests. Need the button fixed to ship

<img width="1091" alt="screenshot 2017-04-08 15 00 34" src="https://cloud.githubusercontent.com/assets/4953703/24829568/31f8d6ce-1c6c-11e7-9af3-740a037130be.png">

**Comment by markmacgillivray** [comment]
Fixed on dev. It wasn't the css, it's where you put the sentence. The layout of things is controlled by the divs they are in, if you put something in a place where it is not expected it can push off the layout of related things. In this case, where the layout of the button is related to the input box, your sentence needs to go below the input-group containing div, then moving the marging spacing down to the new sentence lays it out fine.
