### ISSUE TITLE
New plugin UX concepts

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#655]
Discussion started by @markmacgillivray in #653 

> today someone I know tried to sign up to oabutton, and their user journey was concerning. Having heard about unpaywall, I recommended they look at oabutton as well. They went to our site, and seemingly tried to get the extension then on the account page were told the account and plugin could not be matched - of course we know this can happen in some circumstances, but what interested me about it is why the user did this at all.
> 
> Because our front page says "get the extension", that takes focus away from our USP - the fact that the user can search for things and then create a request if it is not available. Instead, the user misses that and is pulled away to getting an extension and seeing an account page where basically nothing happens.
> 
> Given that the plugin is not our core function, and given that it seems to be detracting from our USP, I still think that it would be better to prompt about our extensions as just a handy add-on AFTER the user tries searching for something and then sees the actual USP functionality we are trying to offer.
> 
> Also, to reduce plugin issues altogether, the "get the extension" link would be better to go to a /install page where we just list the available extensions/plugins/bookmarklets and can mention unpaywall there too (especially once they link through to us on failure to find). And our extension and bookmarklet should be simplified down to just a trigger that goes to our site front page and runs the search, then creates or redirects to a request or available item as necessary, at which point all the user account stuff manages the workflow anyway. This makes the plugins very simple to maintain and removes the need for the account page syncing with the extensions, and thus simplifies and reduces error.
> 
> A /install page will require some content be written for it.
> 
> I propose the above, please let me know if I can proceed @JosephMcArthur @chealsye and if someone can provide /install page copy.

**Comment by chealsye** [comment]
Mentioned this to Joe in conversation, so adding as a note. This is more in regards to an institutional plugin, but I think this is the issue Joe instructed to comment on.

I think we should be mindful of color blindness in designing the (institutional) plugin, especially if it has more of an Unpaywall look with a side tab. For institutions enabling use despite sight differences will be important. We don't necessarily need different colors, but different icons could help the potential problem.

**Comment by JosephMcArthur** [comment]
will deal with this inside jisc case studys, so closing this
