### ISSUE TITLE
Author request template inaccurate unsubscribe

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#656]
The current author request email template includes a link at the bottom which is described as an "unsubscribe" link. However, authors never subscribed to our service, and there is no service from which they can unsubscribe. Offering them an unsubscribe link makes it sound like we have subscribed them to something, and therefore implies that we have done so without their consent.

**Comment by JosephMcArthur** [comment]
Very good point, will fix in this sprint

**Comment by JosephMcArthur** [comment]
done
