### ISSUE TITLE
Searched for http://onlinelibrary.wiley.com/doi/10.1002/ncr.187/ but linked to a completely different article

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#658]
Searched for an OA version of this article: http://onlinelibrary.wiley.com/doi/10.1002/ncr.187/ - OA button website indicated that the article was available but linked to this ( https://dr.ntu.edu.sg/handle/10220/25927?show=full ), a completely different article (though on a similar theme, was not useful to me) 

reported by: cyberoctopus@gmail.com

**Comment by markmacgillivray** [comment]
That Wiley URL just 404s
