### ISSUE TITLE
When an email is delivered (or, not delivered) to an author give a notification for admins

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#670]
@natalianorori said it would be extremely helpful to have something like the login email update systems for sending to authors.

**Comment by natalianorori** [comment]
I am now getting notifications from mailgun when delivery fails, which is super useful

**Comment by JosephMcArthur** [comment]
Okay, this doesn't seem like the most pressing issue now we've fixed via mailgun, closing.
