### ISSUE TITLE
Hide hold & close all requests there

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#671]
The hold status is currently not serving the intended purpose. Would suggest simplification here by:
- [x] hide the "hold" status on live - @markmacgillivray 
- [x] remove all requests (only 5) from hold on live - @natalianorori 

Until such a time as we think it's helpful!

**Comment by natalianorori** [comment]
I moved them from hold to help (they still needed help) and marked them on my spreadsheet
