### ISSUE TITLE
Dealing with "other" actions when request is in moderation

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#673]
Most of the time a request can be sent to an author now, however, there are a few other things which happen from time to time. Dealing with these takes up a significant portion of the manual, and I'd like to simplify. 

* Story too bad to send
  * Rate story as fail
  * Send emails/author_request_article_v2_nostory.html to author
  * send emails/requesters_request_inprogress.html to requestors
* Request isn't a scholarly article
  * close request
  * send emails/initiator_invalid.html to user
* Dead author
  * close request
  * send emails/requesters_request_failed_authordeath.html to requestors
* User is testing
   * send emails/initiator_testing.html to iniatior
   * mark as test
   * close request
   * mark story as failed 
* Link given doesn't work
   * Send: emails/initiator_brokenlink.html user

While I think the send to author should be a big button, I feel like these can be a dropdown menu type affair, or similar.

**Comment by markmacgillivray** [comment]
Actions in place on dev in admin area of each request page now. Please test on dev to be sure it is sending the expected emails. Make sure to use emails of team members for authors, supporters, and creators, or else you'll email real people.

**Comment by JosephMcArthur** [comment]
Assigning @natalianorori for that!

**Comment by natalianorori** [comment]
Hi Mark, 
Joe and I both tested this on dev today. The system is sending out the right emails, but they are displayed as templates. I am attaching screenshots of the emails I got: 
![screen shot 2017-04-27 at 20 47 16](https://cloud.githubusercontent.com/assets/20844934/25512459/1dfb1ac8-2b8b-11e7-8556-02b556d2eb2b.png)
![screen shot 2017-04-27 at 20 48 57](https://cloud.githubusercontent.com/assets/20844934/25512458/1dfae04e-2b8b-11e7-8ba1-ed8357df8c11.png)

**Comment by JosephMcArthur** [comment]
@natalianorori are other things here working as you'd expect?

**Comment by natalianorori** [comment]
Yes, emails get sent, the only issue I am seeing is the template

**Comment by markmacgillivray** [comment]
OK, try again now

**Comment by natalianorori** [comment]
tested it and it is working!

**Comment by JosephMcArthur** [comment]
@natalianorori so, have you tested everything here & are happy to close?

**Comment by natalianorori** [comment]
yes, I tested everything here again on friday, emails are sending out correctly and statuses are being changed in all different scenarios. during my last test, I tested with my email address and Allana's email address. Happy to close
