### ISSUE TITLE
Make moderation from mobiles easy

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#677]
This was a highly desired feature from Natalia. For sure, having one button sending would make this good. I'm keeping this here to make sure we pay attention to the mobile experience of this. 

One potentially highly valuable addition here would be moderation over email. For example, when a new request comes in allowing us to reply to that notification with "send" (or, any string) to send it on. That is, in my books, a pretty perfect mobile experience.

**Comment by JosephMcArthur** [comment]
Another thought, it would be even better if (for simple story edits) we could respond to the email with an edited story to change it.

**Comment by JosephMcArthur** [comment]
So, the point at which an email would need to be sent here is on "moderate". This becomes obvious once you think that help requests would now be sent to m-terk to have details completed. Since there is little user action required, and a notification "at the time" would waste effort currently being exerted there. 

Assigning to @markmacgillivray. Keen to know:
- [ ] how tricky you think this is to do

For me this makes sense as it ties notification with action, without folks needing to head to any other places / sign in etc. For a majority of requests it seems like with "one button" send, we can get things moving much faster. 

The complexity comes when you consider many people may get these emails. Therefor, a question becomes how we handle people not wasting too much time (or confusing the system) by sending multiple responses to a notification. Sending to a group email that shared by multiple people would handle this well enough I guess. 

Assigning @natalianorori to:
- [ ] confirm that you still think this is something that would be good

In later sprints we can implement.

**Comment by markmacgillivray** [comment]
Triggering changes to the system via email response is an entirely new functionality that we do not have at all yet. It is possible, but will have to be the focus of at least one sprint worth of work just on its own. There is no way this can be done in the same sprint as stats, and additionally I am not sure if this is higher priority than updating our extensions/bookmarklets, or bulk upload. 

I expect only one of the following can be achieved on one one-week sprint:

* trigger system changes by email response
* stats
* bulk upload + extensions/bookmarklets rewrite

**Comment by JosephMcArthur** [comment]
Extremely helpful. Bumping to backlog for now.

**Comment by JosephMcArthur** [comment]
OR. We could flip back to the other option here. Reviewing the mobile interface for moderation & just making relatively simple UI changes to make this simple. If we already have notification, simply having a link in the email to the request & a nice-ish interface would make a lot of progress here. 

Let's explore this:
- [ ] review mobile interface - me 
- [ ] suggest simple changes, if they exist.

**Comment by JosephMcArthur** [comment]
Won't do now, idea is to make moderation not needed by us.
