### ISSUE TITLE
searching @ in emails does not work on /request

### ISSUE THREAD

**Issue by clghmlr** [OAButton/discussion#679]
From: joe@righttoresearch.org<br>
Date: April 16, 2017 at 10:36AM<br><br>
From Chealsye:&nbsp; For example, searching @fsu.edu returns nothing, but searching fsu.edu does - the problem is that at times other urls will get pulled in like sfsu.edu in this example.

**Comment by JosephMcArthur** [comment]
Won't fix for now. Does work just need to know how.
