### ISSUE TITLE
Automation of received requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#682]
Thought I had more time than I did to write this, but leaving a note to myself to expand.

* Email Natalia
* Send thank you emails to authors & users automatically

**Comment by JosephMcArthur** [comment]
Okay, first step, when a request becomes received:
- [ ] email Natalia

The next step is harder. We want to get to a point where we also
- [ ] send thanks message to author (not yet written)
- [ ] send emails/requestors_request_success_article.html to requestors. 

For the latter, we need to close #687 and be much more "bug free" on that page, including inclusion of Sherpa Romeo etc.

**Comment by markmacgillivray** [comment]
Do notification to Natalia this sprint, and continue rest in next sprint

**Comment by markmacgillivray** [comment]
Done on dev, now to @natalianorori and @JosephMcArthur to decide email and process

**Comment by natalianorori** [comment]
We actually do have a template to thank authors. Its called authors_thanks_article. Its only for articles tho, for data requests we have the author_request_badge_data template but I don't know how difficult it would be to actually attach images of that badge.

**Comment by JosephMcArthur** [comment]
Okay, so I'd like us to close #687, at least, before moving forwards here. 

* if article success
 - [ ] send thanks authors_thanks_article.html to author
 - [ ] if article success: send emails/requestors_request_success_article.html to requestors.
 - [ ] change status to "received"
* If data success, continue to handle manually. 

and for now I'd like us to continue handling data requests manually.

**Comment by natalianorori** [comment]
+1 to everything above, including handling data requests manually

**Comment by JosephMcArthur** [comment]
Should be able to move forwards on this now @markmacgillivray

**Comment by markmacgillivray** [comment]
Done on dev, ready to test there, will go on to live site when live API is next updated.

**Comment by JosephMcArthur** [comment]
@natalianorori can you look at this today?

**Comment by natalianorori** [comment]
> if article success
 send thanks authors_thanks_article.html to author
 if article success: send emails/requestors_request_success_article.html to requestors.
 change status to "received"

Just tested it. I submitted a URL as a user, put up a test email address I have for requests in the author's email box and my personal email address as the requestor. When I submitted the link the request status changed to received, however, no emails were automatically sent to neither of the email addresses.

**Comment by markmacgillivray** [comment]
It seems there are some things missing here. For example, stuff can now be received from authors OR from admins. There is also a request from @JosephMcArthur for a tickbox to show that although an admin is providing the received content, that it is not actually content from an author.

Presumably this means that we should not actually be sending thanks to the author in some cases? And also, if it is an administrator providing the content, should we be sending a different email?

This also has to relate to the weekly requests check - if any of them trigger a receive, then emails will be sent out. Which emails should those be?

In addition to all of the above, it should still have emailed @natalianorori when she tested it - Natalia, can you tell me which request you tested with?

**Comment by markmacgillivray** [comment]
Also, did you refresh the email templates on the dev system? There is a button on the admin page for refreshing templates that was previously requested as part of this workflow - if new emails have been written / edited, but nobody has refreshed the templates in the system, then a test that tries to use an email that has not been uploaded into the relevant system (dev or live) could fail, because it will not know what to send.

**Comment by JosephMcArthur** [comment]
Good points [here](https://github.com/OAButton/discussion/issues/682#issuecomment-315828413) Mark. Self-assigned to answer.

**Comment by JosephMcArthur** [comment]
@natalianorori can you update where we're at with this from your perspective?

**Comment by JosephMcArthur** [comment]
I think what we need to close this is have a quick action called "received by author"on admin which:
* publishes to Zenodo
* send authors_thanks_article.html to author
* send emails/requestors_request_success_article.html to requestors.
* change status to "received"

We need another quick action called "received by admin"on admin which:
* publishes to Zenodo
* send emails/requestors_request_success_article.html to requestors.
* change status to "received"

@natalianorori, does this make sense to you? 

Can we also confirm what happens when people submit a link. Looking @markmacgillivray.

**Comment by markmacgillivray** [comment]
When a link is submitted the same receive process takes place but nothing is sent to zenodo. We just save the link as the location of the file and mark the request as received. As with zenodo uploads, an email gets sent to requests@oab to notify that a request has been received. I have altered the subject line of those emails to say "URL provided" when a url is provided, or "zenodo publish required" if we get a file upload but autopublish is off, or "file published on zenodo" if autopublish is on.

**Comment by JosephMcArthur** [comment]
Gotcha, so we'd want:

a quick action called "link by author" which:

* send authors_thanks_article.html to author
* send emails/requestors_request_success_article.html to requestors.
* change status to "received"

We need another quick action called "link by admin" on admin which:

* send emails/requestors_request_success_article.html to requestors.
* change status to "received"

**Comment by JosephMcArthur** [comment]
Again, @natalianorori let me know if this makes sense.

**Comment by markmacgillivray** [comment]
@JosephMcArthur @natalianorori the live API has now been updated, so it should be possible for you to import records and click the checkbox on the import page to indicate that you want emails to be sent out as well. 

@natalianorori I have tested this on dev, but if possible could you please try an import of just a couple of requests with the checkbox checked, and then let me know, and I can check to see that the expected changes happened and that the emails got sent.

There is no reason why this should not work, but as we recently had issues with getting the emails to send on live when people created requests, I want to make sure that there are no gaps in the logic that could cause this to make you think that emails were sent for many requests when they weren't, so this extra check seems valuable.

It will only take me a few minutes to check that emails were sent once I hear from you, and after that we can close this issue and you will be able to do more imports any time after that.

**Comment by markmacgillivray** [comment]
Oh hold on - I think I have put the last comment on the wrong issue...

**Comment by markmacgillivray** [comment]
OK deleted my incorrect comment above - sorry about that. This issue is still outstanding, will be done soon once I add the second quick action

**Comment by markmacgillivray** [comment]
It seems this issue is awaiting confirmation from @natalianorori about @JosephMcArthur s comment above - can you let me know if this should be progressed as described above? If so, I can complete it.

**Comment by markmacgillivray** [comment]
This is done on dev and will be on live when I next deploy - could be this weekend, but if not then on Monday 28th. Will close issue or reassign for testing on Monday.

**Comment by markmacgillivray** [comment]
@natalianorori this has been pushed to live you should see the new admin buttons there now and can try them. I will close the issue but reopen if there are any problems.
