### ISSUE TITLE
Add copy to catch false negatives on new request page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#685]

**Comment by JosephMcArthur** [comment]
@markmacgillivray can we move the not what you were expecting phrase:
* inside the green box
* to the centre

Note: as it is currently - https://www.dropbox.com/s/hngdvdofq7pkcwl/Screenshot%202017-05-03%2011.18.26.png?dl=0

**Comment by chealsye** [comment]
What copy is needed here?

**Comment by JosephMcArthur** [comment]
See the screenshot for what's there at the moment. Let me know if you'd change that at all.

**Comment by JosephMcArthur** [comment]
See the screenshot for what's there at the moment. Let me know if you'd change that at all.

**Comment by chealsye** [comment]
Fine with this copy and I agree moving it into the green box and centered. This would catch false positives, not false negatives. We need to add it for when we are saying there isn't an OA copy (but the user might know there is).

**Comment by JosephMcArthur** [comment]
Oh, oh. I've got this issue backwards, thanks for flagging this Chealyse. 

Yes. We need to consider how to put a something on request pages to catch when we miss an open copy (as the form we usually use wouldn't be available). 

I think a sentence under "contact us" is all we could do, but it doesn't seem great.

**Comment by chealsye** [comment]
Yes, we could add a sentence under "contact us." This is why I've been pushing for a form to catch false negatives and positives by librarians, because we receive these reports and there should be a better way to report and gather.

Simple sentence could be added after contact us.

> Do you know of an available copy in a repository that we missed? Let us know!

The wrong content form includes "A copy I know is availiable wasn't shown" (available is spelled wrong on the form!). Should that item be removed? Or should "let us know" lead to that form?

**Comment by JosephMcArthur** [comment]
Can we try a shorter version of this? 

> Do you know of an available copy in a repository that we missed? Let us know!

The actual reason to read the sentence doesn't come to midway through? 

Something like:

> Missed an available copy? Let us know.

We might even want to drop let us know, and just link the rest.

In terms of a form, I'd suggest @markmacgillivray we:
* send them to feedback#wrong
* put in the request ID
* pre-tick "available"

Typo fixed, thanks.

**Comment by chealsye** [comment]
Yeah, that's fine.

**Comment by markmacgillivray** [comment]
Moved, on dev.

**Comment by chealsye** [comment]
@markmacgillivray not sure why I was assigned. @JosephMcArthur and I agreed on

> Missed an available copy? Let us know.

Just needs to get added to the site now.

**Comment by markmacgillivray** [comment]
@chealsye I wasn't sure which of you was doing that, so just assigned both as you had both had input to previous discussions, so wanted to make sure I didn't leave anyone out. Just unassign yourself if it is not relevant :)

**Comment by chealsye** [comment]
If it is on dev, wouldn't this be closed then? Copy has been agreed upon.

**Comment by JosephMcArthur** [comment]
Not yes sadly, I need to check it turns up & completes forms correctly

**Comment by JosephMcArthur** [comment]
Okay, tested (and text centered) so closing!
