### ISSUE TITLE
System did not populate title on found request

### ISSUE THREAD

**Issue by svmelton** [OAButton/discussion#686]
I received a notification that a requested paper was found (https://openaccessbutton.org/request/awcC37JNSmDQJGuWa) but in the email, the title was not present:
![screen shot 2017-04-17 at 10 02 56 am](https://cloud.githubusercontent.com/assets/7232545/25091070/170e4606-2355-11e7-8563-a8e5740717da.png)

**Comment by JosephMcArthur** [comment]
On the move... aside from the specific issue here, can we consider a more
graceful failure status here such as "an article"

**Comment by natalianorori** [comment]
Hi Sarah,

Thanks for pointing this out, you actually are the only user with whom I
have used this template. I think the best solution might be replacing with
" an article" since this is a template we don't use a lot (it's the one for
when we find urls on our own)

**Comment by JosephMcArthur** [comment]
@natalianorori why wasn't there a title in the first place?

**Comment by JosephMcArthur** [comment]
Ah, wrong tag. Fixed.

**Comment by markmacgillivray** [comment]
If this is an issue with the wrong tag being used, what do I need to use to fix?

**Comment by JosephMcArthur** [comment]
On call decided this isn't needed.
