### ISSUE TITLE
Add a check / box in the request moderation process to try and get the journal title

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#688]
This will power the sherpa / romeo look up. We have the journal title in around 50% of cases currently. 

Assigning myself to think about how to handle this.

**Comment by JosephMcArthur** [comment]
We can ask users for this for sure

**Comment by JosephMcArthur** [comment]
- [ ] @markmacgillivray have we explored all our avenues for picking up the journal name automatically? 

If not, I think we should run via mturk.

**Comment by markmacgillivray** [comment]
Yes, we scrape the page content and look up the APis we query as well.

**Comment by JosephMcArthur** [comment]
- [ ] @markmacgillivray can we add a box in the admin process for this please? If we know the journal from the automated system it should just show here. 

cc @natalianorori

**Comment by natalianorori** [comment]
Happy to test when this is on dev

**Comment by markmacgillivray** [comment]
Added box to admin area of requests, that will be populated if we already know it, or can be manually added by admins.

**Comment by JosephMcArthur** [comment]
this is on live!
