### ISSUE TITLE
Items in BASE and OpenAire not appearing as Open

### ISSUE THREAD

**Issue by svmelton** [OAButton/discussion#689]
From ZenDesk:

Dear Open Access Button-Team,

I am the head librarian at the Institute for Advanced Studies in Vienna and am also the manager of our repository IRIHS (https://irihs.ihs.ac.at/) (IRIHS (https://irihs.ihs.ac.at/) (http://irihs.ihs.ac.at/cgi/oai2 ). Our repository is indexed in BASE and also in OpenAIRE, but our open access items do not show up with Open Access Button, which uses, as far as I understand, various sources, amongst them also BASE. Can we do anything to have our results listed in your search engine?

I searched e.g. for the following items, both indexed in BASE:

http://irihs.ihs.ac.at/3849/

http://irihs.ihs.ac.at/3822/

Thank you for your help and kind regards

Elisabet

Mag. Elisabet Torggler

Bibliotheksleiterin - Head of Library

Institut für Höhere Studien - Institute for Advanced Studies

Josefstädter Straße 39, 1080 Vienna, Austria

Tel: +43 1 59991 - 236

Fax: +43 1 59991 - 555

E-mail: torggler@ihs.ac.at

Web: http://www.ihs.ac.at (http://www.ihs.ac.at/)

**Comment by markmacgillivray** [comment]
Reading the titles out of that repo site needed a bit of a change to check eprints and dc titles, then had to adjust the check against BASE for german characters. Works now.

**Comment by markmacgillivray** [comment]
(works only on dev so far, but will go to live when API is next updated)
