### ISSUE TITLE
Nonopen versions of articles

### ISSUE THREAD

**Issue by svmelton** [OAButton/discussion#690]
User reported that they searched for http://onlinelibrary.wiley.com/doi/10.1002/wdev.195/full and were taken to http://hdl.handle.net/11858/00-001M-0000-0029-D716-C. There is no fulltext version of the article on that page.

**Comment by svmelton** [comment]
User reported that they searched for http://vc.bridgew.edu/socialwork_fac/53, which links to a nonopen version of the article. Likely nothing that we can do, but flagging it.

**Comment by svmelton** [comment]
User reported that they searched for http://www.tandfonline.com/doi/pdf/10.1080/1941126X.2017.1270096 and were taken to http://dx.doi.org/10.1080/1941126X.2017.1270096, which is not open.

**Comment by JosephMcArthur** [comment]
cannot replicate any of these on the new system - closing!
