### ISSUE TITLE
Statistics available on the UI: do they reflect the database?

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#691]
Dear team,

On the UI, one can see the number of requests that succeed or failed.

Are these figures the actual ones achieved through the OAButton?
I would like to know, and maybe ask for a line on the UI to indicate if not,
before advertising the results (for example on twitter).

Best regards

**Comment by jibe-b** [comment]
This has connections with #598.

And you may already have a roadmap of data analytics. I'd be glad if you can tell me a bit about it, and if not, tell me and I'll add suggestions in issues. And maybe realise them.

**Comment by JosephMcArthur** [comment]
Yes, those results should be fairly correct. Although, they come with the * that we're still running the system at quite a small scale, and only on new requests. We're working now to beef up our moderation processes to handle the backlog.
