### ISSUE TITLE
On single-request display, "profession" showing up twice - once transformed to lowercase

### ISSUE THREAD

**Issue by allanaaa** [OAButton/discussion#702]
See pull request here: https://github.com/OAButton/website/pull/43
When a request is viewed, e.g. https://openaccessbutton.org/request/biP7PXuyKHTYxY42f
The requesting user's profession is being pulled twice, e.g. "Librarian librarian"

Code in lines 330-334 of the item.html page seem to be the culprit: 
In line 330, ', [Profession]' is being generated; 
In line 334, '[profession]' is being added on.

You might have better fixes in mind; in my pull request I've just modified the former line to have the lowercase transformation applied and commented out the latter line.

**Comment by markmacgillivray** [comment]
Closed the PR, closing the issue - fixed alternatively, as described in PR response
