### ISSUE TITLE
Change feedback form to be more human readable

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#704]
in feedback.html are all the things to form submits. changing e.g . "wrong" to something that's clearer would help.

**Comment by JosephMcArthur** [comment]
@markmacgillivray how easy is it to improve the formatting of the emails sent by things like the feedback form.

**Comment by JosephMcArthur** [comment]
@svmelton you're looking at these most. If you can give me names for fields that would be more useful for you, I can implement.

**Comment by JosephMcArthur** [comment]
@markmacgillivray is there anything you can do simply to improve how these land in our inboxes? They're pretty ugly and it can be hard to decipher, a little work would probably go a long way.

**Comment by markmacgillivray** [comment]
On dev I have altered the format of the feedback form email - I have not actually looked at it, but give it a go and see what you think.

**Comment by JosephMcArthur** [comment]
This looks much better @markmacgillivray. 

Assuming these changes will apply to all our forms I'm closing.
