### ISSUE TITLE
Firefox plugin + bookmarklet issues

### ISSUE THREAD

**Issue by allanaaa** [OAButton/discussion#706]
Two reports recently via Twitter that the Firefox plugin is giving an error message when people try to install from https://addons.mozilla.org/en-US/firefox/addon/openaccessbutton/

See discussion here: https://twitter.com/BoltonPlatt/status/855076333369556992
We've asked them to submit bug reports on the website.

I replicated this on Firefox 53.0.2 just now. Error message is:
"The add-on downloaded from this site could not be installed because it appears to be corrupt."

I logged in to openaccessbutton.org and tested out the bookmarklet as an alternative.
I was able to use the bookmarklet successfully in Firefox, but @chealsye said it installed but wouldn't work for her, so we didn't recommend it for use in the meantime.

(My apologies if this should be two separate issues on Github?)

**Comment by JosephMcArthur** [comment]
- [ ] me, figure out why the mozilla plugin is in stores
- [ ] @chealsye explain bookmarklet issues futhur. 
- [ ] @markmacgillivray fix bookmarklet issues when we know what they are... 

cc @svmelton

**Comment by chealsye** [comment]
Yesterday when I installed the Firefox bookmarklet and tried to use it it just was stuck on the "we're searching" but just tested it again and it is working. 
![screen shot 2017-05-09 at 12 24 13](https://cloud.githubusercontent.com/assets/9299248/25861513/f92f77e4-34b2-11e7-9b19-8820744cd476.png)

**Comment by JosephMcArthur** [comment]
Okay, can't do much about the bookmarklet stuff without the ability to replicate. 

Have removed the FF plugin from stores... which I thought had already happened. 

Closing now!
