### ISSUE TITLE
How can users change their role and affiliation? 

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#707]
I want to update my role and affiliation (as it is inconsistent with the request story I just submitted), but am unable to. How can I change my role and affiliation?

Adding this as a github issue and not an emailed question, so we have a record to advise users in the future or fix it if it is a bug.

**Comment by JosephMcArthur** [comment]
Yeah... probably time we let people change their details here. 

@markmacgillivray can we:
* display boxes on the account page where people can just change & save details? We might want an "edit account info" button on the page to hide this when we want them to install the plugin
* when details are updated, only update requests from that point on.

**Comment by JosephMcArthur** [comment]
Note, I think this will help address #703 as many people spoke about altering account details or being confused.
