### ISSUE TITLE
/request & item page disagreeing about availablity 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#708]
Reported from a user:

![screen shot 2017-05-09 at 0 22 23 openaccessbutton org request ahlh9d8gdfnsfwfrh](https://cloud.githubusercontent.com/assets/4953703/25837353/5a35e83a-3485-11e7-8af0-acc6739700d3.png)

On the results list, following item was listed as being available, but when clicking URL https://openaccessbutton.org/request/AhLh9D8GDfnsFWFRH to the individual results page, page says “This article is inaccessible” instead.

![image](https://cloud.githubusercontent.com/assets/4953703/25837359/602eca7c-3485-11e7-989f-7cc2298d6427.png)

— What is the reason for the mismatch on the search results listing?
— Was that article originally opened for people, but subsequently closed from public access?

URL of the search results was:
https://openaccessbutton.org/request?source={%22query%22:{%22filtered%22:{%22query%22:{%22bool%22:{%22must%22:[{%22match_all%22:{}}]}},%22filter%22:{%22bool%22:{%22must%22:[{%22exists%22:{%22field%22:%22story%22}},{%22query%22:{%22query_string%22:{%22query%22:%22story:*%22}}},{%22term%22:{%22status.exact%22:%22received%22}}]}}}},%22from%22:0,%22size%22:500,%22fields%22:[%22status%22,%22type%22,%22user.profession%22,%22user.affiliation%22,%22_id%22,%22url%22,%22created_date%22,%22createdAt%22,%22title%22,%22email%22,%22user.username%22,%22user.firstname%22,%22user.email%22,%22location.geo.lat%22,%22location.geo.lon%22,%22story%22,%22count%22],%22sort%22:[{%22createdAt%22:%22desc%22}],%22facets%22:{%22status%22:{%22terms%22:{%22field%22:%22status.exact%22}},%22user%22:{%22terms%22:{%22field%22:%22user.profession.exact%22,%22size%22:100}},%22type%22:{%22terms%22:{%22field%22:%22type.exact%22}},%22keyword%22:{%22terms%22:{%22field%22:%22keywords.exact%22,%22size%22:1000}},%22journal%22:{%22terms%22:{%22field%22:%22journal.exact%22,%22size%22:1000}}}}

**Comment by markmacgillivray** [comment]
This request has a status of received, but has no information in it about what was received - no URL, no zenodo link, no OSF link. I would recommend changing the status back to progress, and progressing it again. There does not seem to be an error in it, but it may have coincided with earlier issues.

**Comment by natalianorori** [comment]
This was marked as received since Maria received the article directly from the author, and she sent it to us. I tried to upload it but it didn't upload because this happen when we were having issues with the responder's page.  I re uploaded the article and it is displayed as available. Feel free to close this

**Comment by JosephMcArthur** [comment]
notified report, thanks all!
