### ISSUE TITLE
Missing article URLs (even while results say that those are available)

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#709]
From a user:

> On the article page “Moving from Patient Advocacy to Partnership: A Long and Bumpy Road”
> https://openaccessbutton.org/request/8DXqjWC3pxxjjBNcs
> page header tells that “This article request is now available.”
> 
> But it is missing.
> 
> URL on the page points to a broken URL:
> »» The article is now available in Zenodo at: https://zenodo.org/record/undefined
> 
> That URL displays error message with text:
> “Page not found — The page you are looking for could not be found.”
> 
> Other articles with broken URLs:
> https://openaccessbutton.org/request/2co9GGfTncpmoNDKc
> 
> Text on the page points says:
> »» The article is now available at: bit.ly/MarineExchanges
> 
> …but the URL actually points to:
> https://openaccessbutton.org/request/bit.ly/MarineExchanges
> 
> That is caused by the missing http:// from the URL,
> making outbound link point to wrong location (under URL on your own site).

@markmacgillivray can we do something to catch the http:// issues in future? 
@natalianorori can you adjust the zenodo link at all or change the request status.

**Comment by markmacgillivray** [comment]
Have added an addition of http:// if not already present in URL to response uploader page, on dev. The zenodo one should be fixable by Natalia once we move the URL editing functionality to live (or possibly she already can).

**Comment by natalianorori** [comment]
This happened when we had the incorrect URL for Zenodo, I went into Zenodo and there is nothing deposited under the article's title that show the undefined link. This is why I asked for the functionality of being able to edit/remove broken or wrong URLs, so this probably should be fixable once we add the functionality to live, as Mark said. 

In the meantime, I changed the request status to progress.

**Comment by JosephMcArthur** [comment]
Great, notified reporter, so closing.

**Comment by svmelton** [comment]
Hi all,

I noticed that this request has the same error: https://openaccessbutton.org/request/5WNqW6Ab3th8uy59e

**Comment by natalianorori** [comment]
contacted the author and changed it to progess!
