### ISSUE TITLE
Group duplicate article titles to improve usability of the search results

### ISSUE THREAD

**Issue by d2s** [OAButton/discussion#710]
### Expected Behavior

- Expected to see article search results combined together, even when there are multiple requests for the same article (from several persons). That would make it much easier to see what items are most needed by people (or have gotten most of the activity).

### Actual Behavior

- There are duplicate article titles in the search results.

![screen shot 2017-05-09 at 11 21 11 new issue oabutton discussion - duplicate article items](https://cloud.githubusercontent.com/assets/135053/25841959/d9350560-34aa-11e7-8909-e2321bab2b60.png)

### Steps to Reproduce this bug

* Hardware versions: _not relevant for this issue_
* Software versions: Chrome 57 (web browser)
* Steps to reproduce:
  - Open [search results with `status:received` tag](https://openaccessbutton.org/request?source={%22query%22:{%22filtered%22:{%22query%22:{%22bool%22:{%22must%22:[{%22match_all%22:{}}]}},%22filter%22:{%22bool%22:{%22must%22:[{%22exists%22:{%22field%22:%22story%22}},{%22query%22:{%22query_string%22:{%22query%22:%22story:*%22}}},{%22term%22:{%22status.exact%22:%22received%22}}]}}}},%22from%22:0,%22size%22:500,%22fields%22:[%22status%22,%22type%22,%22user.profession%22,%22user.affiliation%22,%22_id%22,%22url%22,%22created_date%22,%22createdAt%22,%22title%22,%22email%22,%22user.username%22,%22user.firstname%22,%22user.email%22,%22location.geo.lat%22,%22location.geo.lon%22,%22story%22,%22count%22],%22sort%22:[{%22createdAt%22:%22desc%22}],%22facets%22:{%22status%22:{%22terms%22:{%22field%22:%22status.exact%22}},%22user%22:{%22terms%22:{%22field%22:%22user.profession.exact%22,%22size%22:100}},%22type%22:{%22terms%22:{%22field%22:%22type.exact%22}},%22keyword%22:{%22terms%22:{%22field%22:%22keywords.exact%22,%22size%22:1000}},%22journal%22:{%22terms%22:{%22field%22:%22journal.exact%22,%22size%22:1000}}}}).
  - Scroll down to find items with a title _“Promoting an open research culture”_ from the list.

## Use case
* **Person** wants to **find what articles & items are most popular** because **it is interesting to see what people are interested of**.

**Comment by JosephMcArthur** [comment]
We've did this a while back in another issue!
