### ISSUE TITLE
Small misspelling on the website footer (Github instead of GitHub)

### ISSUE THREAD

**Issue by d2s** [OAButton/discussion#711]
### Expected Behavior

*Expected HTML output:*

```html
Proudly open source on <a href="https://github.com/oabutton">GitHub</a>
```

*Diff comparison:*

```diff
-Proudly open source on <a href="https://github.com/oabutton">Github</a>
+Proudly open source on <a href="https://github.com/oabutton">GitHub</a>
```

### Actual Behavior

- _GitHub_ was spelled as _Github_.

### Steps to Reproduce this bug

* Hardware versions: _not relevant to this issue_
* Software versions: OAButton website’s Git tree at the commit [96be218402f990ee170697e3c3bb0e06f86302fc](https://github.com/OAButton/website/tree/96be218402f990ee170697e3c3bb0e06f86302fc)
* Steps to reproduce:
  - Source code: [website/footer.html at master · OAButton/website](https://github.com/OAButton/website/blob/master/templates/footer.html#L7) on the line 7.
    ```html
     Proudly open source on <a href="https://github.com/oabutton">Github</a>
     ```

## Use case template
* **Company** wants to **have a consistent branding** because of **reasons**.
* **Reader** wants to **have a consistent naming conventions** because **it shows the quality of the site’s content**.

**Comment by JosephMcArthur** [comment]
Thanks @d2s, I've changed that in the footer & elsewhere in the repo. All those changes are now on dev.
