### ISSUE TITLE
Extra space character in the Privacy Policy text

### ISSUE THREAD

**Issue by d2s** [OAButton/discussion#712]
### Expected Behavior

*Diff comparison:*

```diff
-t hat
+that
```

*Expected HTML output:*

```html
<p>Cookies are used for our account system. Users remain logged in but this can be controlled by the user and their own browser. We use session cookies on certain portions of the website. Session cookies expire when you close your browser. If you wish to keep your connection information anonymous, there are various free and paid services available that will keep your connection information anonymous, but please note that you can still be identified if you log in.</p>
```

### Actual Behavior

![screen shot 2017-05-09 at 13 36 50 new issue oabutton discussion - extra space character](https://cloud.githubusercontent.com/assets/135053/25847140/8b6e72a4-34bd-11e7-81aa-a70a1db32566.png)

### Steps to Reproduce this bug
*Please include any info about the version of the tool you're using and your system. - remove this note before posting*

* Software versions: Git commit [187baf5590e7f37de2c072720018182f17ca6dff](https://github.com/OAButton/website/blob/187baf5590e7f37de2c072720018182f17ca6dff/content/privacy.html)
* Steps to reproduce:
  - Open the [Privacy Policy](https://openaccessbutton.org/privacy) page of Open Access Button.
  - Search for `t hat`

## Use case
* **Person** wants to **have no writing mistakes on the privacy policy** because **it creates trust between the reader and the service**.

**Comment by JosephMcArthur** [comment]
Fixed, thank you!
