### ISSUE TITLE
emailing request supporters 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#714]
we are not currently doing it at the moment. As an admin, I am not able to see who supported a request (can't see their email addresses) and haven't been emailing supporters once things are made available. 

Some of the steps that I think are needed:

-Create a template to notify supporters when the request is made available
-Being able to see data about who supports a request
-have the system automatically notify supporters when things are made available (this notification should be sent out at the same time that we notify the requester and thank the author)
@JosephMcArthur

**Comment by allanaaa** [comment]
Also, maybe we could:
- add a field in the author-request email that says "After this request was made, [$supportercount] more users expressed interest in your work!" 
Maybe even "Within hours of the first request, [$supportercount] more users...."

**Comment by JosephMcArthur** [comment]
@markmacgillivray is your understanding that request updates don't get sent to supporters? Mine was that this does happen.

**Comment by natalianorori** [comment]
Is there a way for us to see who supported each request? like their contact
info? at the moment we can only see the amount of supporters for each
request.

**Comment by JosephMcArthur** [comment]
Hmmm, not in the UI right now it seems. What's that useful now?

**Comment by natalianorori** [comment]
@JosephMcArthur It would be useful because if I have the contact info I could manually notify supporters when requests are received/refused. request updates are not automatically sent to supporters and I know this process could be automated later, but since its not a priority we have to find a quick solution and manual moderation is what comes to my mind.

**Comment by markmacgillivray** [comment]
Request supporters do get emailed by the admin one-click actions that you already defined, and also by the automation of emails to received requests currently being discussed in #682

**Comment by JosephMcArthur** [comment]
That's what I thought, phew.
