### ISSUE TITLE
Suggested changes to homepage

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#718]
Uploading here to track & share. Haven't been able to form an opinion on the suggested changes! 

![oab proposed changes 25-04-17 3](https://cloud.githubusercontent.com/assets/4953703/26028977/578f86c2-3822-11e7-9484-daa5bb0ca488.png)

**Comment by chealsye** [comment]
We've been through this a few times - but 100% want to stay with the orange/red logo. It is a shift away from our identity and the OA recognition.
