### ISSUE TITLE
Paper has been made available but not pudated in oab db (probably no answer from author)

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#720]
[One request](https://openaccessbutton.org/request/KYb8qiqg5rQCJnJbL) was quickily succesfuly as the author uploaded her paper on HAL](https://hal.archives-ouvertes.fr/hal-01516082/file/Cohen-Boulakia-etal-reproductibility.pdf)

unfortunately, the status of the request was not updated.

I guess that the author did not answer to the email.

Would it be possible to have a bot that passes DOI regularly to OADOI and checks the header to check if the status of a request should be updated?

**Comment by JosephMcArthur** [comment]
Thanks @jibe-b, this is helpful. I think it would be covered by #333. Take a look and let me know.

**Comment by jibe-b** [comment]
I guess the implementation you designed is to be run!

Didn't have time to read through the discussion but if it has not been implemented, add an email to thank the author :)

**Comment by JosephMcArthur** [comment]
Thanks @jibe-b, we've done that :D If you don't mind, I'm going to close this to keep things less confusing for us! But, feel free to watch that other issue for progress here.

**Comment by natalianorori** [comment]
changed status to received and notified the user! Thanks for pointing this
out :)

**Comment by jibe-b** [comment]
the user says: "thanks"!

Am 16. Mai 2017 21:35:18 MESZ schrieb Natalia Norori <notifications@github.com>:
