### ISSUE TITLE
Demo a simplified plugin to see if OAB team and library users could like it

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#721]

**Comment by JosephMcArthur** [comment]
Things I'm thinking about:
* How to handle data in the tool (if one click goes to paper, how do we get to surface data?)
* How do we handle institutional functionality well?
* Can we do doi searching on the page similar to OC?
* Highlighting stuff on the page & then clicking the button is a familiar UI & builds on a lot of our work well. Probably needs no extra UI elements.

**Comment by markmacgillivray** [comment]
This needs to be moved to do in July / August (possibly after official end)

**Comment by JosephMcArthur** [comment]
got a new version, will bump chat into other issues!
