### ISSUE TITLE
Complete admin upload of bulk sheets

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#722]

**Comment by JosephMcArthur** [comment]
Can this be done as a separate page for now (however basic that is), just to replicate the current direction for it being a stand-alone tool. 

Also, are you counting being able to make requests off those sheets as in-scope for this sprint?

**Comment by markmacgillivray** [comment]
Await #739

**Comment by markmacgillivray** [comment]
The admin page on dev now has a "manage batch jobs button", press it to see a file upload bar and a list of previous jobs, with their completeness and download links.

As it is only on dev, large batch jobs could take a while, and it needs further testing and better UI for wider use. But you should be able to get answers out of it. The JSON and CSV download links to what you'd expect, and you can either download results and send to people or give them the links directly - note though that as it is on dev, the links may not last long as we wipe data from dev periodically.

**Comment by JosephMcArthur** [comment]
- [ ] Would be great to have the source of availability listed (e.g base / oadoi etc)

**Comment by JosephMcArthur** [comment]
I tried to upload a file with 15k lines (Interlending Requests - full sample.csv) & it said it failed to upload. After that, when I refreshed all the record of previous jobs took quite a while to appear, but when it did showed the job was running (actually it was)

**Comment by JosephMcArthur** [comment]
- [ ] send notification when progress stalls, not when progress reaches 100%

The "finished" notification seems to only send at 100% but it seems like if a line errors for one reason or another the number won't reach 100%.

**Comment by JosephMcArthur** [comment]
Mid way through running `Interlending Requests - full sample.csv` and trying to download a csv I got:

`TypeError: Cannot read property 'replace' of undefined at Object.CLapi.addRoute.get.action (app/apps/clapi/server/endpoints/service/oabutton.js:758:25) at Route.share.Route.Route._callEndpoint (packages/restivus-mm/lib/route.coffee:147:25) at packages/restivus-mm/lib/route.coffee:59:33 at packages/json-routes-mm/json-routes.js:76:1`

at https://dev.api.cottagelabs.com/service/oab/job/EysuG3mD4Kg3piFtE/results.csv. 

Which tbh was pretty terrible timing :'(

**Comment by JosephMcArthur** [comment]
- [ ] ability to cancel jobs

would like this as I've accidentally made a few that aren't needed, and would like to cancel to free up job que.

**Comment by JosephMcArthur** [comment]
can't add this sheet successfully: https://docs.google.com/spreadsheets/d/1brsgt8u4Nv97lLdT-TGXWYhJW5uq-4OauDULJJXtRw4/edit#gid=0

**Comment by markmacgillivray** [comment]
Added ability to cancel jobs, and fixed the CSV download error you got. 

I don't have access to your google sheet example of the one where you got errors uploading it - I asked for permission, give me that and I will check. What errors did you get? The problem with it seemingly going down was a sorting problem on the display of old jobs, because the big nearly complete jobs were bottlenecking things. I have improved how that is calculated and added a waiting message to the UI. As you got emails about job success, I suspect the errors you got may just have been these UI errors, in which case these should be resolved now.

Some particular rows are still causing occasional errors, this is just something we have to work through to get all jobs to complete. I have started rerunning all the rows that had previously failed while I was away, so this will incrementally improve, and with the fixes above you should at least still get a working UI, and you can now remove any old jobs that are no longer relevant to free things up.

**Comment by markmacgillivray** [comment]
Ah thanks, so that one was the spiral gsheets one, most of which have worked. I think your errors would have been the UI errors then, unless you remember seeing other specific error messages. Later today, once the system has worked through some of the reruns I have kicked off, I will look for any specific failings.

**Comment by JosephMcArthur** [comment]
Okay, so I'd suggest closing this then and having other problems be other issues!
