### ISSUE TITLE
Saying available when it is really not

### ISSUE THREAD

**Issue by moqri** [OAButton/discussion#724]
### Expected Behavior
not found

### Actual Behavior
success

### Steps to Reproduce this bug
https://api.openaccessbutton.org/availability?url=http://pubsonline.informs.org/doi/10.1287/mnsc.2015.2168

The paper is not openly accesible from the suggested link

**Comment by JosephMcArthur** [comment]
Thanks @moqri! This is a known issue, and something we're going to be taking on in a big way over the course of June! Thanks for the report.

**Comment by moqri** [comment]
You are welcome, 
Let me know if I can help with this is any way. We plan to direct our [website ](http://brdb.warrington.ufl.edu/) users to your api when this is fixed.

**Comment by JosephMcArthur** [comment]
That's awesome, will let you know!

**Comment by JosephMcArthur** [comment]
On our new system (which specifically aims to fix issues like this) I can't replicate this now - good news! Closing this issue now.
