### ISSUE TITLE
Error uploading file to responders page in requests with no story

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#726]
I got an email yesterday of a user who could not upload their request through our responders page, so I offered to upload the file on their behalf. When I tried uploading the file as both an admin and as the author, the tab froze and went blank. after about 5 minutes waiting I got an error message, saying that my file could not be uploaded. What I did is that I uploaded the file directly to Zenodo, and submitted the zenodo link as an admin on the request page. This worked and the request was marked as received, which makes me think that the "error"only happens when trying to upload things directly through the website. This only happens to me on requests with no story. 
Any help fixing this is appreciated
@markmacgillivray @JosephMcArthur

**Comment by markmacgillivray** [comment]
@natalianorori could you try this on the dev site too, just make a test request without a story, and use the admin access to get to the response page, and try uploading the same file that you were trying when you got this error. I have looked at the current code and can't see a reason why not having a story would cause this, hence a test on the dev site would help. If you get the same problem on dev, please email me the file you were trying to upload, and reassign back to me. Thanks!

**Comment by JosephMcArthur** [comment]
@natalianorori bump

**Comment by natalianorori** [comment]
I didn't have the same problem on dev, tested it already.  Not sure what happened the first time I tried. @JosephMcArthur we can close this
