### ISSUE TITLE
closing requests for extremely old articles

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#728]
Since authors are obviously dead. 
steps that I suggest we take here are:

- filtering the requests by article date
- marking old requests as closed
- notifying the users that we are closing with requesters_request_failed_authordead template

**Comment by JosephMcArthur** [comment]
@natalianorori hope you don't mind, but I've changed the title here to be a bit more specific (the title sounded a bit like another issue). 

So, @markmacgillivray the key question here is probably if we can get the published on date for articles. 

I think, right now, this is probably a fairly low priority as it's just an optimisation of things we already have handled in other ways.

**Comment by JosephMcArthur** [comment]
Linked to #988

**Comment by JosephMcArthur** [comment]
Closing this older issue. Not a concern now.
