### ISSUE TITLE
Request pages duplicating my role "Librarian, librarian"

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#729]
I just submitted a request and saw this:

![screen shot 2017-05-19 at 12 49 53 pm](https://cloud.githubusercontent.com/assets/9299248/26258224/bb97415a-3c91-11e7-8128-b06d86ac9e9f.png)

_Librarian, librarian_

I figured this is a bug, so I wanted to flag it!

**Comment by allanaaa** [comment]
This got fixed a short time ago - the update just hasn't rolled out yet, I think? 
See https://github.com/OAButton/website/commit/02de6eaf47997ecf4664ef382a718fa4a05bc00f
and #702.
