### ISSUE TITLE
"429, too many requests" error code

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#731]
Some of our folks at the BL have been repeatedly making requests while testing and apparently got told this error code. 

@markmacgillivray can you let me know what this is?

**Comment by markmacgillivray** [comment]
On the api or on the website? Did they say what times? If it coincides with the heavy use we've been seeing, the we either have to turn on more cluster machines or start rate limiting / blocking people to stop them using too much too quickly.

**Comment by JosephMcArthur** [comment]
Website, I think (judging by their implementation of oab). No, they didn't say the times sadly.

**Comment by markmacgillivray** [comment]
It would not be good if people make automated repeated requests via the site. Do you know why their implementation goes via the site instead of the API? I think we'll need to spend some time adding monitoring and limiting / blocking asap, as this risks making the UI bad for normal users.

**Comment by JosephMcArthur** [comment]
Nope, but I've asked for them to use the API & they'll be looking at it now. 

I doubt the requests to the site were automated, just lots of manual ones. 

I'm super hesitant to fix issues by blocking / limiting, but if you feel like adding monitoring is important then let's go ahead there. Otherwise, can we discuss alternatives to blocking / limiting?

**Comment by markmacgillivray** [comment]
If anyone is getting 429 errors on the UI, then we have to deal with it asap. The only alternative to limiting / blocking is turning on more cluster machines, which is more cost. It's not much per machine, but you'd still have to decide at what point you're willing to keep paying for. Also, with every extra machine, we hit every other service we query harder, so we'll need to keep tracking our responses from them too.

**Comment by markmacgillivray** [comment]
Handle this in relation to #739

**Comment by markmacgillivray** [comment]
Can't be resolved until we move to a new API logging method, which is on hold. Unassigning and descheduling for now, but keeping open.

**Comment by JosephMcArthur** [comment]
Haven't seen this in over two years, closing for now.
