### ISSUE TITLE
Doing tests on citation vs title vs (doi / URL / pmc) to improve our title / citation searching

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#732]
Apparently, the BL have been testing this and found issues. This isn't a surprise, and I'm just opening an issue here to track and note this. 

What I'll do soon is:
- [x] Get titles for DOI's/ URL's with known results in the system & upload them to the spreadsheet upload
- [ ] Analyse and share the results with Mark
- [ ] get them fixed, or have an update, and go back to the BL. 

This is important as most ILL work will need titles or citations to move ahead, getting this right is important.

**Comment by markmacgillivray** [comment]
It will be impossible to get certain matches with titles or citations.

**Comment by JosephMcArthur** [comment]
Yup, I know :) But, I'm assuming there are things we can make better, so want to get some data on that.

**Comment by JosephMcArthur** [comment]
I've done all the hard work here, moving forwards to communicate out!

**Comment by JosephMcArthur** [comment]
bumping to backlog as we're already making complex infrastructure changes. Best not to had fire to the flames with a different issue.
