### ISSUE TITLE
False positive: "Stability of perovskite solar cells"

### ISSUE THREAD

**Issue by allanaaa** [OAButton/discussion#735]
Hi, someone on Twitter reported a false-positive at this URL:
http://www.sciencedirect.com/science/article/pii/S092702481500673X

The Button reports an open article, but then leads to 
http://jbc.bj.uj.edu.pl/Content/202782/DIGONLINE002583.html

which leads to
sciencedirect.com

I replicated it on the Firefox bookmarklet and the Chrome plugin.

When I used the DOI on the website, it brought up 
http://www.unsworks.unsw.edu.au/primo_library/libweb/action/dlDisplay.do?vid=UNSWORKS&docId=unsworks_modsunsworks_38687

which is an IR link, but has no full-text available.

I submitted an error report on the website with the latter piece of information.

There *is* a ResearchGate copy available, which I will send to the requester on Twitter if everyone is okay with it. 

I searched but couldn't find a record of a request made that might've had either of those URLs submitted. 

Thank you!

**Comment by natalianorori** [comment]
I am not sure that we can share Researchgate copies publicly or on Twitter,
maybe we can contact them directly by email, explaining that this is only
partially open but that we wanted to make the paper available to them asap

Natalia

**Comment by JosephMcArthur** [comment]
Don't send the RG copy, just say we'll work on getting this fixed :)

**Comment by allanaaa** [comment]
Another pair:
http://www.sciencedirect.com/science/article/pii/S1342937X17300527
http://jbc.bj.uj.edu.pl/Content/202782/DIGONLINE002583.html

**Comment by allanaaa** [comment]
Now being worked on in #748.
