### ISSUE TITLE
Button sending users to paywalls

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#737]
I submitted these errors on the feedback form as "the article wasn't actually available," but I wanted to draw attention that these aren't false positives in repositories but rather the Button is sending users to paywalls. Do we know this is occurring and potentially why?

10.1002/asi.23621
http://hdl.handle.net/10.1002/asi.23621

Characterisation of academic journals in the digital age
http://link.springer.com/10.1007/s11192-016-2219-4

10.1007/s11192-016-2232-7
http://link.springer.com/10.1007/s11192-016-2232-7

10.1007/s11192-016-2088-x
http://link.springer.com/10.1007/s11192-016-2088-x

**Comment by chealsye** [comment]
This happened again today with Springer journals. 
10.1007/s11192-016-1983-5
10.1007/s11192-016-1907-4
10.1007/s11192-016-1833-5

**Comment by JosephMcArthur** [comment]
These now all return the expected result.
