### ISSUE TITLE
Perturbating "This article is available" while article is only accessible if authentified

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#743]
When requesting this paper:

https://openaccessbutton.org/?url=Identifying%20the%20Rubisco%20Recognition%20Domain%20and%20Critical%20Arginines%20in%20Activase%20and%20Engineering%20Activase%20With%20Improved%20Thermostability%20for%20Arabidopsis

A "handle.net" url is found: http://hdl.handle.net/2142/87049 but "The file you are attempting to access is a restricted file and may require credentials to view."

**Comment by JosephMcArthur** [comment]
can't replicate on new system
