### ISSUE TITLE
new signature box in the request system page

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#744]
Since we are going to have volunteers managing the initial moderation process of the request system, email templates shouldn't all go off signed under my name. So my idea is to add a new box in the admin page to identify who managed the request, and the template could drag the signature name from that box. We could extract the signature name from the volunteer's account. 

(not sure if this has the best title, feel free to change it)

**Comment by JosephMcArthur** [comment]
Closing to clean repo of older ideas.
