### ISSUE TITLE
Missed Linkage around "-"

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#746]
Paywall: http://www.sciencedirect.com/science/article/pii/S0921509316308498
OA version: https://hal.archives-ouvertes.fr/hal-01393509/

**Comment by markmacgillivray** [comment]
This sciencedirect URL also just returns from BASE the Polish repo that links back to the front page of science direct. I don't see the HAL one come out at all. I am not sure what you mean about the missing linkage around "-".

**Comment by JosephMcArthur** [comment]
So, the paywall link should go to the Hal link. However, it doesn't. When I submitted this I think that page just found nothing, but may have been caught in #748. 

I thought it may have been because of the "-" in the title.
