### ISSUE TITLE
minor copy updates to /response page success via link page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#747]
https://www.dropbox.com/s/6otqvdg2hm9zlan/Screenshot%202017-06-23%2012.46.12.png?dl=0

- [x] Need to change link text color (there is a word between "the" and "'page")
- [ ] remove 2nd sentance

**Comment by allanaaa** [comment]
Link text meaning what? Not the title of the article, I assume.

Remove "The link to your content .... few minutes." ?

**Comment by JosephMcArthur** [comment]
so, updated the above to be a bit clearer. 

Honestly, I think this whole bit of copy could be better & more accurate. The update is basically instant afaik, and for articles we don't validate. Let's link out to dissem.in too for authors to deposit more work.

**Comment by allanaaa** [comment]
Gotcha! 

We can [span class="typedata"] on the part about validating, if I'm reading the code right. Or we can take it out entirely.
Is it our request moderation team that validates data, or is it a community of Open Science Foundation users?

Link colour changed. 

I changed "minutes" to "moments" - or we could instead rewrite that part:
"The link to your work, saved Z/OSF, will appear on the request page in a few moments."
> "Your work, saved Z/OSF, is now available to everyone and can be accessed from our list of successful requests." (with appropriate link)


How about we add, immediately following:
> "If you search for your own work on Dissem.in, you can find other opportunities to increase the impact of your research."

or 
> "Please take a minute to search for your own name on Dissem.in, and see if there is more of your work you can share with the research community."

or 
> "You may want to visit Dissem.in to find other articles or data you can make Open Access."

**Comment by allanaaa** [comment]
I also changed the word "content" throughout the response/item page, to "work" and "research" variously.

**Comment by jibe-b** [comment]
It may be nice to suggest to the author to check and upload all of his/her missing publications.
dissem.in/ is developped in this goal: dissem.in/search/?authors=<author_name>.

cc @an3m

PS: I wrote this in a bad place before, writting it again here.

**Comment by JosephMcArthur** [comment]
Now we're getting authors 1st & last name as part of the moderation process, this is actually much easier / nicer than prior. I'm planning to meeting with @wetneb next month to discuss a few changes to dissem.in that we think would make it much more effective. Will consider that here too.

**Comment by allanaaa** [comment]
That's a great idea!

In the meantime, let's pick a version for the copy and close this, then edit the Dissem.in link later if applicable.

Also: Is it our request moderation team that validates data, or is it a community of Open Science Foundation users?

**Comment by JosephMcArthur** [comment]
on live!
