### ISSUE TITLE
Another example of false positives

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#751]
http://dx.doi.org/10.1093/jts/os-XIII.49.29

Our case study at Hudderfield found this one. So, @me get back to them when shut!

**Comment by svmelton** [comment]
Just got this note via Zendesk:

Hello -- I just wanted to report that the OA button is sometimes pointing to password-protected repositories (such as from http://www.tandfonline.com/doi/full/10.1080/09644016.2017.1343766 to https://repository.abertay.ac.uk/jspui/handle/10373/2720).

Thanks!

**Comment by JosephMcArthur** [comment]
cant' replicate on new dev system, closing
