### ISSUE TITLE
[Legal] French obligation for data producers to answer to a request within one month

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#752]
Just a bit of information about the French context: a producer of data that is funded by the state has to answer within one month to a request for release of data.

In case the data producer does not answer, the CADA commission can be asked to act as a mediator.

Source : p26 of http://prodinra.inra.fr/ft?id={97224C30-C56B-4CC2-8F78-41C7E1AF5148}

Text of law:
https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000031366350&idArticle=LEGIARTI000031370409&dateTexte=&categorieLien=cid

**Comment by jibe-b** [comment]
To be discussed at OpenCon cc @wetneb @JosephMcArthur

**Comment by wetneb** [comment]
oh you applied too! great!

**Comment by JosephMcArthur** [comment]
No longer doing data work, no capacity. Focusing on articles to build plumbing and hoping to return to data later. Closing this for now to keep the repo clean.
