### ISSUE TITLE
SHERPA/RoMEO not showing up on submission pages

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#754]
As noted in today's call, I haven't seen a submission page that included info from SHERPA/RoMEO, including for articles I know the journal was in the SHERPA/RoMEO. Here are three examples:

**Example 1**
Request: https://openaccessbutton.org/request/cCtXndRPZri4kNBmt
Submission Page: https://openaccessbutton.org/response/cCtXndRPZri4kNBmt
Journal: Nonprofit and Voluntary Sector Quarterly
SHERPA/RoMEO: http://www.sherpa.ac.uk/romeo/issn/0899-7640/

**Example 2**
Request: https://openaccessbutton.org/request/PA6mXq6nd8J4vbqZr
Submission Page: https://openaccessbutton.org/response/eQNszNJLLSujmft9R
Journal: Journal of the Association for information science and technology
SHERPA/RoMEO: http://www.sherpa.ac.uk/romeo/issn/2330-1635/

**Example 3**
Request: https://openaccessbutton.org/request/87k9C3rtZxwr2ogFA 
Submission Page: https://openaccessbutton.org/response/JExmqfbGNg8if2F3E
Journal: Science Communication (This request pulled in the journal title and not the article title)
SHERPA/RoMEO: http://www.sherpa.ac.uk/romeo/issn/1075-5470/

**Comment by JosephMcArthur** [comment]
Note, I need to look at the API calls for this & see if journal info is present. Mark has shown me how to do this somewhere...

**Comment by markmacgillivray** [comment]
Dev site updated with changes to show Sherpa statements. Here is one on dev where it checks Sherpa but cannot find anything, so shows the sherpa_unknown message:

http://dev.openaccessbutton.org/response/A8mW6tKoMYgevByjw

Just update the live site with the current dev branch content to get this on live, if it seems like the fix you are looking for.

**Comment by chealsye** [comment]
Could I see an example of a deposit page with SHERPA/RoMEO info?

**Comment by markmacgillivray** [comment]
Yes, if you create a request on dev that is in a journal that you know has a sherpa color, and that is on a web page from which we can extract the journal title (or if you create a request then manually add a suitable journal title in the admin area) then when you look at the response page you should see the appropriate green/yellow/red section.

**Comment by chealsye** [comment]
I was told by @JosephMcArthur that the SHERPA/RoMEO integration was live and should appear to authors. Is there no way for us to know of an example where this is the case?

I could create a new request - but I don't know if it would work. I'm seeking a live example where this is working. The three examples I started this issue with all are in SHERPA/RoMEO and are recent requests we should've been able to pull the title from. Is pulling the journal title the problem with these requests not showing the SHERPA/RoMEO info then?

**Comment by JosephMcArthur** [comment]
Here is an example of it working on dev: https://dev.openaccessbutton.org/response/YCXfZiZrm2TAovAkN.

**Comment by markmacgillivray** [comment]
If we know a journal title for an article, it will show up in the admin area of the request page. If it is not there, it can be manually added by an admin. If we have the journal title and the item is in Sherpa, the various correct colour statements should show up on the response page. This is true on dev, but may not be on live - I just made a change to dev, as mentioned above, so a push to live may be required.

**Comment by JosephMcArthur** [comment]
Just made a push, lets see!

**Comment by chealsye** [comment]
"You can legally give us the accepted version of your article!"

That's it? No linking to the SHERPA/RoMEO record? Or further explanation about how/why we know that and they should listen to us?

**Comment by chealsye** [comment]
Looks like those requests I flagged do include the SHERPA/RoMEO info now, which is great! But I really think we need to link out to the SHERPA/RoMEO record or provide additional information why they should trust us. Additionally, my eyes totally glance over that important information and I think it is worth considering the design of the deposit page.

**Comment by JosephMcArthur** [comment]
Totally agree, and have moved that last comment to a place where it can be considered in the redesign. The copy used is yours, but if you'd like to add links or something like that I assume we can do that (it'll need some dev time but probably worth it). 

The bug causing the issue above is closed now though. Design issues are in #719, issues for grabbing journal names & missing sherpa data are in other issues. 

If you want to adjust copy, probably best done in a new issue. 

Would suggest closing now, reopen or start new issues if desired though.
