### ISSUE TITLE
When the author name box is left blank, replace name with "colleague" tag on email template

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#762]
The system currently leaves a blank space when the author's name box is left empty. It should replace the blank space with the word "colleague". Tested it on dev.

**Comment by markmacgillivray** [comment]
Added on dev, please test and see if it is what you want.

**Comment by natalianorori** [comment]
tested on dev and working

**Comment by natalianorori** [comment]
can we push this to live asap? @JosephMcArthur

**Comment by JosephMcArthur** [comment]
should be on live now! cc @markmacgillivray 

Is it not working?

**Comment by markmacgillivray** [comment]
It looks like the code is up on live, it should work just the same as it did on dev...

**Comment by natalianorori** [comment]
tested on live and working, thanks Mark.
