### ISSUE TITLE
[Moderation] Cache story-validation mapping for automatic validation

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#764]
Among the fields to validate through moderation, the story field is the most subjective one.

In the case of repetitive/automatised requests for articles, a user could reuse the same story several times, provoking an overload of moderation requests.

Is the validation status of a story cached? In this case, the cache could be used to pre-fill the validation status of the story, reducing the charge on moderators.

It could also be an opt-in option for users: submit a story template, which will then be manually validated only once.

**Comment by JosephMcArthur** [comment]
This is a great idea. I mentioned it [here](https://github.com/OAButton/discussion/issues/440#issuecomment-300296948) but never actually made an issue for it.

The validation of a story status isn't cached - I don't think.

**Comment by jibe-b** [comment]
As the moderation process is growing with @natalianorori 's work, let's do it!

May I ask for indications on how it can be done? I don't promise I will do it but if you tell me 
1. where stories and results of moderation  are stored
2. where the preprocessing of a request is done (where middlewares live act)

I may hack a middleware that uses the cache. And don't hesitate to remind me I said this (if you den't see activity, it means I ain't doing it).

**Comment by jibe-b** [comment]
I will wait for #766 as progress may be done in the meantime https://github.com/OAButton/discussion/issues/766#issuecomment-313640995

**Comment by JosephMcArthur** [comment]
@markmacgillivray can we do this however makes sense for you? Essentially, if we approve a story once, remember that status for all others that use it. 

The primary use case here is stories that might come in from ILL or other services via the API that might all use the same story for their users. However, it'll also be helpful when we do bulk requests ourselves and when users want to do stuff via the UI. 

Right now, nothing needs to be displayed to a user about this, however, in future we may want to provide "previous" stories they've used before (that we're approved) so keep that in mind. For admins, clearly they should be able to see via the UI that it's approved. 

If an admin then "fails" a story that was once bulk approved, it should be failed for all others after.

Vice verse of all of this for failed stories. 

Ideally, any emails or things like that would be triggered on rating of the story as failed / pass would go ahead here (i.e when we fail a story the user gets an email normally).

**Comment by JosephMcArthur** [comment]
Awesome! thank you Mark. Closed.
