### ISSUE TITLE
stories rated with "fail" shouldn't show on /request

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#768]
test: https://openaccessbutton.org/request/cz4jEoKmPdFsaNbGL & https://openaccessbutton.org/request?source={%22query%22:{%22filtered%22:{%22query%22:{%22bool%22:{%22must%22:[{%22query_string%22:{%22default_operator%22:%22AND%22,%22query%22:%22*cancer*%20%22}}]}},%22filter%22:{%22bool%22:{%22must%22:[{%22exists%22:{%22field%22:%22story%22}},{%22query%22:{%22query_string%22:{%22query%22:%22story:*%22}}}]}}}},%22from%22:0,%22size%22:500,%22fields%22:[%22status%22,%22type%22,%22user.profession%22,%22user.affiliation%22,%22_id%22,%22url%22,%22created_date%22,%22createdAt%22,%22title%22,%22email%22,%22user.username%22,%22user.firstname%22,%22user.email%22,%22location.geo.lat%22,%22location.geo.lon%22,%22story%22,%22count%22],%22sort%22:[{%22createdAt%22:%22desc%22}],%22facets%22:{%22status%22:{%22terms%22:{%22field%22:%22status.exact%22}},%22user%22:{%22terms%22:{%22field%22:%22user.profession.exact%22,%22size%22:100}},%22type%22:{%22terms%22:{%22field%22:%22type.exact%22}},%22keyword%22:{%22terms%22:{%22field%22:%22keywords.exact%22,%22size%22:1000}},%22journal%22:{%22terms%22:{%22field%22:%22journal.exact%22,%22size%22:1000}}}}

**Comment by markmacgillivray** [comment]
Fixed on dev, will fix live display as soon as website dev branch is merged to master
