### ISSUE TITLE
[bug] on request pages meaning it doesn’t show!

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#776]
For the request https://openaccessbutton.org/request/caW8k4MEv7YdnsvT8

the UI doesn't display everything.

JS console errors contains:

```
Uncaught TypeError: Cannot read property 'firstname' of undefined
    at Object.details [as success] (caW8k4MEv7YdnsvT8:538)
    at c (jquery-1.10.2.min.js:4)
    at Object.fireWith [as resolveWith] (jquery-1.10.2.min.js:4)
    at k (jquery-1.10.2.min.js:6)
    at XMLHttpRequest.r (jquery-1.10.2.min.js:6)
details @ caW8k4MEv7YdnsvT8:538
c @ jquery-1.10.2.min.js:4
fireWith @ jquery-1.10.2.min.js:4
k @ jquery-1.10.2.min.js:6
r @ jquery-1.10.2.min.js:6
```

**Comment by JosephMcArthur** [comment]
@markmacgillivray I'm guessing this comes from the last push - can you take a look?

**Comment by markmacgillivray** [comment]
I have fixed on the dev site, there are no examples but it is straightforward, so would fix the display of the problematic record on live once we make a push to live.
