### ISSUE TITLE
[doc] question: who can push to develop branch?

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#782]
In https://github.com/OAButton/website /README.md 

`Anyone can commit to develop branch to test changes`

Who is everyone?

(doing my own FAQ ;) )

**Comment by JosephMcArthur** [comment]
Ah, maybe not anyone, just core members of our team. Most need to make a PR.

**Comment by jibe-b** [comment]
Hopefully, somehow ;)

I guess it should be stated clearly for newcomers.

**Comment by JosephMcArthur** [comment]
+1

**Comment by jibe-b** [comment]
Done at commit https://github.com/OAButton/website/commit/b52542e2049330d45905065865b2ef3dac581cf0
