### ISSUE TITLE
[bug] MAJOR BUG: filling of form during moderation is NOT recorded

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#785]
Here is what I did (and it could have been any moderator I guess):

- click "notify me" because the subject interest me (alot)

- fill the admin form in https://openaccessbutton.org/request/Ne7KDFe4rsWExXydh with Name, email address, Journal, DOI
- validated story
- clicked "send to author"

Received the email stating: "Your request is in progress

```
Hi,

The article request for "ScienceDirect" has been sent to the author. You can view and share your request here: https://openaccessbutton.org/request/Ne7KDFe4rsWExXydh.

[..]
```

This email does not contain the information filled right before.

Neither does the form itself https://openaccessbutton.org/request/Ne7KDFe4rsWExXydh

which looks like reverted to the state before moderation.

**Comment by jibe-b** [comment]
ping @JosephMcArthur @natalianorori

**Comment by JosephMcArthur** [comment]
@markmacgillivray can you take a look at this ASAP?

**Comment by jibe-b** [comment]
I wonder if this is linked to the reappearence of many requests I filled and sent yesterday OR on tuesday.

Does someone do a second check of requests before sending requests?

If no data is kept, then the requests sent might simply look bad as no data was kept.

**Comment by natalianorori** [comment]
Jibé, did you press "save changes" before clicking the " send to author" Button?

**Comment by jibe-b** [comment]
@natalianorori no, for none of them. :cry:

**Comment by jibe-b** [comment]
I read "Make sure to save the author's name in the "author name" box and save changes after doing so." in 
https://docs.google.com/document/d/1jmyBiDtONn2QWc0WMmAYTw06wXusGTLnAlqDXR_uGJQ/edit#

**Comment by jibe-b** [comment]
There definitely is a collision between the "action button" and the "save" button.

Action button should save the form, shouldn't it? If not there should be an indication "all data added to the form and not saved will be lost", I guess.

**Comment by jibe-b** [comment]
I am really sorry for the quite big number of requests that were incomplete :/

**Comment by markmacgillivray** [comment]
I don't think there is anything I can fix here. The action buttons do not save information - that requires a click on the "save" button. I could make the action buttons also trigger a save first, but that would cause unnecessary delay and the point of the action buttons as I understood them was to do quick actions.

I think it is a process decision, and possible a need for better instructions for how admins should use the admin controls - as mentioned above, warnings etc could be added to the UI about what different things do.

If you decide you want the functionality changed, I can change it, but otherwise, does not look like a bug here, just previously intended behaviour.

**Comment by natalianorori** [comment]
@jibe-b In order for information to be recorded you need to save changes after filling all information. This also helps you review that everything you entered is correct before pressing the "send to author" action button. 

You are right, the save button is manual but if you don't press it changes don't get saved and the action button won't save the form if it finds information missing. 

 Do you have any idea of how many you sent out like this? I left a similar message to this one  yesterday on the gitter group explaining the difference between the buttons

**Comment by jibe-b** [comment]
@markmacgillivray @natalianorori Sadly "save" still fails https://github.com/OAButton/discussion/issues/770 (I just tried again)

**Comment by natalianorori** [comment]
@markmacgillivray you are right, this is a process decision. We decided that we need to save changes before pressing the button in order to make sure all information entered is correct, so I'd like to keep things as it is. I give emphasis to this on the instructions and I also sent a message to all volunteers in our group yesterday explaining that we need to save changes firsts.

**Comment by JosephMcArthur** [comment]
> I don't think there is anything I can fix here. The action buttons do not save information - that requires a click on the "save" button. I could make the action buttons also trigger a save first, but that would cause unnecessary delay and the point of the action buttons as I understood them was to do quick actions.

@markmacgillivray Why would a save cause unnecessary delay? Surely it is slower for a user to save, then click the button?

**Comment by natalianorori** [comment]
@jibe-b what request are you having trouble saving changes to? Can you send me the link?

**Comment by markmacgillivray** [comment]
@JosephMcArthur because a save is not always required. If the action button has to do a save first, then it has to do it every time, which makes the action button slower, which detracts from the point of the action button (to do admin fast).

**Comment by markmacgillivray** [comment]
@JosephMcArthur and the action buttons in the request page are supposed to be precursors for action buttons directly on the /request listing page, where saves will not be possible. So, if the workflow concept of the action button changes to being something that we always expect requiring an edit and save to occur first, then action buttons on the /request page would be infeasible.

**Comment by JosephMcArthur** [comment]
I think we're thinking about speed in very different ways here. Surely the "save" you're talking about is taking fractions of a second or a bit more where the user doesn't need to be doing stuff. Even if they didn't put in an input, this feels trivial (it's quick as it removes the need for several pages / clicks / training - not because it's 1 second vs 2 seconds). However, needing to train people to save before pressing (which I think seems very counter intuitive) and fix errors where people miss this (or include big UI warnings) is going to take a long time. 

If these buttons on /request don't save, that seems fine, we simply don't design them to always think a save is needed on /request.

**Comment by markmacgillivray** [comment]
Well, looks like you and @natalianorori have to discuss and decide - it does not seem to fit with her comments above about wanting to save explicitly, and would not allow an administrator to check the changes they make before executing an action.

**Comment by JosephMcArthur** [comment]
We shall, @natalianorori happy to discuss here or offline (I know we have some time tomorrow, yes?). @jibe-b also interested in your thoughts as a new user of the moderation system. 

@markmacgillivray I don't understand why this wouldn't allow for checking? Use the code needed to save (which presumably flags errors of some sort) and stop the action if it errors?

**Comment by natalianorori** [comment]
@JosephMcArthur My only concern with making the "send to author"button save changes at the same time is that it doesn't give us a change to double check our entry. But I agree with you that it might be hard to train people to save changes before pressing. We thought about buttons to work a certain way when I was the only one working on the system, but as we bring more people over our needs might change as well.

**Comment by markmacgillivray** [comment]
It's not a save error. If there is a save error, yes the action can cease. But also, that means writing the code to manage that. The point is that Natalia says she wants to check WHAT she saves, not IF it saves. The code cannot know if what is saved is what the user wanted. The only way to do that is to have the user save, then the user looks at it, then the user clicks an action button, which is what we made so far.

**Comment by JosephMcArthur** [comment]
When you say "double check our entry" @natalianorori, what does that mean here? Do things often change after they've saved?

**Comment by natalianorori** [comment]
not often, but remember we are dealing with names an email addresses in here. I re read what I enter to avoid typos. We could just ask people to re read things carefully, but lets be honest not everyone is going to do that. The "save changes" button makes people do it.

**Comment by JosephMcArthur** [comment]
> The "save changes" button makes people do it.

I wish I had as much faith in people - it probably wouldn't make me double check to be honest.

**Comment by natalianorori** [comment]
If you don't think it's going to make them double check we can just remove it and have the UI entry save all changes. We are going to have typos every once in a while and probably would still having them even if we keep the "save changes" button.  On the other hand, if people forget to save changes the system sends out unfilled templates, which might be worse than a typo.

**Comment by JosephMcArthur** [comment]
Just to make sure the path forward is clear here, what I'd like to see is for clicking an action button to save any changes in the form before taking the action. 

@jibe-b, are you going to take another shot at your PR in the near future, seems like you were close! If not, I'll ask Mark to handle.

**Comment by jibe-b** [comment]
:+1: for making clicking "save" not reload the page :)

**Comment by jibe-b** [comment]
I validate how it behaves now!

1. indication to save before any other action
2. "Changes saved" appearing one second is really useful :)

I thinks this issue can be closed. Thanks for the work done!

**Comment by JosephMcArthur** [comment]
Thanks for your help here Jibe!

**Comment by JosephMcArthur** [comment]
Thanks for your help here Jibe!
