### ISSUE TITLE
Have an option to send request to author without notifying the user

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#789]
users have been complaining about 
- receiving too many notifications from the button when they create a lot of requests
- receiving notifications for requests they don't care about anymore, which are usually pretty old. 

two options come to mind: 
- Having the user check a box saying that they don't want to receive confirmation emails from us. 
- Having an option in the entry box in the admin UI that sends request to the author but doesn't notify the user which could be use in special cases (when we moderate old requests/do tests)

temporary solution: 
- Let volunteers know that we are currently not moderating requests received prior to 2016 since users may not care about being notified anymore and they're notified each time the "send to author"button is pressed,  and leaving old request moderation to me.

**Comment by JosephMcArthur** [comment]
Closing to clean repo of older ideas / needs.
