### ISSUE TITLE
[doc] question: is dev.openaccessbutton.org/request?url=<DOI> fine to make a request?

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#790]
http://github.com/dissemin/dissemin redirects users to dev.openaccessbutton.org/request?url=<DOI> to make requests. Is it fine to use the dev instance?

I myself have problems with logging in the dev instance, so I am unsure about it.

**Comment by JosephMcArthur** [comment]
nope, needs to be production (although dev is fine for testing). Dev site is periodically cleared (for one reason or another).

**Comment by jibe-b** [comment]
Ok, I change this immediately on dissemin.
