### ISSUE TITLE
on full screen, get extension button on /account fails to install

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#791]
Same issue that we fixed on the frontpage, but here. @markmacgillivray 

Should be a quick fix.

**Comment by JosephMcArthur** [comment]
nope nope nope, actually just having this issue globally

**Comment by JosephMcArthur** [comment]
not we have a PR for this here https://github.com/OAButton/website/pull/35 which is when we thought it was fixed

**Comment by markmacgillivray** [comment]
The code from that PR is already in our code. If this issue is occurring again, then it is something that requires a different solution.

**Comment by markmacgillivray** [comment]
See #657

**Comment by markmacgillivray** [comment]
Now opens the url separately.
