### ISSUE TITLE
on Edge, download for chrome shows, not the bookmarklet

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#803]

**Comment by markmacgillivray** [comment]
Have tried adding a fix on dev, because:

https://webmasters.stackexchange.com/questions/83804/why-does-the-internet-think-microsoft-edge-is-google-chrome

Edge tries to identify itself as chrome, amongst other things.

Can someone with Edge try the dev site and see what comes up now?

**Comment by markmacgillivray** [comment]
Will assign to @JosephMcArthur but reassign to anyone with Edge.

**Comment by JosephMcArthur** [comment]
@allanaaa you should be able to test this while you work on #804. 

Use browserstack for crossbrower testing. The login is in lasspass.

**Comment by allanaaa** [comment]
Still linking to Chrome, sorry! (Or, the Chrome webstore link shows in the bottom bar of the browser; the link doesn't actually load.)

**Comment by JosephMcArthur** [comment]
this is fixed on /account and while looking we caught another unrelated bug on the homepage!

**Comment by markmacgillivray** [comment]
OK, fixed on homepage
