### ISSUE TITLE
Investigate some missing stories

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#807]
On our stats page it says we only have ~3250 stories. This is odd as we'd have imported about 8.5k from the old system, and have got many since. 

Case in point:
* Data requests with stories = 47
* Data requests without stories = 906

Those numbers include a huge number of old data requests (from when stories were very mandatory) which still exist (i.e weren't purged for some reason like being duplicates or having bad user data) but just don't have stories. 

The [en-mass story rating exercise ] which was created from a datadump on Feb 16th (https://docs.google.com/spreadsheets/d/1SCJmFuZYRhDfrezc7gC_0uIKWBPF7k5VWW4F5eS1mtA/edit#gid=2060199913) lists 2700k stories, so I'd take a guess that our problem (if it exists) happened between Oct-Feb. 

Currently, this seems to only affect old requests, which we know people aren't worrying about that much. @markmacgillivray and I have had an initial chat about how to look into this:

> I'd just have to go back and look at every import script we ran, the reasons for running them, why they have the logic they do, which issues they related to, what data dumps were used to run them with, and probably rerun all into a test index and see what the outcome is.
> I'd think at least a day to do

Assigning myself to continue to try and narrow down the issue. How I might do that:
- [ ] search through request data related issued
- [ ] try and pull together all exported data I have
- [ ] speak to Natalia about her weekly updates
- [ ] review oaevent.txt (our datadump from the last oab) vs current request data. 
- [ ] review stories pre-stories being optional for what's missing.

**Comment by markmacgillivray** [comment]
Closing this to keep track in #966
