### ISSUE TITLE
Allow an identifier to pass in / out of /bulk unchanged (can use a simpler number)

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#811]
I've just found that in my analysis workflow the title matching (which I thought I tested going in / out the sheet and seeing it as being unchanged) in fact isn't... which is going to cause major headaches. 

I really need to be able to match data easily going in & out. I think a simple UID column would work really well.

Doesn't need to be required.

**Comment by markmacgillivray** [comment]
What does this mean?

**Comment by JosephMcArthur** [comment]
Can we add a column to the input of /bulk that is just a column of numbers that doesn't change in any way & is just outputted? 

That would solve my problem.

**Comment by JosephMcArthur** [comment]
@markmacgillivray can we bump this into this sprint? Need to get this soon (currently going to have to do like 500 by hand I think!)

**Comment by JosephMcArthur** [comment]
To be clear, this means I can put in something like 

| title                                          | UID |
|------------------------------------------------|-----|
| a thing                                        | 1   |
| a thing revoked                                | 15  |
| you'll never guess what we found about a thing | 45  |

and it'll come out with that UID column in the results unchanged.

**Comment by JosephMcArthur** [comment]
Could also do this by just saving the file used initially and presenting that (assuming row orders don't change). That would be fine for me for now.

**Comment by markmacgillivray** [comment]
This could still do with some work re. how it presents answers, but it is working now - also, you won't have to rerun your old jobs if you just want to match them against something you already had in your sheet.

Try downloading the CSV results of a job on the bulk page, you will now see that it output whatever fields were input when you uploaded to start the job, and THEN it starts with our MATCH field and the rest of our answers.

At the moment certain field names should not be used as column names if you want to see them in the results. These are 'plugin','libraries','refresh','url','library','discovered','source'.

Once you try downloading an old job and see what you expect, try creating a new job with some other column name in it with whatever values you want in them. You should get them back as the first columns of your output.

I did this quick and will want to do some improvements, but for now it should enable you to finish your urgent stats work @JosephMcArthur

**Comment by markmacgillivray** [comment]
btw if there are any problems, I am out until 5pm today, so won't be fixing anything until tonight at the earliest.
