### ISSUE TITLE
Email validation giving false error

### ISSUE THREAD

**Issue by allanaaa** [OAButton/discussion#816]
I wanted to push along a request that needed an author email. I supplied the address given on the article page, but got an error.
![uh](https://user-images.githubusercontent.com/28012148/28723981-8a735344-7386-11e7-9e4b-41ab4774bd15.PNG)

Are we validating with a regular expression? Is it perhaps catching up on the periods strewn throughout this address?

**Comment by allanaaa** [comment]
Never mind, I tried it on a totally normal email address for another request and that gave me an error too.

**Comment by JosephMcArthur** [comment]
Hmmm... well that's a problem if I ever saw one! Can you test on the dev site too please? @allanaaa

**Comment by JosephMcArthur** [comment]
and link to specific requests

**Comment by allanaaa** [comment]
Sure! The one above is https://openaccessbutton.org/request/Wom2YgYKrndrpFizu

**Comment by markmacgillivray** [comment]
Mailgun started charging for validation checks last night. I knew about this and meant to mention to Joe at our last meeting, but forgot. However I thought it would keep working fine, but it turns out that because payment did not used to be required, we never actually used to send the oabutton mailgun api key along with the requests at all - so now, because we are not authenticating, we are not getting responses back for mailgun validation checks. I have just fixed this on dev, but will need to do a quick edit to live to get it working there too.

**Comment by allanaaa** [comment]
On dev, the email address I entered didn't appear to be accepted (nothing happened on the page), but when I refreshed the request it had moved on to moderation status.
https://dev.openaccessbutton.org/request/sAuT7ubAcaCXG8ouN

**Comment by markmacgillivray** [comment]
Probably your dev test clashed with me making the change. You should find that it works now as expected on dev. Live has been changed but takes about ten minutes for it to deploy to all the cluster machines, so try that in ten minutes too and it should work. I have checked the mailgun account and it is registering validations from today now, so appears to be working already. Have a look, then close this once you are happy.

**Comment by allanaaa** [comment]
https://openaccessbutton.org/request/Wom2YgYKrndrpFizu

Same visual when entering this email: nothing happens when the Save button is pressed, but on refresh the email appears to have been saved. 

https://openaccessbutton.org/request/LBSgRo9JDGmsgcuk3
![oab1](https://user-images.githubusercontent.com/28012148/28726894-0459ac1c-7391-11e7-950a-c3348dcdd24f.gif)

**Comment by markmacgillivray** [comment]
If the email is valid then it won't show anything - it just accepts it.

**Comment by JosephMcArthur** [comment]
This sounds fixed now, so closing!
