### ISSUE TITLE
[moderation] clicking "broken link" status action doesn't seem to do its job

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#817]
The following request has a doi not resolved oadoi.org/10.3945/acjn.116.146837

https://openaccessbutton.org/request/r3oTwAH4y5jRMDCkJ

but clicking "broken link" in status action button doesn't modify the status of the request after reload.

**Comment by natalianorori** [comment]
It doesn't modify the status, but it does send out an email to the user fyi :)

**Comment by jibe-b** [comment]
Ok, thanks for the info!

I suggest to update it to:

- display "an email has been sent to the user who requested to indicate the link was broken"
- change status to "bad request"

Unfortunately, one user received the emael two or three times as I was reproducing the strange behaviour^^

**Comment by jibe-b** [comment]
Reminder to myself: add an admin note like "already sent the broken url notification"

**Comment by JosephMcArthur** [comment]
@natalianorori can you test if this is still a thing?

**Comment by natalianorori** [comment]
It is sending the template but it is not modifying the status, it still
leaves the status on "help". I am all for changing it to "closed" and then
reopening the request if the author gives us the link. Will avoid confusion
in the moderation process.

**Comment by JosephMcArthur** [comment]
noted, lets do that then @markmacgillivray

**Comment by markmacgillivray** [comment]
Done on dev

**Comment by JosephMcArthur** [comment]
Thanks Mark! Natalia, please test & close if all good.

**Comment by natalianorori** [comment]
thanks mark. it works
