### ISSUE TITLE
change how the job history content is calculated, and increase the timeouts

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#818]

**Comment by markmacgillivray** [comment]
Changed when job history is calculated, still to check timeouts

**Comment by markmacgillivray** [comment]
Check how the trigger to request from bulk jobs works - is it waiting for progress data? Does not work now since the change to progress check, so look into it.

**Comment by markmacgillivray** [comment]
Timeouts at 10 minutes, should be OK, open new issue if large sheets still fail, and particularly if they fail in less than 10 minutes.
