### ISSUE TITLE
make emails sent for /bulk editable in static & send on dev as they would on  live

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#831]
@markmacgillivray the latter suggestion is to have the status checks done ever 15 minutes as they would on live & confirmation emails be sent. 

Just want to be able to passively test / edit these as we do day to day testing.

**Comment by markmacgillivray** [comment]
This is in place, create an email template called bulk_complete.html and push it into the emails folder on the dev branch, then go to admin and click refresh templates, then go to the bulk page and upload a little job (like a couple of DOIs) then wait fifteen minutes, you should get an email based on the template.

**Comment by JosephMcArthur** [comment]
I've already done this twice with the same results. Doesn't send the template I put in. 

Also, what would be the {{ }} for the job title, if there is one.
