### ISSUE TITLE
Installing search bar widget as one line or i-frame

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#834]
I think having it as one line would make it feel less scary to install & an iframe is likely to be less frightening for people (as they're familiar). 

I'd love to understand the trade-offs of these options further.

**Comment by JosephMcArthur** [comment]
We can do iframes, but there would be less control over formatting. 

@markmacgillivray what's the easiest way to have a page on our site without the normal templating where we can just embed the search bar?

**Comment by markmacgillivray** [comment]
I just added one, and added an example of use to the embed_oa page

**Comment by JosephMcArthur** [comment]
Prefect!
