### ISSUE TITLE
Displaying "suggested" author names from /scrape for moderators

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#838]
The /scrape api sometimes picks up author names. Can we display these as suggestions for moderators? 

Ideally, a suggestion should be clickable, and when clicked put into the author box (or something like that).

**Comment by JosephMcArthur** [comment]
@markmacgillivray Natalia spends a lot of time tracking down author names, so we'd like to try and cut that down. 

Seems like Scrape sometimes get these, can we start by displaying corresponding author names (which I suppose could be guessed by being first / last) to admins. 

If there are other easy sources of author lists, e.g DOI's, or orcids available, can we get those displayed too? 

This is yours to decide how to implement technically / UI, and @natalianorori 's to test. Natalia, anything you can do to help expand at this point is helpful.

**Comment by markmacgillivray** [comment]
Added a possible authors button which shows if there is no author name set but if author names were found during scraping. Hit the button to show the author names. Click one to put it in the author name box. Can be seen working on this request:

https://dev.openaccessbutton.org/request/JHhi6n4YCacikGRFd

**Comment by natalianorori** [comment]
This works and it's awesome. Thank you
