### ISSUE TITLE
pass plugin errors to the /feedback

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#864]
add a parameter called code, then show some stuff.

@markmacgillivray where you can reuse copy from the existing plugin that would be good!

**Comment by markmacgillivray** [comment]
Added functionality to feedback page to show the bug form if it is passed an error code from the new plugin. This will insert the error code into the form and hide the question that asks the user for that, but enables the user to provide other info about the error event, then we can see what they say.
