### ISSUE TITLE
track requests made from different plateforms

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#867]
Currently, we're using URL parameters onto the API to track platform usage for availabilities. Would be good to pass these through to requests too so we can track that. 

- [x] pass tracking
- [ ] have a way to get data out & process

Need to test similarly to #866

**Comment by markmacgillivray** [comment]
All requests are created on the site now - nobody creates them anywhere else. I have updated the /request page on the site to passthrough URL params called "from","plugin", or "embedded", so any other thing like our plugins or embeds that pass any of those through will get picked up if they trigger a request BY INCLUDING THEM.

So it is now a case of adding those things where you want them to be passed through into requests too. Where would that be?

**Comment by JosephMcArthur** [comment]
Not quite following you. 

> All requests are created on the site now - nobody creates them anywhere else. I have updated the /request page on the site to passthrough URL params called "from","plugin", or "embedded", so any other thing like our plugins or embeds that pass any of those through will get picked up if they trigger a request BY INCLUDING THEM.

So, this means that (for example) we'll be able to tell requests made from plugin users, or a particular embedoa widget. 

> So it is now a case of adding those things where you want them to be passed through into requests too. Where would that be?

I think the answer to this is let's always pass them through.

**Comment by markmacgillivray** [comment]
The changes I just added are for anything that goes via the UI. That is, the embeds etc that we have just made, that pass a "from" or "plugin" param to the front page to do an availability check, if that check then creates a request, the request will have that param in it too. Plugins already send the plugin param to requests that they create. So, I think this is complete?

**Comment by JosephMcArthur** [comment]
Can we pass the params into the request export sheet? That would complete the other todo in the initial comment. 

potentially relevant for #892

**Comment by markmacgillivray** [comment]
As far as I can still tell, this is complete. The code again may have been missing because of the recent git issues, but it is there now, both the request and availability exports include the plugin, from and embedded fields. But because the code that collected those from the various pages was also unintentionally removed, there may not be much to show on current exports anyway.

Reassigning back to you to confirm and close, or else let me know what else could be done.

**Comment by JosephMcArthur** [comment]
excellent! lets close
