### ISSUE TITLE
URL encoding issues on illiad

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#872]
+ are used instead of spaces on illiad, which causes us to not recognise titles

**Comment by JosephMcArthur** [comment]
An example:
* Openaccessbutton.org-created URL: https://openaccessbutton.org/?url=Effect%20of%20Saxagliptin%20on%20Renal%20Outcomes%20in%20the%20SAVOR-TIMI%2053%20Trial
* ILLiad Addon-created URL: https://openaccessbutton.org/?url=Effect%2Bof%2BSaxagliptin%2Bon%2BRenal%2BOutcomes%2Bin%2Bthe%2BSAVOR-TIMI%2B53%2BTrial

**Comment by markmacgillivray** [comment]
Fixed on dev, needs an API update to get on live.

https://dev.openaccessbutton.org/?url=Effect%2Bof%2BSaxagliptin%2Bon%2BRenal%2BOutcomes%2Bin%2Bthe%2BSAVOR-TIMI%2B53%2BTrial

https://dev.openaccessbutton.org/?url=Effect%20of%20Saxagliptin%20on%20Renal%20Outcomes%20in%20the%20SAVOR-TIMI%2053%20Trial
