### ISSUE TITLE
Add in time delayed feedback messages and other error catching (like false positives)

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#879]

**Comment by allanaaa** [comment]
I'm for a time-delayed message suggesting how to report an error - I've suggested it lines 55-57. Not sure how to time-delay in python tho.

**Comment by jibe-b** [comment]
in Python:

> import time
t = 10 # seconds
time.sleep(t)

Notice though that it stops the execution, hence better to have the code executing asynchronously

**Comment by allanaaa** [comment]
Great, why don't you go ahead and look at the actual code and figure out where that would fit in?

**Comment by jibe-b** [comment]
'cause I'm working, right now ;)
