### ISSUE TITLE
generate & test ff file for new plugin

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#883]

**Comment by markmacgillivray** [comment]
See issue #851 which is awaiting a review of the plugin too - so do that and this together.

**Comment by markmacgillivray** [comment]
I have generated a new FF plugin xpi, it is in the phoenix branch of the plugin repo, in the firefox folder. How do we usually test FF? Do you do that? I don't think I know what we usually do for it, or for the FF plugin store... but maybe I just forgot.

**Comment by JosephMcArthur** [comment]
Done some testing, what I've found:
* It installs fine
* It will successfully open an article that's OA
- [ ] It seems to hang on requests, i.e it never starts them
* It opens the welcome page successfully
* It uploads to the store with no automated errors
- [ ] once clicked (even when successfully opening an OA article) it never stops spinning

So, there are some bugs to quash above before I can usefully test this further, but progress! 

- [ ] Let's see if we can get a build up that will be recognised via the store as a beta channel - https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Maintenance so that we can get this into the real environment asap. Looks easy (just naming conventions)

**Comment by markmacgillivray** [comment]
OK, this works now on my test machine. Spinner stops spinning, requests open if necessary. Try it again yourself and if all good, can close this issue.

**Comment by JosephMcArthur** [comment]
Does this need another push to the repo? Doesn't seem to have been updated.

**Comment by markmacgillivray** [comment]
No, the last error was on the API side, I altered that, and now seems OK. So try with the plugin you already have on FF.

**Comment by JosephMcArthur** [comment]
Okay great, looks good. Is there anything else you want to do before it goes to the store?

**Comment by markmacgillivray** [comment]
Great. At the moment it's connecting to the dev API so only put it in the store if you want a dev one in there. Otherwise just wait until testing is done and you're happy for everything to go to live, probably the end of this week, then I'll move the new plugin out of the phoenix branch and make chrome and Firefox versions that connect to the live API, and those can go in the respective stores.

**Comment by JosephMcArthur** [comment]
It's now in the store! Currently invisible, download links are added.
