### ISSUE TITLE
a link that works on the frontpage doesn't on embedoa

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#884]
http://www.jstor.org/stable/20865428?seq=1#page_scan_tab_contents

> Using the widget, the search circle, kept going as if it was still thinking. I did a similar search simultaneously on the OA button website and got a response fairly quickly that the article was not available and asked if I wanted to contact the author.  I'm still waiting for a response from the widget search...

**Comment by JosephMcArthur** [comment]
Ah, it turns out that currently nothing works in embed oa!

**Comment by markmacgillivray** [comment]
Error with the UID passthrough we introduced at the end of last week. Fixed now.
