### ISSUE TITLE
consider parts of the website flow that should be improved for new plugin

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#886]
most of this will simply be trying to speed stuff up & tidying formatting on pages & adding messages during loading I think.

**Comment by JosephMcArthur** [comment]
Some more detailed thoughts & updates:
- [x] when a request is being made, show some text

>   Hold on. Warming a request to the author for you. Give us a moment.

- [ ] when a request is being made, show a cleaner loading page (where the footer isn't taking over the whole page) - @markmacgillivray

**Comment by markmacgillivray** [comment]
Speed increase will come along with specifying which places to search for, because I will rewrite the search process then. So another issue is probably not required.

**Comment by JosephMcArthur** [comment]
> Hold on. Warming a request to the author for you. Give us a moment.

can you put that on the request page when it loads (like on availability). I ticket it, but actually failed to do it if I remember

**Comment by markmacgillivray** [comment]
I'm not sure where you are encountering the delay.

The request page where a request is created already has a loading spinner and says "Starting a new request. One moment please."

After that, the actual new request page is loaded, and details are retrieved from the backend. If it is at this point that you want to show a message, then it would have to be something that makes sense in the context of new requests and old requests - both require a query to the backend to get the details.

**Comment by JosephMcArthur** [comment]
The spinner can sometimes drag on for a while in my experience, that's all I'm concerned about since people are going to be entering at this page a lot from the plugin / widget / frontpage / deliveroa.

**Comment by markmacgillivray** [comment]
I'm still not sure what I can do with this issue. The main front page and the request page both have loading spinners and messages already, the main page tells you it is searching thousands of repos, the request page tells you it is creating a request. Apart from making the backend faster, which we're going to do as soon as I can set some time to do a refactor of that, I don't know if there is much more we can do on the site side of things.

Maybe the "creating a request" message is one that went missing in the recent loss of content? Or is it just that you want the specific text to be changed to the "warming a request" sentence you have above?

**Comment by JosephMcArthur** [comment]
if the creating a request message is there, then I'm happy to close pending a refactor
