### ISSUE TITLE
try and get the loading spinner to be the app icon

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#887]

**Comment by JosephMcArthur** [comment]
this is probably less important than #886

**Comment by markmacgillivray** [comment]
Loading spinner is now the app icon, and code has been simplified further yet should still work with bookmarklet - testing with bookmarklet and changing bookmarklet style is next on list, but prob won't get to it until Saturday. The latest code in the phoenix branch of the plugin repo should work as you'd like for the plugin - the oab icon itself changes in the chrome navbar and becomes a spinning spinner, and when a result is achieved the new page opens and the spinner stops then turns back into the oab logo. Works well for me. @JosephMcArthur please try this dev version on your machine, and if happy, make a new release and push to dev plugin on chrome store for others to try, and confirm to me you are happy. Then I can continue with using this code to generate a firefox version and to style the bookmarklet.

**Comment by JosephMcArthur** [comment]
it's WONDERFUL. Only tested on one article then uploaded to chrome store (to see the animation). If whatever simplifaction you did you think needs more testing than that let me know and I'll get that done.
