### ISSUE TITLE
make a nice 404 page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#890]
@markmacgillivray is there an easy way to make a template for this that I can then fill in?

**Comment by markmacgillivray** [comment]
Just make a page in the content folder called 404.html and put whatever you want in it.

**Comment by JosephMcArthur** [comment]
okay, done. But, it doesn't do what I'd expected, for example shifting https://dev.openaccessbutton.org/dafa to /404.

**Comment by allanaaa** [comment]
I think you have to put in a manual redirect to your 404. Did a quick copyedit here, added a sentence sending people back to the homepage (in case they miss the big Open Access Button in the header).

**Comment by JosephMcArthur** [comment]
@markmacgillivray this page exists but it doesn't seem to appear
