### ISSUE TITLE
bookmarklet styling

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#892]
This is the suggested approach from Sam, which I think looks good (clean, nice simple use of color and obviously clickable buttons). All the icons should be in the repo from last time we did this (they're reused)

![received_10159402607405500](https://user-images.githubusercontent.com/4953703/29818744-a37698d6-8cb5-11e7-8876-081a719f4303.png)

**Comment by markmacgillivray** [comment]
Done, available on dev to test on the bookmarklet test page:

https://dev.openaccessbutton.org/static/bookmarklet/index.html

**Comment by JosephMcArthur** [comment]
This (even on browserstack) is simply redirecting me (it actually feels kind of shocking, as you see it pop up, try and read them get sent away). Nothing we can really do about that right now though, and it's good news of course. 

Two questions:
* what did you do when it shows errors? 
* what did you do when we don't work on the page (i.e it's blacklisted)?

**Comment by markmacgillivray** [comment]
It says sorry there was an error please click to report it, and tries to open the link to the feedback page, unless it was a blacklist error, in which case they will click or it will try to open and they will see the instructions page and the info warning saying they must have tried to use on a blacklisted place.

**Comment by JosephMcArthur** [comment]
What's the styling like? Can I see a screenshot?

**Comment by markmacgillivray** [comment]
The styling is as shown in the image at the top of this issue, except instead of the "???" text the test is "Sorry, there was an error. Please click to report it".
