### ISSUE TITLE
make the text of "This article is available!" smaller on embedoa & add final copy in widget

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#895]

**Comment by JosephMcArthur** [comment]
- [ ] When an article isn't found, the widget doesn't display "this article isn't available". Only shows the text asking if they'd like to make a request - @markmacgillivray 
- [ ] Ask users to make ILL's - me

**Comment by markmacgillivray** [comment]
I don't understand this - as far as I can tell that "not available" text is in the embed widget, but also the widget redirects to a new request page anyway, so that may never get seen. Also, the embedoa page now seems to have been broken, with js includes to w3schools that don't work and some layout issues too.

I have resized the text though.

**Comment by JosephMcArthur** [comment]
Page formatting fixed, that was just a little mistake I made. 

I'd rather not have the redirecting behavior right now without consulting users, I think many of them like the more traditional nature & will be putting this on pages they want their users to stay on. I can see a lot of uses for the auto-redirect though and I'd encourage you to keep the version of the code that powers this in a separate file that I can use to test with people while we also finish up this version. 

The bug was that while the code looked fine ( I check it ) when the response came back on articles that weren't available there was a blank line where (now bolg) response would be.

**Comment by markmacgillivray** [comment]
OK, have made the redirect an option on the widget, so by default it does not redirect. To make it redirect, whatever page you call openaccessbutton_widget from, set openaccessbutton_widget({redirect:true})
