### ISSUE TITLE
when bulk requests are made, have them made by the user who started the bulk job

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#896]
currently, they're shown as made by an anonymous user. This is okay, however, in a larger job makes it hard to be able to be sure which requests are created as part of the job when exporting.

**Comment by markmacgillivray** [comment]
Hmm according to the code the requests are already created by the admin user that wants them. Do you have an example where that did not happen?

**Comment by JosephMcArthur** [comment]
I'm not 100% sure which job. But, I think that this one was made through bulk: https://dev.openaccessbutton.org/request/qLSLck7neLrM5iqbz while I was logged in.

**Comment by markmacgillivray** [comment]
Ah, we don't allow requests to be allocated to a user unless they have a story. So bulk jobs do generate requests by the logged in user, but then we don't keep that info because there is no story yet. So what should the story be for these bulk created requests? Let me know that and this can be closed quickly.

**Comment by JosephMcArthur** [comment]
It would be different in each case I guess. Could we add a box when making bulk requests to put in a story for them? Again, this is admin only right now, doesn't need to be pretty, just needs to work.

**Comment by markmacgillivray** [comment]
From a bulk job you create multiple requests though - do you mean a different story for every request in a bulk job, or just a way to provide one story to be applied to every request in a bulk job?

If you want to provide a different story for every request in a bulk job, we would probably be better off just adding some tag to those bulk requests, then you create them after running your bulk job and we allow them to be assigned as being created by you, and then you go and find them in the usual requests page and write stories into each of them.

Or if you want to do one story for every request in a bulk job, that is easy enough - right now you run a bulk job and once it is done you get the "request" button that allows you to try to create requests for all the items that were in the bulk job. I can just add a stage to that "request" button that will ask you for a story to be attached to all the requests in the job.

**Comment by JosephMcArthur** [comment]
one story to be applied to every request in a bulk job. So:

> Or if you want to do one story for every request in a bulk job, that is easy enough - right now you run a bulk job and once it is done you get the "request" button that allows you to try to create requests for all the items that were in the bulk job. I can just add a stage to that "request" button that will ask you for a story to be attached to all the requests in the job.

is the ideal here.

**Comment by markmacgillivray** [comment]
OK it now throws a context box to ask you for a story when you try to create the requests from a bulk job, and that should create the requests with the story and with you as the owner. I have pushed this onto dev but not had time to test, so give it a go and reassign to me if any problems.

**Comment by JosephMcArthur** [comment]
This looks good!
