### ISSUE TITLE
reprocess all old requests against our new journal catching & sherpa romeo

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#898]
From exports, it looks recent updates to the request system's ability to catch journal info is vastly superior. However, this hasn't been reflected in earlier requests so they lack journal info & then also sherpa data. 

Can we reprocess old requests against our current system to update journal info & sherpa records.

**Comment by markmacgillivray** [comment]
Written a script for this, still to test on dev then can be run on live.

**Comment by JosephMcArthur** [comment]
I know @natalianorori would love to see this asap. lmk what's needed to test.

**Comment by jibe-b** [comment]
+1

**Comment by natalianorori** [comment]
(y) Yes please! This is essential for the next test we have to run

**Comment by markmacgillivray** [comment]
I ran the script on the dev site, it worked fine.

There are 382 requests on dev, 106 of them had a journal name and 66 had a sherpa color. Processing took about an hour. 276 requests were page-scraped again (the amount for which we did not know the journal name) and journal names were found for 23 (about 9%). We found sherpa colors for 17 (these could have been ones we re-scraped, or ones we had a journal name for but did not have the sherpa color, although this is less likely).

There are 25486 requests on live, and only 5745 have journal names, and 473 have sherpa colors (the earliest request with a sherpa color was created on 27/06/2017). So there are 19741 that we would have to page-scrape, which could take about 3 days to run (we have to request the pages, render the js, and sometimes wait for slow redirects, and not trigger site max request policies). If we get a similar return to the dev run, we could maybe find about 1800 journal names, then maybe sherpa colors for 1500.

So, @JosephMcArthur @natalianorori would you like this run on live?

**Comment by JosephMcArthur** [comment]
Yes please!

**Comment by natalianorori** [comment]
Was this script already run on live?

**Comment by markmacgillivray** [comment]
Done.
