### ISSUE TITLE
SHARE returning "Chrome extension error: “Your file was not found”"

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#902]
I've seen this in other places (the big sheets) and I think it points to an issue with the Share integration. 

![image](https://user-images.githubusercontent.com/4953703/30312368-1e831406-9791-11e7-8353-b3ffedbd185b.png)

**Comment by markmacgillivray** [comment]
This is fixed. It was actually a combination of a problem with the redirect checker and the plugin feedback link. Both sorted now on dev. Requires an API update to live.
