### ISSUE TITLE
[feature] Make first character upper case in title and journal fields

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#905]
In the admin form on the website, the title and journal fields are always starting with a lower case character, which is a bit annoying.

Making it automatically upper case would save, 100ms per request moderation ;)

**Comment by JosephMcArthur** [comment]
@markmacgillivray Hoping this is trivial, but will help save bits of moderation time!

**Comment by markmacgillivray** [comment]
Done on dev

**Comment by JosephMcArthur** [comment]
Natalia, please test & close :)

**Comment by natalianorori** [comment]
works :)
