### ISSUE TITLE
[UI] blue banner for data requests?

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#907]
I suggest to make use of the color code made for paper vs data requests (orange vs blue) and place a blue banner for data requests.

That would help moderators to handle paper and data requests differently.

**Comment by JosephMcArthur** [comment]
@lorrainechu3n

**Comment by natalianorori** [comment]
Doesnt 'need to be a blue banner, but +1 to have some distinction that will make it easy to spot data requests. I just sent a data request with the article email template by mistake and know this could happen to others in the system, specially new volunteers.  

@JosephMcArthur

**Comment by JosephMcArthur** [comment]
no longer doing data work for the time being, closing this!
