### ISSUE TITLE
[Admin] add iframe with article's landing page

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#908]
It would save some time to moderators as no longer need to open the page of the article.

For example, for request https://openaccessbutton.org/request/NiTj5wFhAibEDyRdZ (IgNobel prize!)

cross-origin request is allowed, so the iframe

`<iframe src="https://link.springer.com/article/10.1007%2Fs10899-009-9174-4" width="100%" height="500px"></iframe>` displays the article.

When cross-origin request is not allowed, then replace iframe with link (like the title currently).

**Comment by markmacgillivray** [comment]
Cross origin request isn't relevant to iframes

**Comment by JosephMcArthur** [comment]
Now a duplicate of #775, which is close to closing.
