### ISSUE TITLE
[bug] requests stay with status "moderate" after having been sent

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#923]
The case for these requests:

https://openaccessbutton.org/request/LptEjAxBhHxFGg3Nj 

https://openaccessbutton.org/request/jtHXujYy5HqZhWuD5

That should be a trigger for me to write regression tests to prevent this type of bugs… I wish I had more time!

**Comment by JosephMcArthur** [comment]
@natalianorori is this to do with sending via the YAMM system?

**Comment by jibe-b** [comment]
Hey @JosephMcArthur @natalianorori @markmacgillivray I am forced to report this again. It looks a bit strange, as other requests seem to see their status changed correctly but the ones I moderate do not.

**Comment by natalianorori** [comment]
This is weird and definetly does  have nothing to do with the YAMM system. Requests I moderate do change their status automatically, it might be a problem linked to Jibe's account. Jibé, have you tried signing out and in to the system again?

**Comment by jibe-b** [comment]
I'll try to moderate one now

**Comment by jibe-b** [comment]
It works fine today (status changed to "In progress" after page refresh)

**Comment by natalianorori** [comment]
Glad this was fixed, if you have this issue again, feel free to reopen
