### ISSUE TITLE
new dropdown button in admin UI: article too old

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#934]
adding a new dropdown option in the admin UI that sends a template for when the article is too old, prior to 1995. We can't make these articles open access due to old publishing agreements so we'd have to close these requests.

**Comment by JosephMcArthur** [comment]
Can you list out all the actions you want the button to take please, and any templates you'd like sent?

**Comment by natalianorori** [comment]
Action button pressed
dropdown option "article too old?" (not sure how to call it)
when pressed  sends out[ template ](https://docs.google.com/document/d/12nLdtKj1R5DgRm4Xk9UncqOS6Z4EgvkRKl5EYswIemQ/edit#)to user and automatically closes the request

**Comment by JosephMcArthur** [comment]
@markmacgillivray please let us know what's needed to get this moving

**Comment by markmacgillivray** [comment]
Added request_too_old to admin dropdown, which tries to send an email using a template called request_too_old.html to all requestors. As long as that template exists and has been refreshed into the system templates on the overall admin page, this should work on dev.

**Comment by JosephMcArthur** [comment]
@natalianorori how is this different to #952. Are both needed?

**Comment by natalianorori** [comment]
Sorry! I hadn't noticed there were two issues. They are the same, I'd suggest we close this issue and stay with the "article prior year 2000" button and template instead.

**Comment by markmacgillivray** [comment]
Done
