### ISSUE TITLE
new dropdown button in admin UI: author email not found

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#935]
for when its impossible to find authors emails, add a dropdown option that notifies the user and automatically closes the request.

**Comment by JosephMcArthur** [comment]
Can you list out all the actions you want the button to take please, and any templates you'd like sent?

**Comment by natalianorori** [comment]
Action button pressed
dropdown option "email not found appears"
when pressed "email not found button" sends out[ template ](https://docs.google.com/document/d/1EzQRUGmadpCUvhV-v0TiNxMocgFKESgaePqqlSW3iNE/edit)to user and automatically closes the request

**Comment by markmacgillivray** [comment]
Added author_email_not_found to admin dropdown, which tries to send an email using a template called author_email_not_found.html to all requestors. As long as that template exists and has been refreshed into the system templates on the overall admin page, this should work on dev.

**Comment by JosephMcArthur** [comment]
template exists, over to @natalianorori

**Comment by natalianorori** [comment]
Tested this, the email is not being sent out and the status is not changed from "moderate". Once this is looked at I can test it again

**Comment by markmacgillivray** [comment]
Hmm, I just tried it and it worked fine on

https://dev.openaccessbutton.org/request/JHhi6n4YCacikGRFd

which you can see now has a status of closed

**Comment by natalianorori** [comment]
again, I tested it again. The status did change, but as a user I am not
receiving the e-mail template that says we are closing it

**Comment by markmacgillivray** [comment]
The request I linked above doesn't have any user attached to it though, it is still an anonymous request. I may be misunderstanding, but I think the email here would only go to the person who created the request or anyone who supports it - but if the request is anonymous and has no supporters, there is nobody to email. I think you'd have to create a request and add a story to it whilst logged in, so that it was not an anonymous request, and then try using the author_not_found admin button, before any email would get triggered.

**Comment by natalianorori** [comment]
Hi, 

I created an issue here under my name https://dev.openaccessbutton.org/request/jnujwYAmirw2yBYvG
but when I press this or "prior to 2000" button request is back to not changing it status to help, or not sending the e-mail notification. 

Also, save changes button is not saving changes on dev again.

**Comment by JosephMcArthur** [comment]
Test and it works, but needed the email syncing on dev. At first it didn't work for me either, then after syncing it did so confident we're good here.
