### ISSUE TITLE
on dev exporting from /export opens https://noddy.api.cottagelabs.com/ in a new tab 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#938]
Needless to say, exporting doesn't actually work.

**Comment by markmacgillivray** [comment]
OK sorry, need to add a fix for this, will do asap

**Comment by JosephMcArthur** [comment]
It now opens 

> https://noddy.api.cottagelabs.com/convert?from=json&to=csv&subset=hits.hits._source&fields=_id,created_date,type,count,status,title,url,doi,journal,publisher,sherpa.color,name,email,user.username,user.email,user.firstname,user.lastname,story,rating,receiver,refused.email,refused.date,received.date,received.from,received.description,received.url,received.admin,received.cron,received.notfromauthor,notes,plugin,from,embedded&url=https%3A%2F%2Fnoddy.api.cottagelabs.com%2Fservice%2Foab%2Frequests%3Fsource%3D%7B%22size%22%3A100000%2C%22query%22%3A%7B%22filtered%22%3A%7B%22query%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22match_all%22%3A%7B%7D%7D%5D%7D%7D%2C%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22range%22%3A%7B%22createdAt%22%3A%7B%22gte%22%3A1262304000000%2C%22lte%22%3A1515628800000%7D%7D%7D%5D%7D%7D%7D%7D%7D

which says

> ReferenceError: which is not defined at Object.API.convert.run (server/api/convert.coffee:43:3) at Object.get [as action] (server/api/convert.coffee:19:25) at Route.share.Route.Route._callEndpoint (server/api/lib/aa-restivus.coffee:180:25) at server/api/lib/aa-restivus.coffee:77:33 at server/api/lib/aa-json-routes.coffee:48:9

**Comment by markmacgillivray** [comment]
OK, works now.
