### ISSUE TITLE
/bulk misses existing requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#940]
See job ID #ceEoe6Cwc237gdwGD on /requests for test case

We have requests on /dev for, at least:

https://doi.org/10.2307/1574276
https://doi.org/10.1093/oxartj/kct044
https://doi.org/10.1093/oxartj/kct044
https://doi.org/10.2307/4058061

- [ ] Also, note, there are some duplicate requests on dev. Any idea what that's about?

**Comment by markmacgillivray** [comment]
It works now, tested with 10.2307/1574276

See:

https://noddy.api.cottagelabs.com/service/oab/job/nTsFpzvunLgkiFtma/results.csv

There is an error on the dev site mappings of the request data, this is just from dirty test data, so if any other ones don't get found when testing this, just add them to this issue and I will check to see if it is the mapping or another problem.

**Comment by JosephMcArthur** [comment]
re-ran the requests checking job. Found them all successfully. Will shut until I notice something else.
