### ISSUE TITLE
White bar sometimes appears

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#941]
Seems to be coming from : `style="margin-top: 33px;"` in the footer in some page formats. Often after something is clicked. 

<img width="1517" alt="screenshot 2018-01-08 11 08 31" src="https://user-images.githubusercontent.com/4953703/34668236-61d0941a-f464-11e7-9e2f-c6425983c5bc.png">

**Comment by markmacgillivray** [comment]
I could only get this to happen if I resized my browser window. Otherwise, it seems to size correctly on first page load. Can you describe any action you can find that causes it other than window resize?

**Comment by markmacgillivray** [comment]
I think then there is not much we need to do with this, please close unless you find more.
