### ISSUE TITLE
expand menu on right click for plugin

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#942]
Chrome is building a UI convention that right-clicking on plugins allows you to do more stuff. 

I'd suggest we expand our menu to allow:
* "report an issue" (takes you to https://openaccessbutton.org/feedback)
* search by doi or title (takes you to https://openaccessbutton.org/) - requested by Rikke Straarup Voulund

> I would love, if I could just press the button to access a new search bar as well. Is this already possible?
> This would be a quick way to check, if I only have a DOI for example.

They're suggesting something slightly different, but I expect just pointing to the site for now is all we can manage. This would also be shut by #515 

* see your requests (takes you to https://openaccessbutton.org/requests and hopefully a URL where you just see your own requests... can't remember what that is)

@markmacgillivray if this is a trivial edition (which it may be) it would be great to get it in the next release. If no, no problem). 

Firefox allows similar right-click functionality.

**Comment by markmacgillivray** [comment]
I can't find info about what you seem to be describing - where did you read about it? I don't know where there are instructions about adding a right click function to the plugin. Do you mean the plugin icon on the top chrome nav bar?

**Comment by markmacgillivray** [comment]
@JosephMcArthur do you have an example of what you mean here? Right click on what? The plugin icon? The web page you execute the plugin on?
