### ISSUE TITLE
Stats for institutional tools

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#949]
For each instance of a tool, we should try to show:

- [ ] total availabilities, 
- [ ] successful availabilities, 
- [ ] requests with stories made, 
- [ ] successful requests
- [ ] date first used

**Comment by markmacgillivray** [comment]
See #985

**Comment by markmacgillivray** [comment]
I have added a filter option to the top of the stats page that allows to filter the stats by tool. This is available for review on dev.
