### ISSUE TITLE
Bye Bye Data :'(

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#950]
Time to say bye bye to data I think while we launch other new stuff:

- [x] frontpage copy change (when I do this, see if I can make the logo nicer on mobile)
- [x] hide data button on availabilities success page
- [x] hide data button on new request page
- [x] hide data options on requests index
- [x] hide on stats page
- [x] move files for emails somewhere

**Comment by markmacgillivray** [comment]
@JosephMcArthur I think I have done all my bits for this.

**Comment by JosephMcArthur** [comment]
Altered the homepage copy so it's passable, but the logo disappearing on mobile and then everything looking kinda rubbish I don't know how to fix without probably screwing up quite a few other things.

**Comment by markmacgillivray** [comment]
I altered the page layout to keep the logo even on small, hopefully it will lay out nicely. Looks good for me. Also merged back in the staging index page to the index page.

**Comment by JosephMcArthur** [comment]
Much better, but a final tweak to how it resizes would make the difference on mobile

![image](https://user-images.githubusercontent.com/4953703/38927999-63c8992c-42ff-11e8-80ba-bc9e1d5c540a.png)

Can the text / logo get a bit smaller on mobile if required?

**Comment by markmacgillivray** [comment]
OK, have resized text and image for smaller screens, see what you think now.

**Comment by JosephMcArthur** [comment]
Better, this could go on infinitely, so lets just shut, it's good enough.

**Comment by JosephMcArthur** [comment]
Should probably also remove data stuff from openaccessbutton_widget too, but since I think it's hidden it's likely best just left...
