### ISSUE TITLE
system is failing to auto fill author's {{name}} with the word colleague when no name is provided

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#953]
before the update, the system automatically filled the box with author's name with the word colleague, when no author name was provided. Tested the drop down action button today and the email sent was: 

> Dear {{name}},

this is priority for automatic moderation. 

@JosephMcArthur @markmacgillivray

**Comment by markmacgillivray** [comment]
OK, the line that added that in was missed when I did the rewrite, sorry about that. It has been added now and is on the dev API, will be on live when we run the next update.

**Comment by natalianorori** [comment]
Thanks Mark

On Wed, Apr 18, 2018 at 12:02 PM, markmacgillivray <notifications@github.com
