### ISSUE TITLE
Save changes button in admin UI is not saving changes

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#956]
Was working fine before the update, this started today. 

@markmacgillivray @JosephMcArthur

**Comment by natalianorori** [comment]
It's the author name box and the journal name box the ones that don't save changes when the "save changes" button is pressed. email and story boxes are working fine.

**Comment by markmacgillivray** [comment]
Please try this again on the dev site, I have put in some changes that should mean it is fixed. So once we do the update to live, this should then be fixed on live.

**Comment by natalianorori** [comment]
it's working, thanks.
