### ISSUE TITLE
OAB is not recognizing journal urls - submit button for stories is not working

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#957]
We have not been getting requests from users, and I'm trying to find out why. 
found two things
the main site openaccessbutton.org is not recognizing sciencedirect URLs, and is only making requests with DOIs.  Tried cell and it worked, tried nature and also worked. The problem seems to be with sciencedirect journals. 

and most importantly, 
The submit button for stories does not work. it gets stuck and doesn't perform any action. This is why all requests look as submitted by anonymous users. 

@JosephMcArthur @markmacgillivray

**Comment by natalianorori** [comment]
oh, I hadn't test this part of the system since the update. What I tested was our end of the system (moderation and uploads).

**Comment by markmacgillivray** [comment]
I can see the popup about sciencedirect URLs when I try them - we don't have a solution for accessing them from our site yet, unfortunately, so a popup is the best we can do.

I still have to look at the submit button for stories not working though

**Comment by JosephMcArthur** [comment]
We really need a push a fix for this out asap, so once addressed I'll do a our staging rejig & push a fix to live asap.

**Comment by markmacgillivray** [comment]
On my local version and the dev version the story submit button is working for me. I have not tried live yet. Can one of you try logging out completely, do a hard refresh of your browser, then login again, then try this?

**Comment by markmacgillivray** [comment]
I just tried a live one and did get the error - will check further.

**Comment by markmacgillivray** [comment]
Story save should be fixed now - I altered the API code, so don't need to worry about changing things on the site. I am keeping this issue open though because I want to keep an eye on it in case the error comes up again. Please let me know if you have problems saving stories, now or later.

**Comment by natalianorori** [comment]
Tested it and its working now, thanks for the fix, I'll keep you posted if
it breaks again.

natalia
