### ISSUE TITLE
searching for whole emails on /admin doesn't work

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#961]

**Comment by markmacgillivray** [comment]
It does if you wrap them in quotes. Anything apart from a normal plain text string should be quoted if you want an exact match on it. e.g anything with spaces, @ symbols, etc, needs to be quoted or it will be tokenized

**Comment by markmacgillivray** [comment]
Assigning to @JosephMcArthur to close if this is acceptable

**Comment by JosephMcArthur** [comment]
can be closed if we can have a UI note for this.
