### ISSUE TITLE
moar footer foul ups

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#962]
seen at https://openaccessbutton.org/request/C7HKYY95ugdCTvHo6 & https://www.dropbox.com/s/7swydo0lp54nkaq/Screenshot%202018-04-26%2015.50.02.png?dl=0

From FF incog, dev edition. Have seen on testrise too.

**Comment by markmacgillivray** [comment]
Hmm looks fine for me on chrome. In the screenshot you shared, it looks like the content is fine but the footer is just not pulling to the bottom. I think this is better than the issue we had before where some content was being hidden. In most cases the footer should pull to the bottom, but possibly not all. This is a matter of how long you want to spend tweaking for edge cases.

**Comment by markmacgillivray** [comment]
Our pages use a lot of dynamic content, and they do it in various different ways. For example the requests page has infinite scroll. Most sites that use infinite scroll won't bother with a footer at all. By default if a page has content that is shorter than the window, the footer will always float above the bottom of your window, showing a gap under it. The footer can be pushed down when the page content isn't long enough, but it either has to be fixed to the bottom which means stuff that later loads may get obscured by it, or it can be given a big margin, which is what leads to it sometimes being quite a bit further below the main page content. Is the footer even that useful?

**Comment by JosephMcArthur** [comment]
Thanks! Right now, lets' just push into backlog.
