### ISSUE TITLE
link hit counter for resources

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#964]
From chat:

>What's the easiest / least instrusive way to track views / downloads / contributions on a page like this: https://openaccessbutton.org/skip_the_paywall?
> I thought GA would do it, but it doesn't actually look like it does.
> Every time someone hits one of those buttons trigger a js that sends an Ajax request to an endpoint on the API with a unique token on it, then later count those hits. I could add that pretty quick if you want it, but probably can't be doing it today. Actually probably won't get anything done today, i have some other things to do. But could add it over the weekend, or early Monday.
> Counts is fine

**Comment by markmacgillivray** [comment]
Actually I got a few minutes to do this just now. Have added to that page, all you have to do is give an ID to the buttons that you want to track, and add the "pinger" class.

@JosephMcArthur assigning to you so you can take a look and add to others you want to track.

**Comment by markmacgillivray** [comment]
Yeah dev hits will be counted on dev API. We will have to add a way for you to view these results, on the stats page or somewhere, but for now you can check directly on the API

**Comment by JosephMcArthur** [comment]
note: https://dev.api.cottagelabs.com/pings is where I can view this. 

Yes, will need to export this somewhere as the API doesn't give me the aggregate number, but it's fine to test each tag works, which it does. This is delightfully easy, thanks.

**Comment by JosephMcArthur** [comment]
@markmacgillivray I presume that the live API was updated to get these hits?

**Comment by markmacgillivray** [comment]
Yes

**Comment by JosephMcArthur** [comment]
Can you build a part of /stats for this?

**Comment by markmacgillivray** [comment]
Yep, but haven't done that as part of this issue yet. You can reassign to me and schedule it in to next week if you want, or make a new issue for adding it to stats, or add it as a comment to the open issue for altering the stats page. It won't be done this week though, but could be next week.
