### ISSUE TITLE
when supporting a requests confirmation is not shown (and possible to support many times)

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#965]
Essentially, without manual refresh "notify me" button gives no response to user

**Comment by JosephMcArthur** [comment]
Being told by users this is happening for all changes on request pages, including things like adding author info.

**Comment by markmacgillivray** [comment]
Shows a thanks msg after you support now, on dev.

**Comment by JosephMcArthur** [comment]
tested on ff, works. Thanks!
