### ISSUE TITLE
displaying sherpa color for article in admin ui

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#968]
when provided, so that we can have a brief idea of each article's copyright and know when to close requests from the admin page (ex. white articles).

**Comment by markmacgillivray** [comment]
Done on dev

**Comment by JosephMcArthur** [comment]
best for @natalianorori  to review here. Natalia, shut if you're happy!

**Comment by JosephMcArthur** [comment]
can see sherpa color when available.
