### ISSUE TITLE
Filters on /export not working

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#971]
@natalianorori  to expand

**Comment by natalianorori** [comment]
Can't filter by date, when the date from the time period wished is submitted the system still displays  "2010", and we used to be able to filter requests by statuses eg. only exporting requests in received status

**Comment by markmacgillivray** [comment]
These have been reinstated on dev, please test and see if suitable.

**Comment by natalianorori** [comment]
working now! thanks
