### ISSUE TITLE
display pings on /stats

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#979]
From #964, can be displayed like current embedoa like stuff. Would be great if we could put in table too to get a time series.

**Comment by JosephMcArthur** [comment]
No table or timeseries required, just the ID's & the number of hits like embedoa

**Comment by JosephMcArthur** [comment]
Please display these under a new header, "Resources"

**Comment by JosephMcArthur** [comment]
Happy to skip the nice table, or move this back to when we do other stats page improvements.

**Comment by markmacgillivray** [comment]
@JosephMcArthur do you have an idea of what extra details you want to see about pings, or are you happy with the list format it now has?

**Comment by JosephMcArthur** [comment]
I think a timeseries would be cool. Kinda like the tables. Maybe be better to flip rows & columns though.
