### ISSUE TITLE
Plan for moving from receive --> deposit 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#983]
Mark, here can you outline a rough plan for moving from Receive to Deposit technically and consider any hurdles with my specs or areas I'm leaving unclear. This plan should eventually be a set of issues in soon. 

I'd like to try and keep the infrastructure work here to a minimum in the first version, and focus on building out the actual deposit systems. 

I'm also happy to make big limitations in scope that keep this simple and close to what we have already built, e.g using only DOI's, focusing on published articles.

I'll use this to outline the key things I think we should have for deposit too. 

# Timeline

I'd like to see us release a MVP version of this within 3 months, but have functional versions that can be tested much sooner as this is building on existing systems. 

Mark, if we can ship bits iteratively that improve what we have, that would be good. We should see day to day improvements within requests sooner

# Spec

* pages should appear on Google as current request pages do. However, pre-launch we'll want to be able to hide them. 
* Pages should show up at /doi. If you were to replace doi.org/ with <<oururl>> this should work. The should probably also turn up at request IDs to align with the current system. 
* For now, we'll only care about already published articles. However, later we should be aware that we may need a structure to care about accepted articles (which may then need a different UID). For now, we won't accept things without DOI's. 
* URL is tbc. Joe is strongly leaning toward a new URL for this system. Suggest we boot at depository.openaccessbutton.org for now. 
* For now, Id' say let's not care about making requests from these pages. If we have time within 3 months, that's great, but let's focus on getting deposits here for now. 
* Let's prioritise initial page load speed and avoid long spinners. Can we fill info from checks as we have it. Pages should probably load as soon as we verify the DOI is valid and get cached. This is relavent to requests too. 
* For now, the designs of receiver pages & the homepage is fine as a homepage / deposit page UI.
* the whole deposit should be a "deposit zone", what if you drag a file it's listening to upload. Most sites that want uploads do this (rather than small "upload here" zones. This is relavent to receiver too.
* I'd like to challenge us to have the UI be so simple that the only thing you'd need to do is drag a file onto the page, at most we should aim for one click to confirm submission, but it would be nice to not even need that (or, have the click to be "I made a mistake, cancel).  
* Anything deposited through this should be tagged in some way on Zenodo. This is relavent to requests too. 
* All admin systems can be managed by oab's current systems
* I'd like the api's that power this to be documented and available for interations in the MVP. We should treat the API as a priority UI.

What we'll also need to think about is:
* a concept note for this
* what to do if the doi isn't valid. Probably show the homepage with a note saying that wasn't a valid DOI, search again. 
* what to do if something is oa. Probably show the homepage with a note saying that's OA (with a link)
* deposit logic (e.g if to show pages where sherpa romeo shows no self archiving is possible, or if only pre-prints are allowed, only include a URL box (not an upload)). 
* a thank you page post deposit. Could probably just show the homepage again, with a thank you note, and inviting more deposits. 
* an MVP library integration (e.g if your institution is associated you're notified of deposit)
* Designs for this

# Build process

Mark, if we wanted to start using feature branches and allowing the site to load from there, this seems like a good moment to start that.

# Criteria for closing

This can be closed when we have other issues to better flesh out the work and feel like we have clarity on what should ship.

**Comment by markmacgillivray** [comment]
It's still not clear to me why a separate product is a good idea - but that's OK, it doesn't need to be clear to me.  However, it seems that what we need to make this is not technical, it is about product design and sales/marketing. There is not much I can to do spec it out, as it is just the receive system we already have, with different names for things and a different website.

What do you mean by treating the API as a priority UI? If this is basically the same service, there is no new API to document. If a new website is required, are you wanting me to make and design that? Usually you want a designer to do the website stuff.

Also if this is going to be a separate product, and therefore presumably totally separate website, I don't think feature branches in the current repos are useful - it may as well just be a new repo for a new static site.

So, should I be designing a website here? A workflow? A new API? And how much of that is me and how much is a designer? Or am I the designer? Sorry, I'm not clear what is required from me to help it move forward.
