### ISSUE TITLE
EmbedOA inside link resolvers

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#989]
Have embedoa run automatically inside a link resolver by listening for openurls (sp). 

Discussed with Mark, possible, need to find out if this is useful.

**Comment by JosephMcArthur** [comment]
Spoken with Mark. Doing this will take about a sprint. Would work by listening for params, and having the ones we can accept set in the UI under some rational defaults.

We'd need to provide some instructions, and instructions on forming a base URL. We'd also need to make sure people understood this will always run. 

Then, once implemented these params would take the place of a users search. So, they'd land on the page and we'd already be looking, and show the relevant response as if they'd searched with the info the open url sent.

**Comment by JosephMcArthur** [comment]
Circling back to expand slightly. 

A few things to note:

## Behaviour

* these params would take the place of a users search. So, they'd land on the page and we'd already be doing look-ups, and show the relevant response as if they'd searched with the info the open url sent.
* If we're given meta-data, let's trust it but try to enrich, much like if a user gives us info
* If a user comes our way via a openurl, let's allow the user to make it optional whether to re-run certain checks (e.g if they come from the link resolver no point re-running the subscription check). 

## Set up

* it would be great if this was 'always on', so it was always listening.
* Seems like we could guess any openurl set up given to us through a mix of sensible defaults or just our general system for catching 
* We should provide an option for people to tell us exactly what key's / values to expect.
* Providing the base URL could be tricky here, as we obviously by default don't know the page we're on. Let's for sure provide the basic e.g add ?openurl= (or whatever). BUT, I know that the embed will know, once used, what URL it is on. Can we use that knowledge to provide the exact base URL after it's been used once?

**Comment by JosephMcArthur** [comment]
I think that for this, we'll want to enable a mode where basically we can silently pass people on. E.g: if we get hit with an openurl, and we know the url for an illform, we may want to just send the user straight there. For many user contexts, showing up the form would just be confusing in that context and add an extra click. we could also enrich data en-route perhaps. However, if we did find an oa copy, we'd want to show that.

**Comment by markmacgillivray** [comment]
If we pass straight on, we will need to at least show something on the page, because if we are going to run an enrichment and find out where to pass them to, there will be a delay. So, what do you want to happen on the page while we are doing this? Remember that as we don't know where an institution might place the instantill widget, we can't know that it will be visible on the page when the page first loads.

**Comment by JosephMcArthur** [comment]
It's worth noting that much like the subscription's open url params, the ones we're sent here could be independent of ILL ones! However, often, they'll conform to OpenURL standards.

**Comment by JosephMcArthur** [comment]
> If we pass straight on, we will need to at least show something on the page, because if we are going to run an enrichment and find out where to pass them to, there will be a delay. So, what do you want to happen on the page while we are doing this? Remember that as we don't know where an institution might place the instantill widget, we can't know that it will be visible on the page when the page first loads.

I think this is actually complex enough to turn into another issue, likely needs more validation too. This moves us basically into the land of a link resolver and would need quite a few changes. E.g. We'd want to provide some 'other' link for this, and likely keep the screen blank for quite a while before then returning a response. This is basically what LRs do now.

**Comment by JosephMcArthur** [comment]
OKAY. Big tidy, and summary for building this next week. But first, some broader context. 

InstantILL is a next gen ILL form. One of the biggest ways people reach ILL forms now is via links in other systems, say library search or link resolvers. Usually, but not always, those links provide some data in the form of an Open URL. We want to make sure InstantILL works well in those settings, and can be integrated. Right now, InstantILL has to be a starting point for submission (via an ILL page). The benefit of that integration for a library is that we can enrich the data given with our meta-data sources, provide a nicer UI, do an OA check, do a subscription check etc.

There are two broad ways that integration can be done:
1. Embedding InstantILL ONTO link resolver or library search pages
2. Linkout from those systems to InstantILL embedded elsewhere

In both cases, URL params are key. In 1. URL params are used by link resolver. If someone embedded InstantILL into their link resolver, ideally we'd be able to understand them and show a result. In 2. data about what the patron is looking for can be embeded into links elsewhere (say an ILL form) via params. In both cases, the key thing to be able to do is recognise params on the page we're embedded into and show a result. 

We can close this when the following is done & tested.

For the end user, we'd want the following behavior:

* URL params from the page we're embedded on to take the place of a users search. So, a user lands on the page and we'd already be doing look-ups, and showing the relevant response as if they'd searched with the info the openurl sent. In terms of what the user sees, this would just be the normal UI expected at that point (during search, or if we'd found something). e.g for search we put whatever we're looking for in the search box as normal.
* When we're given meta-data via params, let's trust it but try to enrich, much like if a user gives us info. If the user then tries to overwrite that, trust this. 

We'd want the following process during set up:

* Let's make it optional whether to re-run the subscription checks. If someone is coming from their link resolver, there is no point in us re-checking. 
* A nice to have is allowing people to remove 'If you need a paper or book you can request it from any library in the world through Interlibrary loan. Start by entering a full article title, citation, DOI or URL:' since if embedded into a link resolver that might not make sense. This would mean all they'd see was the search box & button. 
* Let's default that this is on by default, but allow it to be turned off. 
* By default, let's recognize the standard openurl key's for meta-data values. However, let's allow these to be edited much like the ones for ILL, but independently from them.
* To aid others providing links to this we'll need to provide the base URL. That could be tricky here, as we obviously by default don't know the page we're on. Let's for sure provide the basic info e.g add ?openurl= (or whatever) to the URL you embedded this one. However, a nice to have would be providing the exact url after it's been used using whatever we do to find the URL for stats.

With each of those ticked, I think we'd be done.

**Comment by JosephMcArthur** [comment]
Shipped out for testing what we have so far today.

**Comment by JosephMcArthur** [comment]
ProgressL

> Basic implementation in place. On the dev site only. Go to the instant ill alpha page. If you provide certain params the lookup will trigger
> Params allowed so far are
> id
> url
> doi
> title
> atitle
> rft_id
> But it only takes the first one
> I'll alter later so it takes more metadata in one go
> No work done on the config of it yet
> I'm out the rest of today though
> * by "the first one" i mean it'll take whichever one of those you provide, but only the first one you provide. It won't read multiple params yet. And I'll add others so that it could pass through full metadata if provided.

**Comment by markmacgillivray** [comment]
It now checks all params provided, and picks out any that can map to title, doi, journal, author, year (or fall back to url in the title). These are the ones it reads because these are the ones we collect and pass through for our searches. Configurability is in progress but not complete.

**Comment by markmacgillivray** [comment]
Apart from the option to re-run subscription, the above config options are now in place. We agreed that re-run subscriptions may as well happen anyway as we will always be sending a request to our backend to get configs and OA checks, and doing the sub checks is not much of an extra on that.

Note however these configs are still being tested, although they are present on the page. @JosephMcArthur I will update this issue again asap once I have done a bit more testing of them.

**Comment by JosephMcArthur** [comment]
Thanks for the update! I've sent over a note to IUPUI on this.

**Comment by markmacgillivray** [comment]
@JosephMcArthur I have finished testing and am happy this seems to be working as expected. You can close the issue or keep it open if you want to keep track of IUPUI response

**Comment by JosephMcArthur** [comment]
Nope! Looks great. Let's close this and move onto 49.

**Comment by JosephMcArthur** [comment]
Can we fix that it doesn’t seem to parse the + sign as a space?

e.g Article Title %20:

https://ulib.iupui.edu/services/ILLTest?atitle=Adjuvant%20rituximab%2C%20a%20potential%20treatment%20for%20the%20young%20patient%20with%20Graves%27%20hyperthyroidism%20%28RiGD%29%3A%20study%20protocol%20for%20a%20single-arm%2C%20single-stage%2C%20phase%20II%20trial.

and 

Article Title +:

https://ulib.iupui.edu/services/ILLTest?atitle=Are+electromyographic+patterns+during+gait+related+to+abnormality+level+of+the+gait+in+patients+with+spastic+cerebral+palsy

Would be good to be agnostic here, or have a config option if being agnostic creates issues.

**Comment by JosephMcArthur** [comment]
More issues I've just noticed:
* multiple param searchs don't work. Seems to take the first param as the title.

https://ulib.iupui.edu/services/ILLTest?sid=google&auinit=JR&aulast=Nelson&atitle=Alexander+Hamilton+and+American+Manufacturing:+A+Reexamination&title=The+Journal+of+American+history+(Bloomington,+Ind.)&volume=65&issue=4&date=1979&spage=971&issn=0021-8723

* in both the + and %20 example above, the + and %20 are passed to the UI (although only one works as a search). These turning up in the UI isn't good, and needs fixing.

**Comment by markmacgillivray** [comment]
OK, done. I have removed id as an allowed param, as it is too likely to conflict with other ones. Also I have tightened up how it matches, and filter out + symbols and URL encoding. Note however that we do not know what other sorts of symbols someone (or some system) may send in these params, so there is not much more we can do than manually filter out any that people ask us about.

This is done on dev, do you want it pushed to live?

**Comment by JosephMcArthur** [comment]
Fab. Yes, but no rush. Let's push to life with the designs etc.
