### ISSUE TITLE
Handling deposit statements

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#991]
@natalianorori some deposits need to be accompanied by a statement e.g http://www.sherpa.ac.uk/romeo/search.php?issn=1547-5816

> This is a pre-copy-editing, author-produced PDF of an article accepted for publication in [insert journal title] following peer review. The definitive publisher-authenticated version [insert complete citation information here] is available online at: xxxxxxx [insert URL that the author will receive upon publication here]. 

Can you work to understand how often this is, patterns in statements (e.g are the always / effectively the same, or always the same for the same publishers), and understand if SR always just says "see policy" for the statement required.

@markmacgillivray I presume that if we gave you templates for these we can fill all this in if we have a DOI & stick it in a comments / description section in Zenodo. 

Started in #738

**Comment by JosephMcArthur** [comment]
@natalianorori while you look at this can you keep an eye on the General Conditions section of SR. Hopefully, if we do the above and the following we're always in compliance there but if there is other stuff that comes up it's important to know. 

We should also do the following with deposits:
- [ ] Give the link we're given by requestors in Zenodo & a DOI if we have it
- [ ] Say what version we're depositing in Zenodo

That should cover us in most cases, I hope, with "general conditions". 

- [ ] We may want to update deposits we've already got with this too but that's better done by hand.

**Comment by natalianorori** [comment]
### General conditions: 

We've look at major publishers conditions, which together represent more than half of all journal articles and concluded that. 

- Most major publishers have similar general conditions - see above 
- Most major publishers require attribution or statements 
- Most major publishers require linking to the pdf version through the DOI 
- Most major publishers require a creative commons license. Although IOP is the only one that forbids CC licenses
- Some major publishers wish to be informed when a preprint or AAM from them is deposited
- Some major publishers only allowed research to be deposited in repos, and strongly prohibit RG and academia.edu 

Detailed information for each publisher's conditions [here](https://docs.google.com/document/d/1rgcG3NUqXiK-L_CMG7q1mmyJKY9JvINH9K72cTj_xQ0/edit#)

### statements: 

Not all journals have specific statements that need to be filled, but all of them require some sort of statement to be made. Statements from major publishers below: 

Oxford University Press
Statement: This is a pre-copyedited, author-produced version of an article accepted for publication in [insert journal title] following peer review. The version of record [insert complete citation information here] is available online at: xxxxxxx [insert URL and DOI of the article on the OUP website].

Cambridge University Press
Statement: This article has been published in a revised form in [Journal] [http://doi.org/XXX]. This version is free to view and download for private research and study only. Not for re-distribution, re-sale or use in derivative works. © copyright holder.

IOP
Statement: Once the Final Published Version has been published, authors should add citation details and a link from their postings of
Preprints/Author’s Originals and/or Accepted Manuscripts to the Version of Record via DOI. IOP Publishing also requires that
authors include the Statement of Provenance as set out below.

SAGE
Statement: When posting or reusing your Contribution under this policy, appropriate credit must be given to the SAGE journal where the Contribution has been published, as the original source of the content, as follows: Author(s), Article Title, Journal Title (Journal Volume Number and Issue Number) pp. xx-xx. Copyright © [year] (Copyright Holder). Reprinted by permission of SAGE Publications. Additionally, please provide a link to the appropriate DOI for the published version of the Contribution on the SAGE Journals website (http://journals.sagepub.com).

Taylor & Francis
Statement: “This is an Accepted Manuscript of an article published by Taylor & Francis in [JOURNAL TITLE] on [date of publication], available online: http://www.tandfonline.com/[Article DOI].”

Wiley
statement : "This is the pre-peer reviewed version of the following article: [FULL CITE], which has been published in final form at [Link to final article using the DOI]. This article may be used for non-commercial purposes in accordance with Wiley Terms and Conditions for Use of Self-Archived Versions."

Elsevier, Nature, Springer and Brill 
Do not have specific statements, but they do require to be cited. We can come up with a simple statement based on what other publishers require.
here's an example of what could be used: 
"This is the <version> of an article published by <publisher name> in <journal title> which has been published in final form at <link with DOI>. "

**Comment by JosephMcArthur** [comment]
Great stuff, Natalia thank you. Please make sure that each of those has a citation associated to the root policy. 

It seems like these are handled on the publisher level, yes? and not currently in Sherpa Romeo. 

So perhaps in the sheets suggested in #483 we should have another sheet call "statements" for each of these that supplements the Sherpa Romeo data. We can code them by the publisher, and the system can pull them in as required. Then, @markmacgillivray can have the info passed over to Zenodo.

The statements will need to be put in the sheet in a way that allows them to have tags the system can fill. E.g <<doi>> where a doi is required. Where we don't have something, at this point, we should put in the closest alternative we do or ignore. We'll fix other issues later once we have a broad system in place that will work for most. 

Both, please move is ahead if you can.

**Comment by natalianorori** [comment]
useful side note: I've chatted with some librarians about deposit statements and this is what they've told me: 

How do IRs staff handle deposit statements: They often create cover pages with the citation and the stage of the article the document is eg. "this is a preprint of xx .. ", The cover page provides a link to the article published version and acknowledges the publisher. Each institution has their own spreadsheet for journal deposit statements, but these are not often shared.

**Comment by JosephMcArthur** [comment]
Closed by #1219
