### ISSUE TITLE
When is a yellow journal not a yellow journal?

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#993]
In this http://www.sherpa.ac.uk/romeo/search.php?issn=1547-5816 the yellow journal actually allows AAM under some simple conditions.

@natalianorori do you know how often this happens, roughly?

For Mark, at some point,

- [ ] Does the API give us a clear signal when you can post the AAM with restrictions?
- [ ] Can we grab & parse the restrictions to programmatically tell when we have what's needed to allow AAM deposit?

**Comment by natalianorori** [comment]
This is a tricky one, 

for my point of view, Sherpa does not classify journals that allow depositing the AAM after an embargo period as green. I've always seen them listed under yellow policies. I might be wrong, but for me green is allowing preprint and post print without restrictions. This is a case in which a librarian input would be useful

**Comment by JosephMcArthur** [comment]
Agreed, please put this on your list of stuff to discuss with people. But, color aside, if we can interpret those restrictions and meet them it sounds like we could deposit the AAM in more cases than we'd otherwise expect! That's got to be good news? :)

**Comment by JosephMcArthur** [comment]
This is an important issue, but since it's all about reinterpreting established signals I think we should push back to a later point when we feel more confident and are more regularly pulling this info in.

**Comment by JosephMcArthur** [comment]
Moving away from SR, won't fix.
